import {readFileSync} from 'node:fs';
import {expect,test,vi} from 'vitest';
import {HAIRLESS_EXAMPLE_NAME,loadHairlessExample,planArtworkImport,sourceForExampleImport} from '../app/artworkExamples';
import {emptyDrawing} from '../domain/drawing/model';
import {saveDrawingSnapshot} from '../domain/drawing/snapshots';
import {useEditor} from '../app/store';
import {useWorkspaceMode} from '../app/workspaceMode';
import {createEmptyProject} from '../app/emptyProject';
import {createArtworkRig,emptyVectorRecording} from '../domain/vectorRecording/model';
const raw=readFileSync(new URL('../assets/hairless-symmetric-two-face.json',import.meta.url),'utf8');
test('bundles the actual authored two-face example without reference pixels or changing the default face',async()=>{
 const base=readFileSync(new URL('../assets/base-face.json',import.meta.url),'utf8'),d=await loadHairlessExample(async()=>raw);expect(d.layers).toHaveLength(13);expect(d.curves).toHaveLength(121);expect(d.fills).toHaveLength(20);expect(d.reference).toBeUndefined();expect(d.layers.some(l=>/刘海|头发|发型|后发/.test(l.name))).toBe(false);expect(d.endpointLinks?.some(l=>l.throughDisplay&&l.joinBrush?.kind==='ARC')).toBe(true);expect(JSON.parse(raw)).toEqual(d);expect(readFileSync(new URL('../assets/base-face.json',import.meta.url),'utf8')).toBe(base);
});
test('imports as a new artwork and preserves an unsaved working copy without overwriting saved artwork',async()=>{
 const art=await loadHairlessExample(async()=>raw),saved=saveDrawingSnapshot({drawing:emptyDrawing()},'Original'),state={...saved,drawing:{...saved.drawing!,mirrorAxisX:.25}},before=JSON.stringify(state),plan=planArtworkImport(state,art,HAIRLESS_EXAMPLE_NAME);
 expect(plan.steps).toHaveLength(1);expect(plan.preservedDraftId).toBeUndefined();expect(plan.state.drawingSnapshots!.items).toHaveLength(2);expect(plan.state.drawingSnapshots!.items[0]).toEqual(saved.drawingSnapshots!.items[0]);expect(plan.state.drawingWorkingCopies![saved.drawingSnapshots!.activeId!].mirrorAxisX).toBe(.25);expect(plan.state.drawing!.curves).toHaveLength(121);expect(JSON.stringify(state)).toBe(before);
 const again=planArtworkImport(plan.state,art,HAIRLESS_EXAMPLE_NAME);expect(again.steps).toHaveLength(1);expect(again.state.drawingSnapshots!.items.at(-1)!.name).toBe(HAIRLESS_EXAMPLE_NAME+' · 2');expect(again.artworkId).not.toBe(plan.artworkId);
});
test('whole import is one undo and preserves unnamed rig ownership on its backup artwork',async()=>{
 const original=useEditor.getState(),mode=useWorkspaceMode.getState().mode;vi.useFakeTimers();try{useWorkspaceMode.getState().setMode('drawing');const source=emptyDrawing(),r=createArtworkRig('$working',source);useEditor.setState({project:{...createEmptyProject(),drawing:source,vectorRecording:{...emptyVectorRecording(),rigs:[r]}},past:[],future:[]});const before=useEditor.getState().project,art=await loadHairlessExample(async()=>raw),plan=planArtworkImport({drawing:sourceForExampleImport(before.drawing,true)},art,HAIRLESS_EXAMPLE_NAME),s=useEditor.getState();s.beginEdit();for(const state of plan.steps)s.setDrawingSnapshotState(state);s.endEdit();expect(useEditor.getState().past).toHaveLength(1);expect(useEditor.getState().project.vectorRecording!.rigs[0].artworkId).toBe(plan.preservedDraftId);expect(useEditor.getState().project.drawingSnapshots!.activeId).toBe(plan.artworkId);s.undo();expect(useEditor.getState().project).toBe(before);s.redo();expect(useEditor.getState().project.drawing!.curves).toHaveLength(121);}finally{vi.runAllTimers();useEditor.setState(original,true);useWorkspaceMode.getState().setMode(mode);vi.useRealTimers();}
});

test('the bundled two face pieces retain their independent white fills and explicit chin route/depth',async()=>{const d=await loadHairlessExample(async()=>raw),halves=d.layers.filter(l=>/面部·[左右]片/.test(l.name));expect(HAIRLESS_EXAMPLE_NAME).toBe('无发·对称双脸片·下颌显线');expect(halves).toHaveLength(2);expect(halves.every(l=>d.fills.some(f=>l.items.includes(f.id)&&f.color==='white'))).toBe(true);expect(d.displayIntervals!.filter(t=>t.displayRoute)).toHaveLength(1);expect(d.displayIntervals!.find(t=>t.displayRoute)!.ranges).toMatchObject([{mode:'SHOW',start:.38526009094373365,end:.6147399090562666}]);expect(d.endpointLinks!.find(l=>l.throughDisplay)!.joinBrush).toEqual({kind:'ARC',trimDistance:.05257222158088604});expect(d.curves.find(c=>c.id==='1a723ec7-9bbe-4c56-8c0f-680d03741aa6')).toMatchObject({depthOffset:1,depthScope:'LAYER'});});

test('explicit front/side example pack preserves old saved/dirty work, front geometry and one Undo',async()=>{
 const {loadArtworkExamplePack,planArtworkExamplePack,MIRROR_EXAMPLE_NAME,SIDE_EXAMPLE_NAME}=await import('../app/artworkExamples'),front=readFileSync(new URL('../assets/hairless-symmetric-two-face-mirror.json',import.meta.url),'utf8'),side=readFileSync(new URL('../assets/right90-reference.json',import.meta.url),'utf8'),pack=await loadArtworkExamplePack(async()=>({front,side}));
 const {mirrorEditing,...geometry}=pack.front;expect(geometry).toEqual(JSON.parse(raw));expect(mirrorEditing).toMatchObject({enabled:true});expect(mirrorEditing!.curvePairs).toHaveLength(54);expect(pack.side.curves).toHaveLength(126);expect(pack.side.layers.some(l=>l.name==='侧面前轮廓·额鼻唇颏')).toBe(true);
 const original=useEditor.getState(),mode=useWorkspaceMode.getState().mode;vi.useFakeTimers();try{useWorkspaceMode.getState().setMode('drawing');const saved=saveDrawingSnapshot({drawing:emptyDrawing()},'Old');useEditor.setState({project:{...createEmptyProject(),...saved,drawing:{...saved.drawing!,mirrorAxisX:.25}},past:[],future:[]});const before=useEditor.getState().project,bytes=JSON.stringify(before),plan=planArtworkExamplePack(before,pack),s=useEditor.getState();s.beginEdit();for(const step of plan.steps)s.setDrawingSnapshotState(step);s.endEdit();const p=useEditor.getState().project;expect(p.drawingSnapshots!.items).toHaveLength(3);expect(p.drawingWorkingCopies![saved.drawingSnapshots!.activeId!].mirrorAxisX).toBe(.25);expect(p.drawingSnapshots!.items.find(a=>a.id===plan.artworkId)!.name).toBe(MIRROR_EXAMPLE_NAME);expect(p.drawingSnapshots!.items.find(a=>a.id===plan.referenceArtworkId)!.name).toBe(SIDE_EXAMPLE_NAME);expect(p.drawingSnapshots!.activeId).toBe(plan.artworkId);expect(p.drawing).toEqual(pack.front);expect(useEditor.getState().past).toHaveLength(1);s.undo();expect(useEditor.getState().project).toBe(before);expect(JSON.stringify(before)).toBe(bytes);s.redo();expect(useEditor.getState().project.drawing).toEqual(pack.front);}finally{vi.runAllTimers();useEditor.setState(original,true);useWorkspaceMode.getState().setMode(mode);vi.useRealTimers();}
});
