import {readFileSync} from 'node:fs';import{expect,test}from'vitest';
import {parseDrawing,shapeOf,curveById,type Point2} from '../domain/drawing/model';
import {setMirrorEditingEnabled} from '../domain/drawing/mirrorCommands';
import {validateMirrorEditing,mirrorWritesForCurves} from '../domain/drawing/mirrorEditing';
import {dragNode} from '../domain/drawing/nodeDrag';import{moveHandle,splitCurve,setMirrorAxis}from'../domain/drawing/commands';
import{finalizeGeometryEdit}from'../domain/drawing/geometryEdit';import{deformDrawing}from'../domain/drawing/deform';
import{displayField,displayPath}from'../domain/drawing/displayIntervals';import{drawingSignature}from'../domain/vectorRecording/model';
import{createWarpGrid,moveWarpNode}from'../domain/vectorWarp/model';import{deformDrawing as warp}from'../domain/vectorWarp/evaluation';
import{saveDrawingSnapshot,snapshotDrawing}from'../domain/drawing/snapshots';
const raw=JSON.parse(readFileSync(new URL('../assets/hairless-symmetric-two-face.json',import.meta.url),'utf8')),recipe=JSON.parse(readFileSync(new URL('../../docs/examples/two-face-mirror-editing-setup.json',import.meta.url),'utf8'));
const source=()=>parseDrawing({...structuredClone(raw),mirrorEditing:structuredClone(recipe.config)});
const jaw='65450d8d-7c62-4d87-b421-616dfbcab097';
function symmetric(d:ReturnType<typeof source>){expect(validateMirrorEditing(d)).toMatchObject({enabled:true,pairCount:54});}
test('configuration/guide-only changes preserve rig geometric signature, while actual mirrored geometry changes it',()=>{const d=source(),off=setMirrorEditingEnabled(d,false);expect(drawingSignature(d)).toBe(drawingSignature(off));expect(drawingSignature(d)).toBe(drawingSignature(parseDrawing(raw)));const movedAxis=setMirrorAxis(off,(d.mirrorAxisX??0)+.1);expect(drawingSignature(movedAxis)).toBe(drawingSignature(d));expect(setMirrorEditingEnabled(movedAxis,true).curves).toEqual(d.curves);const c=curveById(d,jaw),rawMove=moveHandle(d,{curveId:jaw,end:0},[c.handles[0][0]+.01,c.handles[0][1]+.01]),n=finalizeGeometryEdit(d,rawMove,{handles:[{curveId:jaw,end:0,position:rawMove.curves.find(c=>c.id===jaw)!.handles[0]}]});expect(drawingSignature(n)).not.toBe(drawingSignature(d));});
test('pointer node follow is finalized through symmetry before one material transport',()=>{const d=source(),before=JSON.stringify(d),c=curveById(d,jaw),node=c.nodes[0],p=d.nodes.find(n=>n.id===node)!.position,target:Point2=[p[0]+.012,p[1]-.007],rawMove=dragNode(d,node,target,.55),n=finalizeGeometryEdit(d,rawMove,{nodes:[{nodeId:node,position:target}]});symmetric(n);const field=displayField(n,displayPath(n,jaw));expect(field.mask).toHaveLength(1);const cuts=field.mask!.flatMap(([a,b])=>[field.at(a).p,field.at(b).p]);expect(Math.min(...cuts.map(p=>Math.hypot(p[0]-target[0],p[1]-target[1])))).toBeLessThan(1e-10);expect(finalizeGeometryEdit(d,n)).toBe(n);expect(n.fills).toEqual(d.fills);expect(n.layers).toEqual(d.layers);expect(JSON.stringify(d)).toBe(before);});
test('fitted four-corner deformation mirrors final handles and transports both sides with their parameter maps',()=>{const d=source(),layer=d.layers.find(l=>l.name==='右耳')!,ids=d.curves.filter(c=>layer.items.includes(c.id)).map(c=>c.id),points=ids.flatMap(id=>shapeOf(d,id)),xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),min:Point2=[Math.min(...xs)-.01,Math.min(...ys)-.01],max:Point2=[Math.max(...xs)+.01,Math.max(...ys)+.01],quad:[Point2,Point2,Point2,Point2]=[[...min],[max[0],min[1]],[max[0]+.014,max[1]+.008],[min[0],max[1]]],n=deformDrawing(d,ids,{min,max},quad,true).document;symmetric(n);expect(finalizeGeometryEdit(d,n,mirrorWritesForCurves(n,ids))).toBe(n);expect(n.fills).toEqual(d.fills);expect(parseDrawing(n)).toEqual(n);});
test('Recording Warp remains asymmetric even while the source artwork retains enabled Drawing mirror settings',()=>{const d=source(),before=JSON.stringify(d),right=d.layers.find(l=>l.name==='右耳')!,ids=new Set(right.items),left=d.layers.find(l=>l.name==='左耳')!,leftId=left.items.find(id=>d.curves.some(c=>c.id===id))!;let g=createWarpGrid({min:[-2,-2],max:[2,2]});for(let i=0;i<g.nodes.length;i++)g=moveWarpNode(g,i,[g.nodes[i].position[0]+.02,g.nodes[i].position[1]]);const n=warp(d,id=>ids.has(id)?[g]:[],{diagnostics:'preview'}).drawing;expect(shapeOf(n,leftId)).toEqual(shapeOf(d,leftId));expect(shapeOf(n,[...ids].find(id=>d.curves.some(c=>c.id===id))!)[0][0]).not.toBe(shapeOf(d,[...ids].find(id=>d.curves.some(c=>c.id===id))!)[0][0]);expect(JSON.stringify(d)).toBe(before);});
test('saved artworks retain mirror references and disabled topology edits prune affected references',()=>{const d=source(),state=saveDrawingSnapshot({drawing:d},'Mirrored front'),restored=snapshotDrawing(state.drawingSnapshots!,state.drawingSnapshots!.activeId!);expect(parseDrawing(restored)).toEqual(d);const split=splitCurve(setMirrorEditingEnabled(d,false),jaw,.5).document;expect(split.mirrorEditing!.curvePairs).toHaveLength(53);expect(parseDrawing(split)).toEqual(split);});
