import {isAnalytic} from '../domain/curves/model';
import {describe,it,expect} from 'vitest';
import {readFileSync,writeFileSync} from 'node:fs';
import {migrateHeadFrame,toHead,toRelative,mirrorPoint,defaultHeadFrame} from '../domain/head/frame';
import {parseLandmarks} from '../domain/landmarks/persistence';
import {evaluationContext} from '../domain/geometry/evaluation';
import {followEndpoints} from '../domain/curves/geometry';
import {dirtyDescendants} from '../domain/geometry/dependencies';
import {solveContinuity} from '../domain/continuity/solver';
import {installSmoothResult} from '../domain/continuity/evaluation';
import {evaluator} from '../domain/patches/geometry';
import {createLandmarkProject} from '../domain/landmarks/presets';
import type {LandmarkProject} from '../domain/landmarks/model';
const raw=JSON.parse(readFileSync('artifacts/head-frame/source.json','utf8')) as LandmarkProject;
const near=(a:number[],b:number[])=>a.forEach((x,i)=>expect(x).toBeCloseTo(b[i],10));
describe('Loomis frame relative semantics',()=>{
 it('migration preserves all source controls and evaluated points, with unchanged handles/fullness',()=>{const p=migrateHeadFrame(raw),a=evaluationContext(raw),b=evaluationContext(p);for(const l of raw.landmarks)near(a.pointPosition(l.id),b.pointPosition(l.id));for(const c of raw.curves)a.curveControls(c.id).forEach((v,i)=>near(v,b.curveControls(c.id)[i]));expect(p.curves).toBe(raw.curves);expect(p.patches).toBe(raw.patches);expect(p.landmarks.some(l=>l.placement.kind==='WORLD')).toBe(false);});
 it('migration keeps final Fair + Fullness surface within solver numerical tolerance',()=>{const p=migrateHeadFrame(raw);for(const q of [raw,p])installSmoothResult(q,solveContinuity(q));let max=0;for(const x of raw.patches!)for(let i=1;i<10;i++)for(let j=1;j<10;j++){const u=i/10,v=j/10;if(x.type==='tri'&&u+v>=1)continue;const a=evaluator(raw,x)(u,v),b=evaluator(p,x)(u,v);max=Math.max(max,Math.hypot(...a.map((v,k)=>v-b[k])));}writeFileSync('artifacts/head-frame/migration-error.json',JSON.stringify({maxFinalSurfaceDistance:max,solverTolerance:5e-4},null,2));expect(max).toBeLessThan(5e-4);});
 it.each(['radiusX','radiusY','radiusZ'] as const)('%s propagates through graph without rewriting relative parameters',axis=>{const p=migrateHeadFrame(raw),q=followEndpoints(p,{...p,headFrame:{...p.headFrame!,[axis]:p.headFrame![axis]*1.3}}),d=dirtyDescendants(p,q);expect(d.points.size).toBe(raw.landmarks.length);expect(d.curves.size).toBe(raw.curves.length);expect(d.patches.size).toBe(raw.patches!.length);expect(q.landmarks).toBe(p.landmarks);expect(q.patches).toBe(p.patches);for(const c of q.curves)if((c.role==='canonical'&&!isAnalytic(c))){const old=p.curves.find(x=>x.id===c.id)!;if((old.role==='canonical'&&!isAnalytic(old))){expect(c.shape.startHandle).toEqual(old.shape.startHandle);expect(c.shape.endHandle).toEqual(old.shape.endHandle);}}expect(parseLandmarks(JSON.stringify(q)).headFrame).toEqual(q.headFrame);});
 it('relative coordinates outside unit ellipsoid are retained and save/load is stable',()=>{const p=parseLandmarks(JSON.stringify(raw));expect(p.landmarks.some(l=>l.placement.kind==='FRAME_RELATIVE'&&l.placement.position.some(v=>Math.abs(v)>1))).toBe(true);expect(parseLandmarks(JSON.stringify(p))).toEqual(p);});
 it('frame-local reflection works with translated and rotated frame',()=>{const p=migrateHeadFrame(createLandmarkProject());p.headFrame={...defaultHeadFrame(),center:[2,3,4],orientation:[0,0,Math.sin(.3),Math.cos(.3)]};const v:[number,number,number]=[.3,-1.4,.8];near(toRelative(p,toHead(p,v)),v);near(mirrorPoint(p,toHead(p,v)),toHead(p,[-v[0],v[1],v[2]]));});
 it('rejects missing/degenerate frame rather than guessing',()=>{const p=migrateHeadFrame(createLandmarkProject());expect(()=>parseLandmarks(JSON.stringify({...p,headFrame:undefined}))).toThrow();expect(()=>parseLandmarks(JSON.stringify({...p,headFrame:{...p.headFrame,radiusX:0}}))).toThrow();});
});
