import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {isValidElement,type ReactElement} from 'react';
import NumericSlider from '../ui/shared/NumericSlider';
const hooks=vi.hoisted(()=>({refs:[] as {current:any}[],index:0,cleanups:[] as (()=>void)[]}));
vi.mock('react',async original=>({...await original<typeof import('react')>(),useRef:(value:any)=>hooks.refs[hooks.index++]??(hooks.refs[hooks.index-1]={current:value}),useState:(value:any)=>[value,vi.fn()],useCallback:(fn:any)=>fn,useEffect:(fn:()=>void|(()=>void))=>{const cleanup=fn();if(cleanup)hooks.cleanups.push(cleanup);}}));
vi.mock('../ui/i18n',()=>({uiText:(value:string)=>value}));
type Props={children?:unknown;[key:string]:any};
function elements(value:unknown):ReactElement<Props>[] {if(Array.isArray(value))return value.flatMap(elements);return isValidElement<Props>(value)?[value,...elements(value.props.children)]:[];}
beforeEach(()=>{hooks.refs=[];hooks.index=0;hooks.cleanups=[];vi.stubGlobal('window',{addEventListener:vi.fn(),removeEventListener:vi.fn()});vi.stubGlobal('document',{addEventListener:vi.fn(),removeEventListener:vi.fn()});vi.stubGlobal('cancelAnimationFrame',vi.fn());vi.stubGlobal('requestAnimationFrame',vi.fn(()=>1));});
afterEach(()=>vi.unstubAllGlobals());
const key=(value:string,extra={})=>({key:value,ctrlKey:false,metaKey:false,shiftKey:false,altKey:false,repeat:false,preventDefault:vi.fn(),stopPropagation:vi.fn(),...extra});
function harness(){const change=vi.fn(),commit=vi.fn(),cancel=vi.fn(),undo=vi.fn(),redo=vi.fn(),start=vi.fn();const tree=NumericSlider({label:'Radius',value:.2,min:0,max:1,onChange:change,onEditStart:start,onEditEnd:commit,onEditCancel:cancel,onUndo:undo,onRedo:redo}),input=elements(tree).find(value=>value.props.type==='range')!;input.props.ref.current={hasPointerCapture:()=>false};return {input:input.props,change,commit,cancel,undo,redo,start};}
it('accepts a held scalar target once and treats release cleanup as visual only',()=>{const h=harness();h.input.onKeyDown(key('ArrowRight'));expect(h.change).toHaveBeenCalledTimes(1);h.input.onKeyUp(key('ArrowRight'));h.input.onLostPointerCapture();expect(h.start).toHaveBeenCalledTimes(1);expect(h.commit).toHaveBeenCalledTimes(1);expect(h.cancel).not.toHaveBeenCalled();});
it.each(['Escape','undo','redo','pointer-cancel','unmount'])('%s retires an active preview without committing it or moving history',action=>{const h=harness();h.input.onKeyDown(key('ArrowRight'));if(action==='Escape')h.input.onKeyDown(key('Escape'));else if(action==='undo'||action==='redo')h.input.onKeyDown(key(action==='undo'?'z':'y',{ctrlKey:true}));else if(action==='pointer-cancel')h.input.onPointerCancel();else hooks.cleanups.forEach(fn=>fn());h.input.onKeyUp(key('ArrowRight'));expect(h.cancel).toHaveBeenCalledTimes(1);expect(h.commit).not.toHaveBeenCalled();expect(h.undo).not.toHaveBeenCalled();expect(h.redo).not.toHaveBeenCalled();});
it('dispatches idle Ctrl+Y and Ctrl+Z once and consumes the event',()=>{const h=harness(),undo=key('z',{ctrlKey:true}),redo=key('y',{ctrlKey:true});h.input.onKeyDown(undo);h.input.onKeyDown(redo);expect(h.undo).toHaveBeenCalledTimes(1);expect(h.redo).toHaveBeenCalledTimes(1);expect(undo.stopPropagation).toHaveBeenCalledOnce();expect(redo.stopPropagation).toHaveBeenCalledOnce();});
