import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {expect,test,vi} from 'vitest';
import {createEmptyProject} from '../app/emptyProject';
import {useEditor} from '../app/store';
import {prepareSnapshotBatch} from '../app/recordingSnapshotApi';
import {emptyDrawing} from '../domain/drawing/model';
import {addLayer,createCurve} from '../domain/drawing/commands';
import {saveDrawingSnapshot} from '../domain/drawing/snapshots';
import {ensureRecordingSnapshots} from '../domain/recordingSnapshot/migration';
import {evaluateRecordingSnapshot} from '../domain/recordingSnapshot/evaluation';
import SnapshotRecordingWorkspace,{retainSnapshotDrawingSelection} from '../ui/vectorRecording/SnapshotRecordingWorkspace';
vi.mock('../app/store',async original=>{const m=await original<typeof import('../app/store')>();return {...m,useEditor:Object.assign((select?:(s:ReturnType<typeof m.useEditor.getState>)=>unknown)=>select?select(m.useEditor.getState()):m.useEditor.getState(),m.useEditor)};});
test('changing view keeps canonical curve/layer selection and drops only absent targets',()=>{const drawing=fixture().drawing!,curve=drawing.curves[0],layer=drawing.layers[0],selection={ids:[curve.id,'missing'],layers:[layer.id,'missing'],handle:{curveId:curve.id,end:0 as const},node:curve.nodes[0]};const next=retainSnapshotDrawingSelection(selection,drawing);expect(next.ids).toEqual([curve.id]);expect(next.layers).toEqual([layer.id]);expect(next.handle).toEqual(selection.handle);expect(next.node).toBe(curve.nodes[0]);expect(selection.ids).toHaveLength(2);expect(retainSnapshotDrawingSelection(next,emptyDrawing()).ids).toEqual([]);});
function fixture(){let drawing=addLayer(emptyDrawing(),'Jaw');drawing=createCurve(drawing,drawing.layers[0].id,[[0,0],[.1,.2],[.4,.3],[.5,.1]],.01,'jaw');const project=ensureRecordingSnapshots({...createEmptyProject(),...saveDrawingSnapshot({drawing},'Source face')});return project;}
test('native workspace starts with an empty view and persistent source list, without mutating geometry or tracks',()=>{const previous=useEditor.getState(),project=fixture();try{useEditor.setState({project,past:[],future:[]});const before=JSON.stringify(project),html=renderToStaticMarkup(createElement(SnapshotRecordingWorkspace));expect(html).toContain('recording-snapshot-v2');expect(html).toContain('class="vector-recording vr-view-workflow"');expect(html).toContain('snapshot-update-view');expect(html).toContain('Source face');expect(html).toContain('scene-angle-pad');expect(html).toContain('scene-onion-controls');expect(JSON.stringify(project)).toBe(before);const workspace=project.recordingSnapshots,recording=workspace.recordings[0];expect(evaluateRecordingSnapshot(workspace,recording.id).drawing.curves).toHaveLength(0);expect(recording.tracks).toHaveLength(0);}finally{useEditor.setState(previous,true);}});
test('cut-paste into first view and inherited second view keep canonical curve identity and sparse keys',()=>{const project=fixture(),workspace=project.recordingSnapshots,source=workspace.snapshots.find(s=>s.kind==='drawing')!,sourceBytes=JSON.stringify(source),libraryBytes=JSON.stringify(workspace.library);const first=prepareSnapshotBatch(project,{commands:[{op:'moveLayers',sourceSnapshotId:source.id,layerIds:source.layers.map(l=>l.id)},{op:'setAngle',angle:{x:90,y:0}},{op:'createSnapshot',name:'Profile'}]}),next=first.recordingSnapshots,r=next.recordings[0];expect(r.snapshotIds).toHaveLength(2);expect(r.tracks).toHaveLength(0);expect(JSON.stringify(next.library)).toBe(libraryBytes);expect(JSON.stringify(next.snapshots.find(s=>s.id===source.id))).toBe(sourceBytes);const zero=evaluateRecordingSnapshot(next,r.id,{angle:{x:0,y:0}}),profile=evaluateRecordingSnapshot(next,r.id,{angle:{x:90,y:0}});expect(profile.drawing.curves.map(c=>c.id)).toEqual(zero.drawing.curves.map(c=>c.id));expect(profile.drawing.nodes).toEqual(zero.drawing.nodes);expect(profile.drawing.curves).toHaveLength(1);});

test('the human workspace emphasizes its current snapshot and opens sources only by explicit choice, with Warp controls hidden',()=>{const previous=useEditor.getState(),project=fixture();try{useEditor.setState({project,past:[],future:[]});const html=renderToStaticMarkup(createElement(SnapshotRecordingWorkspace));expect(html).toContain('当前视角快照');expect(html).toContain('snapshot-show-source');expect(html).not.toContain('data-testid="snapshot-cut-source"');expect(html).not.toContain('aria-label="Active Warp"');expect(html).not.toContain('全选网格');expect(html).not.toContain('Warp Bézier 柄');expect(html).toContain('vr-tool-select');expect(html).toContain('vr-tool-direct');}finally{useEditor.setState(previous,true);}});

test('endpoint-pair workspace offers inverse correction at thirty degrees without arbitrary Add View or geometry keys',()=>{
 const previous=useEditor.getState();let project=fixture();try{const workspace=project.recordingSnapshots,source=workspace.snapshots.find(s=>s.kind==='drawing')!,start=workspace.recordings[0].snapshotIds[0];
  const assembly=prepareSnapshotBatch(project,{commands:[{op:'moveLayers',sourceSnapshotId:source.id,layerIds:source.layers.map(l=>l.id)},{op:'setAngle',angle:{x:-90,y:0}},{op:'createSnapshot',name:'Side'}]});project={...project,recordingSnapshots:assembly.recordingSnapshots};
  const original=assembly.recordingSnapshots.recordings[0],end=original.snapshotIds[1],made=prepareSnapshotBatch(project,{commands:[{op:'createEndpointPairRecording',startSnapshotId:start,endSnapshotId:end}]});project={...project,recordingSnapshots:made.recordingSnapshots};
  const preview=prepareSnapshotBatch(project,{commands:[{op:'setAngle',angle:{x:-30,y:0}}]});project={...project,recordingSnapshots:preview.recordingSnapshots};useEditor.setState({project,past:[],future:[]});
  const before=JSON.stringify(project),html=renderToStaticMarkup(createElement(SnapshotRecordingWorkspace));expect(html).toContain('endpoint-correction-position');expect(html).toContain('snapshot-save-correction');expect(html).toContain('endpoint-correction-editor');expect(html).not.toContain('data-testid="snapshot-create-view"');expect(html).not.toContain('data-testid="interpolation-weight-editor"');expect(html).toContain('反推修正位置');expect(JSON.stringify(project)).toBe(before);
  const pair=project.recordingSnapshots.recordings.find(r=>r.mode==='endpoint-pair')!;expect(pair.snapshotIds).toHaveLength(2);expect(pair.tracks).toHaveLength(0);
 }finally{useEditor.setState(previous,true);}
});
