import {isValidElement,type ReactElement} from 'react';
import {beforeEach,afterEach,test,expect,vi} from 'vitest';
import {createCurve} from '../domain/drawing/commands';
import {emptyDrawing,nodeAt,type DrawingDocument,type Point2} from '../domain/drawing/model';
import SceneWarpCanvas,{type RecordingCanvasTool} from '../ui/vectorRecording/SceneWarpCanvas';
import type {DrawingSelection} from '../ui/drawing/session';
const hooks=vi.hoisted(()=>({states:[] as unknown[],refs:[] as {current:unknown}[],deps:[] as (unknown[]|undefined)[],cleanups:[] as ((()=>void)|void)[],effects:[] as (()=>void)[],stateIndex:0,refIndex:0,effectIndex:0,dirty:false}));
vi.mock('react',async original=>({...await original<typeof import('react')>(),useState:(initial:unknown)=>{const i=hooks.stateIndex++;if(!(i in hooks.states))hooks.states[i]=typeof initial==='function'?initial():initial;return [hooks.states[i],(next:unknown)=>{const value=typeof next==='function'?next(hooks.states[i]):next;if(!Object.is(value,hooks.states[i])){hooks.states[i]=value;hooks.dirty=true;}}];},useRef:(initial:unknown)=>hooks.refs[hooks.refIndex++]??(hooks.refs[hooks.refIndex-1]={current:initial}),useCallback:(fn:unknown)=>fn,useMemo:(fn:()=>unknown)=>fn(),useEffect:(fn:()=>void|(()=>void),deps?:unknown[])=>{const i=hooks.effectIndex++,previous=hooks.deps[i];if(!previous||!deps||deps.some((value,j)=>!Object.is(value,previous[j]))){hooks.deps[i]=deps;hooks.effects.push(()=>{hooks.cleanups[i]?.();hooks.cleanups[i]=fn();});}}}));
vi.mock('../ui/drawing/session',async original=>{const actual=await original<typeof import('../ui/drawing/session')>();return {...actual,useDrawing:Object.assign((selector:(state:ReturnType<typeof actual.useDrawing.getState>)=>unknown)=>selector(actual.useDrawing.getState()),actual.useDrawing)};});
class Target{closest(){return null;}}
const listeners=new Map<string,(event:unknown)=>void>();
beforeEach(()=>{hooks.states=[];hooks.refs=[];hooks.deps=[];hooks.cleanups=[];listeners.clear();vi.stubGlobal('Element',Target);vi.stubGlobal('window',{addEventListener:(name:string,fn:(event:unknown)=>void)=>listeners.set(name,fn),removeEventListener:(name:string,fn:unknown)=>{if(listeners.get(name)===fn)listeners.delete(name);}});});
afterEach(()=>vi.unstubAllGlobals());
type Props={children?:unknown;[key:string]:any};
const elements=(tree:unknown):ReactElement<Props>[]=>Array.isArray(tree)?tree.flatMap(elements):isValidElement<Props>(tree)?[tree,...elements(tree.props.children)]:[];
function harness(enabled=true){
 let source=emptyDrawing();source.layers=[{id:'left',name:'Left',visible:true,locked:false,items:[]},{id:'right',name:'Right',visible:true,locked:false,items:[]}];source=createCurve(source,'left',[[-1,0],[-.7,.2],[-.3,.2],[0,0]],.02,'A','a');source=createCurve(source,'right',[[.3,.3],[.5,.6],[.8,.6],[1,.3]],.03,'B','b');
 let drawing=source,layerId='left',historyKey={},targetKey='view-0',tool:RecordingCanvasTool='select',selection:DrawingSelection={ids:[]},editable=enabled;const error=vi.fn(),preview=vi.fn(),commit=vi.fn((before:DrawingDocument,next:DrawingDocument)=>{expect(before).toBe(drawing);drawing=next;historyKey={};return historyKey;}),svg={focus:vi.fn(),setPointerCapture:vi.fn(),hasPointerCapture:()=>false,getBoundingClientRect:()=>({left:0,top:0})};let all:ReactElement<Props>[]=[];
 const render=()=>{let count=0;do{hooks.dirty=false;hooks.stateIndex=0;hooks.refIndex=0;hooks.effectIndex=0;hooks.effects=[];all=elements(SceneWarpCanvas({source,drawing,targetKey:`${targetKey}/${layerId}`,label:'Test',zh:false,onPreview:preview,onCommit:vi.fn(),showWarpTools:false,selection,interaction:{tool,onToolChange:next=>{tool=next;}},topology:{editable,onSplit:vi.fn(),relations:{editable,disabledReason:'Real snapshot required',targetKey,historyKey,layerId,onCommit:commit,onSelection:next=>{selection=next;},onError:error}}}));all.find(element=>element.props['data-testid']==='vr-scene-canvas')!.props.ref.current=svg;hooks.effects.forEach(fn=>fn());if(++count>8)throw Error('Effects did not settle');}while(hooks.dirty);};render();
 const element=(testId:string)=>all.find(element=>element.props['data-testid']===testId)!,targets=()=>all.filter(element=>element.props['data-testid']==='recording-endpoint-target');return {source,render,element,targets,error,commit,preview,drawing:()=>drawing,selection:()=>selection,layer:()=>{layerId='right';render();},navigate:()=>{targetKey='view-1';render();},sourceChange:()=>{historyKey={};render();},readonly:()=>{editable=false;render();}};
}
const pointer=(point:Point2)=>({button:0,pointerId:1,clientX:point[0],clientY:point[1],shiftKey:false,altKey:false,stopPropagation:vi.fn(),preventDefault:vi.fn()});
const xy=(element:ReactElement<Props>):Point2=>[element.props.x+4,element.props.y+4];
function begin(h:ReturnType<typeof harness>){h.element('vr-tool-link').props.onClick();h.render();const first=h.targets().find(element=>element.props['data-end']===1)!;h.element('vr-scene-canvas').props.onPointerDown(pointer(xy(first)));h.render();return first;}
test('two clicks use Drawing’s actual local link command and keep the first endpoint across a layer switch',()=>{
 const h=harness(),saved=JSON.stringify(h.source);begin(h);expect(h.selection().ids).toEqual(['a']);h.layer();const second=h.targets().find(element=>element.props['data-end']===0)!,point=xy(second);h.element('vr-scene-canvas').props.onPointerMove(pointer(point));h.render();const paint=elements(h.element('vr-scene-canvas')).find(element=>element.props.curveDown)!;expect(nodeAt(paint.props.d,{curveId:'b',end:0}).position).toEqual([0,0]);expect(h.commit).not.toHaveBeenCalled();
 h.element('vr-scene-canvas').props.onPointerDown(pointer(point));h.render();expect(h.commit).toHaveBeenCalledTimes(1);expect(h.drawing().endpointLinks).toHaveLength(1);expect(nodeAt(h.drawing(),{curveId:'a',end:1}).id).not.toBe(nodeAt(h.drawing(),{curveId:'b',end:0}).id);expect(h.selection().ids).toEqual(['b']);expect(JSON.stringify(h.source)).toBe(saved);expect(h.error).not.toHaveBeenCalled();
});
test.each(['escape','navigate','source','tool'])('%s cancels an incomplete link without authoring a relation',action=>{
 const h=harness();begin(h);if(action==='escape')listeners.get('keydown')!({key:'Escape',code:'Escape',target:new Target(),preventDefault:vi.fn()});else if(action==='navigate')h.navigate();else if(action==='source')h.sourceChange();else {h.element('vr-tool-direct').props.onClick();h.render();h.element('vr-tool-link').props.onClick();}h.render();h.layer();h.element('vr-scene-canvas').props.onPointerDown(pointer(xy(h.targets()[0])));h.render();expect(h.commit).not.toHaveBeenCalled();
});
test('correction-frame capability disables linking and its click handler cannot commit',()=>{const h=harness(false);expect(h.element('vr-tool-link').props.disabled).toBe(true);expect(h.element('vr-tool-link').props.title).toBe('Real snapshot required');h.element('vr-tool-link').props.onClick();h.render();expect(h.targets()).toEqual([]);expect(h.commit).not.toHaveBeenCalled();});
