import {isSection} from '../domain/curves/model';
import {test,expect} from 'vitest';
import {ensureScaffold,RING_X,RING_Y,RING_Z,SIDE_R,SIDE_L,HELMET,roles,scaffoldPointRelative,helmetRelative,sideShellX} from '../domain/head/scaffold';
import {helmetMesh} from '../domain/head/helmet';
import {createLandmarkProject} from '../domain/landmarks/presets';
import {migrateHeadFrame,toRelative,mirrorPoint} from '../domain/head/frame';
import {evaluationContext,pointPosition} from '../domain/geometry/evaluation';
import {curveMemberships} from '../domain/head/membership';
import {eligibleAnchors,boundaryGeometry,mirrorBoundary} from '../domain/patches/boundary';
import {parseLandmarks} from '../domain/landmarks/persistence';
import {deleteClosure,dirtyDescendants} from '../domain/geometry/dependencies';
import {duplicateRing} from '../domain/head/duplicateRing';
import {duplicateLandmark} from '../domain/landmarks/management';
import {setLoomisOffset} from '../domain/head/offset';
import {addOnCurvePoint} from '../domain/landmarks/placement';
import {contourSource} from '../domain/contour/source';
function fixture(){const p=migrateHeadFrame(createLandmarkProject());return ensureScaffold({...p,landmarks:[],curves:[],patches:[],centerlineOrder:[]});}
test('16 derived points, three logical main rings, side pair, additive deterministic migration',()=>{const p=fixture();expect(p.landmarks).toHaveLength(16);expect(p.curves).toHaveLength(8);expect(p.loomisScaffold).toMatchObject({sidePosition:.75,roundness:.5,apexHeight:.85,visible:true});expect(ensureScaffold(p)).toEqual(p);const legacy=migrateHeadFrame(createLandmarkProject()),a=ensureScaffold(legacy);expect(a.landmarks.filter(l=>!l.systemRole)).toEqual(legacy.landmarks);expect(a.loomisScaffold?.visible).toBe(true);expect(parseLandmarks(JSON.stringify(p))).toMatchObject({loomisScaffold:p.loomisScaffold,curves:p.curves,landmarks:p.landmarks});});
test('intersection membership on every host, exact span endpoint and mirror span',()=>{const p=fixture(),ctx=evaluationContext(p);for(const l of p.landmarks.filter(l=>!l.systemRole?.startsWith('APEX'))){const ms=curveMemberships(p,l.id);expect(ms.length).toBeGreaterThanOrEqual(2);for(const m of ms){expect(eligibleAnchors(p,m.curveId).some(x=>x.id===l.id)).toBe(true);expect(Math.hypot(...ctx.curve(m.curveId).evaluate(m.t).map((v,i)=>v-pointPosition(p,l.id)[i]))).toBeLessThan(1e-10);}}
 const a=p.landmarks.find(l=>l.systemRole==='BROW')!,b=p.landmarks.find(l=>l.systemRole==='SIDE_R_1')!,use={curveId:RING_Y,startLandmarkId:a.id,endLandmarkId:b.id};const g=boundaryGeometry(p,use),other=boundaryGeometry(p,mirrorBoundary(p,use));for(let i=0;i<=10;i++)expect(Math.hypot(...mirrorPoint(p,g.evaluate(i/10)).map((v,j)=>v-other.evaluate(i/10)[j]))).toBeLessThan(1e-10);});
test('side movement updates intersections and Apex; Apex is exactly on final Helmet',()=>{const p=fixture(),next=ensureScaffold({...p,loomisScaffold:{...p.loomisScaffold!,sidePosition:.6,roundness:.4}});const dirty=dirtyDescendants(p,next);expect(dirty.curves.has(SIDE_R)).toBe(true);for(const l of next.landmarks.filter(l=>l.systemRole?.startsWith('APEX'))){if(l.placement.kind!=='LOOMIS_SCAFFOLD')throw Error('Expected scaffold placement');const v=scaffoldPointRelative(next,l.placement.role),s=next.loomisScaffold!;expect(Math.abs(v[0])).toBe(sideShellX(s,v[1],v[2]));expect(v[1]).toBeCloseTo(.85*.8,12);expect(pointPosition(p,l.id)).not.toEqual(pointPosition(next,l.id));}});
test('Helmet field is position/first-derivative continuous on side ring, mirrored finite mesh',()=>{const p=fixture(),s=p.loomisScaffold!,c=s.sidePosition;const at=(x:number,a:number)=>helmetRelative(s,[x,Math.sqrt(1-x*x)*Math.cos(a),Math.sqrt(1-x*x)*Math.sin(a)]);for(const a of [0,.4,1,2,3]){const eps=1e-5,left=at(c-eps,a),center=at(c,a),right=at(c+eps,a);center.forEach((v,i)=>expect(Math.abs((right[i]-v)/eps-(v-left[i])/eps)).toBeLessThan(.002));}const mesh=helmetMesh(p);expect(mesh.vertices.length).toBeGreaterThan(100);expect(mesh.vertices.flat().every(Number.isFinite)).toBe(true);expect(contourSource(p).mesh.triangles.length).toBe(mesh.triangles.length);});
test('system topology cannot delete, ordinary duplicate can; composite only one closed provider',()=>{const p=fixture();expect(()=>deleteClosure(p,[`curve:${RING_Y}`])).toThrow();expect(()=>deleteClosure(p,[`point:${p.landmarks[0].id}`])).toThrow();const d=duplicateRing(p,RING_Y);expect(d.project.curves).toHaveLength(p.curves.length+1);const c=d.project.curves.at(-1)!;expect(c).toMatchObject({logicalRing:'COMPOSITE'});expect('systemRole' in c).toBe(false);expect(evaluationContext(d.project).curve(c.id).closed).toBe(true);expect(deleteClosure(d.project,[`curve:${c.id}`]).curves).toHaveLength(8);const side=duplicateRing(p,SIDE_R);expect(side.project.curves).toHaveLength(p.curves.length+2);expect(deleteClosure(side.project,[`curve:${side.selectedId}`]).curves).toHaveLength(8);const point=duplicateLandmark(p,p.landmarks[0].id,'copy');expect(point.project.landmarks.at(-1)!.systemRole).toBeUndefined();expect(()=>setLoomisOffset(p,p.landmarks[0].id,0,.1)).toThrow();});
test('logical Ring ON_CURVE pair shares host; s and roundtrip remain valid',()=>{const r=addOnCurvePoint(fixture(),RING_Y);expect(r.project.landmarks).toHaveLength(18);expect(()=>parseLandmarks(JSON.stringify(r.project))).not.toThrow();});
test('self-symmetric Ring Cap hosts symmetric points without false CENTERLINE classification',async()=>{const {addCap,addCapPoint,setCapPoint}=await import('../domain/head/caps');let p=fixture();p=addCap(p,RING_Y);const r=addCapPoint(p,p.loomisCaps![0].id,.2,.4),q=setCapPoint(r.project,r.selectedId,.3,.5);expect(q.landmarks.at(-2)?.type).toBe('RIGHT');expect(()=>parseLandmarks(JSON.stringify(q))).not.toThrow();});
test('high resolution Contour is finite/deterministic across front, oblique, side and top',async()=>{const {silhouette}=await import('../domain/contour/silhouette'),{writeFileSync,mkdirSync}=await import('node:fs');const p=fixture(),mesh=contourSource(p).mesh;const views:[string,[number,number,number,number]][]=[['Front',[0,0,0,1]],['45',[0,Math.sin(Math.PI/8),0,Math.cos(Math.PI/8)]],['Side',[0,Math.SQRT1_2,0,Math.SQRT1_2]],['Top',[-Math.SQRT1_2,0,0,Math.SQRT1_2]]];const parts=views.map(([name,q],i)=>{const s=silhouette(mesh,q,768);expect(s.coveredPixels).toBeGreaterThan(1000);expect(s.paths.length).toBeGreaterThan(0);expect(s.paths.flat(2).every(Number.isFinite)).toBe(true);return `<g transform="translate(${i*400},0)"><text x="12" y="20">${name}</text><g transform="translate(0,25) scale(.5)">${s.paths.map(path=>`<polyline points="${path.map(v=>v.join(',')).join(' ')}" fill="none" stroke="black" stroke-width="2"/>`).join('')}</g></g>`;});mkdirSync('artifacts/scaffold',{recursive:true});writeFileSync('artifacts/scaffold/contours.svg',`<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="420"><rect width="1600" height="420" fill="white"/>${parts.join('')}</svg>`);writeFileSync('artifacts/scaffold/default.json',JSON.stringify(p,null,2));});
test('Helmet mesh symmetry and frame resize, copied rings/cap/offset/Region keep legacy support',async()=>{const {addCap,addCapPoint}=await import('../domain/head/caps'),{setLoomisOffset}=await import('../domain/head/offset'),{regionCandidates}=await import('../domain/head/regions');let p=fixture();const m=helmetMesh(p),keys=new Set(m.vertices.map(v=>toRelative(p,v).map(n=>n.toFixed(8)).join(',')));for(const v of m.vertices){const q=toRelative(p,v);expect(keys.has([-q[0],q[1],q[2]].map(n=>(Math.abs(n)<1e-9?0:n).toFixed(8)).join(','))).toBe(true);}const c=duplicateRing(p,SIDE_R);p=addCap(c.project,c.selectedId);const a=addCapPoint(p,p.loomisCaps![0].id,.2,.3);p=setLoomisOffset(a.project,a.selectedId,0,.2);expect(()=>parseLandmarks(JSON.stringify(p))).not.toThrow();expect(regionCandidates(p,[RING_X,RING_Y]).length).toBeGreaterThan(0);});

test('composite copy has shared endpoint identities, follows offset and deletes as a unit',()=>{const d=duplicateRing(fixture(),RING_Y),p=d.project,c=p.curves.find(c=>c.id===d.selectedId)!;if(!isSection(c)||c.role!=='canonical')throw Error();const ends=c.logicalEndpoints!;expect(ends).toHaveLength(2);expect(()=>parseLandmarks(JSON.stringify(p))).not.toThrow();for(const id of ends){expect(eligibleAnchors(p,c.id).some(l=>l.id===id)).toBe(true);expect(()=>setLoomisOffset(p,id,0,.1)).toThrow();const copy=duplicateLandmark(p,id,'endpoint copy');expect(()=>parseLandmarks(JSON.stringify(copy.project))).not.toThrow();}const q=deleteClosure(p,[`point:${ends[0]}`]);expect(q.curves).toHaveLength(8);expect(q.landmarks).toHaveLength(16);});
