import {expect,test} from 'vitest';
import {createEmptyProject} from '../../app/emptyProject';
import {prepareSnapshotEdit,snapshotEditContext} from '../../app/snapshotEditTransaction';
import {createCurveSplitIntent,applyCurveSplitIntent,mapCurveSplitIntent} from '../../domain/drawing/layerEditIntent';
import {emptyDrawing,shapeOf,type DrawingDocument} from '../../domain/drawing/model';
import {neutralBend} from '../../domain/deformation/coons';
import {ensureRecordingSnapshots} from '../../domain/recordingSnapshot/migration';
import {canonicalElementId,drawingSnapshotForArtwork} from '../../domain/recordingSnapshot/sources';
import {emptyRecordingSnapshot,emptySnapshotRecording} from '../../domain/recordingSnapshot/model';
import {resolveSnapshot,evaluateRecordingSnapshot} from '../../domain/recordingSnapshot/evaluation';
import {createSnapshotAngleGraph} from '../../domain/recordingSnapshot/angleGraph';
import {evaluatedControlParameter} from '../../domain/drawing/evaluatedDeformation';
import {createSnapshotSplitParameterField,recordSnapshotSplitParameterRanges,resolveSnapshotFitParameter} from '../../domain/recordingSnapshot/splitParameterField';
import {remapSnapshotMaterialPartitions} from '../../domain/recordingSnapshot/materialSplit';
import {remapSnapshotMaterialPathLineages} from '../../domain/recordingSnapshot/materialPathLineages';
import {transportSnapshotSimplexMaterial} from '../../domain/recordingSnapshot/simplexMaterial';
import {displayField,displayPath} from '../../domain/drawing/displayIntervals';
import {point} from '../../domain/drawing/sampling';
import {subcurve} from '../../domain/drawing/roundedJoin';
const cid=(id:string)=>canonicalElementId('$working',id),curveId=cid('curve'),nativeT=.371;
function fixture(scope:'CURVE'|'PATH'='CURVE',ends:readonly [number,number]=[.15,.82]){
 const drawing:DrawingDocument={...emptyDrawing(),nodes:[{id:'a',position:[-.8,-.3]},{id:'b',position:[.7,.5]}],curves:[{id:'curve',name:'Curve',nodes:['a','b'],handles:[[-.6,.6],[.4,-.5]],width:.01,visible:true,locked:false}],layers:[{id:'layer',name:'Layer',items:['curve'],visible:true,locked:false}],displayIntervals:[{id:'material',...(scope==='CURVE'?{scope}:{}),anchor:{id:'curve',reverse:false},ranges:[{id:'range',start:ends[0],end:ends[1]}]}]};
 const project=ensureRecordingSnapshots({...createEmptyProject(),drawing}),workspace=project.recordingSnapshots,source=drawingSnapshotForArtwork(workspace,'$working')!,view=emptyRecordingSnapshot('view'),bend=neutralBend();bend.handles[1][0][0]=1.25;
 view.layers=[{kind:'reference',id:'slot',name:'Curve',baseSnapshotId:source.id,baseLayerId:cid('layer')}];view.deformation.layerDomains=[{kind:'h-coons',id:'cage',layerIds:['slot'],restRect:{min:[-1,-1],max:[1,1]},quad:[[-1,-1],[1,-.7],[.7,1],[-.9,.8]],bend}];workspace.snapshots.push(view);
 const other=emptyRecordingSnapshot('other-view','Other','view',{x:90,y:0});other.layers=structuredClone(view.layers);workspace.snapshots.push(other);const recording=emptySnapshotRecording('recording');recording.mode='triangulated';recording.snapshotIds=['view','other-view'];recording.activeSnapshotId='view';recording.angleGraph=createSnapshotAngleGraph([{snapshotId:'view',angle:{x:0,y:0}},{snapshotId:'other-view',angle:{x:90,y:0}}]);workspace.recordings=[recording];workspace.activeRecordingId=recording.id;
 let serial=0;const intent=createCurveSplitIntent(drawing,'curve',nativeT,{allocateId:()=>`proof-${++serial}`}),canonical=mapCurveSplitIntent(intent,cid),bases=recording.snapshotIds.map(snapshotId=>({snapshotId,drawing:resolveSnapshot(workspace,snapshotId,{useDraft:false}).drawing}));
 return {project,workspace,drawing,recording,intent,canonical,bases};
}
test('one cached parent arc table gives the existing material-law cut and preserves the whole parent',()=>{
 const f=fixture(),cuts=f.bases.map(basis=>evaluatedControlParameter(basis.drawing,curveId,nativeT));expect(cuts[0]).toBeCloseTo(.3470678634323764,14);
 for(const angle of [.00001,31,89.99999]){
  const parent=shapeOf(evaluateRecordingSnapshot(f.workspace,f.recording.id,{angle:{x:angle,y:0},useDraft:false}).drawing,curveId),field=createSnapshotSplitParameterField(parent),weights=[1-angle/90,angle/90],q=field.parameterAt(cuts,weights);
  expect(createSnapshotSplitParameterField(parent)).toBe(field);if(angle===31){expect(q).toBeCloseTo(.3553454299646163,14);expect(Math.abs(q-cuts.reduce((sum,value,i)=>sum+value*weights[i],0))).toBeGreaterThan(.00003);}
  if(angle<1)expect(Math.abs(q-cuts[0])).toBeLessThan(3e-9);if(angle>89)expect(Math.abs(q-cuts[1])).toBeLessThan(3e-9);
  const children=[subcurve(parent,0,q),subcurve(parent,q,1)];for(let i=0;i<=100;i++){const t=i/100,a=point(parent,t),b=t<=q?point(children[0],t/q):point(children[1],(t-q)/(1-q));expect(Math.hypot(a[0]-b[0],a[1]-b[1])).toBeLessThan(1e-12);}
 }
});
test('shared-edge parameter sampling ignores an inactive third vertex and runtime ranges remain transient',()=>{
 const f=fixture(),drawing=evaluateRecordingSnapshot(f.workspace,f.recording.id,{angle:{x:31,y:0},useDraft:false}).drawing,parent=shapeOf(drawing,curveId),field=createSnapshotSplitParameterField(parent),cuts=f.bases.map(b=>evaluatedControlParameter(b.drawing,curveId,nativeT)),weights=[59/90,31/90],q=field.parameterAt(cuts,weights);
 expect(field.parameterAt([...cuts,.9],[...weights,0])).toBe(q);expect(field.parameterAt([cuts[1],.1,cuts[0]],[weights[1],0,weights[0]])).toBeCloseTo(q,14);
 const bytes=JSON.stringify(drawing);recordSnapshotSplitParameterRanges(drawing,new Map([[curveId,[.2,.8] as const]]));expect(JSON.stringify(drawing)).toBe(bytes);
 expect(resolveSnapshotFitParameter(drawing,[{curveId,parameterRange:[0,1]}],.371)).toBeCloseTo(.371,14);
});
for(const scope of ['CURVE','PATH'] as const)for(const ends of [[.15,.82],[.371,.371]] as const)test(`${scope} material world endpoints survive a fitted split at31 degrees (${ends.join(',')})`,()=>{
 const f=fixture(scope,ends),angle=31,weights=[1-angle/90,angle/90],before=evaluateRecordingSnapshot(f.workspace,f.recording.id,{angle:{x:angle,y:0},useDraft:false}).drawing,parent=shapeOf(before,curveId),cuts=f.bases.map(b=>evaluatedControlParameter(b.drawing,curveId,nativeT)),q=createSnapshotSplitParameterField(parent).parameterAt(cuts,weights),track=before.displayIntervals![0],field=displayField(before,displayPath(before,track.anchor.id)),expected=[field.at(field.native(track,track.ranges[0].start)).p,field.at(field.native(track,track.ranges[0].end)).p];
 // Isolate the material handoff from the scalar-expression implementation:
 // real bases use the source transaction; the ghost receives the exact parent.
 const sourceProject={...f.project,recordingSnapshots:{...f.workspace,recordings:[],activeRecordingId:undefined}},after=prepareSnapshotEdit(snapshotEditContext(sourceProject,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project.recordingSnapshots!,bases=f.recording.snapshotIds.map(snapshotId=>({snapshotId,drawing:resolveSnapshot(after,snapshotId,{useDraft:false}).drawing})),parts=[{curveId:f.canonical.childCurveIds[0],parameterRange:[0,nativeT] as const},{curveId:f.canonical.childCurveIds[1],parameterRange:[nativeT,1] as const}];
 bases.forEach((basis,i)=>expect(resolveSnapshotFitParameter(basis.drawing,parts,nativeT)).toBeCloseTo(cuts[i],10));
 const divided=applyCurveSplitIntent(before,{...f.canonical,t:q}).document,ghost={...divided,displayIntervals:structuredClone(bases[0].drawing.displayIntervals)},ranges=new Map([[f.canonical.childCurveIds[0],[0,q] as const],[f.canonical.childCurveIds[1],[q,1] as const]]);recordSnapshotSplitParameterRanges(ghost,ranges);
 const partitions=remapSnapshotMaterialPartitions(undefined,f.canonical,f.bases.flatMap(b=>b.drawing.displayIntervals??[])),pathLineages=remapSnapshotMaterialPathLineages(undefined,f.canonical,f.bases.map(b=>b.drawing)),sampled=transportSnapshotSimplexMaterial(bases,ghost,weights,{partitions,pathLineages});expect(sampled.diagnostics).toEqual([]);
 const tracks=sampled.drawing.displayIntervals!,left=tracks.find(t=>t.id===cid('material'))!,right=scope==='CURVE'?tracks.find(t=>t.id===f.canonical.intervals[0].rightTrackId)!:left,finalField=displayField(sampled.drawing,displayPath(sampled.drawing,left.anchor.id)),actual=(['start','end'] as const).map(end=>{const track=scope==='CURVE'?[left,right].find(track=>track.ranges[0][end]<1)??right:left;return finalField.at(finalField.native(track,track.ranges[0][end])).p;});
 actual.forEach((p,i)=>p.forEach((value,axis)=>expect(value).toBeCloseTo(expected[i][axis],8)));if(ends[0]===ends[1])expect(actual[0]).toEqual(actual[1]);
});

for(const scope of ['CURVE','PATH'] as const)test(`complete scalar transaction retains ${scope} world material with nonuniform handle response`,()=>{
 const f=fixture(scope),graph=f.recording.angleGraph!,edge=graph.mesh.edges[0];graph.edgeResponses[edge.id]={nodes:{},handles:{[curveId]:[{x:[[.4,.82]],y:[[.6,.21]]},{x:[[.3,.1]]}]}};
 const angles=[.00001,11,31,47,75,89.99999],before=angles.map(x=>evaluateRecordingSnapshot(f.workspace,f.recording.id,{angle:{x,y:0},useDraft:false}).drawing),after=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project.recordingSnapshots!;
 angles.forEach((x,index)=>{const old=before[index],parent=shapeOf(old,curveId),q=createSnapshotSplitParameterField(parent).parameterAt(f.bases.map(b=>evaluatedControlParameter(b.drawing,curveId,nativeT)),[1-x/90,x/90]),actual=evaluateRecordingSnapshot(after,f.recording.id,{angle:{x,y:0},useDraft:false}).drawing,expected=[subcurve(parent,0,q),subcurve(parent,q,1)];
  f.canonical.childCurveIds.forEach((id,k)=>shapeOf(actual,id).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(expected[k][i][a],8))));const track=old.displayIntervals![0],field=displayField(old,displayPath(old,curveId)),wanted=(['start','end'] as const).map(end=>field.at(field.native(track,track.ranges[0][end])).p),left=actual.displayIntervals!.find(t=>t.id===cid('material'))!,right=scope==='CURVE'?actual.displayIntervals!.find(t=>t.id===f.canonical.intervals[0].rightTrackId)!:left,finalField=displayField(actual,displayPath(actual,left.anchor.id));
  (['start','end'] as const).forEach((end,index)=>{const track=scope==='CURVE'?[left,right].find(track=>track.ranges[0][end]<1)??right:left,p=finalField.at(finalField.native(track,track.ranges[0][end])).p;p.forEach((v,a)=>expect(v).toBeCloseTo(wanted[index][a],8));});
 });
});

test('the retained scalar restriction follows later live cage and source controls through JSON',async()=>{
 const {parseRecordingSnapshots}=await import('../../domain/recordingSnapshot/persistence'),{upsertDrawingSource}=await import('../../domain/recordingSnapshot/sources'),f=fixture(),graph=f.recording.angleGraph!,edge=graph.mesh.edges[0];graph.edgeResponses[edge.id]={nodes:{},handles:{[curveId]:[{x:[[.4,.82]],y:[[.6,.21]]},{x:[[.3,.1]]}]}};
 const candidate=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project.recordingSnapshots!,after=parseRecordingSnapshots(JSON.parse(JSON.stringify(candidate))),before=structuredClone(f.workspace);for(const w of [before,after]){const cage=w.snapshots.find(s=>s.id==='view')!.deformation.layerDomains![0];if(cage.kind!=='h-coons')throw Error('fixture');cage.quad[1][0]+=.08;cage.bend!.handles[2][1][1]+=.06;}
 const changed=structuredClone(f.drawing);changed.curves[0].handles[0][1]+=.07;const old=upsertDrawingSource(before,'$working',changed),next=upsertDrawingSource(after,'$working',applyCurveSplitIntent(changed,f.intent).document),bases=f.recording.snapshotIds.map(snapshotId=>({snapshotId,drawing:resolveSnapshot(old,snapshotId,{useDraft:false}).drawing}));
 for(const x of [13,31,67]){const original=evaluateRecordingSnapshot(old,f.recording.id,{angle:{x,y:0},useDraft:false}).drawing,parent=shapeOf(original,curveId),q=createSnapshotSplitParameterField(parent).parameterAt(bases.map(b=>evaluatedControlParameter(b.drawing,curveId,nativeT)),[1-x/90,x/90]),actual=evaluateRecordingSnapshot(next,f.recording.id,{angle:{x,y:0},useDraft:false}).drawing,pieces=[subcurve(parent,0,q),subcurve(parent,q,1)];f.canonical.childCurveIds.forEach((id,k)=>shapeOf(actual,id).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(pieces[k][i][a],8))));}
});

test('repeating a source split restricts the retained intermediate field again',()=>{
 const f=fixture(),first=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project,oldId=f.canonical.childCurveIds[0],before=evaluateRecordingSnapshot(first.recordingSnapshots!,f.recording.id,{angle:{x:31,y:0},useDraft:false}).drawing,parent=shapeOf(before,oldId);let serial=0;const intent=createCurveSplitIntent(first.drawing!,f.intent.childCurveIds[0],.413,{allocateId:()=>`repeat-field-${++serial}`}),canonical=mapCurveSplitIntent(intent,cid),parts=[{curveId:canonical.childCurveIds[0],parameterRange:[0,intent.t] as const},{curveId:canonical.childCurveIds[1],parameterRange:[intent.t,1] as const}],next=prepareSnapshotEdit(snapshotEditContext(first,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(first.drawing!,intent).document,intent}).project.recordingSnapshots!,bases=f.recording.snapshotIds.map(id=>resolveSnapshot(next,id).drawing),q=createSnapshotSplitParameterField(parent).parameterAt(bases.map(d=>resolveSnapshotFitParameter(d,parts,intent.t)!),[59/90,31/90]),expected=[subcurve(parent,0,q),subcurve(parent,q,1)],actual=evaluateRecordingSnapshot(next,f.recording.id,{angle:{x:31,y:0},useDraft:false}).drawing;
 canonical.childCurveIds.forEach((id,k)=>shapeOf(actual,id).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(expected[k][i][a],8))));
});

test('A correction after the source split uses the same saved scalar field and keeps the unrelated child handle',async()=>{
 const {applySnapshotCommand}=await import('../../domain/recordingSnapshot/commands'),{parseRecordingSnapshots}=await import('../../domain/recordingSnapshot/persistence'),f=fixture(),after=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project.recordingSnapshots!;applySnapshotCommand(after,{op:'setAngle',angle:{x:31,y:0}});const before=evaluateRecordingSnapshot(after,f.recording.id,{angle:{x:31,y:0},useDraft:false}).drawing,left=f.canonical.childCurveIds[0],right=f.canonical.childCurveIds[1],p=shapeOf(before,left)[1],target=[p[0]+.01,p[1]-.015] as [number,number];applySnapshotCommand(after,{op:'moveShapeHandle',layerId:'slot',curveId:left,end:0,position:target});applySnapshotCommand(after,{op:'updateSnapshot'});const loaded=parseRecordingSnapshots(JSON.parse(JSON.stringify(after))),actual=evaluateRecordingSnapshot(loaded,f.recording.id,{angle:{x:31,y:0},useDraft:false}).drawing;shapeOf(actual,left)[1].forEach((v,a)=>expect(v).toBeCloseTo(target[a],8));shapeOf(actual,right).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(shapeOf(before,right)[i][a],8)));
});

test('a triangular scalar field and its shared edge keep the same parent geometry after fitted splitting',async()=>{
 const {locateSnapshotSimplex}=await import('../../domain/recordingSnapshot/triangulation'),f=fixture(),third=structuredClone(f.workspace.snapshots.find(s=>s.id==='view')!);third.id='up-view';third.angle={x:0,y:90};const cage=third.deformation.layerDomains![0];if(cage.kind!=='h-coons')throw Error('fixture');cage.quad[2][0]-=.08;f.workspace.snapshots.push(third);f.recording.snapshotIds.push(third.id);f.recording.angleGraph=createSnapshotAngleGraph(f.recording.snapshotIds.map(snapshotId=>({snapshotId,angle:f.workspace.snapshots.find(s=>s.id===snapshotId)!.angle})));const graph=f.recording.angleGraph,triangle=graph.mesh.triangles[0];graph.triangleResponses[triangle.id]={nodes:{},handles:{[curveId]:[{x:[{id:'inside',at:[.2,.3,.5],weights:[.4,.1,.5]}]},{}]}};
 const angles=[{x:24,y:25},{x:31,y:0}],before=angles.map(angle=>evaluateRecordingSnapshot(f.workspace,f.recording.id,{angle,useDraft:false}).drawing),after=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project.recordingSnapshots!;
 angles.forEach((angle,index)=>{const location=locateSnapshotSimplex(graph.mesh,angle)!,cuts=location.snapshotIds.map(id=>evaluatedControlParameter(resolveSnapshot(f.workspace,id).drawing,curveId,nativeT)),parent=shapeOf(before[index],curveId),q=createSnapshotSplitParameterField(parent).parameterAt(cuts,location.geometricWeights),expected=[subcurve(parent,0,q),subcurve(parent,q,1)],actual=evaluateRecordingSnapshot(after,f.recording.id,{angle,useDraft:false}).drawing;f.canonical.childCurveIds.forEach((id,k)=>shapeOf(actual,id).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(expected[k][i][a],8))));});
});

test('inserting a real view after fitted splitting retains the old geometry and material fields',async()=>{
 const {applySnapshotCommand}=await import('../../domain/recordingSnapshot/commands'),f=fixture(),after=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project.recordingSnapshots!,angles=[11,31,59.99,60,60.01,77],before=angles.map(x=>evaluateRecordingSnapshot(after,f.recording.id,{angle:{x,y:0},useDraft:false}).drawing);applySnapshotCommand(after,{op:'createSnapshot',angle:{x:60,y:0}});
 angles.forEach((x,index)=>{const actual=evaluateRecordingSnapshot(after,f.recording.id,{angle:{x,y:0},useDraft:false}).drawing;for(const curve of before[index].curves)shapeOf(actual,curve.id).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(shapeOf(before[index],curve.id)[i][a],8)));for(const track of before[index].displayIntervals??[]){const next=actual.displayIntervals!.find(t=>t.id===track.id)!,a=displayField(before[index],displayPath(before[index],track.anchor.id)),b=displayField(actual,displayPath(actual,next.anchor.id));for(const end of ['start','end'] as const){const expected=a.at(a.native(track,track.ranges[0][end])).p,p=b.at(b.native(next,next.ranges[0][end])).p;p.forEach((v,axis)=>expect(v).toBeCloseTo(expected[axis],8));}}});
});

test('an existing nonlinear SMOOTH field is projected before its live fitted restriction',async()=>{
 const {createCurve,connect}=await import('../../domain/drawing/commands'),{upsertDrawingSource}=await import('../../domain/recordingSnapshot/sources'),f=fixture(),created=createCurve(f.drawing,'layer',[[.7,.5],[.78,.7],[.91,.85],[.9,.95]],.01,'Neighbor','neighbor'),drawing=connect(created,{curveId:'curve',end:1},{curveId:'neighbor',end:0},'SMOOTH'),workspace=upsertDrawingSource(f.workspace,'$working',drawing),project={...f.project,drawing,recordingSnapshots:workspace},recording=workspace.recordings[0],graph=recording.angleGraph!,edge=graph.mesh.edges[0];graph.edgeResponses[edge.id]={nodes:{},handles:{[curveId]:[{}, {x:[[.3,.7]],y:[[.65,.2]]}],[cid('neighbor')]:[{x:[[.7,.25]],y:[[.4,.8]]},{}]}};
 const angles=[11,31,62,84],before=angles.map(x=>evaluateRecordingSnapshot(workspace,recording.id,{angle:{x,y:0},useDraft:false}).drawing),bases=recording.snapshotIds.map(id=>resolveSnapshot(workspace,id).drawing);let serial=0;const intent=createCurveSplitIntent(drawing,'curve',nativeT,{allocateId:()=>`smooth-field-${++serial}`}),canonical=mapCurveSplitIntent(intent,cid),after=prepareSnapshotEdit(snapshotEditContext(project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(drawing,intent).document,intent}).project.recordingSnapshots!;
 angles.forEach((x,index)=>{const parent=shapeOf(before[index],curveId),q=createSnapshotSplitParameterField(parent).parameterAt(bases.map(d=>evaluatedControlParameter(d,curveId,nativeT)),[1-x/90,x/90]),expected=[subcurve(parent,0,q),subcurve(parent,q,1)],actual=evaluateRecordingSnapshot(after,recording.id,{angle:{x,y:0},useDraft:false}).drawing;canonical.childCurveIds.forEach((id,k)=>shapeOf(actual,id).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(expected[k][i][a],8))));shapeOf(actual,cid('neighbor')).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(shapeOf(before[index],cid('neighbor'))[i][a],8)));});
 const {applySnapshotCommand}=await import('../../domain/recordingSnapshot/commands');applySnapshotCommand(after,{op:'setAngle',angle:{x:31,y:0}});const current=evaluateRecordingSnapshot(after,recording.id,{angle:{x:31,y:0},useDraft:false}).drawing,right=canonical.childCurveIds[1],old=shapeOf(current,right)[2],target=[old[0]+.006,old[1]-.008] as [number,number];applySnapshotCommand(after,{op:'moveShapeHandle',layerId:'slot',curveId:right,end:1,position:target});applySnapshotCommand(after,{op:'updateSnapshot'});const changed=evaluateRecordingSnapshot(after,recording.id,{angle:{x:31,y:0},useDraft:false}).drawing;shapeOf(changed,right)[2].forEach((v,a)=>expect(v).toBeCloseTo(target[a],8));
});
