import {expect,test} from 'vitest';
import {createEmptyProject} from '../../app/emptyProject';
import {prepareSnapshotEdit,snapshotEditContext} from '../../app/snapshotEditTransaction';
import {createCurveSplitIntent,applyCurveSplitIntent,mapCurveSplitIntent} from '../../domain/drawing/layerEditIntent';
import {deleteCurves,deleteLayer,moveHandle} from '../../domain/drawing/commands';
import {emptyDrawing,shapeOf,type DrawingDocument,type Cubic} from '../../domain/drawing/model';
import {neutralBend} from '../../domain/deformation/coons';
import {ensureRecordingSnapshots} from '../../domain/recordingSnapshot/migration';
import {canonicalElementId,drawingSnapshotForArtwork,upsertDrawingSource} from '../../domain/recordingSnapshot/sources';
import {emptyRecordingSnapshot,emptySnapshotRecording} from '../../domain/recordingSnapshot/model';
import {resolveSnapshot,evaluateRecordingSnapshot} from '../../domain/recordingSnapshot/evaluation';
import {applySnapshotMembershipEdit} from '../../domain/recordingSnapshot/localMembership';
import {parseRecordingSnapshots} from '../../domain/recordingSnapshot/persistence';
import {derivedUses} from '../../domain/drawing/roundedJoin';
import {createSnapshotAngleGraph} from '../../domain/recordingSnapshot/angleGraph';
import {continueCubicRange} from '../../domain/drawing/cubicRangeContinuation';
import {subcurve} from '../../domain/drawing/roundedJoin';
const cid=(id:string)=>canonicalElementId('$working',id);
function fixture(postShape=false){
 const drawing:DrawingDocument={...emptyDrawing(),nodes:[{id:'a',position:[-.8,-.3]},{id:'b',position:[.7,.5]},{id:'c',position:[-.7,.7]},{id:'d',position:[.6,.8]}],curves:[{id:'curve',name:'Curve',nodes:['a','b'],handles:[[-.6,.6],[.4,-.5]],width:.01,visible:true,locked:false},{id:'other',name:'Other',nodes:['c','d'],handles:[[-.1,.3],[.4,.9]],width:.01,visible:true,locked:false}],layers:[{id:'layer',name:'Layer',items:['curve','other'],visible:true,locked:false}],displayIntervals:[{id:'material',scope:'CURVE',anchor:{id:'curve',reverse:false},ranges:[{id:'range',start:.15,end:.82}]}]};
 const project=ensureRecordingSnapshots({...createEmptyProject(),drawing}),workspace=project.recordingSnapshots,source=drawingSnapshotForArtwork(workspace,'$working')!,view=emptyRecordingSnapshot('view'),bend=neutralBend();bend.handles[1][0][0]=1.25;
 view.layers=[{kind:'reference',id:'slot',name:'Curve',baseSnapshotId:source.id,baseLayerId:cid('layer')}];view.deformation.layerDomains=[{kind:'h-coons',id:'cage',layerIds:['slot'],restRect:{min:[-1,-1],max:[1,1]},quad:[[-1,-1],[1,-.7],[.7,1],[-.9,.8]],bend,...(postShape?{postShape:{nodes:{[cid('a')]:[.03,.05] as [number,number]},handles:{[cid('curve')]:[[.04,.06],[-.02,.01]] as [[number,number],[number,number]]}}}:{})}];workspace.snapshots.push(view);
 const other=emptyRecordingSnapshot('other-view');other.layers=structuredClone(view.layers);workspace.snapshots.push(other);const recording=emptySnapshotRecording('recording');recording.mode='triangulated';recording.snapshotIds=['view','other-view'];recording.activeSnapshotId='view';recording.angleGraph=createSnapshotAngleGraph([{snapshotId:'view',angle:{x:0,y:0}},{snapshotId:'other-view',angle:{x:90,y:0}}]);workspace.recordings=[recording];workspace.activeRecordingId=recording.id;
 let serial=0;const intent=createCurveSplitIntent(drawing,'curve',.371,{allocateId:()=>`partial-${++serial}`}),canonical=mapCurveSplitIntent(intent,cid),split=prepareSnapshotEdit(snapshotEditContext(project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(drawing,intent).document,intent}).project;
 return {project:split,workspace:split.recordingSnapshots!,intent,canonical,sourceId:source.id};
}
const expectShape=(a:Cubic,b:Cubic)=>a.forEach((p,i)=>p.forEach((v,k)=>expect(v).toBeCloseTo(b[i][k],8)));
function exclude(f:ReturnType<typeof fixture>,id:string){applySnapshotMembershipEdit(f.workspace,'view',{op:'excludeElements',layerId:'slot',elementIds:[id]},()=>{throw Error('Unexpected identity allocation');});}
for(const postShape of [false,true])test(`local exclusion retains live sibling fit and unrelated cage geometry, correction=${postShape}`,()=>{
 const f=fixture(postShape),left=f.intent.childCurveIds[0],right=f.canonical.childCurveIds[1],sourceCurve=f.project.drawing!.curves.find(curve=>curve.id===left)!;
 // Deliberately break the ideal parent restriction at an outer control. The
 // absent sibling is required, so continuing just the survivor is not enough.
 f.workspace=upsertDrawingSource(f.workspace,'$working',moveHandle(f.project.drawing!,{curveId:left,end:0},[sourceCurve.handles[0][0]+.12,sourceCurve.handles[0][1]-.07]));
 const before=resolveSnapshot(f.workspace,'view'),library=JSON.stringify(f.workspace.library);exclude(f,cid(left));const after=resolveSnapshot(f.workspace,'view');
 expect(after.diagnostics.filter(issue=>issue.code==='LAYER_DOMAIN')).toEqual([]);expect(after.drawing.curves.map(curve=>curve.id)).toEqual([right,cid('other')]);expect(JSON.stringify(f.workspace.library)).toBe(library);expectShape(shapeOf(after.drawing,right),shapeOf(before.drawing,right));expectShape(shapeOf(after.drawing,cid('other')),shapeOf(before.drawing,cid('other')));
 for(const stage of ['source','baseDrawing','topologyInputDrawing','drawing','preShapeDrawing','prePlacementDrawing','preElementPlacementDrawing'] as const){expect(after[stage].curves.some(curve=>curve.id===cid(left))).toBe(false);expect(after[stage].layers.flatMap(layer=>layer.items)).not.toContain(cid(left));}
 expect(after.provenance[cid(left)]).toBeUndefined();expect(after.drawing.nodes.some(node=>node.id===cid('a'))).toBe(false);expect(derivedUses(after.drawing,[{id:right,reverse:false}]).error).toBeUndefined();expect(f.workspace.library.curves[cid(left)]).toBeDefined();expect(resolveSnapshot(f.workspace,f.sourceId).drawing.curves.some(curve=>curve.id===cid(left))).toBe(true);
 const loaded=parseRecordingSnapshots(JSON.parse(JSON.stringify(f.workspace)));expectShape(shapeOf(resolveSnapshot(loaded,'view').drawing,right),shapeOf(after.drawing,right));
});
for(const postShape of [false,true])for(const end of [0,1] as const)test(`source child ${end} deletion retains original parent field, correction=${postShape}`,()=>{
 const f=fixture(postShape),before=resolveSnapshot(f.workspace,'view'),removed=f.canonical.childCurveIds[end],survivor=f.canonical.childCurveIds[1-end],changed=deleteCurves(f.project.drawing!,[f.intent.childCurveIds[end]]),project=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:changed}).project,ws=project.recordingSnapshots!,after=resolveSnapshot(ws,'view');
 expect(after.diagnostics.filter(issue=>issue.code==='LAYER_DOMAIN')).toEqual([]);expect(ws.library.curves[removed]).toBeUndefined();expect(after.drawing.curves.map(curve=>curve.id)).toEqual([survivor,cid('other')]);expectShape(shapeOf(after.drawing,survivor),shapeOf(before.drawing,survivor));expectShape(shapeOf(after.drawing,cid('other')),shapeOf(before.drawing,cid('other')));expect(derivedUses(after.drawing,[{id:survivor,reverse:false}]).error).toBeUndefined();
 for(const snapshot of ws.snapshots)expect(resolveSnapshot(ws,snapshot.id).drawing.curves.some(curve=>curve.id===removed)).toBe(false);
 for(const angle of [0,31,90]){const result=evaluateRecordingSnapshot(ws,'recording',{angle:{x:angle,y:0},useDraft:false});expect(result.drawing.curves.some(curve=>curve.id===removed)).toBe(false);expect(result.angleSurface?.outsideCurves.some(curve=>curve.curveId===removed)).toBe(false);expect(result.paintBatches.some(batch=>(batch.owner??batch.item.id)===removed)).toBe(false);}
 const loaded=parseRecordingSnapshots(JSON.parse(JSON.stringify(ws)));expectShape(shapeOf(resolveSnapshot(loaded,'view').drawing,survivor),shapeOf(after.drawing,survivor));expect(Object.keys(ws.library.curves).sort()).toEqual(Object.keys(f.workspace.library.curves).filter(id=>id!==removed).sort());
});
test('last source curves leave an empty layer; explicit source-layer deletion removes aliases',()=>{
 const f=fixture(),empty=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:deleteCurves(f.project.drawing!,f.project.drawing!.curves.map(curve=>curve.id))}).project,ws=empty.recordingSnapshots!;
 expect(resolveSnapshot(ws,'view').drawing.layers).toHaveLength(1);expect(resolveSnapshot(ws,'view').drawing.layers[0].items).toEqual([]);expect(resolveSnapshot(ws,'view').drawing.curves).toEqual([]);
 const gone=prepareSnapshotEdit(snapshotEditContext(empty,true),{kind:'original-geometry',drawing:deleteLayer(empty.drawing!,'layer')}).project.recordingSnapshots!;expect(resolveSnapshot(gone,'view').drawing.layers).toEqual([]);
});
test('continuation uses only surviving controls and refuses numerically unavailable tiny intervals',()=>{
 const parent:Cubic=[[-.8,-.3],[-.6,.6],[.4,-.5],[.7,.5]];for(const range of [[0,.371],[.371,1],[.2,.65]] as const)expectShape(continueCubicRange(subcurve(parent,range[0],range[1]),range[0],range[1]),parent);
 expect(()=>continueCubicRange(subcurve(parent,.3,.300001),.3,.300001)).toThrow(/ill-conditioned/);
});
test('local excluded dependency retains its parent cage and the child own cage in one input pass',()=>{
 const f=fixture(true),view=f.workspace.snapshots.find(s=>s.id==='view')!,child=emptyRecordingSnapshot('child');child.parentSnapshotId='view';child.layers=[{kind:'reference',id:'nested',name:'Nested',baseSnapshotId:'view',baseLayerId:'slot'}];child.deformation.layerDomains=structuredClone(view.deformation.layerDomains);child.deformation.layerDomains!.forEach(domain=>{domain.id=`child-${domain.id}`;domain.layerIds=['nested'];delete domain.postShape;delete domain.shapeLineages;});f.workspace.snapshots.push(child);
 const before=resolveSnapshot(f.workspace,'child').drawing,left=f.canonical.childCurveIds[0],right=f.canonical.childCurveIds[1];applySnapshotMembershipEdit(f.workspace,'child',{op:'excludeElements',layerId:'nested',elementIds:[left]},()=>{throw Error('Unexpected identity allocation');});const after=resolveSnapshot(f.workspace,'child');expect(after.diagnostics.filter(issue=>issue.code==='LAYER_DOMAIN')).toEqual([]);expectShape(shapeOf(after.drawing,right),shapeOf(before,right));expectShape(shapeOf(after.drawing,cid('other')),shapeOf(before,cid('other')));
});
test('moving a split sibling to another layer leaves the original layer fit stable',()=>{
 const f=fixture(true),before=resolveSnapshot(f.workspace,'view').drawing,left=f.canonical.childCurveIds[0],right=f.canonical.childCurveIds[1],view=f.workspace.snapshots.find(s=>s.id==='view')!;exclude(f,left);
 view.layers.push({kind:'reference',id:'moved',name:'Moved',baseSnapshotId:f.sourceId,baseLayerId:cid('layer'),membership:{excludeElementIds:[right,cid('other')]}});view.memberSources={[left]:f.sourceId};view.nodeForks={'moved-seam':{curveId:left,end:1}};view.relations.joins={disable:[f.canonical.seamJoinId]};
 const after=resolveSnapshot(f.workspace,'view');expect(after.diagnostics.filter(issue=>issue.code==='LAYER_DOMAIN')).toEqual([]);expectShape(shapeOf(after.drawing,right),shapeOf(before,right));expectShape(shapeOf(after.drawing,cid('other')),shapeOf(before,cid('other')));expect(after.drawing.curves.map(curve=>curve.id).sort()).toEqual([left,right,cid('other')].sort());expect(after.drawing.layers.find(layer=>layer.id==='moved')!.items).toEqual([left]);expect(after.provenance[left].sourceSnapshotId).toBe(f.sourceId);
});
for(const end of [0,1] as const)test(`nested split correction survives deletion of local child ${end} without renormalizing`,async()=>{
 const {prepareSnapshotLocalDrawingEdit}=await import('../../domain/recordingSnapshot/drawingTopology'),f=fixture(true),left=f.canonical.childCurveIds[0],initial=resolveSnapshot(f.workspace,'view').drawing,target=moveHandle(initial,{curveId:left,end:0},[-.5,.65]);f.project.recordingSnapshots=prepareSnapshotLocalDrawingEdit(f.workspace,{snapshotId:'view',state:'saved',beforeDrawing:initial,drawing:target}).workspace;
 let serial=0;const intent=createCurveSplitIntent(f.project.drawing!,f.intent.childCurveIds[0],.43,{allocateId:()=>`nested-delete-${++serial}`}),canonical=mapCurveSplitIntent(intent,cid),split=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.project.drawing!,intent).document,intent}).project,before=resolveSnapshot(split.recordingSnapshots!,'view').drawing,deleted=prepareSnapshotEdit(snapshotEditContext(split,true),{kind:'original-geometry',drawing:deleteCurves(split.drawing!,[intent.childCurveIds[end]])}).project,after=resolveSnapshot(deleted.recordingSnapshots!,'view');
 expect(after.diagnostics.filter(issue=>issue.code==='LAYER_DOMAIN')).toEqual([]);for(const id of [canonical.childCurveIds[1-end],f.canonical.childCurveIds[1],cid('other')])expectShape(shapeOf(after.drawing,id),shapeOf(before,id));
});
test('source child deletion, Undo, and Redo are one source transaction',async()=>{
 const {useEditor}=await import('../../app/store'),f=fixture(true),previous=useEditor.getState(),plan=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:deleteCurves(f.project.drawing!,[f.intent.childCurveIds[0]])});
 try{useEditor.setState({project:f.project,past:[],future:[]});useEditor.getState().commitPreparedSnapshotEdit(plan);expect(useEditor.getState().past).toEqual([f.project]);expect(useEditor.getState().project.recordingSnapshots!.library.curves[f.canonical.childCurveIds[0]]).toBeUndefined();useEditor.getState().undo();expect(useEditor.getState().project).toBe(f.project);useEditor.getState().redo();expect(useEditor.getState().project).toBe(plan.project);expect(resolveSnapshot(useEditor.getState().project.recordingSnapshots!,'view').diagnostics.filter(issue=>issue.code==='LAYER_DOMAIN')).toEqual([]);}finally{useEditor.setState(previous,true);}
});
test('an ill-conditioned sole remnant is rejected atomically before source deletion can disable its layer',()=>{
 const f=fixture(),project=f.project;let serial=0;const intent=createCurveSplitIntent(project.drawing!,f.intent.childCurveIds[0],.01,{allocateId:()=>`tiny-delete-${++serial}`}),split=prepareSnapshotEdit(snapshotEditContext(project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(project.drawing!,intent).document,intent}).project,bytes=JSON.stringify(split),removed=[intent.childCurveIds[1],f.intent.childCurveIds[1]];
 expect(()=>prepareSnapshotEdit(snapshotEditContext(split,true),{kind:'original-geometry',drawing:deleteCurves(split.drawing!,removed)})).toThrow(/Cannot delete source members.*ill-conditioned/);expect(JSON.stringify(split)).toBe(bytes);
});
test('a descendant own cage receives only the excluded parent family dependency, with no new member',()=>{
 const f=fixture(true),left=f.intent.childCurveIds[0],right=f.canonical.childCurveIds[1],curve=f.project.drawing!.curves.find(c=>c.id===left)!;f.workspace=upsertDrawingSource(f.workspace,'$working',moveHandle(f.project.drawing!,{curveId:left,end:0},[curve.handles[0][0]+.12,curve.handles[0][1]-.07]));
 const view=f.workspace.snapshots.find(s=>s.id==='view')!,child=emptyRecordingSnapshot('child');child.parentSnapshotId='view';child.layers=[{kind:'reference',id:'nested',name:'Nested',baseSnapshotId:'view',baseLayerId:'slot'}];child.deformation.layerDomains=structuredClone(view.deformation.layerDomains);child.deformation.layerDomains!.forEach(domain=>{domain.id=`child-${domain.id}`;domain.layerIds=['nested'];delete domain.postShape;delete domain.shapeLineages;});f.workspace.snapshots.push(child);const before=resolveSnapshot(f.workspace,'child').drawing;exclude(f,cid(left));
 const after=resolveSnapshot(f.workspace,'child');expect(after.diagnostics.filter(issue=>issue.code==='LAYER_DOMAIN')).toEqual([]);expectShape(shapeOf(after.drawing,right),shapeOf(before,right));expect(after.drawing.curves.some(curve=>curve.id===cid(left))).toBe(false);expect(after.provenance[cid(left)]).toBeUndefined();
});
test('an excluded sibling remains a live dependency after source updates and never enters serialized state',()=>{
 const f=fixture(true),raw=f.intent.childCurveIds[0],left=f.canonical.childCurveIds[0],right=f.canonical.childCurveIds[1],source=f.project.drawing!,curve=source.curves.find(curve=>curve.id===raw)!;exclude(f,left);
 const before=shapeOf(resolveSnapshot(f.workspace,'view').drawing,right),edited=moveHandle(source,{curveId:raw,end:0},[curve.handles[0][0]+.15,curve.handles[0][1]-.11]),changed=upsertDrawingSource(f.workspace,'$working',edited),full=structuredClone(changed);delete (full.snapshots.find(snapshot=>snapshot.id==='view')!.layers[0] as {membership?:unknown}).membership;
 const actual=resolveSnapshot(changed,'view').drawing,expected=resolveSnapshot(full,'view').drawing;expectShape(shapeOf(actual,right),shapeOf(expected,right));expect(shapeOf(actual,right)).not.toEqual(before);expect(JSON.stringify(changed)).not.toContain('cage-dependency:');expect(actual.curves.some(curve=>curve.id===left)).toBe(false);
});
test('local exclusion at an inserted real view preserves survivor fields and scalar response membership',async()=>{
 const {applySnapshotCommand}=await import('../../domain/recordingSnapshot/commands'),f=fixture(true);applySnapshotCommand(f.workspace,{op:'createSnapshot',angle:{x:60,y:0}});const snapshotId=f.workspace.recordings[0].activeSnapshotId!,before=resolveSnapshot(f.workspace,snapshotId).drawing,left=f.canonical.childCurveIds[0],right=f.canonical.childCurveIds[1],layerId=before.layers.find(layer=>layer.items.includes(left))!.id;
 applySnapshotCommand(f.workspace,{op:'excludeElements',layerId,elementIds:[left]});const result=resolveSnapshot(f.workspace,snapshotId);expect(result.diagnostics.filter(issue=>issue.code==='LAYER_DOMAIN')).toEqual([]);expect(result.drawing.curves.some(curve=>curve.id===left)).toBe(false);expectShape(shapeOf(result.drawing,right),shapeOf(before,right));expectShape(shapeOf(result.drawing,cid('other')),shapeOf(before,cid('other')));
});
test('an inherited-only intermediate layer carries excluded family inputs through its local placement',()=>{
 const f=fixture(true),left=f.canonical.childCurveIds[0],right=f.canonical.childCurveIds[1],view=f.workspace.snapshots.find(s=>s.id==='view')!,middle=emptyRecordingSnapshot('middle'),child=emptyRecordingSnapshot('grandchild');middle.layers=[{kind:'reference',id:'middle-slot',name:'Middle',baseSnapshotId:'view',baseLayerId:'slot'}];middle.deformation.layers['middle-slot']={placement:{translation:[.05,.08],rotation:.12,scale:.9}};child.layers=[{kind:'reference',id:'end-slot',name:'End',baseSnapshotId:'middle',baseLayerId:'middle-slot'}];child.deformation.layerDomains=structuredClone(view.deformation.layerDomains);child.deformation.layerDomains!.forEach(domain=>{domain.id=`end-${domain.id}`;domain.layerIds=['end-slot'];delete domain.postShape;delete domain.shapeLineages;});f.workspace.snapshots.push(middle,child);
 const before=resolveSnapshot(f.workspace,'grandchild').drawing;applySnapshotMembershipEdit(f.workspace,'middle',{op:'excludeElements',layerId:'middle-slot',elementIds:[left]},()=>{throw Error('Unexpected identity allocation');});const after=resolveSnapshot(f.workspace,'grandchild');expect(after.diagnostics.filter(issue=>issue.code==='LAYER_DOMAIN')).toEqual([]);expectShape(shapeOf(after.drawing,right),shapeOf(before,right));expect(after.drawing.curves.some(curve=>curve.id===left)).toBe(false);
});
