import {expect,test} from 'vitest';
import {createEmptyProject} from '../../app/emptyProject';
import {prepareSnapshotEdit,snapshotEditContext} from '../../app/snapshotEditTransaction';
import {createCurveSplitIntent,applyCurveSplitIntent,mapCurveSplitIntent} from '../../domain/drawing/layerEditIntent';
import {emptyDrawing,shapeOf,type DrawingDocument,type Cubic,type Point2} from '../../domain/drawing/model';
import {neutralBend} from '../../domain/deformation/coons';
import {ensureRecordingSnapshots} from '../../domain/recordingSnapshot/migration';
import {canonicalElementId,drawingSnapshotForArtwork} from '../../domain/recordingSnapshot/sources';
import {emptyRecordingSnapshot} from '../../domain/recordingSnapshot/model';
import {resolveSnapshot} from '../../domain/recordingSnapshot/evaluation';
import {subcurve} from '../../domain/drawing/roundedJoin';
import {evaluatedControlParameter} from '../../domain/drawing/evaluatedDeformation';
const cid=(id:string)=>canonicalElementId('$working',id);
// Independent three-level de Casteljau arithmetic is the topology oracle.
const manualSplit=(s:Cubic,t:number):[Cubic,Cubic]=>{const mix=(a:Point2,b:Point2):Point2=>[a[0]*(1-t)+b[0]*t,a[1]*(1-t)+b[1]*t],a=mix(s[0],s[1]),b=mix(s[1],s[2]),c=mix(s[2],s[3]),d=mix(a,b),e=mix(b,c),p=mix(d,e);return [[s[0],a,d,p],[p,e,c,s[3]]];};
function fixture(){
 const drawing:DrawingDocument={...emptyDrawing(),nodes:[{id:'a',position:[-.8,-.3]},{id:'b',position:[.7,.5]}],curves:[{id:'curve',name:'Curve',nodes:['a','b'],handles:[[-.6,.6],[.4,-.5]],width:.01,visible:true,locked:false}],layers:[{id:'layer',name:'Layer',items:['curve'],visible:true,locked:false}]};
 const project=ensureRecordingSnapshots({...createEmptyProject(),drawing}),workspace=project.recordingSnapshots,source=drawingSnapshotForArtwork(workspace,'$working')!,view=emptyRecordingSnapshot('view'),bend=neutralBend();bend.handles[1][0][0]=1.25;
 view.layers=[{kind:'reference',id:'slot',name:'Curve',baseSnapshotId:source.id,baseLayerId:cid('layer')}];view.deformation.layerDomains=[{kind:'h-coons',id:'cage',layerIds:['slot'],restRect:{min:[-1,-1],max:[1,1]},quad:[[-1,-1],[1,-.7],[.7,1],[-.9,.8]],bend}];workspace.snapshots.push(view);
 let next=0;const intent=createCurveSplitIntent(drawing,'curve',.371,{allocateId:()=>`split-${++next}`});return {project,workspace,drawing,view,intent,canonical:mapCurveSplitIntent(intent,cid)};
}
test('source split restricts the existing fitted cage at its native material parameter',()=>{
 const f=fixture(),before=resolveSnapshot(f.workspace,'view').drawing,parent=shapeOf(before,cid('curve')),q=evaluatedControlParameter(before,cid('curve'),f.intent.t),expected=manualSplit(parent,q);
 const plan=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}),actual=resolveSnapshot(plan.project.recordingSnapshots!,'view').drawing;
 for(const [child,index] of f.canonical.childCurveIds.map((child,index)=>[child,index] as const))shapeOf(actual,child).forEach((point,i)=>point.forEach((value,axis)=>expect(value).toBeCloseTo(expected[index][i][axis],9)));
 const maxError=Math.max(...f.canonical.childCurveIds.flatMap((id,k)=>shapeOf(actual,id).flatMap((point,i)=>point.map((value,axis)=>Math.abs(value-expected[k][i][axis])))));expect(maxError).toBeLessThan(1e-10);
 expect(actual.curves.map(curve=>curve.id)).toEqual(f.canonical.childCurveIds);
});

test('split source material and existing domain correction survive JSON with the same world endpoints',async()=>{
 const {displayField,displayPath}=await import('../../domain/drawing/displayIntervals'),{parseRecordingSnapshots}=await import('../../domain/recordingSnapshot/persistence'),f=fixture();
 f.drawing.displayIntervals=[{id:'material',scope:'CURVE',anchor:{id:'curve',reverse:false},ranges:[{id:'range',start:.15,end:.82}]}];const {upsertDrawingSource}=await import('../../domain/recordingSnapshot/sources');f.project.recordingSnapshots=upsertDrawingSource(f.workspace,'$working',f.drawing);const view=f.project.recordingSnapshots.snapshots.find(s=>s.id==='view')!;view.deformation.layerDomains![0].postShape={nodes:{[cid('a')]:[.04,.08]},handles:{[cid('curve')]:[[.03,.07],[-.02,.04]]}};
 let n=0;const intent=createCurveSplitIntent(f.drawing,'curve',.371,{allocateId:()=>`material-${++n}`}),canonical=mapCurveSplitIntent(intent,cid),before=resolveSnapshot(f.project.recordingSnapshots,'view').drawing,old=before.displayIntervals![0],field=displayField(before,displayPath(before,old.anchor.id)),ends=[field.at(field.native(old,old.ranges[0].start)).p,field.at(field.native(old,old.ranges[0].end)).p];
 const after=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,intent).document,intent}).project.recordingSnapshots!,loaded=parseRecordingSnapshots(JSON.parse(JSON.stringify(after))),drawing=resolveSnapshot(loaded,'view').drawing,tracks=drawing.displayIntervals!,left=tracks.find(t=>t.id===cid('material'))!,right=tracks.find(t=>t.id===canonical.intervals[0].rightTrackId)!,next=displayField(drawing,displayPath(drawing,left.anchor.id)),actual=[next.at(next.native(left,left.ranges[0].start)).p,next.at(next.native(right,right.ranges[0].end)).p];
 actual.forEach((point,i)=>point.forEach((value,axis)=>expect(value).toBeCloseTo(ends[i][axis],8)));expect(loaded).toEqual(after);
});

test('repeated source splits retain the composed common fit and one source identity plan',()=>{
 const f=fixture(),old=resolveSnapshot(f.workspace,'view').drawing,q=evaluatedControlParameter(old,cid('curve'),f.intent.t),first=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project;
 const before=resolveSnapshot(first.recordingSnapshots!,'view').drawing,curveId=f.intent.childCurveIds[1],canonicalId=cid(curveId);let n=0;const intent=createCurveSplitIntent(first.drawing!,curveId,.413,{allocateId:()=>`repeat-${++n}`}),canonical=mapCurveSplitIntent(intent,cid),cut=evaluatedControlParameter(before,canonicalId,intent.t),expected=[subcurve(shapeOf(before,canonicalId),0,cut),subcurve(shapeOf(before,canonicalId),cut,1)];
 const after=prepareSnapshotEdit(snapshotEditContext(first,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(first.drawing!,intent).document,intent}).project,actual=resolveSnapshot(after.recordingSnapshots!,'view').drawing;canonical.childCurveIds.forEach((id,k)=>shapeOf(actual,id).forEach((point,i)=>point.forEach((value,axis)=>expect(value).toBeCloseTo(expected[k][i][axis],8))));expect(q).not.toBe(f.intent.t);
});

test('a parent cage and a child cage each restrict their own fit without repeating native t',()=>{
 const f=fixture(),child=emptyRecordingSnapshot('child');child.parentSnapshotId='view';child.layers=[{kind:'reference',id:'nested',name:'Nested',baseSnapshotId:'view',baseLayerId:'slot'}];const cage=structuredClone(f.view.deformation.layerDomains![0]);cage.id='child-cage';cage.layerIds=['nested'];if(cage.kind!=='h-coons')throw Error('fixture');cage.bend!.handles[2][1][1]=.85;child.deformation.layerDomains=[cage];f.workspace.snapshots.push(child);
 const before=resolveSnapshot(f.workspace,'child').drawing,q=evaluatedControlParameter(before,cid('curve'),f.intent.t),parent=shapeOf(before,cid('curve')),expected=[subcurve(parent,0,q),subcurve(parent,q,1)],after=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project.recordingSnapshots!,drawing=resolveSnapshot(after,'child').drawing;
 f.canonical.childCurveIds.forEach((id,k)=>shapeOf(drawing,id).forEach((point,i)=>point.forEach((value,axis)=>expect(value).toBeCloseTo(expected[k][i][axis],8))));
});

test('source child handle edits remain continuous, preserve source controls, and keep the real SMOOTH seam',async()=>{
 const {moveHandle}=await import('../../domain/drawing/commands'),{upsertDrawingSource}=await import('../../domain/recordingSnapshot/sources'),f=fixture(),project=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project,base=resolveSnapshot(project.recordingSnapshots!,'view').drawing,left=f.intent.childCurveIds[0];
 const errors:number[]=[];for(const delta of [.01,.001,.0001]){const curve=project.drawing!.curves.find(c=>c.id===left)!,drawing=moveHandle(project.drawing!,{curveId:left,end:1},[curve.handles[1][0]+delta,curve.handles[1][1]+delta*.4]),workspace=upsertDrawingSource(project.recordingSnapshots!,'$working',drawing),after=resolveSnapshot(workspace,'view');expect(after.diagnostics.filter(d=>d.code==='LAYER_DOMAIN')).toEqual([]);
  for(const curve of drawing.curves)expect(workspace.library.curves[cid(curve.id)].handles).toEqual(curve.handles);const a=shapeOf(after.drawing,f.canonical.childCurveIds[0]),b=shapeOf(after.drawing,f.canonical.childCurveIds[1]),u=[a[2][0]-a[3][0],a[2][1]-a[3][1]],v=[b[1][0]-b[0][0],b[1][1]-b[0][1]];expect(a[3]).toEqual(b[0]);expect(u[0]*v[1]-u[1]*v[0]).toBeCloseTo(0,9);errors.push(Math.max(...f.canonical.childCurveIds.flatMap(id=>shapeOf(after.drawing,id).flatMap((p,i)=>p.map((x,k)=>Math.abs(x-shapeOf(base,id)[i][k]))))));expect(Number.isFinite(after.maxError)).toBe(true);
 }
 expect(errors[2]).toBeLessThan(errors[1]);expect(errors[1]).toBeLessThan(errors[0]);expect(errors[2]).toBeLessThan(.001);
});

test('post-split A changes its own nonshared outer handle and preserves another child, then one Undo restores the source split',async()=>{
 const {moveHandle}=await import('../../domain/drawing/commands'),{prepareSnapshotLocalDrawingEdit}=await import('../../domain/recordingSnapshot/drawingTopology'),{useEditor}=await import('../../app/store'),f=fixture();f.view.deformation.layerDomains![0].postShape={nodes:{[cid('a')]:[.03,.05]},handles:{[cid('curve')]:[[.04,.06],[-.02,.01]]}};
 const plan=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}),workspace=plan.project.recordingSnapshots!,before=resolveSnapshot(workspace,'view').drawing,left=f.canonical.childCurveIds[0],right=f.canonical.childCurveIds[1],wanted=[-.4,.8] as [number,number],target=moveHandle(before,{curveId:left,end:0},wanted),after=prepareSnapshotLocalDrawingEdit(workspace,{snapshotId:'view',state:'saved',beforeDrawing:before,drawing:target}).workspace,result=resolveSnapshot(after,'view').drawing;
 shapeOf(result,left)[1].forEach((v,i)=>expect(v).toBeCloseTo(wanted[i],12));shapeOf(result,right).forEach((p,i)=>p.forEach((v,k)=>expect(v).toBeCloseTo(shapeOf(before,right)[i][k],9)));expect(after.library).toEqual(workspace.library);
 const previous=useEditor.getState();try{useEditor.setState({project:f.project,past:[],future:[]});useEditor.getState().commitPreparedSnapshotEdit(plan);expect(useEditor.getState().past).toEqual([f.project]);useEditor.getState().undo();expect(useEditor.getState().project).toBe(f.project);useEditor.getState().redo();expect(useEditor.getState().project).toBe(plan.project);}finally{useEditor.setState(previous,true);}
});

test('an ARC keeps its fitted bridge and trimmed native pieces when the parent is split',async()=>{
 const {createCurve,connect}=await import('../../domain/drawing/commands'),{upsertDrawingSource}=await import('../../domain/recordingSnapshot/sources'),{derivedUses,roundedJoins}=await import('../../domain/drawing/roundedJoin'),f=fixture();
 const added=createCurve(f.drawing,'layer',[[.7,.5],[.8,.6],[.9,.8],[.8,.9]],.01,'Other','other'),drawing=connect(added,{curveId:'curve',end:1},{curveId:'other',end:0},'ARC',.03);f.project.drawing=drawing;f.project.recordingSnapshots=upsertDrawingSource(f.workspace,'$working',drawing);
 const before=resolveSnapshot(f.project.recordingSnapshots,'view').drawing,join=before.joins.find(j=>j.mode==='ARC')!,bridge=roundedJoins(before).get(join.id)!;expect(bridge.error).toBeUndefined();let n=0;const intent=createCurveSplitIntent(drawing,'curve',.371,{allocateId:()=>`arc-${++n}`}),after=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(drawing,intent).document,intent}).project.recordingSnapshots!,result=resolveSnapshot(after,'view').drawing,actual=roundedJoins(result).get(join.id)!;
 const rawBefore=roundedJoins(drawing).get(drawing.joins.find(j=>j.mode==='ARC')!.id)!,rawAfter=roundedJoins(applyCurveSplitIntent(drawing,intent).document).get(drawing.joins.find(j=>j.mode==='ARC')!.id)!,error=(a:typeof bridge,b:typeof bridge)=>Math.max(...a.shapes.flatMap((shape,k)=>shape.flatMap((p,i)=>p.map((v,axis)=>Math.abs(v-b.shapes[k][i][axis]))))),sourceError=error(rawBefore,rawAfter),outputError=error(bridge,actual);expect(actual.error).toBeUndefined();expect(outputError).toBeLessThanOrEqual(sourceError);expect(outputError).toBeLessThan(.00004);expect(derivedUses(result,[{id:cid(intent.childCurveIds[0]),reverse:false},{id:cid(intent.childCurveIds[1]),reverse:false},{id:cid('other'),reverse:false}]).error).toBeUndefined();
});

test('old parent corrections and a later child A compose through another source split',async()=>{
 const {moveHandle}=await import('../../domain/drawing/commands'),{prepareSnapshotLocalDrawingEdit}=await import('../../domain/recordingSnapshot/drawingTopology'),f=fixture();f.view.deformation.layerDomains![0].postShape={nodes:{[cid('a')]:[.03,.05]},handles:{[cid('curve')]:[[.04,.06],[-.02,.01]]}};
 const first=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project,left=f.canonical.childCurveIds[0],initial=resolveSnapshot(first.recordingSnapshots!,'view').drawing,target=moveHandle(initial,{curveId:left,end:0},[-.5,.65]);first.recordingSnapshots=prepareSnapshotLocalDrawingEdit(first.recordingSnapshots!,{snapshotId:'view',state:'saved',beforeDrawing:initial,drawing:target}).workspace;
 const before=resolveSnapshot(first.recordingSnapshots,'view').drawing;let n=0;const intent=createCurveSplitIntent(first.drawing!,f.intent.childCurveIds[0],.43,{allocateId:()=>`after-A-${++n}`}),canonical=mapCurveSplitIntent(intent,cid),q=evaluatedControlParameter(before,left,intent.t),expected=[subcurve(shapeOf(before,left),0,q),subcurve(shapeOf(before,left),q,1)],after=prepareSnapshotEdit(snapshotEditContext(first,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(first.drawing!,intent).document,intent}).project.recordingSnapshots!,result=resolveSnapshot(after,'view').drawing;
 canonical.childCurveIds.forEach((id,k)=>shapeOf(result,id).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(expected[k][i][a],8))));
});

test('a two-curve source batch freezes each fitted material cut before replacing either identity',async()=>{
 const {createCurve}=await import('../../domain/drawing/commands'),{upsertDrawingSource}=await import('../../domain/recordingSnapshot/sources'),{createVectorEditingApi}=await import('../../app/vectorEditingApi'),{useEditor}=await import('../../app/store'),{useWorkspaceMode}=await import('../../app/workspaceMode'),f=fixture(),drawing=createCurve(f.drawing,'layer',[[-.7,.6],[-.2,.9],[.2,.1],[.6,.7]],.01,'Other','other');f.project.drawing=drawing;f.project.recordingSnapshots=upsertDrawingSource(f.workspace,'$working',drawing);const before=resolveSnapshot(f.project.recordingSnapshots,'view').drawing,previous=useEditor.getState(),mode=useWorkspaceMode.getState().mode;
 try{useWorkspaceMode.setState({mode:'drawing'});useEditor.setState({project:f.project,past:[],future:[]});const result=createVectorEditingApi().execute({commands:[{op:'splitCurve',curveId:'curve',t:.371},{op:'splitCurve',curveId:'other',t:.423}]});expect(result.ok,result.ok?'':result.error.message).toBe(true);if(!result.ok)return;const {curveSplitIntents}=await import('../../domain/drawing/layerEditIntent'),after=resolveSnapshot(useEditor.getState().project.recordingSnapshots!,'view').drawing;
  for(const intent of result.value.topologyIntents!.flatMap(curveSplitIntents)){const parent=cid(intent.curveId),q=evaluatedControlParameter(before,parent,intent.t),shape=shapeOf(before,parent),pieces=[subcurve(shape,0,q),subcurve(shape,q,1)];intent.childCurveIds.forEach((id,k)=>shapeOf(after,cid(id)).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(pieces[k][i][a],8))));}expect(useEditor.getState().past).toEqual([f.project]);
 }finally{useEditor.setState(previous,true);useWorkspaceMode.setState({mode});}
});

test('an identity parameter map still retains its nonuniform cage material source',async()=>{
 const {upsertDrawingSource}=await import('../../domain/recordingSnapshot/sources'),{displayField,displayPath}=await import('../../domain/drawing/displayIntervals'),f=fixture();f.drawing.displayIntervals=[{id:'material',scope:'CURVE',anchor:{id:'curve',reverse:false},ranges:[{id:'range',start:.12,end:.83}]}];f.project.recordingSnapshots=upsertDrawingSource(f.workspace,'$working',f.drawing);const domain=f.project.recordingSnapshots.snapshots.find(s=>s.id==='view')!.deformation.layerDomains![0];if(domain.kind!=='h-coons')throw Error('fixture');domain.bend!.enabled=false;domain.quad=[[-1,-1],[2,-1],[2,1],[-1,1]];
 const before=resolveSnapshot(f.project.recordingSnapshots,'view').drawing,old=before.displayIntervals![0],field=displayField(before,displayPath(before,old.anchor.id)),ends=[field.at(field.native(old,old.ranges[0].start)).p,field.at(field.native(old,old.ranges[0].end)).p];let n=0;const intent=createCurveSplitIntent(f.drawing,'curve',.371,{allocateId:()=>`identity-${++n}`});expect(evaluatedControlParameter(before,cid('curve'),intent.t)).toBe(intent.t);
 const after=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,intent).document,intent}).project.recordingSnapshots!,drawing=resolveSnapshot(after,'view').drawing,tracks=drawing.displayIntervals!,left=tracks.find(t=>t.id===cid('material'))!,right=tracks.find(t=>t.id===cid(intent.intervals[0].rightTrackId))!,next=displayField(drawing,displayPath(drawing,left.anchor.id)),actual=[next.at(next.native(left,left.ranges[0].start)).p,next.at(next.native(right,right.ranges[0].end)).p];actual.forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(ends[i][a],8)));
});

test('cage parameter replacement and independent copy retain their remapped split programs',async()=>{
 const {writeLayerDomainOperation}=await import('../../app/layerDomainOperation'),{createLayerCageIntent}=await import('../../domain/drawing/layerDomainIntent'),{prepareIndependentSnapshotLayers}=await import('../../domain/recordingSnapshot/independentCopy'),f=fixture(),project=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project,workspace=project.recordingSnapshots!,view=workspace.snapshots.find(s=>s.id==='view')!,domain=view.deformation.layerDomains![0];if(domain.kind!=='h-coons')throw Error('fixture');
 const changed={kind:'h-coons' as const,restRect:domain.restRect,quad:structuredClone(domain.quad),bend:domain.bend};changed.quad[1][0]+=.03;view.deformation.layerDomains=writeLayerDomainOperation(view.deformation.layerDomains,view.deformation.layerDomains!,createLayerCageIntent(['slot'],changed,{operationId:domain.id,replace:true}));expect((view.deformation.layerDomains[0] as typeof domain).fitLineages).toEqual(domain.fitLineages);
 const before=resolveSnapshot(workspace,'view').drawing;let n=0;const copy=prepareIndependentSnapshotLayers(workspace,view,['slot'],()=>`copy-${++n}`),detached={...workspace,library:copy.library,snapshots:[copy.snapshot]},after=resolveSnapshot(detached,copy.snapshot.id).drawing;
 for(const curve of before.curves)shapeOf(after,copy.idMap[curve.id]).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(shapeOf(before,curve.id)[i][a],8)));
});

test('Recorder A saves a split child response independently and survives strict JSON validation',async()=>{
 const {emptySnapshotRecording}=await import('../../domain/recordingSnapshot/model'),{createSnapshotAngleGraph}=await import('../../domain/recordingSnapshot/angleGraph'),{applySnapshotCommand}=await import('../../domain/recordingSnapshot/commands'),{parseRecordingSnapshots}=await import('../../domain/recordingSnapshot/persistence'),f=fixture(),project=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project,workspace=project.recordingSnapshots!,recording=emptySnapshotRecording('recording');recording.mode='triangulated';recording.snapshotIds=['view'];recording.activeSnapshotId='view';recording.angleGraph=createSnapshotAngleGraph([{snapshotId:'view',angle:{x:0,y:0}}]);workspace.recordings=[recording];workspace.activeRecordingId=recording.id;
 const before=resolveSnapshot(workspace,'view').drawing,left=f.canonical.childCurveIds[0],right=f.canonical.childCurveIds[1],position=[-.3,.72] as [number,number];applySnapshotCommand(workspace,{op:'moveShapeHandle',layerId:'slot',curveId:left,end:0,position});applySnapshotCommand(workspace,{op:'saveSelected',layerIds:['slot'],warpIds:[]});const loaded=parseRecordingSnapshots(JSON.parse(JSON.stringify(workspace))),after=resolveSnapshot(loaded,'view').drawing;
 shapeOf(after,left)[1].forEach((v,i)=>expect(v).toBeCloseTo(position[i],12));shapeOf(after,right).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(shapeOf(before,right)[i][a],9)));expect(loaded.snapshots.find(s=>s.id==='view')!.draft).toBeUndefined();
 const broken=JSON.parse(JSON.stringify(loaded)),domain=broken.snapshots.find((s:{id:string})=>s.id==='view').deformation.layerDomains[0];domain.fitLineages[0].parts[1].curveId=domain.fitLineages[0].parts[0].curveId;expect(()=>parseRecordingSnapshots(broken)).toThrow(/lineage|parameter/);
});

test('reflected fitted source restriction preserves the existing reflected controls',()=>{
 const f=fixture(),mirror=emptyRecordingSnapshot('mirror');mirror.parentSnapshotId='view';mirror.inputMirror={axisX:0,curvePairs:[]};mirror.layers=[{kind:'reference',id:'mirror-slot',name:'Mirror',baseSnapshotId:'view',baseLayerId:'slot'}];f.workspace.snapshots.push(mirror);const before=resolveSnapshot(f.workspace,'mirror').drawing,q=evaluatedControlParameter(before,cid('curve'),f.intent.t),expected=manualSplit(shapeOf(before,cid('curve')),q),after=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project.recordingSnapshots!,actual=resolveSnapshot(after,'mirror').drawing;f.canonical.childCurveIds.forEach((id,k)=>shapeOf(actual,id).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(expected[k][i][a],9))));
});

test('a split family can be mirrored and then copied through the shared recursive program descriptor',async()=>{
 const {prepareIndependentSnapshotLayers}=await import('../../domain/recordingSnapshot/independentCopy'),f=fixture(),project=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project,workspace=project.recordingSnapshots!,mirror=emptyRecordingSnapshot('mirror');mirror.parentSnapshotId='view';mirror.inputMirror={axisX:.2,curvePairs:[]};mirror.layers=[{kind:'reference',id:'mirror-slot',name:'Mirror',baseSnapshotId:'view',baseLayerId:'slot'}];workspace.snapshots.push(mirror);const before=resolveSnapshot(workspace,'mirror').drawing;let n=0;const copy=prepareIndependentSnapshotLayers(workspace,mirror,['mirror-slot'],()=>`reflected-split-copy-${++n}`),detached={...workspace,library:copy.library,snapshots:[copy.snapshot]},after=resolveSnapshot(detached,copy.snapshot.id).drawing;
 for(const curve of before.curves)shapeOf(after,copy.idMap[curve.id]).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(shapeOf(before,curve.id)[i][a],8)));
});

test('a source split preserves the old centerline field with its continuous material parameter at 31 degrees',async()=>{
 const {emptySnapshotRecording}=await import('../../domain/recordingSnapshot/model'),{createSnapshotAngleGraph}=await import('../../domain/recordingSnapshot/angleGraph'),{evaluateRecordingSnapshot}=await import('../../domain/recordingSnapshot/evaluation'),f=fixture(),other=emptyRecordingSnapshot('other-view','Other','view',{x:90,y:0});other.layers=structuredClone(f.view.layers);f.workspace.snapshots.push(other);const recording=emptySnapshotRecording('recording');recording.mode='triangulated';recording.snapshotIds=['view','other-view'];recording.activeSnapshotId='view';recording.angleGraph=createSnapshotAngleGraph([{snapshotId:'view',angle:{x:0,y:0}},{snapshotId:'other-view',angle:{x:90,y:0}}]);f.workspace.recordings=[recording];f.workspace.activeRecordingId=recording.id;
 const before=evaluateRecordingSnapshot(f.workspace,recording.id,{angle:{x:31,y:0},useDraft:false}).drawing,parent=shapeOf(before,cid('curve')),{createSnapshotSplitParameterField,snapshotSplitParameterRange}=await import('../../domain/recordingSnapshot/splitParameterField'),qs=recording.snapshotIds.map(id=>evaluatedControlParameter(resolveSnapshot(f.workspace,id).drawing,cid('curve'),f.intent.t)),q=createSnapshotSplitParameterField(parent).parameterAt(qs,[59/90,31/90]),expected=manualSplit(parent,q),after=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyCurveSplitIntent(f.drawing,f.intent).document,intent:f.intent}).project.recordingSnapshots!,actual=evaluateRecordingSnapshot(after,recording.id,{angle:{x:31,y:0},useDraft:false}).drawing;
 f.canonical.childCurveIds.forEach((id,k)=>shapeOf(actual,id).forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(expected[k][i][a],8))));expect(snapshotSplitParameterRange(actual,f.canonical.childCurveIds[0])![1]).toBeCloseTo(q,10);
});
