import {afterEach,expect,it,vi} from 'vitest';
import {createEmptyProject} from '../../app/emptyProject';
import {prepareSnapshotEdit,snapshotEditContext} from '../../app/snapshotEditTransaction';
import {prepareDrawingSnapshotEdit} from '../../app/drawingSnapshotEdit';
import {currentDrawingPresentation} from '../../app/drawingSnapshotPresentation';
import {useEditor} from '../../app/store';
import {useWorkspaceMode} from '../../app/workspaceMode';
import {emptyDrawing,shapeOf,type DrawingDocument} from '../../domain/drawing/model';
import {moveToLayer,moveNode,createCurve} from '../../domain/drawing/commands';
import {movePaint,reorderPaint} from '../../domain/drawing/paintCommands';
import {resolveSnapshot} from '../../domain/recordingSnapshot/evaluation';
import {emptyRecordingSnapshotWorkspace,emptyRecordingSnapshot,emptySnapshotRecording} from '../../domain/recordingSnapshot/model';
import {upsertDrawingSource,canonicalElementId,syncRecordingSnapshotSources,drawingSnapshotForArtwork} from '../../domain/recordingSnapshot/sources';
import {createSnapshotAngleGraph} from '../../domain/recordingSnapshot/angleGraph';
import {parseRecordingSnapshots} from '../../domain/recordingSnapshot/persistence';
import {createCurveSplitIntent,mapCurveSplitIntent,applyCurveSplitIntent} from '../../domain/drawing/layerEditIntent';
import {prepareSnapshotCurveSplit,finishSnapshotCurveSplit} from '../../domain/recordingSnapshot/topologyEdits';
import {removeDeletedSourceReferences} from '../../domain/recordingSnapshot/sourceDeletion';
const id=(value:string)=>canonicalElementId('asset',value);
const editor=useEditor.getState(),mode=useWorkspaceMode.getState().mode;
afterEach(()=>{useEditor.setState(editor,true);useWorkspaceMode.getState().setMode(mode);vi.useRealTimers();});
function fixture(){
 const drawing:DrawingDocument={...emptyDrawing(),layers:[{id:'left',name:'Left',visible:true,locked:false,items:['first','offset']},{id:'right',name:'Right',visible:true,locked:false,items:['second']}],nodes:[{id:'a',position:[0,0]},{id:'b',position:[1,1]},{id:'c',position:[3,2]},{id:'d',position:[4,3]}],curves:[{id:'first',name:'First',nodes:['a','b'],handles:[[.2,.3],[.7,.6]],width:.01,visible:true,locked:false},{id:'second',name:'Second',nodes:['c','d'],handles:[[3.6,2.8],[3.7,2.6]],width:.01,visible:true,locked:false}],offsets:[{id:'offset',name:'Offset',source:[{id:'first',reverse:false}],distance:.13,start:.1,end:.8,taper:.08,width:.02,translation:[.04,.09],visible:true,locked:false}]};
 let workspace=upsertDrawingSource(emptyRecordingSnapshotWorkspace(),'asset',drawing,'Asset');const source=workspace.snapshots[0],view=emptyRecordingSnapshot('view');
 view.layers=source.layers.map((layer,index)=>({kind:'reference' as const,id:index?'right-slot':'left-slot',name:layer.name,baseSnapshotId:source.id,baseLayerId:layer.id}));
 const recording=emptySnapshotRecording('recording');recording.mode='triangulated';recording.snapshotIds=[view.id];recording.activeSnapshotId=view.id;recording.angleGraph=createSnapshotAngleGraph([{snapshotId:view.id,angle:view.angle}]);workspace={...workspace,snapshots:[...workspace.snapshots,view],recordings:[recording],activeRecordingId:recording.id};return {drawing,source,project:{...createEmptyProject(),drawing,recordingSnapshots:workspace}};
}
function edit(project:ReturnType<typeof fixture>['project'],change:(drawing:DrawingDocument)=>DrawingDocument){const before=resolveSnapshot(project.recordingSnapshots,'view',{useDraft:true}).drawing;return prepareSnapshotEdit(snapshotEditContext(project,false),{kind:'local-drawing-topology',recordingId:'recording',snapshotId:'view',angle:{x:0,y:0},beforeDrawing:before,drawing:change(before)});}
it('moves a referenced curve using the same canonical ID, preserves its live parent and local attributes, and saves one Undo',()=>{
 const f=fixture(),view=f.project.recordingSnapshots.snapshots.find(value=>value.id==='view')!;f.source.deformation.layers[id('left')]={placement:{translation:[.5,.2],rotation:0,scale:1}};view.deformation.layers['left-slot']={curveAppearance:{[id('first')]:{width:.04}},visibility:{[id('first')]:false},shape:{nodes:{[id('a')]:[.1,.2]},handles:{}}};
 const before=resolveSnapshot(f.project.recordingSnapshots,'view',{useDraft:true}).drawing,plan=edit(f.project,drawing=>moveToLayer(drawing,[id('first')],'right-slot')),workspace=plan.project.recordingSnapshots!,next=workspace.snapshots.find(value=>value.id==='view')!,actual=resolveSnapshot(workspace,'view',{useDraft:true}).drawing;
 expect(actual.layers.find(layer=>layer.id==='right-slot')!.items[0]).toBe(id('first'));expect(actual.layers.find(layer=>layer.id==='left-slot')!.items).not.toContain(id('first'));expect(shapeOf(actual,id('first'))).toEqual(shapeOf(before,id('first')));expect(next.memberSources).toEqual({[id('first')]:f.source.id});expect(next.deformation.layers['right-slot'].curveAppearance).toEqual({[id('first')]:{width:.04}});expect(next.deformation.layers['right-slot'].visibility).toEqual({[id('first')]:false});expect(workspace.library).toEqual(f.project.recordingSnapshots.library);expect(workspace.snapshots.find(value=>value.id===f.source.id)).toEqual(f.source);expect(workspace.recordings).toEqual(f.project.recordingSnapshots.recordings);
 const sourceChanged=upsertDrawingSource(workspace,'asset',moveNode(f.drawing,'b',[1.8,1.4]),'Asset'),updated=resolveSnapshot(sourceChanged,'view').drawing;expect(updated.nodes.find(node=>node.id===id('b'))!.position).not.toEqual(actual.nodes.find(node=>node.id===id('b'))!.position);expect(updated.curves.find(curve=>curve.id===id('first'))!.width).toBe(.04);expect(updated.curves.find(curve=>curve.id===id('first'))!.visible).toBe(false);
 vi.useFakeTimers();useWorkspaceMode.getState().setMode('recording');useEditor.setState({project:f.project,past:[],future:[]});useEditor.getState().commitPreparedSnapshotEdit(plan);expect(useEditor.getState().past).toEqual([f.project]);useEditor.getState().undo();expect(useEditor.getState().project).toBe(f.project);useEditor.getState().redo();expect(useEditor.getState().project).toBe(plan.project);
});
it('moves and reorders an offset without duplicating or changing its source/attributes; JSON keeps the authored order',()=>{
 const f=fixture(),before=resolveSnapshot(f.project.recordingSnapshots,'view').drawing,plan=edit(f.project,drawing=>movePaint(drawing,id('offset'),'right-slot')),moved=plan.project as typeof f.project,ordered=edit(moved,drawing=>reorderPaint(drawing,id('offset'),id('second'),true)),loaded=parseRecordingSnapshots(JSON.parse(JSON.stringify(ordered.project.recordingSnapshots))),actual=resolveSnapshot(loaded,'view').drawing;
 expect(actual.offsets).toEqual(before.offsets);expect(actual.layers.find(layer=>layer.id==='right-slot')!.items).toEqual([id('second'),id('offset')]);expect(loaded.snapshots.find(value=>value.id==='view')!.layers.find(layer=>layer.id==='right-slot')).toMatchObject({membership:{addElementIds:[id('offset')],orderOverride:[id('second'),id('offset')]}});
 const created=createCurve(f.drawing,'right',[[5,0],[5.2,.3],[5.7,.4],[6,1]],.01,'Fresh','fresh'),updated=upsertDrawingSource(loaded,'asset',created,'Asset'),live=resolveSnapshot(updated,'view').drawing;expect(live.layers.find(layer=>layer.id==='right-slot')!.items.slice(0,2)).toEqual([id('second'),id('offset')]);expect(live.layers.find(layer=>layer.id==='right-slot')!.items).toContain(id('fresh'));
});
it('source split and source deletion remap or prune moved member references and local order',()=>{
 const f=fixture(),moved=edit(f.project,drawing=>moveToLayer(drawing,[id('first')],'right-slot')).project.recordingSnapshots!,raw=createCurveSplitIntent(f.drawing,'first',.4),intent=mapCurveSplitIntent(raw,id),plan=prepareSnapshotCurveSplit(moved,f.source.id,intent),source=upsertDrawingSource(moved,'asset',applyCurveSplitIntent(f.drawing,raw).document,'Asset',{splitRetiredIds:new Set([intent.curveId])}),split=finishSnapshotCurveSplit(plan,source),view=split.snapshots.find(value=>value.id==='view')!,actual=resolveSnapshot(split,'view').drawing;
 expect(Object.keys(view.memberSources!).sort()).toEqual([...intent.childCurveIds].sort());expect(actual.layers.find(layer=>layer.id==='right-slot')!.items).toEqual([...intent.childCurveIds,id('second')]);expect(parseRecordingSnapshots(JSON.parse(JSON.stringify(split))).snapshots.find(value=>value.id==='view')!.memberSources).toEqual(view.memberSources);
 const deleted=structuredClone(moved);delete deleted.library.curves[id('first')];const clean=removeDeletedSourceReferences(moved,deleted,f.source.id,new Set([id('first')]));expect(clean.snapshots.find(value=>value.id==='view')!.memberSources).toEqual({});expect(resolveSnapshot(clean,'view').drawing.layers.find(layer=>layer.id==='right-slot')!.items).not.toContain(id('first'));
});
it('Drawing reference members share the same local route, while source-owned moves update the actual asset and live references',()=>{
 const f=fixture(),project={...f.project,drawingSnapshots:{version:1 as const,activeId:'asset',items:[{id:'asset',name:'Asset',drawing:f.drawing}],images:[]}},source=drawingSnapshotForArtwork(project.recordingSnapshots,'asset')!;
 const sourcePlan=prepareDrawingSnapshotEdit(project,moveToLayer(currentDrawingPresentation(project),['first'],'right')),changed=sourcePlan.project;
 expect(changed.drawing!.layers.find(layer=>layer.id==='right')!.items).toContain('first');expect(changed.drawing!.curves.map(curve=>curve.id)).toEqual(f.drawing.curves.map(curve=>curve.id));expect(changed.recordingSnapshots!.library.curves[id('first')]).toEqual(project.recordingSnapshots.library.curves[id('first')]);const child=resolveSnapshot(changed.recordingSnapshots!,'view').drawing;expect(child.layers.find(layer=>layer.id==='left-slot')!.items).not.toContain(id('first'));expect(child.layers.find(layer=>layer.id==='right-slot')!.items).toContain(id('first'));
 const consumerDrawing={...emptyDrawing(),layers:[]},consumer=upsertDrawingSource(changed.recordingSnapshots!,'consumer',consumerDrawing,'Consumer'),adapter=drawingSnapshotForArtwork(consumer,'consumer')!;adapter.layers=source.layers.map((layer,index)=>({kind:'reference' as const,id:index?'ref-right':'ref-left',name:layer.name,baseSnapshotId:source.id,baseLayerId:layer.id}));const consumerProject={...changed,drawing:consumerDrawing,drawingSnapshots:{version:1 as const,activeId:'consumer',items:[{id:'consumer',name:'Consumer',drawing:consumerDrawing}],images:[]},recordingSnapshots:consumer},before=currentDrawingPresentation(consumerProject),plan=prepareDrawingSnapshotEdit(consumerProject,movePaint(before,id('offset'),'ref-right'));
 expect(plan.project.drawing).toBe(consumerDrawing);expect(currentDrawingPresentation(plan.project).layers.find(layer=>layer.id==='ref-right')!.items).toContain(id('offset'));expect(plan.project.recordingSnapshots!.snapshots.find(value=>value.id===source.id)).toEqual(consumer.snapshots.find(value=>value.id===source.id));
});
it('a move between differently placed local layers preserves saved and draft controls without copying library geometry',()=>{
 const f=fixture(),view=f.project.recordingSnapshots.snapshots.find(value=>value.id==='view')!;view.deformation.layers={'left-slot':{placement:{translation:[.5,.3],rotation:14,scale:1.2}},'right-slot':{placement:{translation:[-.2,.6],rotation:-10,scale:.8}}};view.draft={angle:{x:0,y:0},channels:[],deformation:{layers:{'left-slot':{shape:{nodes:{[id('a')]:[.2,.1]},handles:{}}}},warps:[],bindings:[],relationPositions:{}}};
 const saved=resolveSnapshot(f.project.recordingSnapshots,'view',{useDraft:false}).drawing,draft=resolveSnapshot(f.project.recordingSnapshots,'view',{useDraft:true}).drawing,plan=edit(f.project,drawing=>moveToLayer(drawing,[id('first')],'right-slot'));
 for(const [useDraft,wanted] of [[false,saved],[true,draft]] as const){const actual=resolveSnapshot(plan.project.recordingSnapshots!,'view',{useDraft}).drawing;for(const curve of wanted.curves)for(const [index,point] of shapeOf(wanted,curve.id).entries())for(const axis of [0,1] as const)expect(shapeOf(actual,curve.id)[index][axis]).toBeCloseTo(point[axis],8);}
 expect(plan.project.recordingSnapshots!.library).toEqual(f.project.recordingSnapshots.library);expect(plan.project.recordingSnapshots!.recordings).toEqual(f.project.recordingSnapshots.recordings);
});
it('moved inherited members keep their chosen parent when the destination references another pose of the same source',()=>{
 const f=fixture(),workspace=f.project.recordingSnapshots,first=emptyRecordingSnapshot('first-parent'),second=emptyRecordingSnapshot('second-parent');for(const parent of [first,second]){parent.layers=f.source.layers.map(layer=>({kind:'reference',id:layer.id,name:layer.name,baseSnapshotId:f.source.id,baseLayerId:layer.id}));parent.deformation.layers[id('left')]={placement:{translation:[parent===first?1:9,0],rotation:0,scale:1}};}
 workspace.snapshots.push(first,second);const view=workspace.snapshots.find(value=>value.id==='view')!;for(const layer of view.layers)if(layer.kind==='reference')layer.baseSnapshotId=layer.id==='left-slot'?first.id:second.id;
 const before=resolveSnapshot(workspace,'view').drawing,plan=edit(f.project,drawing=>moveToLayer(drawing,[id('first')],'right-slot')),actual=resolveSnapshot(plan.project.recordingSnapshots!,'view').drawing;expect(shapeOf(actual,id('first'))).toEqual(shapeOf(before,id('first')));expect(plan.project.recordingSnapshots!.snapshots.find(value=>value.id==='view')!.memberSources).toEqual({[id('first')]:first.id});
 const changed=structuredClone(plan.project.recordingSnapshots!);changed.snapshots.find(value=>value.id===first.id)!.deformation.layers[id('left')].placement!.translation=[2,0];const live=resolveSnapshot(changed,'view').drawing;expect(live.nodes.find(node=>node.id===id('a'))!.position[0]).toBeCloseTo(actual.nodes.find(node=>node.id===id('a'))!.position[0]+1,8);
});
it('Group to Layer creates one local destination while retaining every existing canonical member and its parent source',async()=>{
 const {groupToLayer}=await import('../../domain/drawing/groups');const f=fixture();f.source.relations.groups={add:[{id:'local-group',name:'Bundle',curveIds:[id('first')],visible:true,locked:false}]};
 const before=resolveSnapshot(f.project.recordingSnapshots,'view').drawing,result=groupToLayer(before,'local-group'),plan=edit(f.project,()=>result.document),workspace=plan.project.recordingSnapshots!,view=workspace.snapshots.find(value=>value.id==='view')!,actual=resolveSnapshot(workspace,'view').drawing;
 expect(actual.layers.find(layer=>layer.id===result.layerId)!.items).toContain(id('first'));expect(view.layers.find(layer=>layer.id===result.layerId)?.kind).toBe('original');expect(actual.curves.map(curve=>curve.id).sort()).toEqual(before.curves.map(curve=>curve.id).sort());expect(shapeOf(actual,id('first'))).toEqual(shapeOf(before,id('first')));expect(workspace.library).toEqual(f.project.recordingSnapshots.library);expect(workspace.snapshots.find(value=>value.id===f.source.id)).toEqual(f.source);expect(parseRecordingSnapshots(JSON.parse(JSON.stringify(workspace))).snapshots.find(value=>value.id==='view')!.memberSources?.[id('first')]).toBe(f.source.id);
});
it('incidental ordering from an endpoint topology command stays on the topology route',async()=>{
 const {hasSnapshotLayerMemberEdit}=await import('../../domain/recordingSnapshot/layerMemberEdit'),{connect}=await import('../../domain/drawing/commands');const f=fixture(),before=resolveSnapshot(f.project.recordingSnapshots,'view').drawing,moved=moveToLayer(before,[id('first')],'right-slot'),connected=connect(moved,{curveId:id('second'),end:0},{curveId:id('first'),end:1},'POSITION');expect(hasSnapshotLayerMemberEdit(moved,connected)).toBe(false);
});
