import {expect,it} from 'vitest';
import {createEmptyProject} from '../../app/emptyProject';
import {prepareDrawingSnapshotEdit,prepareDrawingCurveSplit,prepareDrawingLayerDomainEdit} from '../../app/drawingSnapshotEdit';
import {currentDrawingPresentation,drawingSnapshotPresentation} from '../../app/drawingSnapshotPresentation';
import {emptyDrawing,type DrawingDocument,shapeOf} from '../../domain/drawing/model';
import {moveToLayer,moveNode,widthChange,deleteObjects} from '../../domain/drawing/commands';
import {emptyRecordingSnapshotWorkspace} from '../../domain/recordingSnapshot/model';
import {upsertDrawingSource,canonicalElementId,drawingSnapshotForArtwork,syncRecordingSnapshotSources} from '../../domain/recordingSnapshot/sources';
import {parseRecordingSnapshots} from '../../domain/recordingSnapshot/persistence';
import {createLayerAffineIntent} from '../../domain/drawing/layerDomainIntent';
const borrowed=(value:string)=>canonicalElementId('B',value),own=(value:string)=>canonicalElementId('A',value);
function fixture(){
 const drawing:DrawingDocument={...emptyDrawing(),layers:[{id:'left',name:'Left',visible:true,locked:false,items:['first']},{id:'right',name:'Right',visible:true,locked:false,items:['second']}],nodes:[{id:'a',position:[0,0]},{id:'b',position:[1,1]},{id:'c',position:[3,2]},{id:'d',position:[4,3]}],curves:[{id:'first',name:'First',nodes:['a','b'],handles:[[.2,.3],[.7,.6]],width:.01,visible:true,locked:false},{id:'second',name:'Second',nodes:['c','d'],handles:[[3.6,2.8],[3.7,2.6]],width:.01,visible:true,locked:false}]};
 let workspace=upsertDrawingSource(emptyRecordingSnapshotWorkspace(),'A',drawing,'A');workspace=upsertDrawingSource(workspace,'B',drawing,'B');const a=drawingSnapshotForArtwork(workspace,'A')!,b=drawingSnapshotForArtwork(workspace,'B')!;a.layers.push({kind:'reference',id:'borrow-slot',name:'Borrowed',baseSnapshotId:b.id,baseLayerId:borrowed('left')});const project={...createEmptyProject(),drawing,drawingSnapshots:{version:1 as const,activeId:'A',items:[{id:'A',name:'A',drawing},{id:'B',name:'B',drawing}],images:[]},recordingSnapshots:workspace};return {project,drawing,a,b};
}
const move=(project:ReturnType<typeof fixture>['project'])=>prepareDrawingSnapshotEdit(project,moveToLayer(currentDrawingPresentation(project),[borrowed('first')],'right')).project as typeof project;
it('borrowed member enters an original Drawing layer through a local overlay without becoming source-owned',()=>{
 const f=fixture(),after=move(f.project),snapshot=drawingSnapshotForArtwork(after.recordingSnapshots,'A')!,view=drawingSnapshotPresentation(after.recordingSnapshots,'A')!,layer=snapshot.layers.find(layer=>layer.id===own('right'))!;
 expect(after.drawing).toBe(f.project.drawing);expect(after.drawingSnapshots).toEqual(f.project.drawingSnapshots);expect(layer).toMatchObject({kind:'original',items:[own('second')],membership:{addElementIds:[borrowed('first')]}});expect(snapshot.source!.originIds[borrowed('first')]).toBeUndefined();expect(snapshot.memberSources?.[borrowed('first')]).toBe(f.b.id);expect(after.recordingSnapshots.library).toEqual(f.project.recordingSnapshots.library);expect(view.objectOwners.get(borrowed('first'))?.kind).toBe('snapshot-local');expect(view.objectOwners.get('second')?.kind).toBe('source-original');expect(view.drawing.layers.find(layer=>layer.id==='right')!.items).toEqual([borrowed('first'),'second']);
 const synced=syncRecordingSnapshotSources(after);expect(drawingSnapshotForArtwork(synced.recordingSnapshots!,'A')!.layers.find(layer=>layer.id===own('right'))).toEqual(layer);expect(currentDrawingPresentation({...after,recordingSnapshots:parseRecordingSnapshots(JSON.parse(JSON.stringify(after.recordingSnapshots)))}).layers.find(layer=>layer.id==='right')!.items).toEqual([borrowed('first'),'second']);
});
it('borrowed geometry and appearance stay local after a mixed-layer move, while original geometry still edits the actual source',()=>{
 const f=fixture(),mixed=move(f.project),drawing=currentDrawingPresentation(mixed),moved=prepareDrawingSnapshotEdit(mixed,moveNode(drawing,borrowed('a'),[.5,.7])).project,styled=prepareDrawingSnapshotEdit(moved,widthChange(currentDrawingPresentation(moved),[borrowed('first')],.05)).project;
 expect(styled.drawing).toBe(f.project.drawing);expect(styled.recordingSnapshots!.library).toEqual(f.project.recordingSnapshots.library);expect(currentDrawingPresentation(styled).nodes.find(node=>node.id===borrowed('a'))!.position).toEqual([.5,.7]);expect(currentDrawingPresentation(styled).curves.find(curve=>curve.id===borrowed('first'))!.width).toBe(.05);
 const original=prepareDrawingSnapshotEdit(styled,moveNode(currentDrawingPresentation(styled),'c',[3.4,2.5])).project;expect(original.drawing!.nodes.find(node=>node.id==='c')!.position).toEqual([3.4,2.5]);expect(original.drawing!.curves.some(curve=>curve.id===borrowed('first'))).toBe(false);expect(currentDrawingPresentation(original).curves.find(curve=>curve.id===borrowed('first'))!.width).toBe(.05);
});
it('mixed-layer transforms retain one local domain for every member, and a borrowed member can split or delete locally',()=>{
 const f=fixture(),mixed=move(f.project),before=currentDrawingPresentation(mixed),domain=createLayerAffineIntent(['right'],[1.2,.1,.2,.8,.4,-.2]),plan=prepareDrawingLayerDomainEdit(mixed,domain),after=currentDrawingPresentation(plan.project);expect(plan.project.drawing).toBe(f.project.drawing);for(const id of ['second',borrowed('first')])for(const [i,p] of shapeOf(before,id).entries()){const q=shapeOf(after,id)[i];expect(q[0]).toBeCloseTo(1.2*p[0]+.2*p[1]+.4,8);expect(q[1]).toBeCloseTo(.1*p[0]+.8*p[1]-.2,8);}
 const split=prepareDrawingCurveSplit(mixed,borrowed('first'),.4),splitDrawing=currentDrawingPresentation(split.project);expect(splitDrawing.layers.find(layer=>layer.id==='right')!.items).toEqual([...split.ids,'second']);expect(split.project.drawing).toBe(f.project.drawing);expect(split.project.recordingSnapshots!.library.curves[borrowed('first')]).toEqual(f.project.recordingSnapshots.library.curves[borrowed('first')]);
 const removed=prepareDrawingSnapshotEdit(mixed,deleteObjects(currentDrawingPresentation(mixed),[borrowed('first')])).project;expect(removed.drawing).toBe(f.project.drawing);expect(currentDrawingPresentation(removed).curves.some(curve=>curve.id===borrowed('first'))).toBe(false);expect(removed.recordingSnapshots!.library.curves[borrowed('first')]).toEqual(f.project.recordingSnapshots.library.curves[borrowed('first')]);
});
it('source-owned moves between original layers still update the asset when the starting layer also contains a borrowed member',()=>{
 const f=fixture(),mixed=move(f.project),moved=prepareDrawingSnapshotEdit(mixed,moveToLayer(currentDrawingPresentation(mixed),['second'],'left')).project;expect(moved.drawing!.layers.find(layer=>layer.id==='left')!.items).toContain('second');expect(moved.drawing!.layers.find(layer=>layer.id==='right')!.items).not.toContain('second');expect(moved.drawing!.curves.map(curve=>curve.id).sort()).toEqual(['first','second']);expect(currentDrawingPresentation(moved).layers.find(layer=>layer.id==='right')!.items).toEqual([borrowed('first')]);
});
it('live source edits and later new original members preserve the borrowed overlay; deleting the borrowed source prunes only its local references',()=>{
 const f=fixture(),mixed=move(f.project),shifted=upsertDrawingSource(mixed.recordingSnapshots,'B',moveNode(f.drawing,'b',[1.8,1.3]),'B'),present=currentDrawingPresentation({...mixed,recordingSnapshots:shifted});expect(present.nodes.find(node=>node.id===borrowed('b'))!.position).toEqual([1.8,1.3]);expect(present.layers.find(layer=>layer.id==='right')!.items).toEqual([borrowed('first'),'second']);
 const erased=upsertDrawingSource(shifted,'B',deleteObjects(f.drawing,['first']),'B'),after=currentDrawingPresentation({...mixed,recordingSnapshots:erased});expect(after.layers.find(layer=>layer.id==='right')!.items).toEqual(['second']);expect(erased.library.curves[own('first')]).toEqual(f.project.recordingSnapshots.library.curves[own('first')]);expect(drawingSnapshotForArtwork(erased,'A')!.memberSources?.[borrowed('first')]).toBeUndefined();
});
it('explicit endpoint link authorship works between original and borrowed members in one mixed layer',async()=>{
 const {linkEndpoints}=await import('../../domain/drawing/commands'),{createSnapshotRelationAuthoringIntent}=await import('../../domain/recordingSnapshot/relationAuthoringIntent');const f=fixture(),mixed=move(f.project),before=currentDrawingPresentation(mixed),wanted=linkEndpoints(before,{curveId:'second',end:0},{curveId:borrowed('first'),end:1},true),view=drawingSnapshotPresentation(mixed.recordingSnapshots,'A')!,intent=createSnapshotRelationAuthoringIntent(view.snapshotId,before,wanted),plan=prepareDrawingSnapshotEdit(mixed,wanted,intent),after=currentDrawingPresentation(plan.project);
 expect(after.endpointLinks).toEqual(wanted.endpointLinks);for(const id of ['second',borrowed('first')])for(const [i,p] of shapeOf(wanted,id).entries())for(const axis of [0,1] as const)expect(shapeOf(after,id)[i][axis]).toBeCloseTo(p[axis],8);expect(plan.project.drawing).toBe(f.project.drawing);expect(plan.project.recordingSnapshots!.library).toEqual(f.project.recordingSnapshots.library);
});
it('source original moves transfer child saved/inherited/draft residual ownership and keep later source point edits live',async()=>{
 const {emptyRecordingSnapshot}=await import('../../domain/recordingSnapshot/model'),{resolveSnapshot}=await import('../../domain/recordingSnapshot/evaluation');const f=fixture(),child=emptyRecordingSnapshot('residual-child');child.layers=[{kind:'reference',id:'child-left',name:'Left',baseSnapshotId:f.a.id,baseLayerId:own('left')},{kind:'reference',id:'child-right',name:'Right',baseSnapshotId:f.a.id,baseLayerId:own('right')}];child.deformation.layers['child-left']={shape:{nodes:{[own('a')]:[.25,-.15]},handles:{[own('first')]:[[.1,.2],[0,0]]}},curveAppearance:{[own('first')]:{width:.043}}};child.inheritedState={warps:[],bindings:[],relationPositions:{},layers:{'child-left':{visibility:{[own('first')]:false}}}};child.draft={angle:child.angle,channels:[],deformation:{warps:[],bindings:[],relationPositions:{},layers:{'child-left':{shape:{nodes:{[own('a')]:[.4,.3]},handles:{[own('first')]:[[.12,.15],[0,0]]}}}}}};f.project.recordingSnapshots.snapshots.push(child);
 const plan=prepareDrawingSnapshotEdit(f.project,moveToLayer(currentDrawingPresentation(f.project),['first'],'right')),workspace=plan.project.recordingSnapshots!,moved=workspace.snapshots.find(value=>value.id===child.id)!;
 expect(moved.deformation.layers['child-right'].shape).toEqual(child.deformation.layers['child-left'].shape);expect(moved.deformation.layers['child-right'].curveAppearance).toEqual(child.deformation.layers['child-left'].curveAppearance);expect(moved.inheritedState!.layers['child-right'].visibility).toEqual({[own('first')]:false});expect(moved.draft!.deformation.layers['child-right'].shape).toEqual(child.draft!.deformation.layers['child-left'].shape);expect(workspace.recordings).toEqual(f.project.recordingSnapshots.recordings);
 const changed=prepareDrawingSnapshotEdit(plan.project,moveNode(currentDrawingPresentation(plan.project),'a',[.8,.9])).project,reloaded=parseRecordingSnapshots(JSON.parse(JSON.stringify(changed.recordingSnapshots)));
 for(const [useDraft,delta] of [[false,[.25,-.15]],[true,[.4,.3]]] as const){const drawing=resolveSnapshot(reloaded,child.id,{useDraft}).drawing,node=drawing.nodes.find(node=>node.id===own('a'))!;expect(node.position[0]).toBeCloseTo(.8+delta[0],8);expect(node.position[1]).toBeCloseTo(.9+delta[1],8);expect(drawing.curves.find(curve=>curve.id===own('first'))!.width).toBe(.043);expect(drawing.curves.find(curve=>curve.id===own('first'))!.visible).toBe(false);}
});
it('A edits under a mixed nonlinear layer use its existing output-control stage while retaining both original sources',async()=>{
 const {createLayerCageIntent}=await import('../../domain/drawing/layerDomainIntent'),{neutralBend}=await import('../../domain/deformation/coons');const f=fixture(),mixed=move(f.project),bend=neutralBend();bend.handles[1][0][0]=.3;const intent=createLayerCageIntent(['right'],{kind:'h-coons',restRect:{min:[-1,-1],max:[5,4]},quad:[[-1,-1],[5.2,-.8],[4.8,4.1],[-1.2,4]],bend}),caged=prepareDrawingLayerDomainEdit(mixed,intent).project,before=currentDrawingPresentation(caged),point=before.nodes.find(node=>node.id==='c')!.position,target=moveNode(before,'c',[point[0]+.1,point[1]+.15]),plan=prepareDrawingSnapshotEdit(caged,target),actual=currentDrawingPresentation(plan.project);
 expect(plan.project.drawing).toBe(f.project.drawing);expect(plan.project.recordingSnapshots!.library).toEqual(f.project.recordingSnapshots.library);for(const curve of target.curves)for(const [i,p] of shapeOf(target,curve.id).entries())for(const axis of [0,1] as const)expect(shapeOf(actual,curve.id)[i][axis]).toBeCloseTo(p[axis],7);
});
it('Pen extension of a borrowed stroke in an original layer creates local identities without adding them to the original asset',async()=>{
 const {createPenCurve,connect}=await import('../../domain/drawing/commands');const f=fixture(),mixed=move(f.project),before=currentDrawingPresentation(mixed),created=createPenCurve(before,'right',[[1,1],[1.2,1.1],[1.6,1.4],[2,1.5]],.01,'borrowed-extension'),wanted=connect(created,{curveId:borrowed('first'),end:1},{curveId:'borrowed-extension',end:0},'POSITION'),plan=prepareDrawingSnapshotEdit(mixed,wanted),actual=currentDrawingPresentation(plan.project),snapshot=drawingSnapshotForArtwork(plan.project.recordingSnapshots!,'A')!;
 expect(plan.project.drawing).toBe(f.project.drawing);expect(snapshot.source!.originIds['borrowed-extension']).toBeUndefined();expect(snapshot.layers.find(layer=>layer.id===own('right'))).toMatchObject({items:[own('second')],membership:{addElementIds:expect.arrayContaining([borrowed('first'),'borrowed-extension'])}});expect(actual.curves.find(curve=>curve.id==='borrowed-extension')!.nodes[0]).toBe(borrowed('b'));expect(plan.project.recordingSnapshots!.library.curves[borrowed('first')]).toEqual(f.project.recordingSnapshots.library.curves[borrowed('first')]);
});
