import {expect,test} from 'vitest';
import {createEmptyProject} from '../../app/emptyProject';
import {prepareSnapshotEdit,snapshotEditContext} from '../../app/snapshotEditTransaction';
import {createCurveSplitIntent,createLayerCurveSplitIntent,applyLayerEditIntent,curveSplitIntents,mapCurveSplitIntent} from '../../domain/drawing/layerEditIntent';
import {emptyDrawing,shapeOf,type DrawingDocument,type Cubic} from '../../domain/drawing/model';
import {evaluatedControlParameter,evaluatedMaterialProgram} from '../../domain/drawing/evaluatedDeformation';
import {neutralBend} from '../../domain/deformation/coons';
import {ensureRecordingSnapshots} from '../../domain/recordingSnapshot/migration';
import {canonicalElementId,drawingSnapshotForArtwork,upsertDrawingSource} from '../../domain/recordingSnapshot/sources';
import {emptyRecordingSnapshot,emptySnapshotRecording} from '../../domain/recordingSnapshot/model';
import {resolveSnapshot} from '../../domain/recordingSnapshot/evaluation';
import {parseRecordingSnapshots} from '../../domain/recordingSnapshot/persistence';
import {createSnapshotAngleGraph} from '../../domain/recordingSnapshot/angleGraph';
import {seedAutomaticExtremeSnapshots} from '../../domain/recordingSnapshot/automaticSnapshotEdits';
import {subcurve} from '../../domain/drawing/roundedJoin';
import {displayField,displayPath} from '../../domain/drawing/displayIntervals';
import {splitMaterialProgram} from '../../domain/recordingSnapshot/materialProgramSplit';
import {applyOwnedMaterialProgram} from '../../domain/recordingSnapshot/materialProgramEvaluation';
import {prepareIndependentSnapshotLayers} from '../../domain/recordingSnapshot/independentCopy';
import {remapLayerDomains} from '../../domain/recordingSnapshot/layerDomains';
const cid=(id:string)=>canonicalElementId('$working',id);
const close=(actual:Cubic,expected:Cubic)=>actual.forEach((p,i)=>p.forEach((v,a)=>expect(v).toBeCloseTo(expected[i][a],9)));
function fixture(paired=false){
 const drawing:DrawingDocument={...emptyDrawing(),nodes:[{id:'a',position:[-.8,-.3]},{id:'b',position:[.7,.5]},...(paired?[{id:'c',position:[.9,-.6] as [number,number]},{id:'d',position:[-.3,.8] as [number,number]}]:[])],curves:[{id:'curve',name:'Curve',nodes:['a','b'],handles:[[-.6,.6],[.4,-.5]],width:.01,visible:true,locked:false},...(paired?[{id:'other',name:'Other',nodes:['c','d'] as [string,string],handles:[[.8,.5],[-.1,-.7]] as [[number,number],[number,number]],width:.02,visible:true,locked:false}]:[])],layers:[{id:'layer',name:'Layer',items:paired?['curve','other']:['curve'],visible:true,locked:false}],mirrorAxisX:0,mirrorEditing:{enabled:true,curvePairs:paired?[{id:'pair',a:'curve',b:'other',reverse:true}]:[]}};
 const project=ensureRecordingSnapshots({...createEmptyProject(),drawing}),workspace=project.recordingSnapshots,source=drawingSnapshotForArtwork(workspace,'$working')!,view=emptyRecordingSnapshot('view','View','view',{x:-90,y:0}),bend=neutralBend();bend.handles[1][0][0]=1.25;
 view.layers=[{kind:'reference',id:'slot',name:'Curve',baseSnapshotId:source.id,baseLayerId:cid('layer')}];view.deformation.layerDomains=[{kind:'h-coons',id:'cage',layerIds:['slot'],restRect:{min:[-1,-1],max:[1,1]},quad:[[-1,-1],[1,-.7],[.7,1],[-.9,.8]],bend}];workspace.snapshots.push(view);
 return {project,workspace,drawing,view,source};
}
const materialEnds=(drawing:DrawingDocument)=>Object.fromEntries((drawing.displayIntervals??[]).map(track=>{const field=displayField(drawing,displayPath(drawing,track.anchor.id));return [track.id,track.ranges.map(range=>[field.at(field.native(track,range.start)).p,field.at(field.native(track,range.end)).p])];}));

test.each([false,true])('owned reflected descriptor reverses the native cut, child order, endpoints and correction lineage exactly (stroke scope=%s)',scoped=>{
 const f=fixture(),domain=f.view.deformation.layerDomains![0];if(domain.kind!=='h-coons')throw Error('fixture');
 const program=[{kind:'reflected' as const,axisX:.17,reverseCurveIds:['curve'],steps:[{kind:'cage' as const,domain:{...domain,layerIds:['layer'],...(scoped?{strokeScope:{kind:'continuous-strokes' as const,curveIds:['curve']}}:{})}},{kind:'post-shape' as const,value:{nodes:{a:[.04,.07] as [number,number]},handles:{curve:[[.03,.08],[-.02,.06]] as [[number,number],[number,number]]}}}]}];
 let n=0;const intent=createCurveSplitIntent(f.drawing,'curve',.371,{allocateId:()=>`owned-${++n}`}),before=applyOwnedMaterialProgram(f.drawing,['layer'],program),q=evaluatedControlParameter(before,'curve',intent.t),expected=[subcurve(shapeOf(before,'curve'),0,q),subcurve(shapeOf(before,'curve'),q,1)],split=splitMaterialProgram(program,intent),after=applyOwnedMaterialProgram(applyLayerEditIntent(f.drawing,intent).document,['layer'],JSON.parse(JSON.stringify(split)));
 intent.childCurveIds.forEach((id,k)=>close(shapeOf(after,id),expected[k]));const reflected=split[0];if(reflected.kind!=='reflected'||reflected.steps[0].kind!=='cage')throw Error('descriptor');expect(reflected.reverseCurveIds).toEqual(intent.childCurveIds);expect(reflected.steps[0].domain.fitLineages).toEqual([{id:'curve',parts:[{curveId:intent.childCurveIds[1],parameterRange:[0,1-intent.t]},{curveId:intent.childCurveIds[0],parameterRange:[1-intent.t,1]}]}]);
 const material=applyLayerEditIntent(f.drawing,intent).document,next=createCurveSplitIntent(material,intent.childCurveIds[0],.419,{allocateId:()=>`owned-repeat-${++n}`}),r=evaluatedControlParameter(after,next.curveId,next.t),parts=[subcurve(shapeOf(after,next.curveId),0,r),subcurve(shapeOf(after,next.curveId),r,1)],repeated=applyOwnedMaterialProgram(applyLayerEditIntent(material,next).document,['layer'],splitMaterialProgram(split,next));next.childCurveIds.forEach((id,k)=>close(shapeOf(repeated,id),parts[k]));
});

test('automatic +90 reflects a reversed paired source split with stable IDs, material, locks, live source and Undo',async()=>{
 const f=fixture(true);f.drawing.displayIntervals=[{id:'material',scope:'CURVE',anchor:{id:'curve',reverse:false},ranges:[{id:'range',start:.1,end:.87}]},{id:'other-material',scope:'CURVE',anchor:{id:'other',reverse:true},ranges:[{id:'other-range',start:.1,end:.87}]}];f.project.recordingSnapshots=upsertDrawingSource(f.workspace,'$working',f.drawing);const w=f.project.recordingSnapshots,recording=emptySnapshotRecording('recording');recording.mode='triangulated';recording.snapshotIds=['view'];recording.activeSnapshotId='view';recording.angleGraph=createSnapshotAngleGraph([{snapshotId:'view',angle:{x:-90,y:0}}]);w.recordings=[recording];w.activeRecordingId=recording.id;let n=0;seedAutomaticExtremeSnapshots(w,recording.id,'view',()=>`auto-${++n}`);const mirror=w.snapshots.find(s=>s.inputMirror)!;mirror.objectLocks={[cid('curve')]:true};
 const before=resolveSnapshot(w,mirror.id).drawing,ends=materialEnds(before),intent=createLayerCurveSplitIntent(f.drawing,'curve',.371,{allocateId:()=>`paired-${++n}`}),canonical=curveSplitIntents(intent).map(i=>mapCurveSplitIntent(i,cid)),expected=canonical.map(i=>{const q=evaluatedControlParameter(before,i.curveId,i.t);return [subcurve(shapeOf(before,i.curveId),0,q),subcurve(shapeOf(before,i.curveId),q,1)];});
 const plan=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyLayerEditIntent(f.drawing,intent).document,intent}),loaded=parseRecordingSnapshots(JSON.parse(JSON.stringify(plan.project.recordingSnapshots))),actual=resolveSnapshot(loaded,mirror.id).drawing;
 canonical.forEach((i,k)=>i.childCurveIds.forEach((id,j)=>close(shapeOf(actual,id),expected[k][j])));expect(actual.curves.map(c=>c.id).sort()).toEqual(canonical.flatMap(i=>[...i.childCurveIds]).sort());for(const id of canonical[0].childCurveIds)expect(actual.curves.find(c=>c.id===id)!.locked).toBe(true);
 expect(resolveSnapshot(loaded,mirror.id).diagnostics.filter(d=>d.code==='LAYER_DOMAIN')).toEqual([]);
 expect(resolveSnapshot(loaded,mirror.id).diagnostics.filter(d=>d.code==='INPUT_MIRROR')).toEqual([]);
 for(const i of canonical)for(const track of i.intervals){const old=ends[track.trackId][0],afterEnds=materialEnds(actual),left=afterEnds[track.trackId][0],right=afterEnds[track.rightTrackId][0],reverse=before.displayIntervals!.find(t=>t.id===track.trackId)!.anchor.reverse,wanted=reverse?[right[0],left[1]]:[left[0],right[1]];wanted.forEach((p,k)=>p.forEach((v,a)=>expect(v).toBeCloseTo(old[k][a],8)));}
 const repeatedIntent=createLayerCurveSplitIntent(plan.project.drawing!,curveSplitIntents(intent)[0].childCurveIds[0],.423,{allocateId:()=>`paired-repeat-${++n}`}),repeatCanonical=curveSplitIntents(repeatedIntent).map(i=>mapCurveSplitIntent(i,cid)),repeatExpected=repeatCanonical.map(i=>{const q=evaluatedControlParameter(actual,i.curveId,i.t);return [subcurve(shapeOf(actual,i.curveId),0,q),subcurve(shapeOf(actual,i.curveId),q,1)];}),repeat=prepareSnapshotEdit(snapshotEditContext(plan.project,true),{kind:'original-geometry',drawing:applyLayerEditIntent(plan.project.drawing!,repeatedIntent).document,intent:repeatedIntent}).project,repeatDrawing=resolveSnapshot(repeat.recordingSnapshots!,mirror.id).drawing;repeatCanonical.forEach((i,k)=>i.childCurveIds.forEach((id,j)=>close(shapeOf(repeatDrawing,id),repeatExpected[k][j])));
 const {moveHandle}=await import('../../domain/drawing/commands'),raw=plan.project.drawing!,left=canonical[0].childCurveIds[0],rawLeft=curveSplitIntents(intent)[0].childCurveIds[0],curve=raw.curves.find(c=>c.id===rawLeft)!,changed=moveHandle(raw,{curveId:rawLeft,end:0},[curve.handles[0][0]+.013,curve.handles[0][1]]),live=upsertDrawingSource(loaded,'$working',changed);expect(resolveSnapshot(live,mirror.id).drawing.curves).not.toEqual(actual.curves);expect(live.library.curves[left].handles).toEqual(changed.curves.find(c=>c.id===rawLeft)!.handles);
 const {useEditor}=await import('../../app/store'),previous=useEditor.getState();try{useEditor.setState({project:f.project,past:[],future:[]});useEditor.getState().commitPreparedSnapshotEdit(plan);expect(useEditor.getState().past).toEqual([f.project]);useEditor.getState().undo();expect(useEditor.getState().project).toBe(f.project);}finally{useEditor.setState(previous,true);}
},20000);

test('independently copied reflected program restricts at its new source root and remains live after JSON',()=>{
 const f=fixture(true),mirror=emptyRecordingSnapshot('mirror');mirror.parentSnapshotId='view';mirror.inputMirror={axisX:.17,curvePairs:[{id:'paired',a:cid('curve'),b:cid('other'),reverse:true}]};mirror.layers=[{kind:'reference',id:'mirror-slot',name:'Mirror',baseSnapshotId:'view',baseLayerId:'slot'}];f.workspace.snapshots.push(mirror);let n=0;
 const copy=prepareIndependentSnapshotLayers(f.workspace,mirror,['mirror-slot'],()=>`copy-${++n}`),detached={...f.workspace,library:copy.library,snapshots:[copy.snapshot]},material=resolveSnapshot(detached,copy.snapshot.id).source,project=ensureRecordingSnapshots({...createEmptyProject(),drawing:material}),source=drawingSnapshotForArtwork(project.recordingSnapshots,'$working')!;source.deformation.layerDomains=remapLayerDomains(copy.snapshot.deformation.layerDomains!,cid);
 const rawId=copy.idMap[cid('curve')],before=resolveSnapshot(project.recordingSnapshots,source.id).drawing,intent=createCurveSplitIntent(material,rawId,.413,{allocateId:()=>`copy-split-${++n}`}),canonical=mapCurveSplitIntent(intent,cid),q=evaluatedControlParameter(before,cid(rawId),intent.t),expected=[subcurve(shapeOf(before,cid(rawId)),0,q),subcurve(shapeOf(before,cid(rawId)),q,1)];expect(evaluatedMaterialProgram(before,cid(rawId))!.some(step=>step.kind==='reflected')).toBe(true);
 const result=prepareSnapshotEdit(snapshotEditContext(project,true),{kind:'original-geometry',drawing:applyLayerEditIntent(material,intent).document,intent}).project,loaded=parseRecordingSnapshots(JSON.parse(JSON.stringify(result.recordingSnapshots))),actual=resolveSnapshot(loaded,source.id).drawing;canonical.childCurveIds.forEach((id,k)=>close(shapeOf(actual,id),expected[k]));
 expect(loaded.snapshots.find(s=>s.id===source.id)!.deformation.layerDomains![0]).toMatchObject({materialProgram:[{kind:'reflected',reverseCurveIds:expect.arrayContaining([...canonical.childCurveIds])}]});
});

test('a cage after a reversed semantic reflection restricts the same parent family',()=>{
 const f=fixture(true),mirror=emptyRecordingSnapshot('mirror');mirror.parentSnapshotId='view';mirror.inputMirror={axisX:0,curvePairs:[{id:cid('pair'),a:cid('curve'),b:cid('other'),reverse:true}]};mirror.layers=[{kind:'reference',id:'mirror-slot',name:'Mirror',baseSnapshotId:'view',baseLayerId:'slot'}];const cage=structuredClone(f.view.deformation.layerDomains![0]);cage.id='after-reflection';cage.layerIds=['mirror-slot'];if(cage.kind!=='h-coons')throw Error('fixture');cage.quad[1][0]+=.1;mirror.deformation.layerDomains=[cage];f.workspace.snapshots.push(mirror);let n=0;
 const before=resolveSnapshot(f.workspace,mirror.id).drawing,intent=createLayerCurveSplitIntent(f.drawing,'curve',.371,{allocateId:()=>`nested-${++n}`}),canonical=curveSplitIntents(intent).map(i=>mapCurveSplitIntent(i,cid)),expected=canonical.map(i=>{const q=evaluatedControlParameter(before,i.curveId,i.t);return [subcurve(shapeOf(before,i.curveId),0,q),subcurve(shapeOf(before,i.curveId),q,1)];}),next=prepareSnapshotEdit(snapshotEditContext(f.project,true),{kind:'original-geometry',drawing:applyLayerEditIntent(f.drawing,intent).document,intent}).project,actual=resolveSnapshot(next.recordingSnapshots!,mirror.id);expect(actual.diagnostics.filter(d=>d.code==='LAYER_DOMAIN')).toEqual([]);canonical.forEach((i,k)=>i.childCurveIds.forEach((id,j)=>close(shapeOf(actual.drawing,id),expected[k][j])));
});
