import {expect,test} from 'vitest';
import {emptyRecordingSnapshotWorkspace,emptyRecordingSnapshot,emptySnapshotRecording,emptySnapshotDeformationState} from '../../domain/recordingSnapshot/model';
import {parseRecordingSnapshots} from '../../domain/recordingSnapshot/persistence';
import {createSnapshotAngleGraph} from '../../domain/recordingSnapshot/angleGraph';
import {classifyRecordingWorkspaceChanges,needsSnapshotLayerPropagation,shareValidatedRecordingWorkspace} from '../../domain/recordingSnapshot/workspaceChanges';
function fixture(){const workspace=emptyRecordingSnapshotWorkspace(),zero=emptyRecordingSnapshot('zero'),side=emptyRecordingSnapshot('side','Side','view',{x:90,y:0}),recording=emptySnapshotRecording('recording');recording.mode='triangulated';recording.snapshotIds=[zero.id,side.id];recording.angleGraph=createSnapshotAngleGraph([zero,side].map(snapshot=>({snapshotId:snapshot.id,angle:snapshot.angle})));workspace.library.nodes={n:{id:'n',position:[0,0]},m:{id:'m',position:[1,1]}};workspace.library.curves={c:{id:'c',name:'Curve',nodes:['n','m'],handles:[[.2,.2],[.8,.8]],width:.01,visible:true,locked:false}};for(const snapshot of [zero,side])snapshot.layers=[{kind:'original',id:'layer',name:'Layer',visible:true,locked:false,items:['c']}];workspace.snapshots=[zero,side];workspace.recordings=[recording];return workspace;}
test('validated adoption retains unchanged source, snapshots and program fragments without retaining fresh aliases',()=>{
 const before=fixture(),raw=structuredClone(before);raw.snapshots[1].draft={angle:{x:90,y:0},deformation:{...emptySnapshotDeformationState(),layers:{layer:{shape:{nodes:{n:[.2,.1]},handles:{}}}}},channels:[]};
 const fresh=parseRecordingSnapshots(raw),next=shareValidatedRecordingWorkspace(before,fresh);expect(next).not.toBe(fresh);expect(next.library).toBe(before.library);expect(next.snapshots[0]).toBe(before.snapshots[0]);expect(next.snapshots[1].deformation).toBe(before.snapshots[1].deformation);expect(next.recordings).toBe(before.recordings);expect(next.snapshots[1].draft).not.toBe(raw.snapshots[1].draft);expect(next).toEqual(fresh);expect(shareValidatedRecordingWorkspace(before,structuredClone(before))).toBe(before);
});
test('coordinate draft and response revisions do not request saved membership propagation',()=>{
 const before=fixture(),next=shareValidatedRecordingWorkspace(before,structuredClone(before));const draft={...next,snapshots:next.snapshots.map(snapshot=>snapshot.id==='side'?{...snapshot,draft:{angle:snapshot.angle,deformation:{...emptySnapshotDeformationState(),layers:{layer:{shape:{nodes:{n:[.2,.1] as [number,number]},handles:{}}}}},channels:[]}}:snapshot)};
 const changes=classifyRecordingWorkspaceChanges(before,draft);expect(changes.geometry).toEqual(['side']);expect(changes.drafts).toEqual(['side']);expect(changes.source).toBeUndefined();expect(needsSnapshotLayerPropagation(changes)).toBe(false);
 const recording=draft.recordings[0],responses={...draft,recordings:[{...recording,angleGraph:{...recording.angleGraph!,edgeResponses:{edge:{nodes:{n:{x:[[.5,.7] as [number,number]]}},handles:{}}}}}]};expect(classifyRecordingWorkspaceChanges(draft,responses).responses).toEqual(['recording']);expect(needsSnapshotLayerPropagation(classifyRecordingWorkspaceChanges(draft,responses))).toBe(false);
});
test('terminal interval changes and navigation do not mark control geometry dirty',()=>{
 const before=fixture(),side=before.snapshots[1],next={...before,snapshots:[before.snapshots[0],{...side,draft:{angle:side.angle,deformation:{...emptySnapshotDeformationState(),layers:{layer:{intervals:{track:{appearance:{id:'track',anchor:{id:'c',reverse:false},ranges:[{id:'range',start:.2,end:.4}]},enabled:{}}}}}},channels:[]}}]};const changes=classifyRecordingWorkspaceChanges(before,next);expect(changes.geometry).toBeUndefined();expect(changes.material).toEqual(['side']);expect(needsSnapshotLayerPropagation(changes)).toBe(false);
 const moved={...before,recordings:[{...before.recordings[0],angle:{x:30,y:0}}]};expect(classifyRecordingWorkspaceChanges(before,moved)).toEqual({});
});
test('source membership, mirror policy and mesh changes invalidate structural consumers',()=>{
 const before=fixture(),next=structuredClone(before);next.snapshots[0].layers.push({kind:'original',id:'new',name:'New',visible:true,locked:false,items:[]});const shared=shareValidatedRecordingWorkspace(before,next),changes=classifyRecordingWorkspaceChanges(before,shared);expect(changes.structure).toEqual(['zero']);expect(needsSnapshotLayerPropagation(changes)).toBe(true);
 const reflected={...before,snapshots:[before.snapshots[0],{...before.snapshots[1],inputMirror:{axisX:0,curvePairs:[]}}]};expect(classifyRecordingWorkspaceChanges(before,reflected).mirrors).toEqual(['side']);expect(needsSnapshotLayerPropagation(classifyRecordingWorkspaceChanges(before,reflected))).toBe(true);
});
