import {test,expect} from '@playwright/test';
test('Section cap pair: 2D/3D rendering, analytic point picking, UV, history, reload and cascade',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.evaluate(async()=>{const {createLandmarkProject}=await import('/src/domain/landmarks/presets.ts' as string),{migrateHeadFrame}=await import('/src/domain/head/frame.ts' as string);const p=migrateHeadFrame(createLandmarkProject());Object.assign(p,{landmarks:[],curves:[],patches:[],centerlineOrder:[],loomisRegions:[],loomisCaps:[]});(window as any).__editorPerfStore.getState().load(p);});
 await page.getByText('Loomis Set',{exact:true}).click();await page.getByRole('button',{name:'+ 侧面剖面对',exact:true}).click();await page.getByRole('button',{name:'封闭为 Loomis 面',exact:true}).click();await expect(page.getByText('Loomis 面：已封闭',{exact:true})).toBeVisible();
 await expect(page.getByTestId('gpu-derived-renderer')).toHaveAttribute('data-surface-count','2');
 const cap=await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.loomisCaps[0]);
 const canvas=page.getByTestId('point-inspect').locator('canvas'),box=(await canvas.boundingBox())!;
 const xy=await page.evaluate(async({id,w,h})=>{const three=await import('/node_modules/.vite/deps/three.js' as string),{capPosition}=await import('/src/domain/head/caps.ts' as string),{useInspectionCamera}=await import('/src/ui/windows/state.ts' as string),p=(window as any).__editorPerfStore.getState().project,pose=useInspectionCamera.getState(),camera=new three.PerspectiveCamera(34,w/h,.1,100);camera.position.fromArray(pose.position);camera.quaternion.fromArray(pose.quaternion);camera.updateMatrixWorld();const v=new three.Vector3(...capPosition(p,id,.15,.2)).project(camera);return [(v.x+1)*w/2,(1-v.y)*h/2];},{id:cap.id,w:box.width,h:box.height});
 await page.evaluate(()=>(window as any).__editorPerfStore.setState({selectedCurveId:null}));await page.mouse.click(box.x+xy[0],box.y+xy[1]);await expect.poll(()=>page.evaluate(()=>{const s=(window as any).__editorPerfStore.getState();return s.project.loomisCaps.some((c:any)=>c.hostSectionCurveId===s.selectedCurveId);})).toBe(true);
 await page.getByRole('button',{name:'+ 球面定位点',exact:true}).click();await page.mouse.click(box.x+xy[0],box.y+xy[1]);await page.keyboard.press('Escape');
 await expect(page.getByTestId('cap-point-inspector')).toBeVisible();const before=await page.evaluate(()=>{const s=(window as any).__editorPerfStore.getState();return {id:s.selectedId,points:s.project.landmarks};});expect(before.points).toHaveLength(2);expect(before.points[0].placement.kind).toBe('ON_SECTION_CAP');
 const slider=page.getByRole('slider',{name:'Cap U',exact:true});await slider.focus();await slider.press('ArrowRight');await slider.blur();const updated=await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.landmarks);expect(updated).not.toEqual(before.points);
 await page.getByRole('button',{name:'撤销',exact:true}).click();expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.landmarks)).toEqual(before.points);
 await page.getByRole('button',{name:'重做',exact:true}).click();await page.waitForTimeout(600);await page.reload();await page.waitForFunction(()=>!!(window as any).__editorPerfStore);const saved=await page.evaluate(()=>(window as any).__editorPerfStore.getState().project);expect(saved.landmarks).toEqual(updated);expect(saved.loomisCaps).toHaveLength(2);
 await page.evaluate(id=>(window as any).__editorPerfStore.getState().selectCurve(id),cap.hostSectionCurveId);await page.getByRole('button',{name:'删除封闭面',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__editorPerfStore.getState().project.landmarks.length)).toBe(0);await expect(page.getByTestId('gpu-derived-renderer')).toHaveAttribute('data-surface-count','0');
 await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(page.getByTestId('gpu-derived-renderer')).toHaveAttribute('data-surface-count','2');expect(errors).toEqual([]);
 await page.screenshot({path:'artifacts/section-axes/caps.png'});
});
