import {test,expect} from '@playwright/test';
import {PerspectiveCamera,Vector3} from 'three';
test('3D clicked curve stays highlighted after pointer leave and orbit, clears on point selection',async({page})=>{
 await page.goto('/');await expect(page.getByTestId('point-inspect').locator('canvas')).toHaveAttribute('data-visible-curves',/\d+/);const data=await page.evaluate(async()=>{const {RING_Y}=await import('/src/domain/head/scaffold.ts'),{evaluationContext}=await import('/src/domain/geometry/evaluation.ts'),{useInspectionCamera}=await import('/src/ui/windows/state.ts'),s=(window as any).__editorPerfStore.getState(),r=document.querySelector('[data-testid=point-inspect] canvas')!.getBoundingClientRect();return {id:RING_Y,p:evaluationContext(s.project).curve(RING_Y).evaluate(.23),pose:useInspectionCamera.getState(),r:{x:r.x,y:r.y,width:r.width,height:r.height}};});
 const {pose,r}=data,c=new PerspectiveCamera(pose.fov,r.width/r.height,.1,100);c.position.fromArray(pose.position);c.quaternion.fromArray(pose.quaternion);c.updateMatrixWorld();const q=new Vector3(...data.p).project(c),x=r.x+(q.x+1)*r.width/2,y=r.y+(1-q.y)*r.height/2,canvas=page.getByTestId('point-inspect').locator('canvas');
 await page.mouse.move(x,y);await expect(canvas).toHaveAttribute('data-hover-curve',data.id);await page.mouse.click(x,y);await expect(canvas).toHaveAttribute('data-highlighted-curve',data.id);await page.mouse.move(5,5);await expect(canvas).not.toHaveAttribute('data-hover-curve');await expect(canvas).toHaveAttribute('data-highlighted-curve',data.id);
 await page.mouse.move(r.x+r.width*.5,r.y+r.height*.5);await page.mouse.down();await page.mouse.move(r.x+r.width*.5+40,r.y+r.height*.5+20,{steps:5});await page.mouse.up();await expect(canvas).toHaveAttribute('data-highlighted-curve',data.id);
 await page.evaluate(()=>{const s=(window as any).__editorPerfStore.getState();s.selectLandmark(s.project.landmarks[0].id);});await expect(canvas).toHaveAttribute('data-highlighted-curve','');
});
