import {test,expect,type Page} from '@playwright/test';
const data=(page:Page)=>page.evaluate(()=>(window as any).__editorPerfStore.getState().project.drawing);
const history=(page:Page)=>page.evaluate(()=>(window as any).__editorPerfStore.getState().past.length);
async function select(page:Page,id:string){await page.locator(`[data-testid=drawing-curve-row][data-id="${id}"] .drawing-object-name`).click();}
async function field(page:Page,label:string,value:number){const f=page.getByRole('spinbutton',{name:label,exact:true});await f.fill(String(value));await f.press('Enter');}
async function seed(page:Page,closed=false){return page.evaluate(async closed=>{const m=await import('/src/domain/drawing/model.ts' as string),c=await import('/src/domain/drawing/commands.ts' as string),p=await import('/src/domain/drawing/paintCommands.ts' as string);let d=c.addLayer(m.emptyDrawing(),'Ink');let ids=['a'];if(closed){const e=c.ellipse(d,d.layers[0].id,[-.65,-.55],[.65,.55],.025);ids=e.ids;d=p.createFill(e.document,ids,'black');}else d=c.createCurve(d,d.layers[0].id,[[-.9,0],[-.3,.5],[.3,.5],[.9,0]],.02,'Legacy','a');(window as any).__editorPerfStore.getState().setDrawing(d);return ids;},closed);}
async function saveReload(page:Page){const before=await data(page),download=page.waitForEvent('download');await page.getByRole('button',{name:'Save JSON',exact:true}).click();await page.locator('header input[type=file]').setInputFiles((await (await download).path())!);await expect.poll(()=>data(page)).toEqual(before);}
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('contour.ui-language','en'));await page.goto('/');await page.getByTestId('drawing-room-toggle').click();});

test('hide every ellipse segment and retain fill, while group/layer hiding, Undo and Save/Load remain available',async({page})=>{
 const ids=await seed(page,true),before=await data(page),path=await page.getByTestId('drawing-fill').getAttribute('d');
 for(const id of ids){await page.locator(`[data-testid=drawing-curve-row][data-id="${id}"]`).getByRole('button',{name:/^Hide /}).click();await expect(page.getByTestId('drawing-fill')).toHaveCount(1);}
 await expect(page.getByTestId('drawing-ink')).toHaveCount(0);expect(await page.getByTestId('drawing-fill').getAttribute('d')).toBe(path);expect((await data(page)).fills).toEqual(before.fills);expect((await data(page)).nodes).toEqual(before.nodes);await expect(page.getByTestId('drawing-chain-visibility')).toHaveAttribute('aria-pressed','mixed');const hiddenSegments=await data(page);
 await page.getByTestId('drawing-chain-visibility').click();await expect(page.getByTestId('drawing-fill')).toHaveCount(0);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await data(page)).toEqual(hiddenSegments);await expect(page.getByTestId('drawing-fill')).toHaveCount(1);await saveReload(page);await expect(page.getByTestId('drawing-fill')).toHaveCount(1);await expect(page.getByTestId('drawing-ink')).toHaveCount(0);
 await page.getByRole('button',{name:'Hide Ink',exact:true}).click();await expect(page.getByTestId('drawing-fill')).toHaveCount(0);await page.getByRole('button',{name:'Show Ink',exact:true}).click();await expect(page.getByTestId('drawing-fill')).toHaveCount(1);
});

test('interval endpoints expose independent taper/extension controls, including closed paths, Undo and persistence',async({page})=>{
 const ids=await seed(page,true),before=await data(page);await select(page,ids[0]);await page.getByRole('button',{name:'Add display interval',exact:true}).click();const added=await data(page);await expect(page.getByRole('spinbutton',{name:'Interval taper distance px',exact:true})).toHaveValue('125');
 await field(page,'Interval start %',85);await field(page,'Interval end %',15);await field(page,'Interval taper distance px',18);const historyBefore=await history(page),short=await data(page);await field(page,'Interval extension distance px',9);const extended=await data(page);expect(await history(page)).toBe(historyBefore+1);expect(extended.curves).toEqual(before.curves);expect(extended.nodes).toEqual(before.nodes);expect(extended.fills).toEqual(before.fills);expect(extended.displayIntervals[0].ranges[0].inkEnds[1]).toEqual(added.displayIntervals[0].ranges[0].inkEnds[1]);await expect(page.getByTestId('drawing-fill')).toHaveCount(1);
 await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await data(page)).toEqual(short);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await data(page)).toEqual(extended);
 await page.getByRole('button',{name:'Interval end',exact:true}).click();await field(page,'Interval taper distance px',35);await field(page,'Interval extension distance px',15);const end=await data(page);expect(end.displayIntervals[0].ranges[0].inkEnds).toEqual([{taper:18/250,extension:9/250},{taper:35/250,extension:15/250}]);
 const point=page.locator('[data-testid=drawing-display-grip][data-end="0"]');await point.click();await expect(page.getByRole('spinbutton',{name:'Interval extension distance px',exact:true})).toHaveValue('9');await saveReload(page);await select(page,ids[0]);await page.getByRole('button',{name:'Interval start',exact:true}).click();await page.getByTestId('language-toggle').click();await expect(page.getByText('区间起点笔触',{exact:true})).toBeVisible();await page.screenshot({path:'artifacts/drawing-intervals/endpoint-brush.png'});
});

test('new Pen chains use width-times-20 taper at their outer ends only; old curves retain their original style',async({page})=>{
 await seed(page);const before=await data(page);await page.getByTestId('drawing-tool-pen').click();
 const rect=(await page.getByTestId('drawing-canvas').boundingBox())!,unit=Math.min(rect.width,rect.height)/2.8;
 for(const [x,y] of [[-.85,-.7],[0,-.7],[.85,-.7]])await page.mouse.click(rect.x+rect.width/2+x*unit,rect.y+rect.height/2-y*unit);await page.keyboard.press('Enter');
 const d=await data(page),fresh=d.curves.filter((c:any)=>c.id!=='a');expect(fresh).toHaveLength(2);expect(d.curves[0]).toEqual(before.curves[0]);for(const c of fresh)expect(c.inkEnds).toEqual([{taperWidthScale:20},{taperWidthScale:20}]);await expect(page.getByTestId('drawing-ink')).toHaveCount(2);
 await select(page,fresh[0].id);await page.getByRole('button',{name:'Stroke start',exact:true}).click();await expect(page.getByRole('spinbutton',{name:'Endpoint taper distance px',exact:true})).toHaveValue('40');await field(page,'Stroke width',4);await expect(page.getByRole('spinbutton',{name:'Endpoint taper distance px',exact:true})).toHaveValue('80');
 await saveReload(page);expect((await data(page)).curves.find((c:any)=>c.id==='a')).toEqual(before.curves[0]);await page.getByRole('button',{name:'Hide editing helpers',exact:true}).click();await page.screenshot({path:'artifacts/drawing-intervals/pen-defaults.png'});
});

test('white highlight has no outline with all four sides hidden; interval ink remains independent of fill',async({page})=>{
 await page.evaluate(async()=>{const m=await import('/src/domain/drawing/model.ts' as string),c=await import('/src/domain/drawing/commands.ts' as string),p=await import('/src/domain/drawing/paintCommands.ts' as string),i=await import('/src/domain/drawing/displayIntervals.ts' as string);let d=c.addLayer(m.emptyDrawing(),'Highlight');const outer=c.ellipse(d,d.layers[0].id,[-.6,-.6],[.6,.6],.012);d=p.createFill(outer.document,outer.ids,'black');for(const id of outer.ids)d=c.curveChange(d,id,{visible:false});const inner=c.ellipse(d,d.layers[0].id,[-.35,.04],[-.05,.39],.02);d=p.createFill(inner.document,inner.ids,'white');for(const id of inner.ids)d=c.curveChange(d,id,{visible:false});d=c.createCurve(d,d.layers[0].id,[[-1,.75],[-.5,1],[.5,1],[1,.75]],.025,'Lid','lid');d=i.addDisplayInterval(d,'lid');(window as any).__editorPerfStore.getState().setDrawing(d);});
 await page.getByRole('button',{name:'Hide editing helpers',exact:true}).click();await expect(page.getByTestId('drawing-fill')).toHaveCount(2);await expect(page.getByTestId('drawing-ink')).toHaveCount(1);await page.screenshot({path:'artifacts/drawing-intervals/highlight.png'});
});
