import {test,expect,type Page} from '@playwright/test';
const data=(p:Page)=>p.evaluate(()=>(window as any).__editorPerfStore.getState().project.drawing);
const row=(p:Page,id:string)=>p.locator(`[data-testid=drawing-curve-row][data-id="${id}"] .drawing-object-name`);
async function seed(p:Page){await p.evaluate(async()=>{const c=await import('/src/domain/drawing/commands.ts' as string),m=await import('/src/domain/drawing/model.ts' as string);let d=c.addLayer(m.emptyDrawing(),'Lines');for(const [i,id] of ['top','middle','bottom'].entries())d=c.createCurve(d,d.layers[0].id,[[-.8,.65-i*.6],[-.3,.65-i*.6],[.3,.65-i*.6],[.8,.65-i*.6]],.02,id,id);(window as any).__editorPerfStore.getState().setDrawing(d);});}
async function group(p:Page){await row(p,'top').click();await row(p,'middle').click({modifiers:['Shift']});await p.getByTestId('drawing-group').click();await expect(p.getByTestId('drawing-group-row')).toHaveCount(1);}
async function at(p:Page,x:number,y:number){const b=(await p.getByTestId('drawing-canvas').boundingBox())!,u=Math.min(b.width,b.height)/2.8;return {x:b.x+b.width/2+x*u,y:b.y+b.height/2-y*u};}
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('contour.ui-language','en'));await page.goto('/');await page.getByTestId('drawing-room-toggle').click();await seed(page);});
test('Shift multi-select, group shortcut, rename/fold, Undo/Redo, save/load and ungroup',async({page})=>{
 const before=await data(page);await row(page,'top').click();await row(page,'middle').click({modifiers:['Shift']});await expect(page.getByTestId('drawing-group')).toBeEnabled();await page.keyboard.press('Control+g');await expect(page.getByTestId('drawing-group-row')).toHaveCount(1);const grouped=await data(page);expect(grouped.curves).toEqual(before.curves);expect(grouped.nodes).toEqual(before.nodes);expect(grouped.joins).toEqual(before.joins);
 await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await data(page)).toEqual(before);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await data(page)).toEqual(grouped);
 await page.getByTestId('drawing-group-select').click();await page.getByRole('textbox',{name:'Group name',exact:true}).fill('Eye details');await page.getByRole('textbox',{name:'Group name',exact:true}).press('Enter');await expect(page.getByTestId('drawing-group-select')).toContainText('Eye details');
 await page.getByRole('button',{name:'Collapse Eye details',exact:true}).click();await expect(page.getByTestId('drawing-group-row').getByTestId('drawing-curve-row')).toHaveCount(0);await expect(page.getByTestId('drawing-ink')).toHaveCount(3);
 const saved=await data(page),download=page.waitForEvent('download');await page.getByRole('button',{name:'Save JSON',exact:true}).click();await page.locator('header input[type=file]').setInputFiles((await (await download).path())!);await expect.poll(()=>data(page)).toEqual(saved);
 await page.getByTestId('drawing-group-select').click();await page.keyboard.press('Control+Shift+g');await expect(page.getByTestId('drawing-group-row')).toHaveCount(0);expect((await data(page)).curves).toEqual(before.curves);
});
test('V picks and drags the entire group; Shift toggles units; A edits one member; group lock/hide',async({page})=>{
 await group(page);const original=await data(page);await page.keyboard.press('v');const a=await at(page,.35,.65);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(a.x+24,a.y+12,{steps:4});await page.mouse.up();let moved=await data(page);const originalNode=(id:string)=>original.nodes.find((n:any)=>n.id===original.curves.find((c:any)=>c.id===id).nodes[0]).position,newNode=(id:string)=>moved.nodes.find((n:any)=>n.id===moved.curves.find((c:any)=>c.id===id).nodes[0]).position;
 const dx=newNode('top')[0]-originalNode('top')[0];expect(dx).toBeGreaterThan(.02);expect(newNode('middle')[0]-originalNode('middle')[0]).toBeCloseTo(dx);expect(newNode('bottom')).toEqual(originalNode('bottom'));
 await page.getByTestId('drawing-group-select').click();await row(page,'bottom').click({modifiers:['Shift']});await expect(page.locator('[data-testid=drawing-curve-row].selected')).toHaveCount(3);await page.getByTestId('drawing-group-select').click({modifiers:['ControlOrMeta']});await expect(page.locator('[data-testid=drawing-curve-row].selected')).toHaveCount(1);
 await page.getByTestId('drawing-group-select').click();await page.getByTestId('drawing-group-lock').click();await expect(page.getByRole('spinbutton',{name:'Position X',exact:true})).toBeDisabled();await page.getByTestId('drawing-group-lock').click();await page.getByTestId('drawing-group-visibility').click();await expect(page.getByTestId('drawing-ink')).toHaveCount(1);await page.getByTestId('drawing-group-visibility').click();await expect(page.getByTestId('drawing-ink')).toHaveCount(3);
 await row(page,'top').click();await expect(page.getByRole('textbox',{name:'Curve name',exact:true})).toHaveValue('top');await expect(page.getByTestId('drawing-handle')).toHaveCount(2);await page.getByTestId('drawing-group-select').click();await page.screenshot({path:'artifacts/drawing-room/line-groups.png'});
});
test('group folder drags to another layer with owned fill, duplicate stays grouped',async({page})=>{
 await page.evaluate(async()=>{const c=await import('/src/domain/drawing/commands.ts' as string),p=await import('/src/domain/drawing/paintCommands.ts' as string),store=(window as any).__editorPerfStore;let d=store.getState().project.drawing;const e=c.ellipse(d,d.layers[0].id,[-.4,-.3],[.4,.3],.02);d=p.createFill(e.document,e.ids,'black');d=c.addLayer(d,'Destination');store.getState().setDrawing(d);});
 const chain=page.getByTestId('drawing-chain-select');await chain.click();await row(page,'top').click({modifiers:['ControlOrMeta']});await page.getByTestId('drawing-group').click();const before=await data(page);await page.getByTestId('drawing-group-visibility').click();await expect(page.getByTestId('drawing-fill')).toHaveCount(0);await page.getByTestId('drawing-group-visibility').click();await expect(page.getByTestId('drawing-fill')).toHaveCount(1);
 await page.getByTestId('drawing-group-row').locator(':scope > .drawing-chain-row').dragTo(page.getByTestId('drawing-layer').filter({has:page.locator('.drawing-layer-row .drawing-object-name',{hasText:'Destination'})}).locator('.drawing-layer-row'),{targetPosition:{x:100,y:14}});
 const moved=await data(page);expect(moved.layers[0].items).toContain(moved.fills[0].id);expect(moved.groups).toEqual(before.groups);await page.getByTestId('drawing-group-select').click();await page.keyboard.press('Control+d');await expect(page.getByTestId('drawing-group-row')).toHaveCount(2);await expect(page.getByTestId('drawing-fill')).toHaveCount(2);
});
test('hidden members can be grouped from the list without appearing; Undo/Redo preserves flags',async({page})=>{
 await page.locator('[data-testid=drawing-curve-row][data-id="top"]').getByRole('button',{name:'Hide top',exact:true}).click();await expect(page.getByTestId('drawing-ink')).toHaveCount(2);
 const before=await data(page);await row(page,'top').click();await row(page,'middle').click({modifiers:['Shift']});await expect(page.getByTestId('drawing-group')).toBeEnabled();await page.getByTestId('drawing-group').click();await expect(page.getByTestId('drawing-group-row')).toHaveCount(1);await expect(page.getByTestId('drawing-ink')).toHaveCount(2);
 const grouped=await data(page);expect(grouped.curves).toEqual(before.curves);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await data(page)).toEqual(before);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await data(page)).toEqual(grouped);
 await page.getByTestId('drawing-group-visibility').click();await expect(page.getByTestId('drawing-ink')).toHaveCount(1);await page.getByTestId('drawing-group-visibility').click();await expect(page.getByTestId('drawing-ink')).toHaveCount(3);expect((await data(page)).curves.every((c:any)=>c.visible)).toBe(true);
});
test('drop a collapsed group on layer plus promotes it with fill in one Undo and survives Save/Load',async({page})=>{
 await page.evaluate(async()=>{const c=await import('/src/domain/drawing/commands.ts' as string),p=await import('/src/domain/drawing/paintCommands.ts' as string),store=(window as any).__editorPerfStore;let d=store.getState().project.drawing;const e=c.ellipse(d,d.layers[0].id,[-.4,-.3],[.4,.3],.02);d=p.createFill(e.document,e.ids,'white');d=c.curveChange(d,'top',{visible:false});store.getState().setDrawing(d);});
 await page.getByTestId('drawing-chain-select').click();await row(page,'top').click({modifiers:['ControlOrMeta']});await page.getByTestId('drawing-group').click();const name=page.getByRole('textbox',{name:'Group name',exact:true});await name.fill('Eyelid');await name.press('Enter');await page.getByRole('button',{name:'Collapse Eyelid',exact:true}).click();
 const before=await data(page),history=await page.evaluate(()=>(window as any).__editorPerfStore.getState().past.length),groupRow=page.getByTestId('drawing-group-row').locator(':scope > .drawing-chain-row'),plus=page.getByTestId('drawing-new-layer');
 // Check both drag feedback and the eventual drop with native pointer events.
 const a=(await groupRow.boundingBox())!,b=(await plus.boundingBox())!;await page.mouse.move(a.x+90,a.y+a.height/2);await page.mouse.down();await page.mouse.move(a.x+94,a.y+a.height/2+5,{steps:3});await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:8});await page.mouse.move(b.x+b.width/2+1,b.y+b.height/2);await expect(plus).toHaveClass(/drawing-new-layer-drop/);await page.screenshot({path:'artifacts/drawing-room/group-to-layer-drop.png'});await page.mouse.up();
 await expect(page.getByTestId('drawing-group-row')).toHaveCount(0);const after=await data(page),created=after.layers.find((l:any)=>l.name==='Eyelid');expect(created).toBeTruthy();expect(created.items).toContain(after.fills[0].id);expect(after.layers.find((l:any)=>l.name==='Lines').items).toEqual(['bottom','middle']);expect(after.curves).toEqual(before.curves);expect(after.nodes).toEqual(before.nodes);expect(after.fills).toEqual(before.fills);expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().past.length)).toBe(history+1);await expect(page.getByRole('textbox',{name:'Layer name',exact:true})).toHaveValue('Eyelid');
 await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await data(page)).toEqual(before);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await data(page)).toEqual(after);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Save JSON',exact:true}).click();await page.locator('header input[type=file]').setInputFiles((await (await download).path())!);await expect.poll(()=>data(page)).toEqual(after);
});
test('A canvas editing and list selection edit members without moving the rest of the group',async({page})=>{
 await group(page);const before=await data(page),origin=(d:any,id:string)=>d.nodes.find((n:any)=>n.id===d.curves.find((c:any)=>c.id===id).nodes[0]).position;
 await page.keyboard.press('a');const a=await at(page,.35,.65);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(a.x+20,a.y+10,{steps:4});await page.mouse.up();const moved=await data(page);expect(origin(moved,'top')[0]).toBeGreaterThan(origin(before,'top')[0]+.02);expect(origin(moved,'middle')).toEqual(origin(before,'middle'));expect(moved.groups).toEqual(before.groups);
 const handle=page.locator('[data-testid=drawing-handle][data-id="top"][data-end="0"]'),h=(await handle.boundingBox())!;await page.mouse.move(h.x+h.width/2,h.y+h.height/2);await page.mouse.down();await page.mouse.move(h.x+h.width/2+15,h.y+h.height/2-14,{steps:4});await page.mouse.up();let edited=await data(page);expect(edited.curves.find((c:any)=>c.id==='top').handles).not.toEqual(moved.curves.find((c:any)=>c.id==='top').handles);expect(edited.curves.find((c:any)=>c.id==='middle')).toEqual(moved.curves.find((c:any)=>c.id==='middle'));
 await row(page,'middle').click();const width=page.getByRole('spinbutton',{name:'Stroke width',exact:true});await width.fill('8');await width.press('Enter');edited=await data(page);expect(edited.curves.find((c:any)=>c.id==='middle').width).toBe(.032);expect(edited.curves.find((c:any)=>c.id==='top').width).toBe(.02);expect(edited.groups).toEqual(before.groups);await expect(page.getByTestId('drawing-group-row')).toHaveCount(1);
});
test('properties conversion preserves hidden group visibility; clicking layer plus still creates an empty layer',async({page})=>{
 await group(page);await page.getByTestId('drawing-group-visibility').click();const before=await data(page);await page.getByTestId('drawing-group-to-layer').click();const after=await data(page);expect(after.layers[0].name).toBe(before.groups[0].name);expect(after.curves.filter((c:any)=>after.layers[0].items.includes(c.id)).every((c:any)=>!c.visible)).toBe(true);expect(after.curves).toEqual(before.curves);await expect(page.getByTestId('drawing-ink')).toHaveCount(1);
 await page.getByTestId('drawing-new-layer').click();expect((await data(page)).layers[0].items).toEqual([]);expect((await data(page)).layers).toHaveLength(3);
});

for(const kind of ['group','layer'] as const)test(`${kind} actions are one-shot: a child can show/unlock and edit, with mixed states and Undo/Save`,async({page})=>{
 await group(page);const original=await data(page),visibility=page.getByTestId(`drawing-${kind}-visibility`),lock=page.getByTestId(`drawing-${kind}-lock`);
 await visibility.click();await expect(page.getByTestId('drawing-ink')).toHaveCount(kind==='group'?1:0);
 const hidden=await data(page),top=page.locator('[data-testid=drawing-curve-row][data-id="top"]');
 await top.getByRole('button',{name:'Show top',exact:true}).click();await expect(page.getByTestId('drawing-ink')).toHaveCount(kind==='group'?2:1);await expect(visibility).toHaveAttribute('aria-pressed','mixed');
 expect((await data(page)).curves.find((c:any)=>c.id==='middle').visible).toBe(false);
 await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await data(page)).toEqual(hidden);await page.getByRole('button',{name:'Redo',exact:true}).click();
 await lock.click();await top.getByRole('button',{name:'Unlock top',exact:true}).click();await expect(lock).toHaveAttribute('aria-pressed','mixed');
 await row(page,'top').click();await expect(page.getByRole('spinbutton',{name:'Position X',exact:true})).toBeEnabled();
 const handle=page.locator('[data-testid=drawing-handle][data-id="top"][data-end="0"]'),b=(await handle.boundingBox())!;
 await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+25,b.y+b.height/2-15,{steps:4});await page.mouse.up();
 const edited=await data(page);expect(edited.curves.find((c:any)=>c.id==='top').handles).not.toEqual(original.curves.find((c:any)=>c.id==='top').handles);expect(edited.curves.find((c:any)=>c.id==='middle')).toMatchObject({visible:false,locked:true});
 await page.getByRole('button',{name:'Undo',exact:true}).click();expect((await data(page)).curves.find((c:any)=>c.id==='top').handles).toEqual(original.curves.find((c:any)=>c.id==='top').handles);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await data(page)).toEqual(edited);
 const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Save JSON',exact:true}).click();await page.locator('header input[type=file]').setInputFiles((await (await dl).path())!);await expect.poll(()=>data(page)).toEqual(edited);await expect(visibility).toHaveAttribute('aria-pressed','mixed');await expect(lock).toHaveAttribute('aria-pressed','mixed');
 await page.screenshot({path:`artifacts/drawing-room/${kind}-member-overrides.png`});
});

test('a fill can show by itself after hiding and locking its layer, group and entire stroke',async({page})=>{
 await page.evaluate(async()=>{const c=await import('/src/domain/drawing/commands.ts' as string),p=await import('/src/domain/drawing/paintCommands.ts' as string),store=(window as any).__editorPerfStore;const d=store.getState().project.drawing,e=c.ellipse(d,d.layers[0].id,[-.4,-.3],[.4,.3],.02);store.getState().setDrawing(p.createFill(e.document,e.ids,'white'));});
 await page.getByTestId('drawing-chain-select').click();await row(page,'top').click({modifiers:['ControlOrMeta']});await page.getByTestId('drawing-group').click();
 for(const kind of ['layer','group','chain']){
  await page.getByTestId(`drawing-${kind}-visibility`).click();await expect(page.getByTestId('drawing-fill')).toHaveCount(0);
  const fill=page.getByTestId('drawing-paint-row');await fill.getByRole('button',{name:/^Show /}).click();await expect(page.getByTestId('drawing-fill')).toHaveCount(1);
  await page.getByTestId(`drawing-${kind}-lock`).click();await fill.getByRole('button',{name:/^Unlock /}).click();await fill.locator('.drawing-object-name').click();const color=page.getByRole('combobox',{name:'Fill color',exact:true});await expect(color).toBeEnabled();await color.selectOption('black');
  expect((await data(page)).fills[0]).toMatchObject({visible:true,locked:false,color:'black'});await expect(page.getByTestId(`drawing-${kind}-visibility`)).toHaveAttribute('aria-pressed','mixed');await expect(page.getByTestId(`drawing-${kind}-lock`)).toHaveAttribute('aria-pressed','mixed');
 }
 await expect(page.getByTestId('drawing-ink')).toHaveCount(0);await expect(page.getByTestId('drawing-fill')).toHaveCount(1);
});
