import {test,expect,type Page} from '@playwright/test';
import {drawingTool} from '../helpers/drawingTool';
const data=(page:Page)=>page.evaluate(()=>(window as any).__editorPerfStore.getState().project.drawing);
const history=(page:Page)=>page.evaluate(()=>(window as any).__editorPerfStore.getState().past.length);
async function seed(page:Page){await page.evaluate(async()=>{const m=await import('/src/domain/drawing/model.ts' as string),c=await import('/src/domain/drawing/commands.ts' as string);let d=c.addLayer(m.emptyDrawing(),'First');d=c.createCurve(d,d.layers[0].id,[[-.9,0],[-.6,.2],[-.3,.2],[0,0]],.014,'A','a');d=c.addLayer(d,'Second');d=c.createCurve(d,d.layers[0].id,[[.3,.25],[.5,.5],[.8,.5],[1,.25]],.04,'B','b');(window as any).__editorPerfStore.getState().setDrawing(d);});}
async function coord(page:Page,x:number,y:number){const r=(await page.getByTestId('drawing-canvas').boundingBox())!,u=Math.min(r.width,r.height)/2.8;return {x:r.x+r.width/2+x*u,y:r.y+r.height/2-y*u};}
async function click(page:Page,x:number,y:number){const p=await coord(page,x,y);await page.mouse.click(p.x,p.y);}
async function layer(page:Page,name:string){await page.locator('.drawing-layer-row').getByRole('button',{name,exact:true}).click();}
async function link(page:Page){await layer(page,'First');await drawingTool(page,'link');await click(page,0,0);await layer(page,'Second');await click(page,.3,.25);}
function position(d:any,id:string,end:number){const c=d.curves.find((c:any)=>c.id===id);return d.nodes.find((n:any)=>n.id===c.nodes[end]).position;}
async function selectNode(page:Page,id:string,end:number){await page.locator(`[data-testid=drawing-curve-row][data-id="${id}"] .drawing-object-name`).click();await page.getByRole('button',{name:`P${end} Endpoint`,exact:true}).click();}
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('contour.ui-language','en'));await page.goto('/');await page.getByTestId('drawing-room-toggle').click();await seed(page);});

test('one toolbar slot: right click, press-and-hold, remembered selection, keyboard and top descriptions',async({page})=>{
 const group=page.locator('[data-tool-group=connections]');await expect(group).toHaveCount(1);await expect(page.getByTestId('drawing-tool-smooth')).toHaveCount(0);await group.hover();await expect(page.getByTestId('drawing-connection-menu')).toHaveCount(0);
 await group.click({button:'right'});await expect(page.getByRole('menuitemradio')).toHaveCount(5);await page.getByTestId('drawing-tool-choice-link').click();await expect(group).toHaveAttribute('data-testid','drawing-tool-link');await expect(page.getByTestId('drawing-tool-description')).toContainText('keep strokes, widths and layers separate');
 await drawingTool(page,'select');await group.click();await expect(group).toHaveAttribute('aria-pressed','true');
 const r=(await group.boundingBox())!;await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await expect(page.getByTestId('drawing-connection-menu')).toBeVisible();await page.mouse.up();await page.getByTestId('drawing-tool-choice-arc').click();await expect(page.getByTestId('drawing-tool-description')).toContainText('rounded transition');
 await selectNode(page,'a',1);const beforeMenu=await data(page),menuHistory=await history(page);await group.focus();await page.keyboard.press('ArrowDown');await expect(page.getByRole('menuitemradio').first()).toBeFocused();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await expect(group).toHaveAttribute('data-testid','drawing-tool-bind');await expect(page.getByTestId('drawing-connection-menu')).toHaveCount(0);expect(await data(page)).toEqual(beforeMenu);expect(await history(page)).toBe(menuHistory);
 await page.getByTestId('language-toggle').click();await group.click({button:'right'});await expect(page.getByRole('menuitemradio',{name:/端点联动/})).toBeVisible();await page.screenshot({path:'artifacts/drawing-links/tool-group.png'});await page.keyboard.press('Escape');await expect(page.getByTestId('drawing-connection-menu')).toHaveCount(0);
});

test('link preview and commit across layers keep strokes, widths, nodes, layers and ordering independent',async({page})=>{
 const before=await data(page),h=await history(page);await layer(page,'First');await drawingTool(page,'link');await click(page,0,0);await layer(page,'Second');const target=await coord(page,.3,.25);await page.mouse.move(target.x,target.y);await expect(page.getByTestId('drawing-endpoint-link-guides')).toBeVisible();expect(await data(page)).toEqual(before);expect(await history(page)).toBe(h);await page.mouse.click(target.x,target.y);const after=await data(page);
 expect(after.endpointLinks).toHaveLength(1);expect(after.layers).toEqual(before.layers);expect(after.curves.map((c:any)=>[c.id,c.nodes,c.width,c.name])).toEqual(before.curves.map((c:any)=>[c.id,c.nodes,c.width,c.name]));expect(after.joins).toEqual(before.joins);expect(position(after,'a',1)).toEqual(position(after,'b',0));expect(after.nodes).toHaveLength(before.nodes.length);expect(await history(page)).toBe(h+1);await expect(page.getByTestId('drawing-ink')).toHaveCount(2);
 await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await data(page)).toEqual(before);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await data(page)).toEqual(after);
 await drawingTool(page,'select');await click(page,-.45,.15);await expect(page.getByTestId('drawing-selected')).toHaveCount(1);await selectNode(page,'a',1);await expect(page.getByRole('button',{name:'Unlink endpoints',exact:true})).toBeVisible();
 const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Save JSON',exact:true}).click();await page.locator('header input[type=file]').setInputFiles((await (await dl).path())!);await expect.poll(()=>data(page)).toEqual(after);
});

test('both ends drag and nudge together without self-snapping; unlink retains positions',async({page})=>{
 await link(page);await selectNode(page,'b',0);let before=await data(page),p=await coord(page,...position(before,'b',0) as [number,number]);
 // Three CSS px is within normal snap tolerance. The linked partner must not pin this drag.
 await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+3,p.y+3,{steps:3});await page.mouse.up();let after=await data(page);expect(position(after,'b',0)).not.toEqual(position(before,'b',0));expect(position(after,'a',1)).toEqual(position(after,'b',0));
 await selectNode(page,'a',1);before=await data(page);p=await coord(page,...position(before,'a',1) as [number,number]);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x-35,p.y-30,{steps:6});await page.mouse.up();after=await data(page);expect(position(after,'a',1)).toEqual(position(after,'b',0));expect(position(after,'b',1)).toEqual(position(before,'b',1));expect(after.layers).toEqual(before.layers);
 await page.getByTestId('drawing-canvas').focus();await page.keyboard.press('ArrowRight');after=await data(page);expect(position(after,'a',1)).toEqual(position(after,'b',0));expect(position(after,'a',1)[0]).toBeCloseTo(position(before,'a',1)[0]-35/(Math.min((await page.getByTestId('drawing-canvas').boundingBox())!.width,(await page.getByTestId('drawing-canvas').boundingBox())!.height)/2.8)+.004,5);
 await page.getByRole('button',{name:'Unlink endpoints',exact:true}).click();const unlinked=await data(page);expect(unlinked.endpointLinks).toEqual([]);expect(unlinked.nodes).toEqual(after.nodes);expect(unlinked.curves).toEqual(after.curves);await page.getByTestId('drawing-canvas').focus();await page.keyboard.press('ArrowRight');expect(position(await data(page),'b',0)).toEqual(position(unlinked,'b',0));expect(position(await data(page),'a',1)).not.toEqual(position(unlinked,'a',1));
});

test('linked partner locks reject the whole move, while layer reassignment does not absorb it',async({page})=>{
 await link(page);await selectNode(page,'a',1);await page.evaluate(async()=>{const c=await import('/src/domain/drawing/commands.ts' as string),s=(window as any).__editorPerfStore.getState(),d=s.project.drawing;s.setDrawing(c.curveChange(d,'b',{locked:true}));});const before=await data(page);await page.getByTestId('drawing-canvas').focus();await page.keyboard.press('ArrowRight');expect(await data(page)).toEqual(before);await expect(page.getByRole('status')).toContainText('locked');
 await page.evaluate(async()=>{const c=await import('/src/domain/drawing/commands.ts' as string),s=(window as any).__editorPerfStore.getState();let d=c.curveChange(s.project.drawing,'b',{locked:false});d=c.addLayer(d,'Third');s.setDrawing(d);});await selectNode(page,'a',1);await page.getByRole('combobox',{name:'Move to layer',exact:true}).selectOption({label:'Third'});const after=await data(page);expect(after.layers[0].items).toEqual(['a']);expect(after.endpointLinks).toEqual(before.endpointLinks);await expect(page.getByTestId('drawing-ink')).toHaveCount(2);
});
