import {test,expect,type Page} from '@playwright/test';
const data=(page:Page)=>page.evaluate(()=>(window as any).__editorPerfStore.getState().project.drawing);
const history=(page:Page)=>page.evaluate(()=>(window as any).__editorPerfStore.getState().past.length);
const row=(page:Page,id:string)=>page.locator(`[data-testid=drawing-curve-row][data-id="${id}"] .drawing-object-name`);
const layer=(page:Page,id:string)=>page.locator(`[data-testid=drawing-layer][data-id="${id}"]>.drawing-layer-row .drawing-object-name`);
async function seed(page:Page){return page.evaluate(async()=>{
 const m=await import('/src/domain/drawing/model.ts' as string),c=await import('/src/domain/drawing/commands.ts' as string),p=await import('/src/domain/drawing/paintCommands.ts' as string),g=await import('/src/domain/drawing/groups.ts' as string),i=await import('/src/domain/drawing/displayIntervals.ts' as string);
 let d=c.addLayer(m.emptyDrawing(),'Source');const source=d.layers[0].id,e=c.ellipse(d,source,[-.6,-.4],[.6,.4],.02);d=p.createFill(e.document,e.ids,'white');d=c.createPenCurve(d,source,[[-.8,.6],[-.3,.8],[.3,.8],[.8,.6]],.02,'line',7);d=i.addDisplayInterval(d,'line');d=c.curveChange(d,'line',{visible:false});d=g.createGroup(d,[e.ids[0],'line'],'Eye');const group=d.groups[0].id;d=c.addLayer(d,'Target');const target=d.layers[0].id;d=c.createCurve(d,target,[[-.8,-.6],[-.3,-.8],[.3,-.8],[.8,-.6]],.01,'Existing','other');(window as any).__editorPerfStore.getState().setDrawing(d);return {source,target,group,ids:e.ids};
 });}
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('contour.ui-language','en'));await page.goto('/');await page.getByTestId('drawing-room-toggle').click();});
test('Ctrl X / Ctrl V moves a hidden-containing group and fill in place, preserving geometry, Undo/Redo and Save/Load',async({page})=>{
 const f=await seed(page),before=await data(page),h=await history(page);await page.getByTestId('drawing-group-select').click();await page.keyboard.press('Control+x');const cut=await data(page);expect(cut.curves.map((c:any)=>c.id)).toEqual(['other']);expect(await history(page)).toBe(h+1);await expect(page.locator('.drawing-status [role=status]')).toContainText('Cut complete');
 await layer(page,f.target).click();await page.keyboard.press('Control+v');const pasted=await data(page);expect(await history(page)).toBe(h+2);expect(pasted.layers.find((l:any)=>l.id===f.target).items).toEqual([...before.layers.find((l:any)=>l.id===f.source).items,'other']);expect(pasted.layers.find((l:any)=>l.id===f.source).items).toEqual([]);expect(pasted.groups).toEqual(before.groups);expect(pasted.fills).toEqual(before.fills);expect(pasted.displayIntervals).toEqual(before.displayIntervals);for(const c of before.curves)expect(pasted.curves.find((x:any)=>x.id===c.id)).toEqual(c);
 await expect(page.locator(`[data-testid=drawing-layer][data-id="${f.target}"] [data-testid=drawing-group-row]`)).toHaveCount(1);
 await page.keyboard.press('Control+z');expect(await data(page)).toEqual(cut);await page.keyboard.press('Control+z');expect(await data(page)).toEqual(before);await page.keyboard.press('Control+Shift+z');await page.keyboard.press('Control+Shift+z');expect(await data(page)).toEqual(pasted);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Save JSON',exact:true}).click();await page.locator('header input[type=file]').setInputFiles((await (await download).path())!);await expect.poll(()=>data(page)).toEqual(pasted);
});
test('Cmd shortcuts, Shift multi-selection, repeated Paste and footer buttons support layer transfers',async({page})=>{
 const f=await seed(page);await page.evaluate(async()=>{const c=await import('/src/domain/drawing/commands.ts' as string);let d=(window as any).__editorPerfStore.getState().project.drawing;for(let j=0;j<3;j++)d=c.createCurve(d,d.layers[0].id,[[j*.2,0],[j*.2+.05,0],[j*.2+.1,0],[j*.2+.15,0]],.01,'Extra '+j,'extra'+j);(window as any).__editorPerfStore.getState().setDrawing(d);});
 await row(page,'extra2').click();await row(page,'extra0').click({modifiers:['Shift']});await page.keyboard.press('Meta+x');expect((await data(page)).curves.some((c:any)=>c.id.startsWith('extra'))).toBe(false);await layer(page,f.source).click();await page.keyboard.press('Meta+v');let d=await data(page);expect(d.layers.find((l:any)=>l.id===f.source).items.slice(0,3)).toEqual(['extra2','extra1','extra0']);const count=d.curves.length;
 await layer(page,f.target).click();await page.keyboard.press('Meta+v');d=await data(page);expect(d.curves).toHaveLength(count);expect(d.layers.find((l:any)=>l.id===f.target).items.slice(0,3)).toEqual(['extra2','extra1','extra0']);
 await row(page,'extra1').click();await page.getByTestId('drawing-cut-selection').click();await layer(page,f.source).click();await page.getByTestId('drawing-paste-selection').click();expect((await data(page)).layers.find((l:any)=>l.id===f.source).items[0]).toBe('extra1');
});
test('locked cuts reject without losing the existing clipboard; text inputs keep native editing shortcuts',async({page})=>{
 const f=await seed(page);await row(page,'other').click();await page.keyboard.press('Control+x');const cut=await data(page);await row(page,f.ids[0]).click();await page.locator(`[data-testid=drawing-curve-row][data-id="${f.ids[0]}"]`).getByRole('button',{name:/^Lock /}).click();const locked=await data(page);await page.keyboard.press('Control+x');expect(await data(page)).toEqual(locked);await expect(page.locator('.drawing-status [role=status]')).toContainText('locked');
 await layer(page,f.source).click();await page.keyboard.press('Control+v');expect((await data(page)).layers.find((l:any)=>l.id===f.source).items[0]).toBe('other');await row(page,'other').click();const name=page.getByRole('textbox',{name:'Curve name',exact:true});await name.focus();await name.selectText();const beforeText=await data(page);await name.press('Control+x');expect(await data(page)).toEqual(beforeText);await name.press('Escape');expect((await data(page)).curves).toHaveLength(cut.curves.length+1);
});
