import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {addPatch} from '../../src/domain/patches/model';
import {parseLandmarks} from '../../src/domain/landmarks/persistence';
const base=parseLandmarks(readFileSync('artifacts/basic-patch/adjusted-source.json','utf8'));
const names=['左面壳前边界·额颞至颧颊','左斜面带横向桥·额颞层','左面壳后边界·颞侧至颧弓','左斜面带横向桥·颧颊层'];
const project=addPatch(base,names.map(n=>base.curves.find(c=>c.name===n)!.id));
test('fullness gestures, mirror editing, reset, history, persistence and final rendering',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await page.locator('input[type=file][accept=".json,application/json"]').setInputFiles({name:'fullness.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});
 await page.getByRole('combobox',{name:'Patch 显示精度',exact:true}).selectOption('low');
 await page.getByTestId('patch-row-'+project.patches![0].id).getByRole('button').first().click();
 const slider=page.getByRole('slider',{name:'面凸度 Fullness',exact:true});
 await expect(slider).toHaveValue('0');
 const canvas=page.getByTestId('point-inspect').locator('canvas'),before=await canvas.screenshot();
 const paths=()=>page.getByTestId('patch-layer').first().locator('path[fill-opacity]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('d')));
 const beforePaths=await paths();
 const rect=await slider.boundingBox();if(!rect)throw Error('slider');
 await page.mouse.move(rect.x+rect.width*.5,rect.y+rect.height/2);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.9,rect.y+rect.height/2,{steps:5});await page.mouse.up();
 const value=await slider.inputValue();expect(+value).toBeGreaterThan(50);
 await expect(page.locator('.point-footer')).toContainText('撤销 2 / 100');
 expect(await paths()).not.toEqual(beforePaths);expect((await canvas.screenshot({path:'test-results/fullness-3d.png'})).equals(before)).toBeFalsy();
 await page.getByRole('slider',{name:'2D Patch 不透明度',exact:true}).fill('50');
 await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(slider).toHaveValue('0');
 await expect(page.getByRole('slider',{name:'2D Patch 不透明度',exact:true})).toHaveValue('50');
 await page.getByRole('button',{name:'重做',exact:true}).click();await expect(slider).toHaveValue(value);
 await page.getByTestId('patch-row-'+project.patches![1].id).getByRole('button').first().click();await expect(slider).toHaveValue(value);
 await page.getByRole('button',{name:'凸度归零',exact:true}).click();await expect(slider).toHaveValue('0');
 await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(slider).toHaveValue(value);
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('contour.landmarks.v039')!));
 expect(saved.landmarks).toEqual(project.landmarks);expect(saved.curves).toEqual(project.curves);
 expect(saved.patches[0].fullness).toBeCloseTo(+value/100);expect(saved.patches[1].fullness).toBeUndefined();
 await page.reload();await page.getByTestId('patch-row-'+project.patches![0].id).getByRole('button').first().click();await expect(slider).toHaveValue(value);
 await page.getByRole('checkbox',{name:'显示 Patch',exact:true}).uncheck();
 await slider.focus();await page.keyboard.press('ArrowLeft');await expect.poll(async()=>+(await slider.inputValue())).toBeCloseTo(+value-.5,10);
 await page.getByRole('checkbox',{name:'显示 Patch',exact:true}).check();
 await expect(page.getByTestId('patch-layer').first().locator('path[fill-opacity]')).toHaveCount(144);
 await page.screenshot({path:'test-results/fullness-ui.png'});
 expect(errors).toEqual([]);
});
