import {test,expect} from '@playwright/test';
test('Gaze Eyeball creation, shared parameters, history, picking, contour and persistence',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>localStorage.setItem('contour.ui-language','en'));await page.goto('/');
 await page.getByTestId('geometry-modules').getByRole('button',{name:'Eyes',exact:true}).click();await page.getByRole('button',{name:'Create Default Eye Scaffold',exact:true}).click();
 const before=await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.patches);
 await page.getByRole('button',{name:'Add Gaze Eyeball',exact:true}).click();await expect(page.getByRole('slider',{name:'Iris Scale',exact:true})).toBeVisible();
 const canvas=page.getByTestId('point-inspect').locator('canvas');await expect(canvas).toHaveAttribute('data-iris-count','2');
 const g=await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.gazeEyeball);expect(g.irisScale).toBe(.3);
 await page.getByRole('button',{name:'Left Gaze Eyeball',exact:true}).click();const slider=page.getByRole('slider',{name:'Iris Scale',exact:true});await slider.locator('..').locator('.numeric-slider-value').dblclick();const entry=slider.locator('..').locator('.numeric-slider-entry');await entry.fill('0.6');await entry.press('Enter');expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.gazeEyeball.irisScale)).toBe(.6);
 await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.gazeEyeball.irisScale)).toBe(.3);await page.getByRole('button',{name:'Redo',exact:true}).click();
 const hit=await page.evaluate(async()=>{const geometry='/src/domain/eyes/gaze.ts',cameraPath='/src/ui/windows/state.ts',three='/node_modules/.vite/deps/three.js',T=await import(three),pose=(await import(cameraPath)).useInspectionCamera.getState(),store=(window as any).__editorPerfStore;store.getState().selectObject(null);const p=store.getState().project,m=(await import(geometry)).irisGeometry(p,'right',new T.Vector3(0,0,1).applyQuaternion(new T.Quaternion(...pose.quaternion)).toArray()),rect=document.querySelector('[data-testid="point-inspect"] canvas')!.getBoundingClientRect(),camera=new T.PerspectiveCamera(pose.fov,rect.width/rect.height,.1,100);camera.position.fromArray(pose.position);camera.quaternion.fromArray(pose.quaternion);camera.updateMatrixWorld();const q=new T.Vector3(...m.evaluate(.8,2.2)).project(camera);return {x:rect.left+(q.x+1)*rect.width/2,y:rect.top+(1-q.y)*rect.height/2};});
 for(let i=0;i<5;i++){await page.mouse.click(hit.x,hit.y);if(await page.getByRole('button',{name:'Right Gaze Eyeball',exact:true}).getAttribute('aria-pressed')==='true')break;}await expect(page.getByRole('button',{name:'Right Gaze Eyeball',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.evaluate(async()=>{const url='/src/ui/windows/state.ts',m=await import(url);m.useWindows.setState(s=>({visible:{...s.visible,contour:true}}));});
 const contour=page.getByTestId('contour-preview');await expect(contour).toHaveAttribute('aria-busy','false',{timeout:20000});expect(await page.locator('[data-contour-open]').count()).toBeGreaterThanOrEqual(2);
 await page.screenshot({path:'artifacts/eyes/gaze-eyeball.png'});
 await page.evaluate(async()=>{const url='/src/ui/windows/state.ts',m=await import(url);m.useInspectionCamera.setState({contourPerspective:true});});await expect(contour).toHaveAttribute('aria-busy','false',{timeout:20000});expect(await page.locator('[data-contour-open]').count()).toBeGreaterThanOrEqual(2);
 await page.evaluate(async()=>{const url='/src/ui/windows/state.ts',m=await import(url);m.useInspectionCamera.setState({contourPerspective:false});});
 for(const yaw of [90,180]){await page.evaluate(async yaw=>{const url='/src/ui/windows/state.ts',m=await import(url),h=yaw*Math.PI/360;m.useInspectionCamera.setState({quaternion:[0,Math.sin(h),0,Math.cos(h)]});},yaw);await expect(contour).toHaveAttribute('aria-busy','false',{timeout:20000});expect(await page.locator('[data-contour-open]').count()).toBeGreaterThanOrEqual(2);}
 const saved=await page.evaluate(async()=>{const store=(window as any).__editorPerfStore,url='/src/domain/landmarks/persistence.ts',p=store.getState().project;store.getState().load((await import(url)).parseLandmarks(JSON.stringify(p)));return store.getState().project;});expect(saved.gazeEyeball).toEqual({...g,irisScale:.6});expect(saved.patches).toEqual(before);
 await page.getByTestId('geometry-modules').getByRole('button',{name:'HeadSet',exact:true}).click();await page.evaluate(()=>(window as any).__editorPerfStore.getState().setGazeParameter('irisScale',.8));expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.gazeEyeball.irisScale)).toBe(.6);expect(errors).toEqual([]);
});
test('tracking is per-view, camera-only is not an edit, OFF and Undo restore default',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('contour.ui-language','en'));await page.goto('/');await page.getByTestId('geometry-modules').getByRole('button',{name:'Eyes',exact:true}).click();await page.getByRole('button',{name:'Create Default Eye Scaffold',exact:true}).click();await page.getByRole('button',{name:'Add Gaze Eyeball',exact:true}).click();
 const toggle=page.getByRole('checkbox',{name:'Gaze Tracking',exact:true});await expect(toggle).not.toBeChecked();await toggle.check();
 const rim=page.locator('[data-gaze-rim]').first();const initial=await rim.getAttribute('d');
 const before=await page.evaluate(()=>{const s=(window as any).__editorPerfStore.getState();return {project:JSON.stringify(s.project),past:s.past.length};});
 const canvas=page.getByTestId('point-inspect').locator('canvas'),oldFacing=await canvas.getAttribute('data-gaze-facing'),box=(await canvas.boundingBox())!;
 await page.mouse.move(box.x+box.width*.8,box.y+box.height*.8);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.65,{steps:12});await page.mouse.up();await expect(canvas).not.toHaveAttribute('data-gaze-facing',oldFacing!);
 expect(await rim.getAttribute('d')).toBe(initial);const after=await page.evaluate(()=>{const s=(window as any).__editorPerfStore.getState();return {project:JSON.stringify(s.project),past:s.past.length};});expect(after).toEqual(before);
 await page.getByRole('button',{name:'Left 45°',exact:true}).click();await expect(rim).not.toHaveAttribute('d',initial!);
 await toggle.uncheck();await expect(toggle).not.toBeChecked();const off=await rim.getAttribute('d');await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Right Gaze Eyeball',exact:true}).click();await expect(toggle).toBeChecked();await expect(rim).not.toHaveAttribute('d',off!);
 await page.screenshot({path:'artifacts/eyes/gaze-tracking.png'});
});
