import {test,expect} from '@playwright/test';
test('3D background: six uploads, thumbnail switch, hide, delete, reload',async({page})=>{
 await page.goto('/');await page.evaluate(()=>(window as any).__editorPerfStore.getState().setInspectionBackground({images:[],activeId:null}));
 const tools=page.getByRole('complementary',{name:'3D 背景图'}),data=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j/pkAAAAASUVORK5CYII=','base64');
 await tools.locator('input[type=file]').setInputFiles(Array.from({length:6},(_,i)=>({name:`bg${i}.png`,mimeType:'image/png',buffer:data})));
 await expect(tools.getByRole('button',{name:'＋背景 6/6'})).toBeDisabled();await tools.getByRole('button',{name:'切换背景 1',exact:true}).click();await expect(tools.getByRole('button',{name:'切换背景 1',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByAltText('3D 背景',{exact:true})).toBeVisible();
 await tools.getByRole('button',{name:'背景设置',exact:true}).click();await page.getByRole('slider',{name:'背景旋转',exact:true}).press('End');await page.getByRole('slider',{name:'背景缩放',exact:true}).press('End');await expect(page.getByAltText('3D 背景',{exact:true})).toHaveCSS('transform','matrix(-5, 0, 0, -5, 0, 0)');await tools.getByRole('button',{name:'切换背景 2',exact:true}).click();await expect(page.getByRole('slider',{name:'背景旋转',exact:true})).toHaveValue('0');await tools.getByRole('button',{name:'切换背景 1',exact:true}).click();await expect(page.getByRole('slider',{name:'背景旋转',exact:true})).toHaveValue('180');
 await tools.getByRole('button',{name:'无背景',exact:true}).click();await expect(page.getByAltText('3D 背景',{exact:true})).toHaveCount(0);await tools.getByRole('button',{name:'切换背景 2',exact:true}).click();await page.waitForTimeout(700);await page.reload();await expect(page.getByAltText('3D 背景',{exact:true})).toBeVisible();await expect(tools.getByRole('button',{name:'切换背景 2',exact:true})).toHaveAttribute('aria-pressed','true');expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.inspectionBackground.images[0].rotation)).toBe(180);await tools.getByRole('button',{name:'删除背景 2',exact:true}).click();await expect(tools.getByRole('button',{name:'＋背景 5/6'})).toBeEnabled();
});
