import {test,expect} from '@playwright/test';
test('default scaffold, user duplicates, Helmet + Apex update, membership and reload',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.evaluate(()=>(window as any).__editorPerfStore.getState().reset());
 if(await page.getByText('Loomis Set',{exact:true}).getAttribute('aria-expanded')==='false')await page.getByText('Loomis Set',{exact:true}).click();await expect(page.getByText('LOOMIS DEFAULT',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'+ 侧面剖面对',exact:true})).toHaveCount(0);
 const info=await page.evaluate(()=>{const s=(window as any).__editorPerfStore.getState();return {points:s.project.landmarks.length,curves:s.project.curves.length,helmet:s.project.loomisScaffold,side:s.project.curves.find((c:any)=>c.systemRole==='SIDE_R').id,middle:s.project.curves.find((c:any)=>c.systemRole==='MAIN_Y').id};});expect(info.points).toBe(16);expect(info.curves).toBe(7);expect(info.helmet.visible).toBe(true);
 await expect(page.getByTestId('gpu-derived-renderer')).toHaveAttribute('data-surface-count','1');await page.evaluate(id=>(window as any).__editorPerfStore.getState().selectCurve(id),info.side);
 const slider=page.getByRole('slider',{name:'Side Ring Position',exact:true});await slider.focus();await slider.press('ArrowLeft');await slider.blur();const changed=await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.loomisScaffold.sidePosition);expect(changed).toBeLessThan(.75);
 await page.getByRole('button',{name:'撤销',exact:true}).click();expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.loomisScaffold.sidePosition)).toBe(.75);
 await page.evaluate(id=>(window as any).__editorPerfStore.getState().selectCurve(id),info.middle);await page.getByRole('button',{name:'复制 Ring',exact:true}).click();await expect(page.getByRole('slider',{name:'Ring Offset',exact:true})).toBeVisible();await expect(page.getByRole('slider',{name:'Section Tilt X',exact:true})).toHaveCount(0);await page.getByRole('slider',{name:'Ring Offset',exact:true}).press('ArrowRight');await page.keyboard.press('Tab');
 expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.curves.length)).toBe(8);await page.evaluate(()=>{const s=(window as any).__editorPerfStore.getState();s.deleteCurve(s.selectedCurveId);});expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.curves.length)).toBe(7);
 await page.getByRole('button',{name:'Default Helmet 系统',exact:true}).click();await page.getByText('Advanced',{exact:true}).click();await page.getByRole('slider',{name:'Side Shell Roundness',exact:true}).press('ArrowLeft');expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.loomisScaffold.roundness)).toBeLessThan(.5);
 await page.waitForTimeout(700);const saved=await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.loomisScaffold);await page.reload();await page.waitForFunction(()=>!!(window as any).__editorPerfStore);expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.loomisScaffold)).toEqual(saved);expect(errors).toEqual([]);await page.screenshot({path:'artifacts/scaffold/default.png'});
});
test('system intersections author spans in both viewports and remain ordinary curve endpoints',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.evaluate(()=>(window as any).__editorPerfStore.getState().reset());
 const ids=await page.evaluate(()=>{const s=(window as any).__editorPerfStore.getState();return Object.fromEntries([...s.project.landmarks,...s.project.curves].filter((x:any)=>x.systemRole).map((x:any)=>[x.systemRole,x.id]));});
 await page.evaluate(id=>{const s=(window as any).__editorPerfStore.getState();s.startPatch();s.setPatchMode('span');s.pickPatchEdge(id);},ids.MAIN_Y);
 // 3D eligible anchor picking, followed by 2D picking, uses the same authoring state.
 const canvas=page.getByTestId('point-inspect').locator('canvas'),box=(await canvas.boundingBox())!;
 const xy=await page.evaluate(async({id,w,h})=>{const three=await import('/node_modules/.vite/deps/three.js' as string),{useInspectionCamera}=await import('/src/ui/windows/state.ts' as string),{pointPosition}=await import('/src/domain/geometry/evaluation.ts' as string),s=(window as any).__editorPerfStore.getState(),pose=useInspectionCamera.getState(),camera=new three.PerspectiveCamera(34,w/h,.1,100);camera.position.fromArray(pose.position);camera.quaternion.fromArray(pose.quaternion);camera.updateMatrixWorld();const v=new three.Vector3(...pointPosition(s.project,id)).project(camera);return [(v.x+1)*w/2,(1-v.y)*h/2];},{id:ids.SIDE_R_1,w:box.width,h:box.height});await page.mouse.click(box.x+xy[0],box.y+xy[1]);expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().patchCreation.start)).toBe(ids.SIDE_R_1);
 await page.getByTestId('span-anchor-'+ids.BROW).press('Enter');expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().patchCreation.uses.length)).toBe(1);
 await page.evaluate(({host,a,b})=>{const s=(window as any).__editorPerfStore.getState();s.pickPatchEdge(host);s.pickPatchAnchor(a);s.pickPatchAnchor(b);},{host:ids.MAIN_X,a:ids.BROW,b:ids.CROWN});await page.evaluate(({host,a,b})=>{const s=(window as any).__editorPerfStore.getState();s.pickPatchEdge(host);s.pickPatchAnchor(a);s.pickPatchAnchor(b);},{host:ids.MAIN_Z,a:ids.CROWN,b:ids.SIDE_R_0});
 expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().patchCreation.uses.length)).toBe(3);
 await page.evaluate(({host,a,b})=>{const s=(window as any).__editorPerfStore.getState();s.pickPatchEdge(host);s.pickPatchAnchor(a);s.pickPatchAnchor(b);},{host:ids.SIDE_R,a:ids.SIDE_R_0,b:ids.SIDE_R_1});expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.patches.length)).toBe(2);
 // Regular free curves remain available from system points after patch creation.
 await page.evaluate(()=>{const s=(window as any).__editorPerfStore.getState();s.cancelPatch();s.startCurve();});await page.evaluate(id=>(window as any).__editorPerfStore.getState().pickCurveEndpoint(id),ids.APEX_R);await page.evaluate(id=>(window as any).__editorPerfStore.getState().pickCurveEndpoint(id),ids.BROW);expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.curves.length)).toBe(9);expect(errors).toEqual([]);
});
test('high quality silhouette review sheet',async({page})=>{const {readFileSync}=await import('node:fs');await page.setViewportSize({width:1600,height:420});await page.setContent(readFileSync('artifacts/scaffold/contours.svg','utf8'));await page.screenshot({path:'artifacts/scaffold/contours.png'});});

test('roundness contour matrix review',async({page})=>{const {readFileSync}=await import('node:fs');await page.setViewportSize({width:1600,height:1340});await page.setContent(readFileSync('artifacts/scaffold/roundness.svg','utf8'));await page.screenshot({path:'artifacts/scaffold/roundness.png'});});
test('Upper Anchor owns Height with Undo, not Helmet controls',async({page})=>{
 await page.goto('/');await page.evaluate(()=>{const s=(window as any).__editorPerfStore.getState();s.reset();s.selectPatch('05500000-0000-4000-8000-000000000006');});
 await expect(page.getByRole('slider',{name:'Apex Height',exact:true})).toHaveCount(0);
 await page.evaluate(()=>{const s=(window as any).__editorPerfStore.getState();s.selectLandmark(s.project.landmarks.find((l:any)=>l.systemRole==='APEX_R').id);});
 const height=page.getByRole('slider',{name:'Height',exact:true});await expect(height).toBeVisible();await height.press('ArrowLeft');await height.blur();expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.loomisScaffold.apexHeight)).toBeLessThan(.85);await page.getByRole('button',{name:'撤销',exact:true}).click();expect(await page.evaluate(()=>(window as any).__editorPerfStore.getState().project.loomisScaffold.apexHeight)).toBe(.85);
});
