import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {addPatch} from '../../src/domain/patches/model';
import {parseLandmarks} from '../../src/domain/landmarks/persistence';
const base=parseLandmarks(readFileSync('artifacts/basic-patch/adjusted-source.json','utf8'));
const names=['左面壳前边界·额颞至颧颊','左斜面带横向桥·额颞层','左面壳后边界·颞侧至颧弓','左斜面带横向桥·颧颊层'];
const project=addPatch(base,names.map(n=>base.curves.find(c=>c.name===n)!.id));
test('real contour follows orientation, ignores zoom/display quality, survives hidden 3D and edits',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await page.locator('input[type=file][accept=".json,application/json"]').setInputFiles({name:'contour.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});
 await page.getByRole('checkbox',{name:'显示 Contour 窗口',exact:true}).check();
 const preview=page.getByTestId('contour-preview'),svg=page.getByTestId('contour-silhouette');
 const settled=async()=>{await expect(preview).toHaveAttribute('aria-busy','false');};
 const paths=()=>svg.locator('path').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('d')));
 await settled();expect((await paths()).length).toBeGreaterThan(0);
 const initial=await paths();
 await page.getByRole('combobox',{name:'Patch 显示精度',exact:true}).selectOption('veryLow');
 await page.getByRole('slider',{name:'3D Patch 不透明度',exact:true}).fill('0');
 await page.getByRole('checkbox',{name:'显示 Patch',exact:true}).uncheck();
 await settled();expect(await paths()).toEqual(initial);
 const canvas=page.getByTestId('point-inspect').locator('canvas'),rect=await canvas.boundingBox();if(!rect)throw Error('canvas');
 await page.mouse.move(rect.x+rect.width*.5,rect.y+rect.height*.5);await page.mouse.wheel(0,220);await page.waitForTimeout(500);await settled();expect(await paths()).toEqual(initial);
 await page.mouse.down();await page.mouse.move(rect.x+rect.width*.7,rect.y+rect.height*.65,{steps:8});await page.mouse.up();await page.waitForTimeout(3000);await settled();
 const rotated=await paths();expect(rotated).not.toEqual(initial);
 await page.getByRole('checkbox',{name:'显示 3D · 空间检查 窗口',exact:true}).uncheck();await settled();
 await expect(preview).toContainText('保持 3D 最后朝向');
 const frozen=await paths();await page.waitForTimeout(300);expect(await paths()).toEqual(frozen);
 await page.getByRole('button',{name:names[0],exact:true}).click();
 const handle=await page.getByTestId('curve-handle-1').boundingBox();if(!handle)throw Error('handle');
 await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await page.mouse.move(handle.x+40,handle.y+20,{steps:5});await page.mouse.up();await settled();
 expect(await paths()).not.toEqual(frozen);
 await page.getByRole('button',{name:'撤销',exact:true}).click();await settled();expect(await paths()).toEqual(frozen);
 await page.getByTestId('patch-row-'+project.patches![0].id).getByRole('button').first().click();
 await page.getByRole('slider',{name:'面凸度 Fullness',exact:true}).fill('100');await settled();
 await page.getByRole('checkbox',{name:'显示 Contour 窗口',exact:true}).uncheck();await expect(preview).toHaveCount(0);
 await page.getByRole('slider',{name:'面凸度 Fullness',exact:true}).fill('-100');
 await page.getByRole('checkbox',{name:'显示 Contour 窗口',exact:true}).check();await settled();
 expect((await paths()).length).toBeGreaterThan(0);
 await page.getByRole('checkbox',{name:'显示 2D 视角 窗口',exact:true}).uncheck();
 await page.screenshot({path:'test-results/contour-preview.png'});
 expect(errors).toEqual([]);
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('contour.landmarks.v039')!));
 expect(saved.landmarks).toEqual(project.landmarks);expect(saved.curves).toEqual(project.curves);
});
