import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {addPatch} from '../../src/domain/patches/model';
import {parseLandmarks} from '../../src/domain/landmarks/persistence';
const base=parseLandmarks(readFileSync('artifacts/basic-patch/adjusted-source.json','utf8'));
const seam='左面壳前边界·颧颊至下颊';
let project=addPatch(base,[seam,'左颊部体积线·颧颊至颊峰','左颊部体积线·颊峰至下颊'].map(n=>base.curves.find(c=>c.name===n)!.id));
project=addPatch(project,[seam,'左斜面带横向桥·颧颊层','左面壳后边界·颧弓至下颌角','左斜面带横向桥·下颊层'].map(n=>base.curves.find(c=>c.name===n)!.id));
test('Smooth worker, shared render field, source preservation, mirror controls and history',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');
 await page.locator('input[type=file][accept=".json,application/json"]').setInputFiles({name:'smooth.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});
 await page.getByRole('combobox',{name:'Patch 显示精度',exact:true}).selectOption('low');
 await page.getByRole('checkbox',{name:'显示 Contour 窗口',exact:true}).check();
 const controls=page.getByTestId('smooth-controls'),on=page.getByRole('checkbox',{name:'Surface Smooth',exact:true}),strength=page.getByRole('slider',{name:'Smooth Strength',exact:true});
 const paths=()=>page.getByTestId('patch-layer').first().locator('path[fill-opacity]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('d')));
 const contour=()=>page.getByTestId('contour-silhouette').locator('path').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('d')));
 const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('contour.landmarks.v039')!));
 await expect(controls).toHaveAttribute('data-state','off');await expect(page.getByTestId('contour-preview')).toHaveAttribute('aria-busy','false');
 const before=await paths(),contourBefore=await contour(),canvas=page.getByTestId('point-inspect').locator('canvas'),imageBefore=await canvas.screenshot();
 await on.check();await expect(controls).toHaveAttribute('data-state','ready');await expect.poll(paths).not.toEqual(before);
 await expect(page.getByTestId('contour-preview')).toHaveAttribute('aria-busy','false');await expect.poll(contour).not.toEqual(contourBefore);
 expect((await canvas.screenshot({path:'test-results/smooth-on-3d.png'})).equals(imageBefore)).toBe(false);
 await controls.getByText('求解诊断 · 完整解').click();const diagnostic=await page.getByTestId('smooth-diagnostics').innerText();
 expect(diagnostic).toContain('Seam residual');
 const rect=await strength.boundingBox();if(!rect)throw Error('slider');await page.mouse.move(rect.x+rect.width-4,rect.y+rect.height/2);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.45,rect.y+rect.height/2,{steps:7});await page.mouse.up();
 const value=await strength.inputValue();expect(+value).toBeLessThan(60);await expect(page.locator('.point-footer')).toContainText('撤销 3 / 100');
 expect(await page.getByTestId('smooth-diagnostics').innerText()).toBe(diagnostic);
 await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(strength).toHaveValue('100');
 await page.getByRole('button',{name:'重做',exact:true}).click();await expect(strength).toHaveValue(value);
 await on.uncheck();await expect.poll(paths).toEqual(before);await expect(page.getByTestId('contour-preview')).toHaveAttribute('aria-busy','false');await expect.poll(contour).toEqual(contourBefore);await on.check();
 await page.getByRole('button',{name:seam,exact:true}).click();const influence=page.getByRole('slider',{name:'Smooth Influence',exact:true});await influence.fill('0');await influence.blur();
 await expect(controls).toHaveAttribute('data-state','ready');await expect.poll(paths).toEqual(before);
 await page.getByRole('button',{name:seam.replace('左','右'),exact:true}).click();await expect(influence).toHaveValue('0');
 await influence.fill('65');await influence.blur();await expect(controls).toHaveAttribute('data-state','ready');
 const saved=await state();expect(saved.landmarks).toEqual(project.landmarks);expect(saved.curves).toEqual(project.curves);expect(saved.patches).toEqual(project.patches);
 expect(Object.keys(saved.surfaceSmooth.edgeInfluenceOverrides)).toHaveLength(1);
 expect(JSON.stringify(saved)).not.toMatch(/displacement|diagnostics|lattice/);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'保存 JSON',exact:true}).click();const stream=await(await download).createReadStream();let json='';for await(const part of stream!)json+=part.toString();expect(parseLandmarks(json).surfaceSmooth).toEqual(saved.surfaceSmooth);
 await page.reload();await expect(controls).toHaveAttribute('data-state','ready');await expect(strength).toHaveValue(value);
 await page.getByTestId('patch-row-'+project.patches![0].id).getByRole('button').first().click();const oldPaths=await paths();await page.getByRole('slider',{name:'面凸度 Fullness',exact:true}).fill('50');
 await expect(controls).toHaveAttribute('data-state','ready');await expect.poll(paths).not.toEqual(oldPaths);
 await page.screenshot({path:'test-results/smooth-ui.png'});expect(errors).toEqual([]);
});
test('source handle, plane and landmark edits re-solve; display precision does not change contour',async({page})=>{
 await page.goto('/');await page.locator('input[type=file][accept=".json,application/json"]').setInputFiles({name:'smooth.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...project,surfaceSmooth:{enabled:true,strength:1,edgeInfluenceOverrides:{}}}))});
 await page.getByRole('combobox',{name:'Patch 显示精度',exact:true}).selectOption('low');
 const panel=page.getByTestId('smooth-controls');await expect(panel).toHaveAttribute('data-state','ready');await panel.getByText('求解诊断 · 完整解').click();
 const diagnostic=page.getByTestId('smooth-diagnostics');let before=await diagnostic.innerText();
 await page.getByRole('button',{name:seam,exact:true}).click();
 const h=await page.getByTestId('curve-handle-1').boundingBox();if(!h)throw Error('handle');await page.mouse.move(h.x+h.width/2,h.y+h.height/2);await page.mouse.down();await page.mouse.move(h.x+17,h.y+8,{steps:4});await page.mouse.up();
 await expect(panel).toHaveAttribute('data-state','ready');await expect(diagnostic).not.toHaveText(before);before=await diagnostic.innerText();
 await page.getByRole('slider',{name:'调整曲线平面',exact:true}).fill('20');await expect(panel).toHaveAttribute('data-state','ready');await expect(diagnostic).not.toHaveText(before);before=await diagnostic.innerText();
 await page.locator('.point-view-tabs').getByRole('button',{name:'侧面',exact:true}).click();
 await page.getByRole('region',{name:'左右对称点',exact:true}).getByRole('button',{name:'左颊峰点',exact:true}).click();
 const point=await page.getByTestId('landmark-左颊峰点').boundingBox();if(!point)throw Error('point');await page.mouse.move(point.x+point.width/2,point.y+point.height/2);await page.mouse.down();await page.mouse.move(point.x+15,point.y+point.height/2,{steps:4});await page.mouse.up();
 await expect(panel).toHaveAttribute('data-state','ready');await expect(diagnostic).not.toHaveText(before);
 await page.getByRole('checkbox',{name:'显示 Contour 窗口',exact:true}).check();await expect(page.getByTestId('contour-preview')).toHaveAttribute('aria-busy','false');
 const paths=()=>page.getByTestId('contour-silhouette').locator('path').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('d'))),contour=await paths(),d=await diagnostic.innerText();
 await page.getByRole('combobox',{name:'Patch 显示精度',exact:true}).selectOption('high');expect(await paths()).toEqual(contour);expect(await diagnostic.innerText()).toBe(d);
});
