import {test,expect} from '@playwright/test';
test('frame-relative XYZ sliders support input, drag, arrows, mirror, undo and centerline',async({page})=>{
 await page.goto('/');const ids=await page.evaluate(async()=>{const {createLandmarkProject}=await import('/src/domain/landmarks/presets.ts'),s=(window as any).__editorPerfStore.getState(),p=createLandmarkProject();p.landmarks=p.landmarks.map((l:any)=>({...l,viewLocks:{}}));s.load(p);const l=p.landmarks.find((l:any)=>l.type==='RIGHT')!,center=p.landmarks.find((l:any)=>l.type==='CENTERLINE')!;s.selectLandmark(l.id);return {id:l.id,mirror:l.mirrorPartnerId,center:center.id};});
 const panel=page.getByTestId('spatial-point-coordinates'),x=panel.getByRole('slider',{name:'X',exact:true});await expect(x).toBeVisible();await expect(x).toHaveAttribute('min','-2');await expect(x).toHaveAttribute('max','2');
 const before=await x.inputValue();await x.locator('..').locator('.numeric-slider-value').dblclick();const input=panel.getByRole('textbox',{name:'X 数值'});await input.fill('1.25');await input.press('Enter');await expect(x).toHaveValue('1.25');
 const coords=()=>page.evaluate(ids=>{const p=(window as any).__editorPerfStore.getState().project;return [ids.id,ids.mirror].map(id=>p.landmarks.find((l:any)=>l.id===id).placement.position);},ids);
 let positions=await coords();expect(positions[0][0]).toBeCloseTo(1.25,8);expect(positions[1][0]).toBeCloseTo(-1.25,8);
 await x.press('Control+z');await expect.poll(async()=>+(await x.inputValue())).toBeCloseTo(+before,8);await x.press('Control+Shift+z');await expect(x).toHaveValue('1.25');await x.press('Alt+ArrowLeft');await expect.poll(async()=>+(await x.inputValue())).toBeCloseTo(1.248,8);
 const z=panel.getByRole('slider',{name:'Z',exact:true}),oldZ=+(await z.inputValue()),r=(await z.boundingBox())!;await page.mouse.move(r.x+r.width*.6,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width*.75,r.y+r.height/2,{steps:5});await page.mouse.up();expect(+(await z.inputValue())).toBeCloseTo(1,1);await z.press('Control+z');await expect.poll(async()=>+(await z.inputValue())).toBeCloseTo(oldZ,8);
 await page.evaluate(id=>(window as any).__editorPerfStore.getState().selectLandmark(id),ids.center);await expect(panel.getByRole('slider',{name:'X',exact:true})).toBeDisabled();await expect(panel.getByRole('slider',{name:'Y',exact:true})).toBeEnabled();
});
