import {test,expect} from '@playwright/test';
const names={viewport:'2D 视角',contour:'Contour',threeD:'3D · 空间检查'};
test('three main windows visibility, focus layouts, ratios and camera retention',async({page})=>{
 await page.goto('/');
 const saved=()=>page.evaluate(()=>localStorage.getItem('contour.landmarks.v039'));
 const before=await saved();
 const toggle=(id:keyof typeof names)=>page.getByRole('checkbox',{name:'显示 '+names[id]+' 窗口',exact:true});
 await expect(page.getByTestId('main-panel-viewport')).toBeVisible();
 await expect(page.getByTestId('main-panel-threeD')).toBeVisible();
 await expect(page.getByTestId('main-panel-contour')).toHaveCount(0);
 await toggle('contour').check();
 const initialDirection=await page.getByTestId('contour-preview').getAttribute('data-direction');
 for(const id of Object.keys(names))await expect(page.getByTestId('main-panel-'+id)).toBeVisible();
 await toggle('viewport').uncheck();
 await expect(page.getByTestId('main-panel-viewport')).toHaveCount(0);
 await toggle('threeD').uncheck();await expect(toggle('contour')).toBeDisabled();
 await expect(page.getByTestId('main-panel-contour')).toBeVisible();
 await toggle('viewport').check();await toggle('contour').uncheck();await expect(toggle('viewport')).toBeDisabled();
 await toggle('threeD').check();await toggle('viewport').uncheck();
 const canvas=page.getByTestId('point-inspect').locator('canvas'),rect=await canvas.boundingBox();if(!rect)throw Error('canvas');
 await page.mouse.move(rect.x+rect.width*.5,rect.y+rect.height*.5);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.65,rect.y+rect.height*.55,{steps:8});await page.mouse.up();await page.waitForTimeout(3000);
 const pixels=()=>canvas.evaluate((node:HTMLCanvasElement)=>{const c=document.createElement('canvas');c.width=node.width;c.height=node.height;const ctx=c.getContext('2d')!;ctx.drawImage(node,0,0);return Array.from(ctx.getImageData(0,0,c.width,c.height).data);});
 const orbit=await pixels();
 await toggle('contour').check();
 const rotatedDirection=await page.getByTestId('contour-preview').getAttribute('data-direction');expect(rotatedDirection).not.toBe(initialDirection);
 await toggle('threeD').uncheck();await expect(page.getByTestId('contour-preview')).toContainText('保持 3D 最后朝向');
 await toggle('threeD').check();await toggle('contour').uncheck();await page.waitForTimeout(300);
 const restored=await pixels();expect(restored.length).toBe(orbit.length);expect(restored.filter((x,i)=>Math.abs(x-orbit[i])>4).length/restored.length).toBeLessThan(.003);
 await toggle('viewport').check();await toggle('contour').check();
 await page.getByText('窗口比例',{exact:true}).click();
 await page.getByRole('slider',{name:'Contour 窗口比例',exact:true}).fill('1.8');
 await page.getByText('窗口比例',{exact:true}).click();
 await page.screenshot({path:'test-results/three-windows.png'});
 expect(await saved()).toBe(before);
 await page.reload();await expect(toggle('contour')).toBeChecked();
 await page.getByText('窗口比例',{exact:true}).click();await expect(page.getByRole('slider',{name:'Contour 窗口比例',exact:true})).toHaveValue('1.8');
});
