import {uid,emptyDrawing,sub,length,nodeAt,curveById,type DrawingDocument,type Point2,type StrokeDisplayIntervals,type DisplayIntervalMode,type TerminusBrushStyle,validInkEnds} from '../drawing/model';
import {moveNode,moveHandle,transform} from '../drawing/commands';
import {linkedNodeIds} from '../drawing/endpointLinks';
import {projectSceneSmoothHandle} from '../recordingScene/shapes';
import {applyScenePlacement,applyScenePlacementMatrix,tryInverseScenePlacement,isScenePlacementSimilarity} from '../recordingScene/tracks';
import {changeDisplayInterval,setDisplayIntervalEnd} from '../drawing/displayIntervals';
import {planArtworkLayerImport} from '../drawing/importArtworkLayers';
import {createWarpGrid,moveWarpNode,validateWarpGrid,type WarpGrid} from '../vectorWarp/model';
import {sameAngle} from '../vectorRecording/interpolation';
import {identityScenePlacement,identitySceneShape,type SceneTrack,type ScenePlacementValue,type SceneShapeValue,type SceneIntervalValue} from '../recordingScene/model';
import {emptyRecordingSnapshot,emptySnapshotRecording,emptySnapshotDeformationState,type RecordingSnapshotWorkspace,type RecordingSnapshot,type SnapshotRecording,type SnapshotDeformationState,type SnapshotPoseTrack,type Angle} from './model';
import {resolveSnapshot} from './evaluation';
import {remapDrawingIdentities,remapIntervalIdentities} from './sources';

export interface SnapshotSelection {layerIds?:string[];warpIds?:string[]}
export interface SnapshotWarpDimensions {name?:string;rows?:number;columns?:number;ref?:string}
export type SnapshotCommand=
 | {op:'createRecording';name?:string;ref?:string}
 | {op:'selectRecording';recordingId:string}
 | {op:'renameRecording';recordingId:string;name:string}
 | {op:'deleteRecording';recordingId:string}
 | {op:'setAngle';angle:Angle}
 | {op:'createSnapshot';name?:string;kind?:'view'|'sculpt'|'assembly';angle?:Angle;ref?:string}
 | {op:'selectSnapshot';snapshotId:string}
 | {op:'updateSnapshot';snapshotId?:string;name?:string}
 | {op:'deleteSnapshot';snapshotId:string}
 | {op:'pasteLayers'|'cloneLayers';sourceSnapshotId:string;layerIds?:string[];ref?:string}
 | {op:'moveLayers';sourceSnapshotId:string;layerIds:string[]}
 | {op:'removeLayers'|'reorderLayers';layerIds:string[]}
 | {op:'setLayerPlacement';layerId:string;value:ScenePlacementValue}
 | {op:'transformShapeElements';curveIds:string[];value:ScenePlacementValue}
 | {op:'moveShapeNode';layerId:string;nodeId:string;position:Point2}
 | {op:'moveShapeHandle';layerId:string;curveId:string;end:0|1;position:Point2}
 | ({op:'createWarp';layerIds:string[]}&SnapshotWarpDimensions)
 | ({op:'createChild';parentWarpId:string;layerIds:string[]}&SnapshotWarpDimensions)
 | ({op:'wrapParent';warpIds:string[]}&SnapshotWarpDimensions)
 | {op:'rebindLayers';layerIds:string[];warpId:string|null}
 | {op:'setWarp';warpId:string;name?:string;parentId?:string|null}
 | {op:'deleteWarp';warpId:string}
 | {op:'editWarpNodes';warpId:string;edits:{index:number;position?:Point2;handleU?:Point2;handleV?:Point2;twist?:Point2}[];moveHandles?:boolean}
 | {op:'setVisibility';layerId:string;objectId?:string;visible:boolean|null}
 | {op:'setLayerOrder';layerId:string;value:number}
 | {op:'changeInterval';layerId:string;sourceTrackId:string;rangeId:string;mode?:DisplayIntervalMode;start?:number;end?:number;fullLoop?:boolean}
 | {op:'setIntervalEnd';layerId:string;sourceTrackId:string;rangeId:string;end:0|1;style:TerminusBrushStyle}
 | {op:'setIntervalEnabled';layerId:string;sourceTrackId:string;rangeId:string;enabled:boolean}
 | ({op:'saveSelected';name?:string}&SnapshotSelection)
 | ({op:'discardSelected'}&SnapshotSelection)
 | {op:'renameKey';trackId:string;keyId:string;name:string}
 | {op:'deleteKey';trackId:string;keyId:string}
 | {op:'setTolerance';pixels:number};
const fields:Record<SnapshotCommand['op'],string[]>={createRecording:['name','ref'],selectRecording:['recordingId'],renameRecording:['recordingId','name'],deleteRecording:['recordingId'],setAngle:['angle'],createSnapshot:['name','kind','angle','ref'],selectSnapshot:['snapshotId'],updateSnapshot:['snapshotId','name'],deleteSnapshot:['snapshotId'],pasteLayers:['sourceSnapshotId','layerIds','ref'],cloneLayers:['sourceSnapshotId','layerIds','ref'],moveLayers:['sourceSnapshotId','layerIds'],removeLayers:['layerIds'],reorderLayers:['layerIds'],setLayerPlacement:['layerId','value'],transformShapeElements:['curveIds','value'],moveShapeNode:['layerId','nodeId','position'],moveShapeHandle:['layerId','curveId','end','position'],createWarp:['layerIds','name','rows','columns','ref'],createChild:['parentWarpId','layerIds','name','rows','columns','ref'],wrapParent:['warpIds','name','rows','columns','ref'],rebindLayers:['layerIds','warpId'],setWarp:['warpId','name','parentId'],deleteWarp:['warpId'],editWarpNodes:['warpId','edits','moveHandles'],setVisibility:['layerId','objectId','visible'],setLayerOrder:['layerId','value'],changeInterval:['layerId','sourceTrackId','rangeId','mode','start','end','fullLoop'],setIntervalEnd:['layerId','sourceTrackId','rangeId','end','style'],setIntervalEnabled:['layerId','sourceTrackId','rangeId','enabled'],saveSelected:['layerIds','warpIds','name'],discardSelected:['layerIds','warpIds'],renameKey:['trackId','keyId','name'],deleteKey:['trackId','keyId'],setTolerance:['pixels']};
export const snapshotCommandNames=Object.keys(fields) as SnapshotCommand['op'][];
export type RecordingSnapshotCommand=SnapshotCommand;
export class SnapshotCommandError extends Error {constructor(readonly code:string,message:string){super(message);}}
const fail=(code:string,message:string):never=>{throw new SnapshotCommandError(code,message);};
const clone=<T,>(value:T):T=>structuredClone(value);
const object=(value:unknown,allowed:readonly string[]):Record<string,unknown>=>{if(!value||typeof value!=='object'||Array.isArray(value))return fail('INVALID_REQUEST','Expected a JSON object.');const o=value as Record<string,unknown>,extra=Object.keys(o).filter(k=>!allowed.includes(k));if(extra.length)fail('INVALID_REQUEST',`Unknown fields: ${extra.join(', ')}`);return o;};
const id=(value:unknown,label='id'):string=>typeof value==='string'&&value.length>0&&value.length<=16384?value:fail('INVALID_REQUEST',`${label} must be a nonempty ID.`);
const name=(value:unknown):string=>typeof value==='string'&&!!value.trim()&&value.length<=256?value.trim():fail('INVALID_REQUEST','name must contain 1–256 characters.');
const number=(value:unknown,label:string,min=-10000,max=10000):number=>typeof value==='number'&&Number.isFinite(value)&&value>=min&&value<=max?value:fail('INVALID_REQUEST',`${label} must be finite in ${min}…${max}.`);
const bool=(value:unknown):boolean=>typeof value==='boolean'?value:fail('INVALID_REQUEST','Expected a boolean.');
const point=(value:unknown):Point2=>{if(!Array.isArray(value)||value.length!==2)fail('INVALID_REQUEST','Expected [x,y].');const p=value as unknown[];return [number(p[0],'x',-1e6,1e6),number(p[1],'y',-1e6,1e6)];};
const ids=(value:unknown,empty=false):string[]=>{if(!Array.isArray(value)||value.length>16384||!empty&&!value.length)fail('INVALID_REQUEST','Expected a nonempty ID array.');const out=(value as unknown[]).map(v=>id(v));if(new Set(out).size!==out.length)fail('INVALID_REQUEST','IDs must be unique.');return out;};
const angle=(value:unknown):Angle=>{const a=object(value,['x','y']);return {x:number(a.x,'angle.x',-90,90),y:number(a.y,'angle.y',-90,90)};};
const placement=(value:unknown):ScenePlacementValue=>{const p=object(value,['translation','rotation','scale','scaleX','scaleY']);return {translation:point(p.translation),rotation:number(p.rotation,'rotation',-1e9,1e9),scale:number(p.scale,'scale',1e-6,1e6),...(p.scaleX===undefined?{}:{scaleX:number(p.scaleX,'scaleX',0,1e6)}),...(p.scaleY===undefined?{}:{scaleY:number(p.scaleY,'scaleY',0,1e6)})};};
export interface SnapshotCreation {kind:'recording'|'snapshot'|'layer'|'warp'|'track'|'key';id:string;ref?:string;created:boolean}
export interface SnapshotCommandEffects {created:SnapshotCreation[];removedIds:string[];idMap?:Record<string,string>}
export const allSnapshotIds=(workspace:RecordingSnapshotWorkspace):string[]=>[...Object.values(workspace.library).flatMap(map=>Object.keys(map)),...workspace.snapshots.flatMap(s=>[s.id,...s.layers.map(l=>l.id),...s.deformation.warps.map(w=>w.id),...(s.inheritedState?.warps??[]).map(w=>w.id)]),...workspace.recordings.flatMap(r=>[r.id,...r.tracks.flatMap(t=>[t.id,...t.keys.map(k=>k.id)])])];

/** Commands mutate a detached transaction draft only. Validation of the complete
 * graph happens after the batch, so linked layer edits can be committed together. */
export function applySnapshotCommand(workspace:RecordingSnapshotWorkspace,raw:unknown):SnapshotCommandEffects {
 const c=object(raw,['op',...new Set(Object.values(fields).flat())]),op=c.op as SnapshotCommand['op'];if(!Object.hasOwn(fields,op))fail('UNKNOWN_COMMAND',`Unknown snapshot command: ${String(op)}`);object(c,['op',...fields[op]]);
 const effects:SnapshotCommandEffects={created:[],removedIds:[]},occupied=new Set(allSnapshotIds(workspace));
 const fresh=()=>{for(let i=0;i<100;i++){const value=uid();if(!occupied.has(value)){occupied.add(value);return value;}}return fail('ID_COLLISION','Unable to allocate a fresh ID.');};
 const created=(kind:SnapshotCreation['kind'],entityId:string,isNew=true,withRef=false)=>effects.created.push({kind,id:entityId,created:isNew,...(withRef&&c.ref!==undefined?{ref:id(c.ref,'ref')}:{})});
 const findRecording=(value:unknown)=>workspace.recordings.find(r=>r.id===id(value,'recordingId'))??fail('NOT_FOUND','Recording does not exist.');
 const findSnapshot=(value:unknown)=>workspace.snapshots.find(s=>s.id===id(value,'snapshotId'))??fail('NOT_FOUND','Snapshot does not exist.');
 if(op==='createRecording') {const recording=emptySnapshotRecording(fresh(),c.name===undefined?'Recording':name(c.name)),view=emptyRecordingSnapshot(fresh(),'View 1');workspace.recordings.push(recording);workspace.snapshots.push(view);recording.snapshotIds.push(view.id);recording.activeSnapshotId=view.id;workspace.activeRecordingId=recording.id;created('recording',recording.id,true,true);created('snapshot',view.id);return effects;}
 if(op==='selectRecording'){workspace.activeRecordingId=findRecording(c.recordingId).id;return effects;}
 if(op==='renameRecording'){findRecording(c.recordingId).name=name(c.name);return effects;}
 if(op==='deleteRecording'){const target=findRecording(c.recordingId);workspace.recordings=workspace.recordings.filter(r=>r!==target);if(workspace.activeRecordingId===target.id)workspace.activeRecordingId=workspace.recordings[0]?.id;effects.removedIds.push(target.id);return effects;}
 const recording=workspace.recordings.find(r=>r.id===workspace.activeRecordingId)??fail('NO_RECORDING','Create or select a Recording first.');
 if(recording.legacy)fail('LEGACY_READ_ONLY',recording.legacy.reason);
 const snapshot=()=>{const s=recording.activeSnapshotId&&workspace.snapshots.find(s=>s.id===recording.activeSnapshotId);return s||fail('NO_SNAPSHOT','Create or select a snapshot first.');};
 const ownedSnapshot=(value:unknown)=>{const s=findSnapshot(value);if(!recording.snapshotIds.includes(s.id))fail('NOT_FOUND','Snapshot does not belong to this Recording.');return s;};
 const layer=(value:unknown,s=snapshot())=>s.layers.find(l=>l.id===id(value,'layerId'))??fail('MISSING_LAYER','Layer does not exist in this snapshot.');
 const selectedLayers=(value:unknown,s=snapshot())=>ids(value).map(value=>layer(value,s));
 const evaluated=(s=snapshot(),at=recording.angle,useDraft=true)=>resolveSnapshot(workspace,s.id,{angle:at,useDraft});
 const state=()=>evaluated().state;
 const writable=(track:SnapshotPoseTrack)=>{if(track.draft&&!sameAngle(track.draft.angle,recording.angle))fail('OBJECT_DRAFT_AT_OTHER_ANGLE','This channel has a draft at another angle. Return to that angle or discard its draft.');};
 const ensureTrack=(channel:SnapshotPoseTrack['channel'],targetId:string,elementId?:string,sourceTrackId?:string):SnapshotPoseTrack=>{let track=recording.tracks.find(t=>t.channel===channel&&t.targetId===targetId&&(channel==='interval'?t.channel==='interval'&&t.sourceTrackId===sourceTrackId:t.elementId===elementId));if(!track){track={id:fresh(),channel,targetId,keys:[],interpolation:'independent',...(elementId?{elementId}:{}),...(sourceTrackId?{sourceTrackId}:{})} as SnapshotPoseTrack;recording.tracks.push(track);created('track',track.id);}return track;};
 const setDraft=(track:SnapshotPoseTrack,value:unknown)=>{writable(track);(track as SceneTrack<unknown>).draft={angle:clone(recording.angle),value:clone(value)};};
 const commit=(tracks:SnapshotPoseTrack[],target:RecordingSnapshot,label?:string)=>{for(const track of tracks){if(!track.draft||!sameAngle(track.draft.angle,target.angle))continue;const old=track.keys.find(k=>sameAngle(k.angle,target.angle)),key={id:old?.id??fresh(),angle:clone(target.angle),value:clone(track.draft.value),...(label?{name:label}:old?.name?{name:old.name}:{})};(track as SceneTrack<unknown>).keys=old?track.keys.map(k=>k===old?key:k):[...track.keys,key];delete track.draft;for(const other of workspace.snapshots)if(other!==target)other.authored=other.authored.filter(ref=>ref.keyId!==key.id);target.authored=target.authored.filter(ref=>ref.trackId!==track.id);target.authored.push({trackId:track.id,keyId:key.id});created('key',key.id,!old);}};
 const selectedTracks=()=>{const ls=c.layerIds===undefined?[]:selectedLayers(c.layerIds).map(l=>l.id),ws=c.warpIds===undefined?[]:ids(c.warpIds);if(!ls.length&&!ws.length)fail('INVALID_REQUEST','Select explicit layerIds or warpIds.');const evaluation=evaluated(),current=evaluation.state;for(const w of ws)if(!current.warps.some(x=>x.id===w))fail('NOT_FOUND','Warp does not exist.');const bound=new Set(current.bindings.filter(b=>ls.includes(b.layerId)).map(b=>b.warpId)),objects=new Set(evaluation.source.layers.filter(l=>ls.includes(l.id)).flatMap(l=>l.items)),links=new Set((evaluation.source.endpointLinks??[]).filter(link=>objects.has(link.a.curveId)||objects.has(link.b.curveId)).map(link=>link.id));return recording.tracks.filter(t=>ls.includes(t.targetId)||ws.includes(t.targetId)||t.channel==='warp'&&bound.has(t.targetId)||t.channel==='relationPosition'&&current.relationPositions[t.targetId]?.sourceLinkIds.some(id=>links.has(id)));};
 const currentWarp=(value:unknown,current=state())=>current.warps.find(w=>w.id===id(value,'warpId'))??fail('NOT_FOUND','Warp does not exist.');
 const structuralState=()=>{const s=snapshot(),value=state();s.deformation=clone(value);delete s.inheritedState;return s.deformation;};
 const newWarp=(bounds:WarpGrid['bounds'],parentId?:string)=>{const rows=c.rows===undefined?3:number(c.rows,'rows',1,16),columns=c.columns===undefined?3:number(c.columns,'columns',1,16);if(!Number.isInteger(rows)||!Number.isInteger(columns))fail('INVALID_REQUEST','Grid subdivisions must be integers.');const current=structuralState(),restGrid=createWarpGrid(bounds,rows,columns),warp={id:fresh(),name:c.name===undefined?`Warp ${current.warps.length+1}`:name(c.name),restGrid,grid:clone(restGrid),...(parentId?{parentId}:{})};current.warps.push(warp);created('warp',warp.id,true,true);const track=ensureTrack('warp',warp.id);for(const sid of recording.snapshotIds){const view=findSnapshot(sid);if(track.keys.some(k=>sameAngle(k.angle,view.angle)))continue;const key={id:fresh(),angle:clone(view.angle),value:clone(restGrid)};(track as SceneTrack<WarpGrid>).keys.push(key);view.authored.push({trackId:track.id,keyId:key.id});created('key',key.id);}return warp;};
 switch(op){
  case 'setAngle':{recording.angle=angle(c.angle);if(recording.snapshotIds.length)recording.activeSnapshotId=recording.snapshotIds.map(sid=>findSnapshot(sid)).sort((a,b)=>Math.hypot(a.angle.x-recording.angle.x,a.angle.y-recording.angle.y)-Math.hypot(b.angle.x-recording.angle.x,b.angle.y-recording.angle.y)||a.angle.y-b.angle.y||a.angle.x-b.angle.x||a.id.localeCompare(b.id))[0].id;break;}
  case 'selectSnapshot':{const s=ownedSnapshot(c.snapshotId);recording.activeSnapshotId=s.id;recording.angle=clone(s.angle);break;}
  case 'createSnapshot':{const at=c.angle===undefined?clone(recording.angle):angle(c.angle);if(recording.snapshotIds.some(sid=>sameAngle(findSnapshot(sid).angle,at)))fail('SNAPSHOT_EXISTS','A snapshot already exists at this angle.');const previous=recording.activeSnapshotId?findSnapshot(recording.activeSnapshotId):undefined;const kind=c.kind===undefined?'view':c.kind;if(!['view','sculpt','assembly'].includes(kind as string))fail('INVALID_REQUEST','Snapshot kind must be view, sculpt, or assembly.');const view=emptyRecordingSnapshot(fresh(),c.name===undefined?`View ${recording.snapshotIds.length+1}`:name(c.name),kind as RecordingSnapshot['kind'],at);if(previous){view.layers=clone(previous.layers);view.relations=clone(previous.relations);view.inheritedState=clone(evaluated(previous,at).state);}workspace.snapshots.push(view);recording.snapshotIds.push(view.id);recording.activeSnapshotId=view.id;recording.angle=clone(at);created('snapshot',view.id,true,true);break;}
  case 'updateSnapshot':{const target=c.snapshotId===undefined?snapshot():ownedSnapshot(c.snapshotId);if(c.name!==undefined)target.name=name(c.name);if(!sameAngle(target.angle,recording.angle))fail('SNAPSHOT_ANGLE_MISMATCH','Navigate to the snapshot’s saved angle before updating it.');commit(recording.tracks,target);break;}
  case 'deleteSnapshot':{
   const target=ownedSnapshot(c.snapshotId);if(workspace.snapshots.some(s=>s.layers.some(l=>l.kind==='reference'&&l.baseSnapshotId===target.id)))fail('SNAPSHOT_IN_USE','This snapshot is referenced by another snapshot.');
   const removed=new Set(target.authored.map(ref=>ref.keyId)),affected=recording.tracks.filter(track=>track.keys.some(key=>removed.has(key.id))),survivors=recording.snapshotIds.filter(sid=>sid!==target.id).map(sid=>findSnapshot(sid));
   const prior=new Map(affected.length?survivors.map(view=>[view.id,resolveSnapshot(workspace,view.id,{useDraft:false,diagnostics:'preview'}).state]):[]);
   workspace.snapshots=workspace.snapshots.filter(s=>s!==target);recording.snapshotIds=recording.snapshotIds.filter(sid=>sid!==target.id);if(recording.activeSnapshotId===target.id){recording.activeSnapshotId=recording.snapshotIds[0];if(recording.activeSnapshotId)recording.angle=clone(findSnapshot(recording.activeSnapshotId).angle);}
   for(const track of affected)track.keys=track.keys.filter(key=>!removed.has(key.id)) as typeof track.keys;
   // A view captures inherited state without keys. Removing its support sample
   // may therefore need a sparse key to preserve the surviving saved pose.
   for(let pass=0;pass<=survivors.length;pass++){let changed=false;for(const view of survivors){if(!affected.length)continue;const next=resolveSnapshot(workspace,view.id,{useDraft:false,diagnostics:'preview'}).state;for(const track of affected){const beforeValue=channelValue(prior.get(view.id)!,track),afterValue=channelValue(next,track);if(beforeValue===undefined||JSON.stringify(beforeValue)===JSON.stringify(afterValue))continue;const old=track.keys.find(k=>sameAngle(k.angle,view.angle)),key={id:old?.id??fresh(),angle:clone(view.angle),value:clone(beforeValue)};(track as SceneTrack<unknown>).keys=old?track.keys.map(k=>k===old?key:k):[...track.keys,key];view.authored=view.authored.filter(ref=>ref.trackId!==track.id);view.authored.push({trackId:track.id,keyId:key.id});created('key',key.id,!old);changed=true;}}if(!changed)break;}
   effects.removedIds.push(target.id,...removed);break;
  }
  case 'pasteLayers':case 'moveLayers':case 'cloneLayers':{
   const target=snapshot(),source=findSnapshot(c.sourceSnapshotId),selected=c.layerIds===undefined?source.layers:selectedLayers(c.layerIds,source);if(!selected.length)fail('INVALID_REQUEST','Select at least one source layer.');
   const resolved=resolveSnapshot(workspace,source.id,{useDraft:false});const plan=planArtworkLayerImport(resolved.drawing,selected.map(l=>l.id));if(plan.additionalLayerIds.length)fail('LAYER_DEPENDENCIES',`Also select dependent layers: ${plan.additionalLayerIds.join(', ')}.`);
   if(op==='cloneLayers'){const result=cloneSnapshotLayers(workspace,source,selected.map(l=>l.id),fresh);effects.idMap=result.idMap;for(const l of result.snapshot.layers){const slot={kind:'reference' as const,id:fresh(),name:l.name,baseSnapshotId:result.snapshot.id,baseLayerId:l.id};target.layers.push(slot);created('layer',slot.id,true,effects.created.every(e=>e.kind!=='layer'));}break;}
   if(source.id===target.id)fail('SNAPSHOT_CYCLE','A snapshot cannot reference or move layers into itself.');
   if(op==='moveLayers'&&selected.every(l=>l.kind==='reference')){const sourceState=resolved.state;for(const l of selected){if(target.layers.some(x=>x.id===l.id))fail('LAYER_EXISTS','The target already contains this layer slot.');target.layers.push(clone(l));if(sourceState.layers[l.id])target.deformation.layers[l.id]=clone(sourceState.layers[l.id]);created('layer',l.id,false);}const selectedIds=new Set(selected.map(l=>l.id));for(const w of sourceState.warps)if(!target.deformation.warps.some(x=>x.id===w.id))target.deformation.warps.push(clone(w));target.deformation.bindings.push(...clone(sourceState.bindings.filter(b=>selectedIds.has(b.layerId))));source.layers=source.layers.filter(l=>!selectedIds.has(l.id));effects.removedIds.push(...selectedIds);
   }else for(const l of selected){const slot={kind:'reference' as const,id:fresh(),name:l.name,baseSnapshotId:source.id,baseLayerId:l.id};target.layers.push(slot);created('layer',slot.id,true,effects.created.every(e=>e.kind!=='layer'));}
   break;
  }
  case 'removeLayers':{const s=snapshot(),selected=new Set(selectedLayers(c.layerIds).map(l=>l.id));s.layers=s.layers.filter(l=>!selected.has(l.id));effects.removedIds.push(...selected);break;}
  case 'reorderLayers':{const s=snapshot(),order=ids(c.layerIds,true);if(order.length!==s.layers.length||order.some(value=>!s.layers.some(l=>l.id===value)))fail('INVALID_REQUEST','Provide every current layer ID exactly once.');s.layers=order.map(value=>layer(value,s));break;}
  case 'setLayerPlacement':{const l=layer(c.layerId);setDraft(ensureTrack('placement',l.id),placement(c.value));break;}
  case 'moveShapeNode':case 'moveShapeHandle':case 'transformShapeElements':{
   const e=evaluated(),current=e.prePlacementDrawing,base=e.preShapeDrawing,relationNodes=new Set<string>();let next:DrawingDocument;
   if(op==='transformShapeElements'){
    const curveIds=ids(c.curveIds),delta=placement(c.value);if(!isScenePlacementSimilarity(delta))fail('INVALID_REQUEST','Element transform must use a positive uniform scale.');for(const curveId of curveIds)if(!e.drawing.curves.some(curve=>curve.id===curveId))fail('MISSING_ELEMENT','Selected curve does not exist.');
    let world=transform(e.drawing,curveIds,p=>applyScenePlacement(delta,p),true,false);for(const curveId of curveIds)for(const end of [0,1] as const)world=projectSceneSmoothHandle(world,{curveId,end});next=clone(current);
    const inverse=(layerId:string,p:Point2):Point2=>{const matrix=tryInverseScenePlacement(e.placements[layerId]??identityScenePlacement());if(!matrix)fail('SINGULAR_PLACEMENT','Restore the affected layer’s zero axis scale before transforming its elements.');return applyScenePlacementMatrix(matrix!,p);};
    for(const node of world.nodes){const prior=e.drawing.nodes.find(n=>n.id===node.id)!;if(length(sub(node.position,prior.position))<1e-12)continue;const owner=current.layers.find(l=>current.curves.some(curve=>l.items.includes(curve.id)&&curve.nodes.includes(node.id)))!;next.nodes.find(n=>n.id===node.id)!.position=inverse(owner.id,node.position);}
    for(const curve of world.curves){const prior=e.drawing.curves.find(c=>c.id===curve.id)!,owner=current.layers.find(l=>l.items.includes(curve.id))!;for(const end of [0,1] as const)if(length(sub(curve.handles[end],prior.handles[end]))>=1e-12)next.curves.find(c=>c.id===curve.id)!.handles[end]=inverse(owner.id,curve.handles[end]);}
   }else{
    const l=layer(c.layerId),owner=current.layers.find(x=>x.id===l.id)??fail('MISSING_LAYER','Resolved layer is missing.'),position=point(c.position);
    if(op==='moveShapeNode'){const nodeId=id(c.nodeId,'nodeId');if(!current.curves.some(curve=>owner.items.includes(curve.id)&&curve.nodes.includes(nodeId)))fail('MISSING_ELEMENT','Node is not owned by this layer.');next=moveNode(current,nodeId,position,true);}
    else{const curveId=id(c.curveId,'curveId');if(!owner.items.includes(curveId)||!current.curves.some(curve=>curve.id===curveId))fail('MISSING_ELEMENT','Curve is not owned by this layer.');if(c.end!==0&&c.end!==1)fail('INVALID_REQUEST','end must be 0 or 1.');next=projectSceneSmoothHandle(moveHandle(current,{curveId,end:c.end as 0|1},position,true),{curveId,end:c.end as 0|1});}
   }
   for(const moved of next.nodes){if(relationNodes.has(moved.id)||length(sub(moved.position,current.nodes.find(n=>n.id===moved.id)!.position))<1e-12)continue;const component=linkedNodeIds(current,moved.id),links=(current.endpointLinks??[]).filter(link=>component.has(nodeAt(current,link.a).id)&&component.has(nodeAt(current,link.b).id));if(!links.length)continue;component.forEach(id=>relationNodes.add(id));const sourceLinkIds=links.map(link=>link.id).sort(),prior=[...Object.entries(e.state.relationPositions),...recording.snapshotIds.flatMap(sid=>{const view=findSnapshot(sid);return [...Object.entries(view.deformation.relationPositions),...Object.entries(view.inheritedState?.relationPositions??{})];})].find(([,v])=>v.sourceLinkIds.some(id=>sourceLinkIds.includes(id))),targetId=prior?.[0]??fresh(),original=base.nodes.find(n=>n.id===moved.id)??fail('MISSING_ELEMENT','Linked node has no baseline.'),offset=sub(moved.position,original.position);
    if([...component].some(nodeId=>{const a=next.nodes.find(n=>n.id===nodeId),b=base.nodes.find(n=>n.id===nodeId);return !!a&&!!b&&length(sub(sub(a.position,b.position),offset))>1e-8;}))fail('LINKED_LOCAL_SPACE','Linked layers have incompatible local placements. Give the linked layers the same placement before transforming these elements.');
    const ownerIds=current.layers.filter(own=>current.curves.some(curve=>own.items.includes(curve.id)&&curve.nodes.some(id=>component.has(id)))).map(own=>own.id);for(const sid of recording.snapshotIds){const view=findSnapshot(sid);if(ownerIds.every(owner=>view.layers.some(l=>l.id===owner))&&!view.deformation.relationPositions[targetId]&&!view.inheritedState?.relationPositions[targetId])view.deformation.relationPositions[targetId]={sourceLinkIds,offset:[0,0]};}snapshot().deformation.relationPositions[targetId]={sourceLinkIds,offset:prior?.[1].offset??[0,0]};setDraft(ensureTrack('relationPosition',targetId),offset);
   }
   for(const own of current.layers){const curveIds=new Set(own.items),curves=next.curves.filter(curve=>curveIds.has(curve.id)),nodeIds=new Set(curves.flatMap(curve=>curve.nodes)),shape:SceneShapeValue=clone(e.state.layers[own.id]?.shape??identitySceneShape());let changed=false;for(const node of next.nodes){if(!nodeIds.has(node.id)||relationNodes.has(node.id))continue;const prior=current.nodes.find(n=>n.id===node.id)!,original=base.nodes.find(n=>n.id===node.id);if(!original||length(sub(node.position,prior.position))<1e-12)continue;shape.nodes[node.id]=sub(node.position,original.position);changed=true;}
    for(const curve of curves){const original=base.curves.find(x=>x.id===curve.id),prior=curveById(current,curve.id);if(!original)continue;const offsets=clone(shape.handles[curve.id]??[[0,0],[0,0]]) as [Point2,Point2];let handleChanged=false;for(const end of [0,1] as const){const vector=sub(curve.handles[end],nodeAt(next,{curveId:curve.id,end}).position),before=sub(prior.handles[end],nodeAt(current,{curveId:curve.id,end}).position);if(length(sub(vector,before))<1e-12)continue;offsets[end]=sub(vector,sub(original.handles[end],nodeAt(base,{curveId:curve.id,end}).position));handleChanged=true;}if(handleChanged){shape.handles[curve.id]=offsets;changed=true;}}
    if(changed)setDraft(ensureTrack('shape',own.id),shape);
   }break;
  }
  case 'createWarp':case 'createChild':{const selected=selectedLayers(c.layerIds),e=evaluated(),current=e.state,parent=op==='createChild'?currentWarp(c.parentWarpId,current):undefined;if(parent&&selected.some(l=>current.bindings.find(b=>b.layerId===l.id)?.warpId!==parent.id))fail('NOT_DIRECT_PARENT','A child Warp can take only layers directly bound to its parent.');const objects=new Set(e.source.layers.filter(l=>selected.some(x=>x.id===l.id)).flatMap(l=>l.items)),curves=e.source.curves.filter(curve=>objects.has(curve.id)),nodes=new Set(curves.flatMap(curve=>curve.nodes)),points=[...e.source.nodes.filter(n=>nodes.has(n.id)).map(n=>n.position),...curves.flatMap(curve=>curve.handles)],min:Point2=points.length?[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1]))]:[-1,-1],max:Point2=points.length?[Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))]:[1,1],pad=Math.max(max[0]-min[0],max[1]-min[1],.1)*.08,warp=newWarp({min:[min[0]-pad,min[1]-pad],max:[max[0]+pad,max[1]+pad]},parent?.id),s=snapshot().deformation;const selectedIds=new Set(selected.map(l=>l.id));s.bindings=s.bindings.filter(b=>!selectedIds.has(b.layerId));s.bindings.push(...selected.map(l=>({layerId:l.id,warpId:warp.id})));for(const sid of recording.snapshotIds){const view=findSnapshot(sid);if(view.id===snapshot().id)continue;const common=view.layers.filter(l=>selectedIds.has(l.id));if(!common.length)continue;const inherited=resolveSnapshot(workspace,view.id,{useDraft:false,diagnostics:'preview'}).state;if(parent&&!inherited.warps.some(w=>w.id===parent.id))continue;view.deformation=clone(inherited);delete view.inheritedState;if(!view.deformation.warps.some(w=>w.id===warp.id))view.deformation.warps.push(clone(warp));const commonIds=new Set(common.map(l=>l.id));view.deformation.bindings=view.deformation.bindings.filter(b=>!commonIds.has(b.layerId));view.deformation.bindings.push(...common.map(l=>({layerId:l.id,warpId:warp.id})));}break;}
  case 'wrapParent':{const current=state(),children=ids(c.warpIds).map(value=>currentWarp(value,current)),parentId=children[0].parentId;if(children.some(w=>w.parentId!==parentId))fail('PARENT_MISMATCH','Selected Warps must share the same immediate parent.');const points=children.flatMap(w=>[w.restGrid.bounds.min,w.restGrid.bounds.max,...w.grid.nodes.flatMap(n=>[n.position,n.handleU,n.handleV])]),warp=newWarp({min:[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1]))],max:[Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))]},parentId);for(const child of snapshot().deformation.warps)if(children.some(w=>w.id===child.id))child.parentId=warp.id;break;}
  case 'rebindLayers':{const selected=selectedLayers(c.layerIds).map(l=>l.id),target=c.warpId===null?undefined:currentWarp(c.warpId),s=structuralState();s.bindings=s.bindings.filter(b=>!selected.includes(b.layerId));if(target)s.bindings.push(...selected.map(layerId=>({layerId,warpId:target.id})));break;}
  case 'setWarp':{const original=currentWarp(c.warpId),s=structuralState(),warp=s.warps.find(w=>w.id===original.id)!;if(c.name===undefined&&c.parentId===undefined)fail('INVALID_REQUEST','Provide name or parentId.');if(c.name!==undefined)warp.name=name(c.name);if(c.parentId!==undefined){if(c.parentId===null)delete warp.parentId;else warp.parentId=currentWarp(c.parentId,s).id;}break;}
  case 'deleteWarp':{const original=currentWarp(c.warpId),s=structuralState();s.warps=s.warps.filter(w=>w.id!==original.id).map(w=>w.parentId===original.id?{...w,parentId:original.parentId}:w);s.bindings=s.bindings.flatMap(b=>b.warpId!==original.id?[b]:original.parentId?[{...b,warpId:original.parentId}]:[]);effects.removedIds.push(original.id);break;}
  case 'editWarpNodes':{const warp=currentWarp(c.warpId);let grid=clone(warp.grid);const follow=c.moveHandles===undefined?true:bool(c.moveHandles);if(!Array.isArray(c.edits)||!c.edits.length||c.edits.length>grid.nodes.length)fail('INVALID_REQUEST','Provide 1…node-count unique edits.');const seen=new Set<number>();for(const raw of c.edits as unknown[]){const edit=object(raw,['index','position','handleU','handleV','twist']),index=number(edit.index,'index',0,grid.nodes.length-1);if(!Number.isInteger(index)||seen.has(index))fail('INVALID_REQUEST','Node indices must be unique integers.');seen.add(index);if(!['position','handleU','handleV','twist'].some(key=>edit[key]!==undefined))fail('INVALID_REQUEST','Each edit needs a position or handle value.');if(edit.position!==undefined)grid=moveWarpNode(grid,index,point(edit.position),follow);for(const key of ['handleU','handleV','twist'] as const)if(edit[key]!==undefined)grid.nodes[index][key]=point(edit[key]);}validateWarpGrid(grid);setDraft(ensureTrack('warp',warp.id),grid);break;}
  case 'setVisibility':{const l=layer(c.layerId),objectId=c.objectId===undefined?undefined:id(c.objectId,'objectId');if(objectId&&!evaluated().drawing.layers.find(x=>x.id===l.id)?.items.includes(objectId))fail('MISSING_ELEMENT','Object is not owned by this layer.');setDraft(ensureTrack('visibility',l.id,objectId),c.visible===null?null:bool(c.visible));break;}
  case 'setLayerOrder':{const l=layer(c.layerId);setDraft(ensureTrack('depth',l.id),number(c.value,'value'));break;}
  case 'changeInterval':case 'setIntervalEnd':case 'setIntervalEnabled':{const l=layer(c.layerId),e=evaluated(),trackId=id(c.sourceTrackId,'sourceTrackId'),base=e.source.displayIntervals?.find(t=>t.id===trackId)??fail('MISSING_INTERVAL','The source interval does not exist.');if(!e.source.layers.find(x=>x.id===l.id)?.items.includes(base.anchor.id))fail('MISSING_INTERVAL','The interval is not owned by this layer.');const existing=recording.tracks.find(t=>t.channel==='interval'&&t.targetId===l.id&&t.sourceTrackId===trackId);if(e.diagnostics.some(d=>d.code==='SOURCE_MATERIAL'&&(d.channelId===trackId||d.channelId===existing?.id)))fail('SOURCE_MATERIAL','Restore or repair the source material mapping before editing this interval channel.');const value:SceneIntervalValue=clone(e.state.layers[l.id]?.intervals?.[trackId]??{appearance:null,enabled:{}}),appearance=value.appearance??base,rangeId=id(c.rangeId,'rangeId');if(!appearance.ranges.some(r=>r.id===rangeId))fail('NOT_FOUND','Range does not exist.');if(op==='setIntervalEnabled')value.enabled[rangeId]=bool(c.enabled);else{const document={...e.source,displayIntervals:[...(e.source.displayIntervals??[]).filter(t=>t.id!==trackId),appearance]};let changed:DrawingDocument;if(op==='setIntervalEnd'){if(c.end!==0&&c.end!==1)fail('INVALID_REQUEST','end must be 0 or 1.');const style=object(c.style,['taper','taperWidthScale','extension','interior']);if(!validInkEnds([style,{}]))fail('INVALID_REQUEST','Invalid terminal brush.');changed=setDisplayIntervalEnd(document,trackId,rangeId,c.end as 0|1,style as TerminusBrushStyle);}else{if(c.mode!==undefined&&c.mode!=='SHOW'&&c.mode!=='HIDE')fail('INVALID_REQUEST','mode must be SHOW or HIDE.');const patch={...(c.mode===undefined?{}:{mode:c.mode as DisplayIntervalMode}),...(c.start===undefined?{}:{start:number(c.start,'start',0,1)}),...(c.end===undefined?{}:{end:number(c.end,'end',0,1)}),...(c.fullLoop===undefined?{}:{fullLoop:bool(c.fullLoop)})};if(!Object.keys(patch).length)fail('INVALID_REQUEST','Provide an interval property.');changed=changeDisplayInterval(document,trackId,rangeId,patch);}value.appearance=clone(changed.displayIntervals!.find(t=>t.id===trackId)!);}setDraft(ensureTrack('interval',l.id,undefined,trackId),value);break;}
  case 'saveSelected':commit(selectedTracks(),snapshot(),c.name===undefined?undefined:name(c.name));break;
  case 'discardSelected':for(const track of selectedTracks())delete track.draft;break;
  case 'renameKey':case 'deleteKey':{const track=recording.tracks.find(t=>t.id===id(c.trackId,'trackId'))??fail('NOT_FOUND','Track does not exist.'),key=track.keys.find(k=>k.id===id(c.keyId,'keyId'))??fail('NOT_FOUND','Key does not exist.');if(op==='renameKey')key.name=name(c.name);else{track.keys=track.keys.filter(k=>k!==key) as typeof track.keys;for(const s of workspace.snapshots)s.authored=s.authored.filter(ref=>ref.keyId!==key.id);effects.removedIds.push(key.id);}break;}
  case 'setTolerance':recording.tolerance=number(c.pixels,'pixels',.1,20)/250;break;
 }
 return effects;
}

/** Duplicate canonical identities and the selected dependency branch, retaining
 * original control points and each node's saved residuals. Never bake a view. */
function cloneSnapshotLayers(workspace:RecordingSnapshotWorkspace,source:RecordingSnapshot,layerIds:string[],fresh:()=>string):{snapshot:RecordingSnapshot;idMap:Record<string,string>} {
 const prefix=`copy:${fresh()}:`,mapping=new Map<string,string>(),map=(value:string)=>{let result=mapping.get(value);if(!result){result=prefix+value;mapping.set(value,result);}return result;};
 const required=new Map<string,Set<string>>(),visiting=new Set<string>();
 const collect=(snapshot:RecordingSnapshot,selected:string[])=>{if(visiting.has(snapshot.id))fail('SNAPSHOT_CYCLE','Cannot clone a cyclic dependency.');visiting.add(snapshot.id);const set=required.get(snapshot.id)??new Set<string>();required.set(snapshot.id,set);for(const layer of snapshot.layers.filter(l=>selected.includes(l.id))){if(set.has(layer.id))continue;set.add(layer.id);if(layer.kind==='reference'){const parent=workspace.snapshots.find(s=>s.id===layer.baseSnapshotId)??fail('MISSING_SNAPSHOT','Cannot clone a missing parent snapshot.');collect(parent,[layer.baseLayerId]);}}visiting.delete(snapshot.id);};collect(source,layerIds);
 const originals=emptyDrawing();for(const [snapshotId,selected] of required){const node=workspace.snapshots.find(s=>s.id===snapshotId)!;for(const l of node.layers)if(selected.has(l.id)&&l.kind==='original'){const {kind,...plain}=l;void kind;originals.layers.push(clone(plain));}}
 const items=new Set(originals.layers.flatMap(l=>l.items));originals.curves=Object.values(workspace.library.curves).filter(c=>items.has(c.id));const nodeIds=new Set(originals.curves.flatMap(c=>c.nodes));originals.nodes=Object.values(workspace.library.nodes).filter(n=>nodeIds.has(n.id));originals.fills=Object.values(workspace.library.fills).filter(f=>items.has(f.id));originals.offsets=Object.values(workspace.library.offsets).filter(o=>items.has(o.id));const remapped=remapDrawingIdentities(originals,map);for(const key of ['nodes','curves','fills','offsets'] as const)for(const element of remapped[key])(workspace.library[key] as Record<string,{id:string}>)[element.id]=element;
 const interval=(value:SceneIntervalValue):SceneIntervalValue=>({appearance:value.appearance?remapIntervalIdentities(value.appearance,map):null,enabled:Object.fromEntries(Object.entries(value.enabled).map(([key,v])=>[map(key),v]))});
 const remapState=(value:SnapshotDeformationState,selected:Set<string>):SnapshotDeformationState=>{const needed=new Set(value.bindings.filter(b=>selected.has(b.layerId)).map(b=>b.warpId));for(const warpId of needed){const w=value.warps.find(w=>w.id===warpId);if(w?.parentId)needed.add(w.parentId);}return {warps:value.warps.filter(w=>needed.has(w.id)).map(w=>({...clone(w),id:map(w.id),...(w.parentId?{parentId:map(w.parentId)}:{})})),bindings:value.bindings.filter(b=>selected.has(b.layerId)).map(b=>({layerId:map(b.layerId),warpId:map(b.warpId)})),layers:Object.fromEntries(Object.entries(value.layers).filter(([key])=>selected.has(key)).map(([key,state])=>[map(key),{...clone(state),...(state.shape?{shape:{nodes:Object.fromEntries(Object.entries(state.shape.nodes).map(([key,v])=>[map(key),clone(v)])),handles:Object.fromEntries(Object.entries(state.shape.handles).map(([key,v])=>[map(key),clone(v)]))}}:{}),...(state.visibility?{visibility:Object.fromEntries(Object.entries(state.visibility).map(([key,v])=>[map(key),v]))}:{}),...(state.intervals?{intervals:Object.fromEntries(Object.entries(state.intervals).map(([key,v])=>[map(key),interval(v)]))}:{})}])),relationPositions:Object.fromEntries(Object.entries(value.relationPositions).map(([key,v])=>[map(key),{sourceLinkIds:v.sourceLinkIds.map(map),offset:clone(v.offset)}])),...(value.intervalMaterialIssues?{intervalMaterialIssues:Object.fromEntries(Object.entries(value.intervalMaterialIssues).map(([key,v])=>[map(key),{...clone(v),sourceSnapshotId:map(v.sourceSnapshotId)}]))}:{})};};
 const result=new Map<string,RecordingSnapshot>();for(const [snapshotId,selected] of required){const node=workspace.snapshots.find(s=>s.id===snapshotId)!,resolved=resolveSnapshot(workspace,node.id,{useDraft:false}),document=resolved.source,selectedItems=new Set(document.layers.filter(l=>selected.has(l.id)).flatMap(l=>l.items)),curves=new Set(document.curves.filter(c=>selectedItems.has(c.id)).map(c=>c.id));
  const relationDocument:DrawingDocument={...emptyDrawing(),joins:document.joins.filter(j=>curves.has(j.a.curveId)||curves.has(j.b.curveId)),endpointLinks:(document.endpointLinks??[]).filter(l=>curves.has(l.a.curveId)||curves.has(l.b.curveId)),groups:(document.groups??[]).filter(g=>g.curveIds.some(cid=>curves.has(cid))),displayIntervals:(document.displayIntervals??[]).filter(t=>curves.has(t.anchor.id))},relations=remapDrawingIdentities(relationDocument,map),copy=emptyRecordingSnapshot(map(node.id),node.name+' copy',node.kind,node.angle);copy.layers=node.layers.filter(l=>selected.has(l.id)).map(l=>l.kind==='reference'?{...clone(l),id:map(l.id),baseSnapshotId:map(l.baseSnapshotId),baseLayerId:map(l.baseLayerId)}:{...clone(l),id:map(l.id),items:l.items.map(map)});copy.relations={joins:{add:relations.joins},endpointLinks:{add:relations.endpointLinks??[]},groups:{add:relations.groups??[]},displayIntervals:{add:relations.displayIntervals??[]}};copy.deformation=remapState(resolved.state,selected);workspace.snapshots.push(copy);result.set(node.id,copy);
 }
 return {snapshot:result.get(source.id)!,idMap:Object.fromEntries(mapping)};
}

function channelValue(state:SnapshotDeformationState,track:SnapshotPoseTrack):unknown {
 const layer=state.layers[track.targetId];switch(track.channel){case 'placement':return layer?.placement;case 'shape':return layer?.shape;case 'visibility':return layer?.visibility?.[track.elementId??track.targetId];case 'interval':return layer?.intervals?.[track.sourceTrackId];case 'depth':return layer?.depth;case 'warp':return state.warps.find(w=>w.id===track.targetId)?.grid;case 'relationPosition':return state.relationPositions[track.targetId]?.offset;}
}
