import {uiText} from "../i18n";
import {RIM_R,RIM_L,HELMET_LOOP} from '../../domain/head/scaffold';
import SymmetricPairListItem from '../shared/SymmetricPairListItem';
import {useEditor} from '../../app/store';
import {HELMET,scaffoldHostIds} from '../../domain/head/scaffold';
import {curveMemberships} from '../../domain/head/membership';
import NumericSlider from '../shared/NumericSlider';
import {formatNumeric} from '../shared/numericSliderMath';
import LoomisLock from './LoomisLock';
export function HelmetCard(){const s=useEditor(),h=s.project.loomisScaffold;if(!h)return null;return <article className="loomis-card" data-loomis-card data-system-id={HELMET}><LoomisLock id={HELMET}/><button className="symmetric-pair-row" aria-pressed={s.selectedPatchId===HELMET} onClick={()=>s.selectPatch(HELMET)}>{uiText("Default Helmet")}<small>{uiText("系统")}</small></button><div className="loomis-inline"><label><input type="checkbox" checked={h.visible} onChange={e=>s.setScaffold('visible',e.target.checked)}/>{uiText("显示 Helmet")}</label><details><summary>{uiText("Advanced")}</summary><RimHeightControl/><NumericSlider label={uiText("Side Shell Roundness")} min={0} max={1} value={h.roundness} formatValue={formatNumeric} onEditStart={()=>s.beginEdit(true)} onEditEnd={s.endEdit} onChange={v=>s.setScaffold('roundness',v)}/></details></div></article>;}
export function SystemPointInspector({id}:{id:string}){const s=useEditor(),l=s.project.landmarks.find(l=>l.id===id);if(l?.placement.kind!=='LOOMIS_SCAFFOLD')return null;const apex=l.placement.role.startsWith('APEX');return <div><small>{uiText("系统 ·")}{uiText(apex?'锚点基位从最终 Helmet 派生':'真实解析交点 · 调整宿主改变位置')}</small>{apex?<><NumericSlider label={uiText("Height")} min={0} max={1} value={s.project.loomisScaffold!.apexHeight} formatValue={formatNumeric} onEditStart={()=>s.beginEdit(true)} onEditEnd={s.endEdit} onChange={v=>s.setScaffold('apexHeight',v)}/><button onClick={()=>s.selectPatch(HELMET)}>{uiText("Host: Default Helmet →")}</button></>:curveMemberships(s.project,id).map(m=><button key={m.curveId} onClick={()=>s.selectCurve(m.curveId)}>{s.project.curves.find(c=>c.id===m.curveId)?.name}{uiText("· s=")}{uiText(formatNumeric(m.s))} →</button>)}</div>;}

export function RimHeightControl(){return <><ScaffoldShapeControls only="horizontal"/><small>{uiText('Rim 与水平环同高 · 衔接处切线连续')}</small><button onClick={()=>useEditor.getState().selectCurve(HELMET_LOOP)}>{uiText('选择 Helmet 闭合下缘')} →</button></>;}
export function HelmetLoopControls(){const s=useEditor();const start=(mode:'span'|'loop')=>{s.startPatch();s.setPatchMode(mode);s.pickPatchEdge(HELMET_LOOP);};return <div data-testid="helmet-loop-inspector"><ScaffoldShapeControls only="horizontal"/><small>{uiText('水平环前段 + 右 Rim + 水平环后段 + 左 Rim · 一个闭环')}</small><button onClick={()=>start('span')}>{uiText('用下缘区间建立 Patch')}</button><button onClick={()=>start('loop')}>{uiText('用整圈建立环形 Patch')}</button></div>;}

export function RimRow(){const s=useEditor(),active=s.selectedCurveId===RIM_R||s.selectedCurveId===RIM_L;return <article className="loomis-card" data-loomis-card><small className="system-badge">{uiText("系统")}</small><SymmetricPairListItem primaryId={RIM_R} mirrorId={RIM_L} selectedId={s.selectedCurveId} displayName="Helmet Rim" onSelect={s.selectCurve}>{()=>"Helmet Rim"}</SymmetricPairListItem>{active&&<div className="loomis-inline" data-ui-keyboard><RimHeightControl/><small>{uiText("安全帽下缘 · 复用侧环前后交点")}</small><button onClick={()=>s.addOnCurvePoint(s.selectedCurveId!)}>{uiText("+ 添加在线定位点")}</button></div>}</article>;}

export function ScaffoldShapeControls({only}:{only?:'horizontal'|'side'}){const s=useEditor(),h=s.project.loomisScaffold;if(!h)return null;const fields=[{key:'horizontalOffset' as const,label:'水平环高度 Y',min:-.9,max:.9},{key:'sidePosition' as const,label:'侧盖切割距离',min:.1,max:.95},{key:'sideTilt' as const,label:'侧盖倾斜（绕 Z）',min:-60,max:60}].filter(f=>!only||(only==='horizontal'?f.key==='horizontalOffset':f.key!=='horizontalOffset'));return <div data-testid="scaffold-shape-controls">{fields.map(f=><NumericSlider key={f.key} label={uiText(f.label)} min={f.min} max={f.max} value={h[f.key]??0} disabled={s.activeModule!=='HEADSET'} onEditStart={()=>s.beginEdit(true)} onEditEnd={s.endEdit} onChange={v=>s.setScaffold(f.key,v)}/>)}<small>{uiText('切割距离以归一化球壳半径为单位；左右镜像。')}</small></div>;}
