import {RIM_R,RIM_L} from '../../domain/head/scaffold';
import SymmetricPairListItem from '../shared/SymmetricPairListItem';
import {useEditor} from '../../app/store';
import {HELMET,scaffoldHostIds} from '../../domain/head/scaffold';
import {curveMemberships} from '../../domain/head/membership';
import NumericSlider from '../shared/NumericSlider';
import {formatNumeric} from '../shared/numericSliderMath';
import LoomisLock from './LoomisLock';
export function HelmetCard(){const s=useEditor(),h=s.project.loomisScaffold;if(!h)return null;return <article className="loomis-card" data-loomis-card data-system-id={HELMET}><LoomisLock id={HELMET}/><button className="symmetric-pair-row" aria-pressed={s.selectedPatchId===HELMET} onClick={()=>s.selectPatch(HELMET)}>Default Helmet <small>系统</small></button><div className="loomis-inline"><label><input type="checkbox" checked={h.visible} onChange={e=>s.setScaffold('visible',e.target.checked)}/>显示 Helmet</label><details><summary>Advanced</summary><RimSagControl/><NumericSlider label="Side Shell Roundness" min={0} max={1} value={h.roundness} formatValue={formatNumeric} onEditStart={()=>s.beginEdit(true)} onEditEnd={s.endEdit} onChange={v=>s.setScaffold('roundness',v)}/></details></div></article>;}
export function SystemPointInspector({id}:{id:string}){const s=useEditor(),l=s.project.landmarks.find(l=>l.id===id);if(l?.placement.kind!=='LOOMIS_SCAFFOLD')return null;const apex=l.placement.role.startsWith('APEX');return <div><small>系统 · {apex?'锚点基位从最终 Helmet 派生':'真实解析交点 · 调整宿主改变位置'}</small>{apex?<><NumericSlider label="Height" min={0} max={1} value={s.project.loomisScaffold!.apexHeight} formatValue={formatNumeric} onEditStart={()=>s.beginEdit(true)} onEditEnd={s.endEdit} onChange={v=>s.setScaffold('apexHeight',v)}/><button onClick={()=>s.selectPatch(HELMET)}>Host: Default Helmet →</button></>:curveMemberships(s.project,id).map(m=><button key={m.curveId} onClick={()=>s.selectCurve(m.curveId)}>{s.project.curves.find(c=>c.id===m.curveId)?.name} · s={formatNumeric(m.s)} →</button>)}</div>;}

export function RimSagControl(){const s=useEditor();return <NumericSlider label="Rim Sag" min={0} max={.5} value={s.project.loomisScaffold!.rimSag} formatValue={formatNumeric} onEditStart={()=>s.beginEdit(true)} onEditEnd={s.endEdit} onChange={v=>s.setScaffold('rimSag',v)}/>;}
export function RimRow(){const s=useEditor(),active=s.selectedCurveId===RIM_R||s.selectedCurveId===RIM_L;return <article className="loomis-card" data-loomis-card><small className="system-badge">系统</small><SymmetricPairListItem primaryId={RIM_R} mirrorId={RIM_L} selectedId={s.selectedCurveId} displayName="Helmet Rim" onSelect={s.selectCurve}>{()=>"Helmet Rim"}</SymmetricPairListItem>{active&&<div className="loomis-inline" data-ui-keyboard><RimSagControl/><small>安全帽下缘 · 复用侧环前后交点</small><button onClick={()=>s.addOnCurvePoint(s.selectedCurveId!)}>+ 添加在线定位点</button></div>}</article>;}
