// dot's checks from the review of c8f3fc2, copied from
// /Users/bowen/Documents/Codex/2026-10-06/task/review-c8f3fc2/proto/base/test/dot-c8.test.ts
// Unchanged except: the lazy base-reference-membership case is moved to test/known-failures.test.ts as
// KF-3 (a stated limit for low-level reference add/remove, not claimed solved). The active-react test
// documents a boundary: the retention limit covers the caches' own entries WITHOUT active subscribers.
import {it,expect,vi} from 'vitest'
import {react} from '@tldraw/state'
import {Editor} from '../src/editor'
import {Derived} from '../src/derived'
import {createDocStore,Reference,Fill} from '../src/schema'
import {exampleRecords,ids} from '../src/fixture'
import * as pose from '../src/pose'
import {counters,resetCounters} from '../src/counters'
function inspect(d:any,roots:any[]=[]){const seen=new Set<any>(),values=new Set<any>();function walk(c:any){if(!c||seen.has(c))return;seen.add(c);if(c.name?.startsWith('yaw')&&c.state?.address)values.add(c.state);for(const p of c.parents??[])walk(p);for(const child of c.children??[])walk(child)}let used=0;for(const k of ['yawCurves','yawFills']){const c=d[k];expect([...c.map.keys()].sort()).toEqual([...c.last.keys()].sort());expect([...c.map.keys()].sort()).toEqual([...c.weights.keys()].sort());for(const w of c.weights.values())used+=w;for(const x of c.map.values())walk(x);for(const v of c.last.values())values.add(v)}for(const r of roots)walk(r);expect(used).toBe(d.yawRetainedItems.used);return{actual:values.size,used,names:[...seen].filter(x=>x.name?.startsWith('yaw')).map(x=>x.name)}}
const setup=(n:number)=>{const e=new Editor(exampleRecords().map(r=>r.id===ids.L2?{...r,locked:false}:r),{yawRetainedItems:n});for(const[cid,aid]of[[ids.C1,'a2'],[ids.C2,'b2']]as const)expect(e.apply({type:'setPoseKey',curveId:cid,yaw:0,offsets:{[aid]:{x:1,y:2}}}).ok).toBe(true);return e}
it('independent parents AND children graph stays bounded without active subscribers for budgets0/1/12 through edits, growth and undo deletion',()=>{for(const budget of[0,1,12]){const e=setup(budget),boundary=(e.reader.get(ids.F)as any).boundary;let max=0;for(let i=0;i<8;i++){expect(e.apply({type:'createFill',id:Fill.createId(`dot${i}`),parentId:ids.L1,boundary}).ok).toBe(true);for(const y of[0,13.5,90]){e.derived.atYaw(y);const r=inspect(e.derived);max=Math.max(max,r.actual);expect(r.actual).toBeLessThanOrEqual(budget)}e.undo();e.derived.curveAt(ids.C1,13.5);expect(inspect(e.derived).actual).toBeLessThanOrEqual(budget);e.derived.atYaw(0);expect(inspect(e.derived).actual).toBeLessThanOrEqual(budget)}console.log('UNOBSERVED_LIMIT',{budget,max})}})
it('active react subscriber retains evicted yaw results via parent children; disposer releases that reachability',()=>{const e=setup(1);let runs=0;const stop=react('dot-angle-consumer',()=>{e.derived.curveAt(ids.C1,0);runs++});const d=e.derived as any;const roots=[...d.yawCurves.map.values()].flatMap((x:any)=>x.parents);e.derived.curveAt(ids.C1,90);const active=inspect(d,roots);expect(active.actual).toBe(2);expect(active.used).toBe(1);expect(e.apply({type:'setPoseKey',curveId:ids.C1,yaw:0,offsets:{a2:{x:3,y:2}}}).ok).toBe(true);expect(runs).toBeGreaterThan(1);stop();const disposed=inspect(d,roots);console.log('ACTIVE_REACT',{active,disposed,runs});expect(disposed.actual).toBeLessThanOrEqual(1)})
it('yaw curve counters must include uncached curve geometry rebuilt inside fill evaluation',()=>{const e=setup(12);e.derived.evaluated();const spy=vi.spyOn(pose,'curveAtYaw');resetCounters();e.derived.fillAt(ids.F,17);const calls=spy.mock.calls.length;const stats={...counters};spy.mockRestore();console.log('INLINE_GEOMETRY_COUNT',{actualCurveAtYawCalls:calls,reportedYawCurveEvals:stats.yawCurveEvals,reportedYawFillEvals:stats.yawFillEvals,boundarySteps:(e.reader.get(ids.F)as any).boundary.length});expect(stats.yawCurveEvals).toBe(calls)})
it('base-cache lifecycle diagnostic: net-zero membership churn skips prune until membership really changes',()=>{const s=createDocStore();s.put(exampleRecords());const d=new Derived(s,s);const first=d.evaluated();for(let i=0;i<3;i++){const r=Reference.create({id:Reference.createId(`life${i}`),name:'x',parentId:ids.L1,sourceId:ids.L3,transform:{a:1,b:0,c:0,d:1,e:0,f:0}});s.put([r]);d.instance(r.id,ids.E1);s.remove([r.id]);}const before=d.instanceCacheSize;const again=d.evaluated();const after=d.instanceCacheSize;const r=Reference.create({id:Reference.createId('live'),name:'x',parentId:ids.L1,sourceId:ids.L3,transform:{a:1,b:0,c:0,d:1,e:0,f:0}});s.put([r]);d.evaluated();console.log('PRUNE_LIFECYCLE',{before,after,sameList:first===again,afterRealMembershipChange:d.instanceCacheSize});expect(d.instanceCacheSize).toBe(2)})
