// dot's independent stage-0 review of 3729d27 (evidence-3729d27/independent.test.ts), kept as a regression
// test: verbatim except import paths, the evidence-file writer, and — by the agreed contract (overlays are only
// BaseReaders; membership scans their final records) — the first test asserts that an overlay has NO query /
// serialize instead of reading them, and the second no longer reads overlay.query; one `as any` for the typecheck.
import {react,transaction} from '@tldraw/state'
import {Editor} from '../src/editor'
import {overlayReader} from '../src/derived'
import {childrenOf,connectionsAt,within} from '../src/indexes'
import {graphProblems} from '../src/model'
import {evaluate,unappliedContainerOpacity} from '../src/evaluate'
import {plan,type Command} from '../src/commands'
import {exampleRecords,ids} from '../src/fixture'
import {Container,Curve,Connection,poseIdOf,deepFreeze,type FillRecord} from '../src/schema'
const report:any={};const unlock=()=>exampleRecords().map(r=>r.id===ids.L2?{...r,locked:false}:r)
const snap=(e:Editor)=>({doc:e.reader.serialize('document'),history:e.history,revision:e.revision,generation:e.generation})
const move=(curveId:any,anchorId:string,x:number):Command=>({type:'moveAnchors',targets:[{curveId,anchorId}],delta:{x,y:0}})
const fill=():Command=>({type:'createFill',parentId:ids.L1,boundary:structuredClone((exampleRecords().find(r=>r.id===ids.F) as FillRecord).boundary)})
it('overlay get enumeration and query membership agree for a deleted record',()=>{const e=new Editor(exampleRecords());childrenOf(e.reader,ids.L3,'curve');const v=overlayReader(e.reader,[],[ids.E1]);report.overlayDeleted={get:v.get(ids.E1),enumerated:v.allRecords().some(r=>r.id===ids.E1),children:childrenOf(v,ids.L3,'curve'),hasQuery:'query' in v,hasSerialize:'serialize' in v};expect('query' in v).toBe(false);expect('serialize' in v).toBe(false);expect(v.get(ids.E1)).toBeUndefined();expect(v.allRecords().some(r=>r.id===ids.E1)).toBe(false);expect(childrenOf(v,ids.L3,'curve')).toEqual([])})
it('overlay creation and reparent membership represent final state',()=>{const e=new Editor(exampleRecords()),newId=Curve.createId('new');childrenOf(e.reader,ids.L1,'curve');const existing:any=e.reader.get(ids.E1),added={...structuredClone(existing),id:newId,parentId:ids.L1};const v=overlayReader(e.reader,[{...existing,parentId:ids.L1},added],[]);report.overlayPut={l1:childrenOf(v,ids.L1,'curve'),l3:childrenOf(v,ids.L3,'curve')};expect(childrenOf(v,ids.L1,'curve')).toContain(newId);expect(childrenOf(v,ids.L1,'curve')).toContain(ids.E1);expect(childrenOf(v,ids.L3,'curve')).not.toContain(ids.E1)})
it('asking an overlay index first must not poison base command membership',()=>{const e=new Editor(exampleRecords()),v=overlayReader(e.reader,[],[ids.E1]);const previewChildren=childrenOf(v,ids.L3,'curve'),baseChildren=childrenOf(e.reader,ids.L3,'curve');const old=(e.reader.get(ids.E1) as any).anchors.e1.p;const r=e.apply({type:'transformContainer',containerId:ids.L3,matrix:{a:1,b:0,c:0,d:1,e:10,f:5}});const now=(e.reader.get(ids.E1) as any).anchors.e1.p;report.poison={previewChildren,baseChildren,result:r,before:old,after:now};expect(baseChildren).toContain(ids.E1);expect(now).toEqual({x:old.x+10,y:old.y+5})})
it('planning against a connection tombstone follows final linkage, not removed connection',()=>{const e=new Editor(unlock());connectionsAt(e.reader,`${ids.C1}#a3`);const v=overlayReader(e.reader,[],[ids.J]);const r=plan(v,move(ids.C1,'a3',2));report.overlayPlan=r;expect(r.ok).toBe(true);if(r.ok)expect(r.puts.map(x=>x.id)).toEqual([ids.C1])})
it('container tombstone is safe for the actual opacity query consumer',()=>{const e=new Editor(exampleRecords()),v=overlayReader(e.reader,[],[ids.L3,ids.E1,ids.R1]);let out:any,error='';try{out=unappliedContainerOpacity(v)}catch(x){error=String(x)}report.opacity={out,error};expect(error).toBe('')})
it('deleting one connected pose cannot write a document that reopen rejects',()=>{const e=new Editor(unlock());expect(e.apply({type:'setPoseKey',curveId:ids.C1,yaw:30,offsets:{a3:{x:10,y:0}}}).ok).toBe(true);expect(graphProblems(e.reader)).toEqual([]);const before=snap(e),r=e.apply({type:'deleteRecords',ids:[poseIdOf(ids.C1)]}),problems=graphProblems(e.reader);let reopen='';try{Editor.open(e.save())}catch(x){reopen=String(x)}report.poseDelete={result:r,problems,reopen};expect(r.ok).toBe(false);expect(e.reader.serialize('document')).toEqual(before.doc)})
it('generic deletion cannot unbind an endpoint in a locked container',()=>{const e=new Editor(exampleRecords()),before=snap(e),r=e.apply({type:'deleteRecords',ids:[ids.J]});const m=e.apply(move(ids.C1,'a3',7));report.lockedConnection={delete:r,subsequentMove:m,c1:(e.reader.get(ids.C1) as any).anchors.a3.p,c2:(e.reader.get(ids.C2) as any).anchors.b3.p};expect(r.ok).toBe(false);expect(e.reader.serialize('document')).toEqual(before.doc)})
it('generation is stale already when committed-write subscribers run',()=>{const e=new Editor(exampleRecords()),op=e.prepare();op.preview(move(ids.E1,'e1',3));let armed=false,nested:any,seen:any;const stop=react('stage0-generation-reentrant',()=>{e.reader.get(ids.C1);if(armed){armed=false;seen={generation:e.generation,revision:e.revision};nested=op.commit()}});armed=true;const outer=e.apply(move(ids.C1,'a2',1));stop();report.reentrant={outer,nested,seen,finalGeneration:e.generation};expect(nested.ok).toBe(false);expect(nested.error.code).toBe('STALE')})
it('prepared IDs latest input, operation switching, independent operations and ending semantics',()=>{const e=new Editor(exampleRecords()),cmd=deepFreeze(fill()),o=e.prepare(),a=o.preview(cmd),b=o.preview(cmd);expect(a.ok&&b.ok).toBe(true);if(!a.ok||!b.ok)return;expect(a.affected).toEqual(b.affected);expect(o.commit().ok).toBe(true);expect(e.reader.get(a.affected[0] as any)).toBeDefined();const once=snap(e);expect(o.commit().ok).toBe(false);expect(snap(e)).toEqual(once);const fresh=e.prepare(),p=fresh.preview(cmd);expect(p.ok&&p.affected[0]).not.toBe(a.affected[0]);fresh.cancel();expect(fresh.commit().ok).toBe(false);const switcher=e.prepare();switcher.preview(fill());switcher.preview(move(ids.E1,'e2',4));const result=switcher.commit();expect(result.ok).toBe(true);expect((e.reader.get(ids.E1) as any).anchors.e2.p.x).toBe(-26);report.operationSwitch={result,policy:'latest command replan; type/target not fixed in stage0'};const rejected=e.prepare();expect(rejected.commit({type:'deleteRecords',ids:['curve:missing']}).ok).toBe(false);expect(rejected.state).toBe('ended')})
it('edit undo ABA, reopened editor isolation, and external rollback preserve history',()=>{const e=new Editor(exampleRecords()),o=e.prepare();o.preview(move(ids.E1,'e1',2));e.apply(move(ids.C1,'a2',1));e.undo();const before=snap(e);expect(o.commit().ok).toBe(false);expect(snap(e)).toEqual(before);const saved=e.save(),reopened=Editor.open(saved),other=reopened.prepare();expect(other.preview(move(ids.E1,'e1',2)).ok).toBe(true);const old=e.prepare();old.preview(move(ids.E1,'e1',9));expect(old.commit().ok).toBe(true);expect((reopened.reader.get(ids.E1) as any).anchors.e1.p.x).toBe(-20);const start=snap(reopened),waiting=reopened.prepare();try{transaction(()=>{reopened.apply(move(ids.E1,'e1',3));throw Error('abort')})}catch{}expect(reopened.reader.serialize('document')).toEqual(start.doc);expect(reopened.history).toEqual(start.history);expect(reopened.revision).toBe(start.revision);expect(waiting.commit(move(ids.E1,'e1',1)).ok).toBe(false)})
it('observer error still reports committed deletion and warning sink cannot undo it',()=>{const e=new Editor(exampleRecords());let armed=false;const stop=react('stage0-delete-observer',()=>{e.reader.get(ids.E1);if(armed)throw Error('observer')});e.onWarning=()=>{throw Error('sink')};armed=true;const r=e.apply({type:'deleteRecords',ids:[ids.E1]});stop();expect(r.ok&&r.written).toBe(true);expect(e.reader.get(ids.E1)).toBeUndefined();expect((r as any).warnings?.map((x:any)=>x.code)).toEqual(['OBSERVER_FAILED','WARNING_HANDLER_FAILED']);expect(e.undo()).toBe(true);expect(e.reader.get(ids.E1)).toBeDefined();report.observer=r})
it('full deletion dependencies locks previews derived and atomic batch rollback',()=>{const e=new Editor(unlock());e.derived.evaluated();const before=snap(e);expect(e.apply({type:'deleteRecords',ids:[ids.L3]}).ok).toBe(false);expect(snap(e)).toEqual(before);const cmd:Command={type:'deleteRecords',ids:[ids.L3,ids.E1,ids.R1]},pv=e.preview(cmd);expect(pv.ok).toBe(true);if(!pv.ok)return;const shown=e.derived.preview(pv.puts,e.derived.previewChanges(pv.puts,pv.removals));expect(e.apply(cmd).ok).toBe(true);expect(e.derived.evaluated()).toEqual(shown);expect(e.derived.evaluated()).toEqual(evaluate(e.reader));expect(e.undo()).toBe(true);expect(e.reader.serialize('document')).toEqual(before.doc);const start=e.reader.serialize('document');try{e.batch('rollback deletion',()=>{expect(e.apply(cmd).ok).toBe(true);throw Error('abort')})}catch{}expect(e.reader.serialize('document')).toEqual(start);expect(e.derived.evaluated()).toEqual(evaluate(e.reader))})
