// Stage 3a (doc 18 §24 v2): prepare a character once, play it read-only; cache and runtime entry.
import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { ctxOf, playCharacter, prepareCharacter, type CharacterGrid } from '../src/character'
import { counters } from '../src/counters'
import { Editor } from '../src/editor'
import { evaluateSaved } from '../src/runtime'
import { schema, type DocRecord, type Shape } from '../src/schema'

const json = (f: string) => JSON.parse(readFileSync(`test/fixtures/${f}`, 'utf8'))
import { converted, eyePlain } from './helpers/stage1'
/** the stage-1 sample in the current format (converted from its pre-I-1 file) */
const sample = (): any[] => converted()
const openRecords = (rs: DocRecord[]) => Editor.open({ store: Object.fromEntries(rs.map((r) => [r.id, r])), schema: schema.serialize() } as any)
const K = 'character:K'
const prep = (rs: any[]) => prepareCharacter(ctxOf({ get: (id: string) => rs.find((r) => r.id === id), allRecords: () => rs } as any), K)
const ok = (p: ReturnType<typeof prep>): CharacterGrid => {
  if (!p.ok) throw new Error(p.problems.join('; '))
  return p.grid
}
const play = (g: CharacterGrid, yaw?: number, blink = 0) => {
  const r = playCharacter(g, { yaw, params: { blink } })
  if (!r.ok) throw new Error(r.problems.join('; '))
  return r
}
const gap = (s: Record<string, Shape>) => Math.hypot(s['curve:lid'].b.p.x - s['curve:lowerLid'].d.p.x, s['curve:lid'].b.p.y - s['curve:lowerLid'].d.p.y)
const maxDiff = (a: Shape, b: Shape) => Math.max(...Object.keys(a).flatMap((k) => (['p', 'hIn', 'hOut'] as const).map((h) => Math.hypot(a[k][h].x - b[k][h].x, a[k][h].y - b[k][h].y))))
const YAWS = [-120, -60, -30, 0, 15, 30, 45, 60, 75, 89, 90, 120]

describe('prepare / play on the stage-1 sample', () => {
  it('the positive sample prepares; the grid covers every key yaw; shared corners coincide everywhere (neutral and closed)', () => {
    const g = ok(prep(sample()))
    expect(g.yaws).toEqual([-60, 0, 45, 90])
    expect(g.params).toEqual(['blink'])
    expect(g.paramCurves).toEqual({ blink: ['curve:lid', 'curve:lowerLid'] })
    for (const y of YAWS) for (const b of [0, 0.5, 1]) expect(gap(play(g, y, b).shapes)).toBe(0)
    const plain = ok(prep(eyePlain(sample())))
    for (const y of YAWS) for (const b of [0, 0.5, 1]) expect(gap(play(plain, y, b).shapes)).toBe(0)
  })

  it('an old file keeps its picture (dot, review of 6eb9635 B1): K — fine-tune and takeovers on the eye — plays exactly what the pre-I-1 code played (golden generated by running 48543da)', () => {
    const golden = json('stage1-legacy-play-48543da.json')
    const g = ok(prep(sample()))
    for (const row of golden.rows) expect(playCharacter(g, { yaw: row.yaw, params: { blink: row.blink } })).toEqual({ ok: true, shapes: row.shapes, visible: expect.anything() })
    // the kept keyframes are marked as converted (the old rule's result), never passed off as the author's fixes
    const k = sample().find((r) => r.id === K)
    const marked = k.exprFixes.filter((x: any) => x.origin === 'converted')
    expect(marked.length).toBeGreaterThan(0)
    expect(k.exprFixes.filter((x: any) => x.origin === undefined).map((x: any) => x.id)).toEqual(['exprFix:lid@90/blink']) // the author's one old fix
  })

  it('the negative sample (Q has only the identity of the strand) is reported, never renormalised', () => {
    const p = prep(converted('stage1-invalid-missing.json'))
    expect(p.ok).toBe(false)
    if (!p.ok) expect(p.problems.join()).toMatch(/preset:Q \(weight 0.4\) has no shape for curve:strand \(identity only\)/)
  })

  it('weights must sum to 1 (never renormalised); presets disagreeing on visibility are refused', () => {
    const rs = sample()
    rs.find((r) => r.id === K).weights['preset:Q'] = 0.5
    expect(prep(rs).ok).toBe(false)
    const neg = sample()
    neg.find((r) => r.id === K).weights = { 'preset:P': 1.4, 'preset:Q': -0.4 }
    expect((prep(neg) as any).problems.join()).toMatch(/finite and non-negative/)
    const vis = sample()
    vis.find((r) => r.id === 'visibility:preset:Q/curve:strand').keys[1].yaw = 40
    const p = prep(vis)
    expect(p.ok === false && p.problems.join()).toMatch(/disagree on visibility at yaw 30/)
  })

  it('T(0) = 0: without fine-tune a preset key with no helper domain is read as drawn (Q strand@90); with fine-tune the basis is reported missing', () => {
    expect(prep(sample()).ok).toBe(true) // Q has no helper domain at 90, strand has no fine-tune
    const rs = sample()
    rs.find((r) => r.id === K).fineTune['curve:strand'] = { w: { dp: { x: 1, y: 0 }, dIn: { x: 1, y: 0 }, dOut: { x: 1, y: 0 } } }
    const p = prep(rs)
    expect(p.ok === false && p.problems.join()).toMatch(/preset:Q has no helper domain at yaw 90 to carry the fine-tune of curve:strand/)
  })

  it('a curve with no original still plays from its yaw track; only the no-yaw context needs the original', () => {
    const g = ok(prep(sample()))
    const s = play(g, 120).shapes['curve:strand']
    expect(s.u.p.x).toBeCloseTo(0.6 * 35 + 0.4 * 34, 12) // P strand(5) / Q strand(4), clamped at 90
    const noYaw = playCharacter(g, {})
    expect(noYaw.ok === false && noYaw.problems.join()).toMatch(/no-yaw context needs an original/)
  })

  it('visibility is the agreed stepped track (hidden below 30)', () => {
    const g = ok(prep(sample()))
    expect(play(g, 29).visible['curve:strand']).toBe(false)
    expect(play(g, 30).visible['curve:strand']).toBe(true)
    expect(play(g, 0).visible['curve:lid']).toBe(true)
  })
})

describe('takeovers and expressions', () => {
  it('a line takeover that does not take the node leaves the shared corner at the normal node result', () => {
    const rs = sample()
    const k = rs.find((r) => r.id === K)
    k.takeovers = k.takeovers.filter((t: any) => t.kind === 'line') // no node takeover
    const g = ok(prep(rs))
    const base = sample()
    const kb = base.find((r) => r.id === K)
    kb.takeovers = []
    const g0 = ok(prep(base))
    for (const y of YAWS) {
      const a = play(g, y).shapes, b = play(g0, y).shapes
      expect(a['curve:lowerLid'].d.p).toEqual(b['curve:lowerLid'].d.p) // the node did not move …
      expect(gap(a)).toBe(0) // … and the taken-over line still ends on it
    }
  })

  it('a node takeover covers its whole range 0 → θₜ: no gap at any in-between angle (0.45 at 45° if it covered 90° only)', () => {
    const g = ok(prep(sample()))
    for (const y of [0, 10, 30, 45, 60, 75, 89, 90]) expect(gap(play(g, y).shapes)).toBe(0)
    const at90 = play(g, 90).shapes['curve:lowerLid'].d.p
    expect(at90).toEqual({ x: 15.5, y: -0.4 }) // basisFront (10, 0) = the current front: target exactly
  })

  it('takeovers ending inside a direction, or overlapping, are refused', () => {
    const rs = sample()
    const k = rs.find((r) => r.id === K)
    k.takeovers[0].state.yaw = 45
    k.takeovers[0].direction.to = 45
    expect(prep(rs).ok === false && (prep(rs) as any).problems.join()).toMatch(/inside the positive range/)
    const ov = sample()
    const k2 = ov.find((r) => r.id === K)
    k2.takeovers.push({ ...structuredClone(k2.takeovers[0]), id: 'takeover:lid@90b' })
    expect((prep(ov) as any).problems.join()).toMatch(/overlaps another takeover/)
  })

  it('a character expression keyframe is played exactly at its yaw; clearing it restores the presets’ keyframes', () => {
    const rs = eyePlain(sample())
    const inherited = ok(prep(rs))
    const at90 = play(inherited, 90, 1).shapes
    const lid = at90['curve:lid']
    const shape = { ...lid, m: { p: { x: lid.m.p.x, y: lid.m.p.y - 2 }, hIn: { x: lid.m.hIn.x, y: lid.m.hIn.y - 2 }, hOut: { x: lid.m.hOut.x, y: lid.m.hOut.y - 2 } } }
    const k = rs.find((r) => r.id === K)
    k.exprFixes = [{ id: 'fix', curveId: 'curve:lid', param: 'blink', yaw: 90, shape }]
    const fixed = ok(prep(rs))
    expect(maxDiff(play(fixed, 90, 1).shapes['curve:lid'], shape)).toBeLessThan(1e-12)
    expect(play(fixed, 90, 1).shapes['curve:lowerLid']).toEqual(at90['curve:lowerLid']) // the other curve keeps its source
    k.exprFixes = []
    for (const y of YAWS) expect(play(ok(prep(rs)), y, 1).shapes).toEqual(play(inherited, y, 1).shapes)
  })

  it('every weighted preset needs the keyframes of a curve the parameter names; a missing one makes only that parameter unplayable', () => {
    const rs = eyePlain(sample())
    rs.find((r) => r.id === 'forms:preset:Q/curve:lowerLid').expr = {}
    const g = ok(prep(rs))
    expect(play(g, 30, 0).shapes['curve:lid']).toBeTruthy() // the open eye still plays
    const r = playCharacter(g, { yaw: 30, params: { blink: 1 } })
    expect(r.ok === false && r.problems.join()).toMatch(/missing blink keyframes of curve:lowerLid in preset:Q \(drawn by the author, never generated\)/)
  })

  it('an unmodified extra preset key never changes the closed track (the closed keyframes are read as drawn)', () => {
    const rs = eyePlain(sample())
    const g = ok(prep(rs))
    // add a P neutral key at 30 equal to P's current interpolated form (what setPresetKey will capture)
    const extra = structuredClone(rs)
    for (const c of ['curve:lid', 'curve:lowerLid']) {
      const f = extra.find((r) => r.id === `forms:preset:P/${c}`)
      const k0 = f.yaw.find((k: any) => k.yaw === 0).shape, k90 = f.yaw.find((k: any) => k.yaw === 90).shape
      const at30 = Object.fromEntries(Object.keys(k0).map((a) => [a, Object.fromEntries((['p', 'hIn', 'hOut'] as const).map((h) => [h, { x: k0[a][h].x + (k90[a][h].x - k0[a][h].x) * (30 / 90), y: k0[a][h].y + (k90[a][h].y - k0[a][h].y) * (30 / 90) }]))]))
      f.yaw.splice(2, 0, { yaw: 30, shape: at30 })
    }
    const g2 = ok(prep(extra))
    for (const y of YAWS) expect(maxDiff(play(g2, y, 1).shapes['curve:lid'], play(g, y, 1).shapes['curve:lid'])).toBeLessThan(1e-12)
  })
})

describe('cache, budget and the runtime entry', () => {
  it('prepare once, play many; edits elsewhere do not rebuild; an edit the character reads does; undo returns the same grid', () => {
    const e = openRecords(sample())
    const before = counters.characterPrepares
    const first = e.derived.characterAt(K, { yaw: 30, params: { blink: 0.5 } })
    expect(first.ok).toBe(true)
    for (const y of [-60, 0, 45, 90]) e.derived.characterAt(K, { yaw: y })
    expect(counters.characterPrepares - before).toBe(1)
    expect(e.apply({ type: 'moveAnchors', targets: [{ curveId: 'curve:C1' as any, anchorId: 'a2' }], delta: { x: 1, y: 0 } }).ok).toBe(true) // not read by the character
    e.derived.characterAt(K, { yaw: 30 })
    expect(counters.characterPrepares - before).toBe(1)
    const grid = JSON.stringify(e.derived.character(K))
    expect(e.apply({ type: 'deleteRecords', ids: ['helperDomain:Q/45'] }).ok).toBe(true) // read (fine-tune transfer)
    const missing = e.derived.characterAt(K, { yaw: 30 })
    expect(missing.ok === false && missing.problems.join()).toMatch(/preset:Q has no helper domain at yaw 45/)
    expect(counters.characterPrepares - before).toBe(2)
    expect(e.undo()).toBe(true)
    expect(JSON.stringify(e.derived.character(K))).toBe(grid) // the same grid as before the deletion
  })

  it('the cache is weighed by the shapes it retains, in the shared budget', () => {
    const e = openRecords(sample())
    const used = e.derived.yawRetainedItems.used
    const p = e.derived.character(K)
    expect(p.ok).toBe(true)
    if (p.ok) expect(e.derived.yawRetainedItems.used - used).toBe(p.grid.retained)
    if (p.ok) {
      // counted independently: the distinct shape objects reachable from the grid
      const seen = new Set<unknown>()
      for (const g of Object.values(p.grid.curves)) {
        g.neutral.forEach((x) => seen.add(x))
        for (const l of Object.values(g.expr)) l.forEach((x) => seen.add(x))
      }
      for (const f of Object.values(p.grid.front)) if (f) seen.add(f)
      expect(p.grid.retained).toBe(seen.size)
      // lid neutral + lid closed + lowerLid neutral + lowerLid closed (its converted keyframes: K's own neutral form, kept
      // explicitly) + strand (blink does not name it: closed = neutral, shared) + two fronts
      expect(seen.size).toBe(4 + 4 + 4 + 4 + 4 + 2)
    }
    expect(e.derived.yawRetainedItems.consistent()).toBe(true)
  })

  it('runtime evaluateSaved with a character = the maker’s cached view (family curves played, legacy curves unchanged)', () => {
    const e = openRecords(eyePlain(sample()))
    for (const y of [-60, 10, 45, 90]) {
      const maker = e.derived.characterAt(K, { yaw: y, params: { blink: 0.25 } })
      if (!maker.ok) throw new Error()
      const rt = evaluateSaved(e.reader.allRecords(), { yaw: y, character: K, expr: { blink: 0.25 } })
      expect(rt).toEqual(maker.evaluated)
      expect(rt.curves.find((c) => c.address === 'curve:C1')).toEqual(e.derived.atYaw(y).curves.find((c) => c.address === 'curve:C1'))
    }
    expect(() => evaluateSaved(converted('stage1-invalid-missing.json'), { yaw: 0, character: K })).toThrow(/cannot be prepared: .*identity only/)
  })
})

describe('review requests for 3a (dot 1791314079): fills and reference instances on family curves, visibility between keys', () => {
  /** the sample + a fill over both lids (closed by the corner connection and a bridge at the left corner) and a
   *  mirrored reference that places container:L1 (holding the family curves) inside L3 */
  const withFillAndInstance = () => {
    const rs = eyePlain(sample())
    rs.push({ typeName: 'fill', id: 'fill:eye', name: 'eye', parentId: 'container:L1', index: 'a0', color: '#fff', depthOffset: 0,
      boundary: [{ curveId: 'curve:lid', segmentId: 's1', dir: 1 }, { curveId: 'curve:lid', segmentId: 's2', dir: 1 }, { curveId: 'curve:lowerLid', segmentId: 's4', dir: -1 }, { curveId: 'curve:lowerLid', segmentId: 's3', dir: -1 }, { bridge: { from: { curveId: 'curve:lowerLid', anchorId: 'c' }, to: { curveId: 'curve:lid', anchorId: 'a' } } }] })
    rs.push({ typeName: 'reference', id: 'reference:R2', name: 'mirrored eye', parentId: 'container:L3', index: 'b1', sourceId: 'container:L1', transform: { a: -1, b: 0, c: 0, d: 1, e: 100, f: 5 }, overrides: {} })
    return rs
  }
  const tp = (m: any, q: { x: number; y: number }) => ({ x: m.a * q.x + m.c * q.y + m.e, y: m.b * q.x + m.d * q.y + m.f })

  it('instances are placed once (transform of the played shape); the fill and its bridge read the played geometry; full = cached = runtime', () => {
    const rs = withFillAndInstance()
    const e = openRecords(rs)
    const m = rs.find((r) => r.id === 'reference:R2').transform
    for (const [yaw, blink] of [[0, 0], [30, 0.5], [90, 1], [-60, 0.2]]) {
      const g = ok(prep(rs))
      const played = play(g, yaw, blink).shapes
      const maker = e.derived.characterAt(K, { yaw, params: { blink } })
      if (!maker.ok) throw new Error(maker.problems.join())
      const ev = maker.evaluated
      const direct = ev.curves.find((c) => c.address === 'curve:lid')!
      const inst = ev.curves.find((c) => c.address === 'reference:R2/curve:lid')!
      for (const [a, q] of Object.entries(played['curve:lid'])) {
        expect(direct.anchors[a].p).toEqual(q.p)
        expect(inst.anchors[a].p).toEqual(tp(m, q.p)) // exactly one placement
        expect(inst.anchors[a].hOut).toEqual(tp(m, q.hOut))
      }
      const fill = ev.fills.find((f) => f.address === 'fill:eye')!
      expect(fill.cubics[0][0]).toEqual(played['curve:lid'].a.p)
      const bridge = fill.cubics[4]
      expect(bridge[0]).toEqual(played['curve:lowerLid'].c.p) // the bridge reads the character's geometry
      expect(bridge[3]).toEqual(played['curve:lid'].a.p)
      expect(evaluateSaved(rs, { yaw, character: K, expr: { blink } })).toEqual(ev) // runtime = maker cache
    }
  })

  it('a reference override on a family curve is refused on open (its meaning is undefined)', () => {
    const rs = withFillAndInstance()
    rs.find((r) => r.id === 'reference:R2').overrides = { 'curve:lid#m': { x: 1, y: 2 } }
    expect(() => openRecords(rs)).toThrow(/reference overrides on preset-form curves are not supported/)
  })

  it('visibility switches exactly at the key between grid points, and holds outside every key', () => {
    const g = ok(prep(sample()))
    for (const [y, want] of [[-1000, false], [-90, false], [29.999999, false], [30, true], [30.000001, true], [44, true], [1000, true]] as const)
      expect(play(g, y).visible['curve:strand']).toBe(want)
  })
})

describe('review of 819dd22 (dot): both node directions, other families, shared yaw budget, expression fix meaning, clearing a source line, notices', () => {
  it('two node takeovers on one connection (−60 and +90) both apply, each over its own range', () => {
    const rs = sample()
    const k = rs.find((r) => r.id === K)
    k.takeovers.push({ kind: 'node', id: 'takeover:corner@-60', connectionId: 'connection:corner', state: { yaw: -60 }, direction: { from: 0, to: -60 }, target: { x: -20, y: 7 }, basisFront: { x: 10, y: 0 }, L: [1, 0, 0, 1], basisFrom: 'takeover:lid@90' })
    const g = ok(prep(rs))
    expect(play(g, -60).shapes['curve:lowerLid'].d.p).toEqual({ x: -20, y: 7 })
    expect(play(g, 90).shapes['curve:lowerLid'].d.p).toEqual({ x: 15.5, y: -0.4 })
    for (const y of [-60, -30, 0, 45, 90]) expect(gap(play(g, y).shapes)).toBe(0)
  })

  it('a change in ANOTHER family (helper domain, rule, visibility) does not rebuild this character', () => {
    const rs = sample()
    rs.push({ typeName: 'family', id: 'family:other', name: 'other', curves: [] }, { typeName: 'preset', id: 'preset:O', name: 'O', familyId: 'family:other' },
      { typeName: 'helperDomain', id: 'helperDomain:O/30', presetId: 'preset:O', yaw: 30, affine: { a: 1, b: 0, c: 0, d: 1, e: 0, f: 0 }, source: { yaw: 0 }, target: { yaw: 30 }, ruleVersion: 1 })
    const e = openRecords(rs)
    e.derived.character(K)
    const before = counters.characterPrepares
    expect(e.apply({ type: 'deleteRecords', ids: ['helperDomain:O/30'] }).ok).toBe(true)
    e.derived.character(K)
    expect(counters.characterPrepares - before).toBe(0)
  })

  it('the shared budget counts a yaw result held by several keys once (distinct objects; consistent bookkeeping)', () => {
    const e = openRecords(sample())
    for (const y of [0, 10, 20, 30, 40, 50, 60]) e.derived.atYaw(y)
    const b = e.derived.yawRetainedItems
    expect(b.used).toBe(b.retainedObjects().size)
    expect(b.consistent()).toBe(true)
  })

  it('a new expression keyframe replaces an imported one with the same meaning (curve, parameter, yaw), whatever its id; two such records are refused on open', () => {
    const rs = eyePlain(sample())
    const now = play(ok(prep(rs)), 90, 1).shapes['curve:lid']
    rs.find((x) => x.id === K).exprFixes = [{ id: 'exprFix:imported', curveId: 'curve:lid', param: 'blink', yaw: 90, shape: now }]
    const e = openRecords(rs)
    const shape = { ...now, m: { p: { x: now.m.p.x, y: now.m.p.y - 2 }, hIn: { x: now.m.hIn.x, y: now.m.hIn.y - 2 }, hOut: { x: now.m.hOut.x, y: now.m.hOut.y - 2 } } }
    const r = e.apply({ type: 'fixExpression', character: K as any, param: 'blink', yaw: 90, keyframes: { 'curve:lid': shape } })
    expect(r.ok && r.written, JSON.stringify(r)).toBe(true)
    const fixes = (e.reader.get(K as any) as any).exprFixes
    expect(fixes.map((x: any) => x.id)).toEqual(['exprFix:imported']) // replaced, id kept
    const p = e.derived.character(K)
    if (!p.ok) throw new Error(p.problems.join())
    const got = playCharacter(p.grid, { yaw: 90, params: { blink: 1 } })
    expect(got.ok && Math.abs((got as any).shapes['curve:lid'].m.p.y - shape.m.p.y)).toBeLessThan(1e-12)
    const dup = structuredClone(rs)
    const kd = dup.find((x) => x.id === K)
    kd.exprFixes.push({ ...structuredClone(kd.exprFixes[0]), id: 'exprFix:other' })
    expect(() => openRecords(dup)).toThrow(/fix the same state .*ambiguous/)
  })

  it('clearing the line a node takeover names as basisFrom is allowed: the node is untouched (copied L, provenance kept); reopen works', () => {
    const e = openRecords(sample())
    const node = () => (e.reader.get(K as any) as any).takeovers.find((t: any) => t.kind === 'node')
    const L = [...node().L]
    const r = e.apply({ type: 'clearFix', character: K as any, id: 'takeover:lid@90' })
    expect(r.ok && r.written, JSON.stringify(r)).toBe(true)
    expect(node().L).toEqual(L)
    expect(node().basisFrom).toBe('takeover:lid@90') // provenance kept as written (history only)
    expect(() => Editor.open(JSON.parse(JSON.stringify(e.save())))).not.toThrow()
    expect(e.derived.character(K).ok).toBe(true)
  })

  it('createCurve in preset author mode is allowed and names the characters that now miss the curve (prepare reports it)', () => {
    const e = openRecords(sample())
    const r = e.apply({ type: 'createCurve', id: 'curve:brow' as any, parentId: 'container:L1' as any, preset: 'preset:P' as any,
      anchors: { p: { id: 'p', p: { x: 0, y: 0 }, hIn: { x: 0, y: 0 }, hOut: { x: 1, y: 0 } }, q: { id: 'q', p: { x: 9, y: 0 }, hIn: { x: -1, y: 0 }, hOut: { x: 0, y: 0 } } }, segments: [{ id: 'k1', from: 'p', to: 'q' }] })
    expect(r.ok && r.written).toBe(true)
    expect(r.ok && (r as any).notices?.join()).toMatch(/character:K cannot be prepared until: preset:Q \(weight 0.4\) has no shape for curve:brow/)
    const p = e.derived.character(K)
    expect(p.ok).toBe(false) // missing is reported, never faked
  })
})
