import {describe,it,expect} from 'vitest';
import {emptyDrawing,type DrawingDocument} from '../../domain/drawing/model';
import {moveWarpNode} from '../../domain/vectorWarp/model';
import {createArtworkRig,addDeformer,currentPose,evaluatePose,saveKeyform,setRigAngle,discardDraft,setDeformerParent,deformerChain,emptyVectorRecording,replaceRig,applyVisibility} from '../../domain/vectorRecording/model';
import {parseVectorRecording} from '../../domain/vectorRecording/persistence';
const source=():DrawingDocument=>({...emptyDrawing(),nodes:[{id:'n0',position:[0,0]},{id:'n1',position:[1,1]}],curves:[{id:'c',name:'Curve',nodes:['n0','n1'],handles:[[.3,.3],[.7,.7]],visible:true,locked:false,width:.01}],layers:[{id:'l',name:'Layer',items:['c'],visible:true,locked:false}]});
function rig(){return addDeformer(createArtworkRig('front'),source(),['l'],undefined,2,2);}
function translate(r:ReturnType<typeof rig>,dx:number,dy=0){const p=currentPose(r),id=r.deformers[0].id,g=p.grids[id];let n=g;for(let i=0;i<g.nodes.length;i++)n=moveWarpNode(n,i,[g.nodes[i].position[0]+dx,g.nodes[i].position[1]+dy]);return {...r,draft:{...p,grids:{...p.grids,[id]:n}}};}
describe('artwork-owned vector keyforms',()=>{
 it('initializes neutral and four directional keys without copying source geometry',()=>{const r=rig();expect(r.keys.map(k=>k.angle)).toEqual([{x:0,y:0},{x:-90,y:0},{x:90,y:0},{x:0,y:90},{x:0,y:-90}]);expect(JSON.stringify(r)).not.toContain('"curves"');expect(r.bindings.l).toBe(r.deformers[0].id);});
 it('interpolates exact cardinal and intermediate keys linearly',()=>{let r=rig();r=saveKeyform(translate(setRigAngle(r,{x:90,y:0}),.9));const id=r.deformers[0].id,base=r.deformers[0].grid.nodes[0].position;expect(evaluatePose(r,{x:45,y:0}).grids[id].nodes[0].position[0]).toBeCloseTo(base[0]+.45,10);expect(evaluatePose(r,{x:90,y:0}).grids[id].nodes[0].position[0]).toBeCloseTo(base[0]+.9,10);});
 it('combines axis deltas and honors explicit corrective lattice keys',()=>{let r=rig();r=saveKeyform(translate(setRigAngle(r,{x:90,y:0}),.9));r=saveKeyform(translate(setRigAngle(r,{x:0,y:90}),0,.9));const id=r.deformers[0].id,base=r.deformers[0].grid.nodes[0].position;expect(evaluatePose(r,{x:45,y:45}).grids[id].nodes[0].position).toEqual([expect.closeTo(base[0]+.45),expect.closeTo(base[1]+.45)]);r=setRigAngle(r,{x:45,y:45});r=saveKeyform(translate(r,.2));expect(evaluatePose(r,{x:45,y:45}).grids[id].nodes[0].position[0]).toBeCloseTo(base[0]+.65);});
 it('prevents navigation from silently dropping a draft and persists it separately',()=>{let r=translate(rig(),.1);expect(()=>setRigAngle(r,{x:30,y:0})).toThrow();const doc=parseVectorRecording({...emptyVectorRecording(),rigs:[r]});expect(doc.rigs[0].draft).toEqual(r.draft);expect(setRigAngle(discardDraft(r),{x:100,y:-100}).angle).toEqual({x:90,y:-90});});
 it('composes nested grids child-to-parent and rejects cycles',()=>{let r=rig();const parent=r.deformers[0].id;r=addDeformer(r,source(),['l'],parent,2,2);const child=r.deformers[1].id;expect(deformerChain(r,'l',currentPose(r))).toEqual([r.deformers[1].grid,r.deformers[0].grid]);expect(()=>setDeformerParent(r,parent,child)).toThrow();});
 it('applies visibility without mutating source items or interval definitions',()=>{const d=source(),json=JSON.stringify(d),p=currentPose(rig());p.visibility={c:false};const result=applyVisibility(d,p);expect(result.curves[0].visible).toBe(false);expect(JSON.stringify(d)).toBe(json);});
 it('rejects malformed, cyclic and incompatible key grid payloads',()=>{const r=rig(),v={...emptyVectorRecording(),rigs:[r]};const bad=structuredClone(v);bad.rigs[0].keys[0].grids[r.deformers[0].id]=structuredClone(bad.rigs[0].keys[0].grids[r.deformers[0].id]);bad.rigs[0].keys[0].grids[r.deformers[0].id].bounds.max[0]+=1;expect(()=>parseVectorRecording(bad)).toThrow();const cycle=structuredClone(v);cycle.rigs[0].deformers[0].parentId=cycle.rigs[0].deformers[0].id;expect(()=>parseVectorRecording(cycle)).toThrow();});
});
