import {editorHistoryTarget} from './editorHistory';
import {ensureRecordingSnapshots} from '../domain/recordingSnapshot/migration';
import ArtworkCleanupDialog from '../ui/artworkCleanup/ArtworkCleanupDialog';
import {loadSceneExample,planSceneExampleImport} from './sceneExamples';
import {loadPerspectiveCandidates,planPerspectiveCandidateImport,PERSPECTIVE_CANDIDATE_SCENE_IDS} from './perspectiveCandidates';
import WorkspaceViewPanel from '../ui/workspaceView/WorkspaceViewPanel';
import {applyWorkspaceView} from './workspaceView';
import {loadArtworkExamplePack,planArtworkExamplePack,sourceForExampleImport} from './artworkExamples';
import {subscribeStorageStatus,getStorageStatus} from './projectStorage';
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {Box,Download,Upload,Undo2,Redo2,Code2} from 'lucide-react';
import {useEditor} from './store';
import {useWorkspaceMode} from './workspaceMode';
import {useLanguage} from '../ui/i18n';
import {useDrawing} from '../ui/drawing/session';
import DrawingRoom from '../ui/drawing/DrawingRoom';
import RecordingWorkspace from '../ui/vectorRecording/RecordingWorkspace';
import {serializeProject} from './autosave';
import {parseLandmarks} from '../domain/landmarks/persistence';
import {loadStarterProject,finishProjectStartup} from './starterProject';
import {APP_VERSION} from './version';
import '../ui/vectorRecording/vectorRecording.css';

/** One vector document workspace. Retired modeling/recording/assembly payloads
 * stay in the project, but are never mounted as competing authoring rooms. */
export default function App(){
 const [cleanupOpen,setCleanupOpen]=useState(false);
 const storage=useSyncExternalStore(subscribeStorageStatus,getStorageStatus,getStorageStatus);
 const s=useEditor(),{mode,setMode}=useWorkspaceMode(),{language,setLanguage}=useLanguage(),zh=language==='zh',text=(cn:string,en:string)=>zh?cn:en;
 const openRequest=useRef(0),file=useRef<HTMLInputElement>(null),apiDialog=useRef<HTMLDialogElement>(null),[viewPanel,setViewPanel]=useState(false),[aiGuides,setAIGuides]=useState(false),[loading,setLoading]=useState(false),[apiInput,setApiInput]=useState('{"commands":[]}'),[apiResult,setApiResult]=useState(''),[apiPreview,setApiPreview]=useState('');
 useEffect(()=>{document.documentElement.lang=zh?'zh-CN':'en';},[zh]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!(e.ctrlKey||e.metaKey)||e.key.toLowerCase()!=='z')return;const target=e.target as HTMLElement;if(target.closest('input,textarea,[role="dialog"],[data-ui-keyboard],[contenteditable]'))return;e.preventDefault();const s=useEditor.getState();e.shiftKey?s.redo():s.undo();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{if(!s.message)return;const timer=setTimeout(()=>useEditor.getState().notify(''),6500);return()=>clearTimeout(timer);},[s.message]);
 const save=()=>{const url=URL.createObjectURL(new Blob([serializeProject(s.project)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=s.project.meta.name+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const loadStarter=async()=>{const request=++openRequest.current,before=s.project;setLoading(true);try{const p=await loadStarterProject();if(request!==openRequest.current)return;if(useEditor.getState().project!==before){s.notify(text('载入期间工程已变更，请重试。','The project changed while loading. Please retry.'));return;}setMode('drawing');s.load(p);s.endEdit();finishProjectStartup();useDrawing.getState().set({room:true,selection:{ids:[]},layerId:null,tool:'select',zoom:1,pan:[0,0]});s.notify(text('基础脸模已载入，可撤销恢复原工程。','Starter face loaded. Undo restores the previous project.'));}catch(e){s.notify((e as Error).message);}finally{if(request===openRequest.current)setLoading(false);}};

 const importExample=async()=>{const request=++openRequest.current,before=useEditor.getState().project;setLoading(true);try{const pack=await loadArtworkExamplePack();if(request!==openRequest.current)return;if(useEditor.getState().project!==before){s.notify(text('载入期间工程已变更，请重试。','The project changed during import. Please retry.'));return;}const plan=planArtworkExamplePack({drawing:sourceForExampleImport(before.drawing,!!before.vectorRecording?.rigs.some(r=>r.artworkId==='$working')),drawingSnapshots:before.drawingSnapshots,drawingWorkingCopies:before.drawingWorkingCopies},pack);setMode('drawing');const editor=useEditor.getState();editor.beginEdit();try{for(const step of plan.steps)editor.setDrawingSnapshotState(step);}finally{editor.endEdit();}useDrawing.getState().set({room:true,selection:{ids:[]},layerId:null,tool:'select',zoom:1,pan:[0,0]});s.notify(text(plan.preservedDraftId?'已导入镜像正面和90°侧参考；原未保存修改已另存，可撤销。':'已新增镜像正面和90°侧参考；原画稿保留，可撤销。',plan.preservedDraftId?'Imported mirrored front and90° side-reference artworks. Unsaved work was saved as a copy; undoable.':'Added mirrored front and90° side-reference artworks. Existing work is preserved; undoable.'));}catch(e){if(request===openRequest.current)s.notify((e as Error).message);}finally{if(request===openRequest.current)setLoading(false);}};
 const importSceneExample=async()=>{const request=++openRequest.current,before=useEditor.getState().project;setLoading(true);try{const example=await loadSceneExample();if(request!==openRequest.current)return;if(useEditor.getState().project!==before){s.notify(text('载入期间工程已变更，请重试。','The project changed during import. Please retry.'));return;}const plan=planSceneExampleImport({drawing:before.drawing,drawingSnapshots:before.drawingSnapshots,drawingWorkingCopies:before.drawingWorkingCopies},example,before.recordingScenes,before.vectorRecording,{excludeSceneIds:Object.values(PERSPECTIVE_CANDIDATE_SCENE_IDS)});setMode('drawing');const editor=useEditor.getState();editor.beginEdit();try{for(const step of plan.steps)editor.setDrawingSnapshotState(step);const current=useEditor.getState().project.recordingScenes??{version:1 as const,scenes:[]};editor.setRecordingScenes({...current,activeSceneId:plan.scene.id,scenes:current.scenes.some(scene=>scene.id===plan.scene.id)?current.scenes:[...current.scenes,plan.scene]});}finally{editor.endEdit();}useDrawing.getState().set({room:true,selection:{ids:[]},layerId:null,tool:'select',zoom:1,pan:[0,0],showFills:false});setMode('recording');s.notify('reused' in plan&&plan.reused?text('已打开现有组装场景，保留当前关键形和草稿。','Opened the existing assembly scene, preserving its keys and drafts.'):text('已建立正面＋90°侧稿的组装场景。蓝绿共享 Warp，侧稿内红片独立 Warp；0°收线与90°压缩尚未制作。','Created an assembly scene from the front and 90° profile artworks. Blue/green share one Warp; the profile recording layer has another. Collapse at 0 and compression at 90 are unfinished.'));}catch(e){if(request===openRequest.current)s.notify((e as Error).message);}finally{if(request===openRequest.current)setLoading(false);}};


 const importPerspectiveCandidates=async()=>{
  const request=++openRequest.current,before=useEditor.getState().project;setLoading(true);
  try{
   const candidates=await loadPerspectiveCandidates();if(request!==openRequest.current)return;
   if(useEditor.getState().project!==before){s.notify(text('载入期间工程已变更，请重试。','The project changed during import. Please retry.'));return;}
   const plan=planPerspectiveCandidateImport({drawing:before.drawing,drawingSnapshots:before.drawingSnapshots,drawingWorkingCopies:before.drawingWorkingCopies},candidates,before.recordingScenes,before.vectorRecording);
   setMode('drawing');const editor=useEditor.getState();editor.beginEdit();
   try{
    for(const step of plan.steps)editor.setDrawingSnapshotState(step);
    const current=useEditor.getState().project.recordingScenes??{version:1 as const,scenes:[]},updates=new Map(plan.scenes.map(scene=>[scene.id,scene]));
    editor.setRecordingScenes({...current,activeSceneId:plan.activeSceneId,scenes:[...current.scenes.map(scene=>updates.get(scene.id)??scene),...plan.scenes.filter(scene=>!current.scenes.some(existing=>existing.id===scene.id))]});
   }finally{editor.endEdit();}
   useDrawing.getState().set({room:true,selection:{ids:[]},layerId:null,tool:'select',zoom:1,pan:[0,0],showFills:false,fillVisibility:{}});setMode('recording');
   s.notify(text('已打开90°候选 B；左侧场景列表可切换 B/C。仅为端点候选，原起步场景保留。初始拟合误差 B 2.924px、C 7.856px，红色超差提示保留。','Opened candidate B at 90°. Switch B/C in the scene list. Endpoint candidates only; the starter scene is retained. Initial fit error: B 2.924px, C 7.856px; warnings remain visible.'));
  }catch(error){if(request===openRequest.current)s.notify((error as Error).message);}finally{if(request===openRequest.current)setLoading(false);}
 };
 const perspectiveCandidate=mode==='recording'&&Object.values(PERSPECTIVE_CANDIDATE_SCENE_IDS).some(id=>id===s.project.recordingScenes?.activeSceneId);

 async function runApi(action:'inspect'|'dryRun'|'execute'|'exportSource'){
  try{const api=(window as unknown as {contourAI?:Record<string,Function>}).contourAI;if(!api)throw Error(text('结构化接口尚未准备好','Structured API is not ready'));
   let method:string,request:Record<string,unknown>;
   if(action==='inspect'){method=mode==='recording'?(s.project.recordingSnapshots?'inspectSnapshots':'inspectScene'):'inspect';request=mode==='recording'?{}:{includeRecording:false};}
   else if(action==='exportSource'){method='exportSource';request={};}
   else{const input=JSON.parse(apiInput);if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Expected a JSON object');
    if(Object.hasOwn(input,'method')){if(!['inspect','preview','artwork','inspectArtworks','inspectRecording','recording','previewRecording','inspectView','view','snapView','select','previewRecordingFrames','inspectScene','scene','previewScene','previewSceneFrames','inspectSnapshots','snapshot','previewSnapshot','previewSnapshotFrames'].includes(input.method)||Object.keys(input).some(k=>k!=='method'&&k!=='request'))throw Error('Unsupported console method');method=input.method;request=input.request??{};if(!request||typeof request!=='object'||Array.isArray(request))throw Error('Expected a request object');}
    else{method='execute';request=input;}
    if(action==='dryRun'&&(method==='execute'||method==='artwork'||method==='recording'||method==='scene'||method==='snapshot'||method==='view'))request={...request,dryRun:true};
   }
   if(typeof api[method]!=='function')throw Error(text('此接口尚未准备好','This API method is not available yet'));
   const value=await api[method](request);setApiResult(JSON.stringify(value,null,2));setApiPreview((method==='preview'||method==='previewRecording'||method==='previewScene'||method==='previewSnapshot')&&value?.ok&&typeof value.value?.svg==='string'?value.value.svg:'');
  }catch(e){setApiResult((e as Error).message);setApiPreview('');}
 }

 return <div className="contour-workspace">
  <header className="topbar"><div className="brand"><Box size={23}/>contour<span className="point-version">{APP_VERSION}</span></div><input className="point-name" aria-label={text('项目名称','Project name')} value={s.project.meta.name} onChange={e=>s.rename(e.target.value)}/><span className={`contour-save-status ${storage.state}`} role="status" data-testid="durable-save-status" title={storage.error??storage.backend}>{storage.state==='saving'?text('保存中…','Saving…'):storage.state==='saved'?text('已自动保存','Autosaved'):storage.state==='error'?text('自动保存失败 · 请导出','Autosave failed · Export JSON'):text('本地存储','Local storage')}</span><div className="point-top-actions">
   <button title={[text('撤销 Ctrl Z','Undo Ctrl Z'),editorHistoryTarget(s.historyPast.at(-1),'undo',zh)].filter(Boolean).join(' · ')} aria-label={text('撤销','Undo')} disabled={!s.past.length} onClick={s.undo}><Undo2 size={17}/></button><button title={[text('重做 Ctrl Shift Z','Redo Ctrl Shift Z'),editorHistoryTarget(s.historyFuture[0],'redo',zh)].filter(Boolean).join(' · ')} aria-label={text('重做','Redo')} disabled={!s.future.length} onClick={s.redo}><Redo2 size={17}/></button>
   <button onClick={()=>file.current?.click()}><Upload size={15}/>{text('打开','Open')}</button><button data-testid="load-starter" disabled={loading} onClick={()=>void loadStarter()}>{text(loading?'载入中…':'载入基础脸模',loading?'Loading…':'Starter face')}</button><details data-ui-keyboard className="contour-example-menu" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))e.currentTarget.open=false;}} onKeyDown={e=>{e.stopPropagation();if(e.key==='Escape')e.currentTarget.open=false;}}><summary aria-label={text('载入示例','Load example')}>{text('载入示例','Examples')}</summary><div className="contour-example-options"><button data-testid="load-hairless-example" disabled={loading} onClick={e=>{e.currentTarget.closest('details')!.open=false;void importExample();}}>{text('镜像正面 + 90°侧参考','Mirrored front + side reference')}</button><button data-testid="load-scene-example" disabled={loading} onClick={e=>{e.currentTarget.closest('details')!.open=false;void importSceneExample();}}>{text('组装场景 · 正面＋90°侧稿（起步）','Assembly scene · front + 90° profile (starter)')}</button><button data-testid="load-perspective-candidates" disabled={loading} onClick={e=>{e.currentTarget.closest('details')!.open=false;void importPerspectiveCandidates();}}>{text('90°形变候选（B/C对比）','90° deformation candidates (B/C)')}</button><small>{text('仅90°端点候选；0°收线及中间角尚未制作','90° endpoint candidates only; collapse at 0° and intermediate poses are unfinished')}</small><small>{text('现有组装场景会复用；新增操作可撤销','Existing assembly scenes are reused; additions are undoable')}</small></div></details><button data-testid="organize-artwork-library" onClick={()=>{useEditor.getState().endEdit();setCleanupOpen(true);}}>{text('整理画稿库','Organize artworks')}</button><button onClick={save}><Download size={15}/>{text('保存 JSON','Save JSON')}</button><button data-testid="ai-editing-console" title={text('结构化编辑接口','Structured editing interface')} onClick={()=>{if(!apiDialog.current?.open)apiDialog.current?.show();void runApi('inspect');}}><Code2 size={16}/>{text('AI 编辑','AI editing')}</button><button data-testid="language-toggle" onClick={()=>setLanguage(zh?'en':'zh')}>{zh?'English':'中文'}</button>
  </div><input ref={file} type="file" hidden accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;const request=++openRequest.current,before=useEditor.getState().project;setLoading(true);try{const raw=await f.text(),p=ensureRecordingSnapshots(parseLandmarks(raw),raw);if(request!==openRequest.current)return;if(useEditor.getState().project!==before){s.notify(text('载入期间工程已变更，请重新打开文件。','The project changed during import. Please open the file again.'));return;}setMode('drawing');s.load(p);s.endEdit();useDrawing.getState().set({room:true,tool:'select',selection:{ids:[]},layerId:null});}catch(error){if(request===openRequest.current)s.notify((error as Error).message);}finally{if(request===openRequest.current)setLoading(false);}}}/></header>
  <nav className="contour-modebar" aria-label={text('工作模式','Workspace mode')}><div className="mode-tabs"><button data-testid="drawing-mode" aria-pressed={mode==='drawing'} onClick={()=>setMode('drawing')}>{text('绘制模式','Drawing')}</button><button data-testid="recording-mode" aria-pressed={mode==='recording'} onClick={()=>setMode('recording')}>{text('录制模式','Recording')}</button></div><span>{perspectiveCandidate?text('仅90°端点候选 · 在左侧切换 B/C · 0°收线及中间角未制作','90° endpoint candidates only · Switch B/C on the left · 0° collapse and intermediate poses unfinished'):mode==='drawing'?text('钢笔 · 图层 · 独立画稿库 · 源线条编辑','Pen · Layers · Independent artwork library · Source geometry'):text('视角快照 · 来源图层引用 · 独立形变与关系','View snapshots · Source layer references · Independent deformation and relations')}</span>{mode==='drawing'&&<button data-testid="view-aids-toggle" aria-pressed={viewPanel} onClick={()=>{setViewPanel(!viewPanel);if(!viewPanel)applyWorkspaceView([{op:'setGuideOptions',rulers:true}]);}}>{text('参考 / 辅助线','Reference / Guides')}</button>}<button data-testid="ai-guides-toggle" aria-pressed={aiGuides} onClick={()=>setAIGuides(!aiGuides)}>{text('AI 辅助视图','AI visual guides')}</button></nav>
  {mode==='drawing'?<DrawingRoom aiGuides={aiGuides}/>:<RecordingWorkspace aiGuides={aiGuides}/>}
  {cleanupOpen&&<ArtworkCleanupDialog close={()=>setCleanupOpen(false)}/>}
  {viewPanel&&mode==='drawing'&&<WorkspaceViewPanel close={()=>setViewPanel(false)}/>}
  {s.message&&<div className="contour-toast" role="status">{s.message}</div>}
  <dialog role="dialog" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();apiDialog.current?.close();}}} ref={apiDialog} className="contour-api-dialog" aria-label={text('AI 结构化编辑','AI structured editing')}><h2>{text('结构化矢量编辑','Structured vector editing')}</h2><p>{text('window.contourAI 提供可检查的源 ID、坐标、事务化命令与预演。源稿与录制写入共享编辑器校验、模式限制和撤销；view 仅修改临时视图，不进入源稿撤销。不会访问外部服务或上传画稿。像素图自动匹配尚未实现。','window.contourAI exposes inspectable source IDs, coordinates, atomic commands and dry runs. Source and rig writes share validation, mode restrictions and undo. View commands change transient aids outside source history. No external requests or artwork uploads. Automatic raster matching is not implemented.')}</p><textarea aria-label="AI command JSON" value={apiInput} onChange={e=>setApiInput(e.target.value)} spellCheck={false}/><footer><button onClick={()=>void runApi('inspect')}>{text('检查源稿','Inspect source')}</button><button data-testid="ai-export-source" onClick={()=>void runApi('exportSource')}>{text('导出源稿 JSON','Export source JSON')}</button><button onClick={()=>void runApi('dryRun')}>{text('预演命令','Dry run')}</button><button onClick={()=>void runApi('execute')}>{text('执行','Apply')}</button><button onClick={()=>apiDialog.current?.close()}>{text('关闭','Close')}</button></footer><p className="contour-api-help">{text('支持 commands 源稿批次，或 inspect / preview / artwork / inspectArtworks / inspectRecording / recording / previewRecording / inspectView / view / snapView / select / previewRecordingFrames / inspectScene / scene / previewScene / previewSceneFrames 请求。v2 使用 inspectSnapshots / snapshot / previewSnapshot；旧 scene/recording 接口只保留兼容数据。','Use source command batches or inspect / preview / artwork / inspectArtworks / inspectRecording / recording / previewRecording / inspectView / view / snapView / select / previewRecordingFrames / inspectScene / scene / previewScene / previewSceneFrames requests. Use snapshot methods for v2 recordings; scene methods are retained for legacy files. Migrated projects retire legacy recording methods.')}</p>{apiPreview&&<img className="contour-api-preview" alt={text('矢量预览','Vector preview')} src={'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(apiPreview)}/>}<pre data-testid="ai-api-result">{apiResult}</pre></dialog>
 </div>;
}
