import WorkspaceViewPanel from '../ui/workspaceView/WorkspaceViewPanel';
import {applyWorkspaceView} from './workspaceView';
import {HAIRLESS_EXAMPLE_NAME,loadHairlessExample,planArtworkImport,sourceForExampleImport} from './artworkExamples';
import {subscribeStorageStatus,getStorageStatus} from './projectStorage';
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {Box,Download,Upload,Undo2,Redo2,Code2} from 'lucide-react';
import {useEditor} from './store';
import {useWorkspaceMode} from './workspaceMode';
import {useLanguage} from '../ui/i18n';
import {useDrawing} from '../ui/drawing/session';
import DrawingRoom from '../ui/drawing/DrawingRoom';
import RecordingWorkspace from '../ui/vectorRecording/RecordingWorkspace';
import {serializeProject} from './autosave';
import {parseLandmarks} from '../domain/landmarks/persistence';
import {loadStarterProject,finishProjectStartup} from './starterProject';
import {APP_VERSION} from './version';
import '../ui/vectorRecording/vectorRecording.css';

/** One vector document workspace. Retired modeling/recording/assembly payloads
 * stay in the project, but are never mounted as competing authoring rooms. */
export default function App(){
 const storage=useSyncExternalStore(subscribeStorageStatus,getStorageStatus,getStorageStatus);
 const s=useEditor(),{mode,setMode}=useWorkspaceMode(),{language,setLanguage}=useLanguage(),zh=language==='zh',text=(cn:string,en:string)=>zh?cn:en;
 const openRequest=useRef(0),file=useRef<HTMLInputElement>(null),apiDialog=useRef<HTMLDialogElement>(null),[viewPanel,setViewPanel]=useState(false),[aiGuides,setAIGuides]=useState(false),[loading,setLoading]=useState(false),[apiInput,setApiInput]=useState('{"commands":[]}'),[apiResult,setApiResult]=useState(''),[apiPreview,setApiPreview]=useState('');
 useEffect(()=>{document.documentElement.lang=zh?'zh-CN':'en';},[zh]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!(e.ctrlKey||e.metaKey)||e.key.toLowerCase()!=='z')return;const target=e.target as HTMLElement;if(target.closest('input,textarea,[role="dialog"],[data-ui-keyboard],[contenteditable]'))return;e.preventDefault();const s=useEditor.getState();e.shiftKey?s.redo():s.undo();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{if(!s.message)return;const timer=setTimeout(()=>useEditor.getState().notify(''),6500);return()=>clearTimeout(timer);},[s.message]);
 const save=()=>{const url=URL.createObjectURL(new Blob([serializeProject(s.project)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=s.project.meta.name+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const loadStarter=async()=>{const request=++openRequest.current,before=s.project;setLoading(true);try{const p=await loadStarterProject();if(request!==openRequest.current)return;if(useEditor.getState().project!==before){s.notify(text('载入期间工程已变更，请重试。','The project changed while loading. Please retry.'));return;}setMode('drawing');s.load(p);s.endEdit();finishProjectStartup();useDrawing.getState().set({room:true,selection:{ids:[]},layerId:null,tool:'select',zoom:1,pan:[0,0]});s.notify(text('基础脸模已载入，可撤销恢复原工程。','Starter face loaded. Undo restores the previous project.'));}catch(e){s.notify((e as Error).message);}finally{setLoading(false);}};
 const importExample=async()=>{const request=++openRequest.current,before=useEditor.getState().project;setLoading(true);try{const drawing=await loadHairlessExample();if(request!==openRequest.current)return;if(useEditor.getState().project!==before){s.notify(text('载入期间工程已变更，请重试。','The project changed during import. Please retry.'));return;}const plan=planArtworkImport({drawing:sourceForExampleImport(before.drawing,!!before.vectorRecording?.rigs.some(r=>r.artworkId==='$working')),drawingSnapshots:before.drawingSnapshots},drawing,HAIRLESS_EXAMPLE_NAME);setMode('drawing');const editor=useEditor.getState();editor.beginEdit();try{for(const step of plan.steps)editor.setDrawingSnapshotState(step);}finally{editor.endEdit();}useDrawing.getState().set({room:true,selection:{ids:[]},layerId:null,tool:'select',zoom:1,pan:[0,0]});s.notify(text(plan.preservedDraftId?'已导入对称双脸片；原未保存修改已另存，可撤销。':'已新增对称双脸片示例；原画稿保留，可撤销。',plan.preservedDraftId?'Imported the symmetric two-face-piece example. Unsaved work was saved as a copy; the import is undoable.':'Added the symmetric two-face-piece example. Existing artworks are preserved; the import is undoable.'));}catch(e){if(request===openRequest.current)s.notify((e as Error).message);}finally{setLoading(false);}};
 async function runApi(action:'inspect'|'dryRun'|'execute'|'exportSource'){
  try{const api=(window as unknown as {contourAI?:Record<string,Function>}).contourAI;if(!api)throw Error(text('结构化接口尚未准备好','Structured API is not ready'));
   let method:string,request:Record<string,unknown>;
   if(action==='inspect'){method='inspect';request={includeRecording:false};}
   else if(action==='exportSource'){method='exportSource';request={};}
   else{const input=JSON.parse(apiInput);if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Expected a JSON object');
    if(Object.hasOwn(input,'method')){if(!['inspect','preview','artwork','inspectArtworks','inspectRecording','recording','previewRecording','inspectView','view','snapView'].includes(input.method)||Object.keys(input).some(k=>k!=='method'&&k!=='request'))throw Error('Unsupported console method');method=input.method;request=input.request??{};if(!request||typeof request!=='object'||Array.isArray(request))throw Error('Expected a request object');}
    else{method='execute';request=input;}
    if(action==='dryRun'&&(method==='execute'||method==='artwork'||method==='recording'||method==='view'))request={...request,dryRun:true};
   }
   if(typeof api[method]!=='function')throw Error(text('此接口尚未准备好','This API method is not available yet'));
   const value=await api[method](request);setApiResult(JSON.stringify(value,null,2));setApiPreview((method==='preview'||method==='previewRecording')&&value?.ok&&typeof value.value?.svg==='string'?value.value.svg:'');
  }catch(e){setApiResult((e as Error).message);setApiPreview('');}
 }

 return <div className="contour-workspace">
  <header className="topbar"><div className="brand"><Box size={23}/>contour<span className="point-version">{APP_VERSION}</span></div><input className="point-name" aria-label={text('项目名称','Project name')} value={s.project.meta.name} onChange={e=>s.rename(e.target.value)}/><span className={`contour-save-status ${storage.state}`} role="status" data-testid="durable-save-status" title={storage.error??storage.backend}>{storage.state==='saving'?text('保存中…','Saving…'):storage.state==='saved'?text('已自动保存','Autosaved'):storage.state==='error'?text('自动保存失败 · 请导出','Autosave failed · Export JSON'):text('本地存储','Local storage')}</span><div className="point-top-actions">
   <button title={text('撤销 Ctrl Z','Undo Ctrl Z')} aria-label={text('撤销','Undo')} disabled={!s.past.length} onClick={s.undo}><Undo2 size={17}/></button><button title={text('重做 Ctrl Shift Z','Redo Ctrl Shift Z')} aria-label={text('重做','Redo')} disabled={!s.future.length} onClick={s.redo}><Redo2 size={17}/></button>
   <button onClick={()=>file.current?.click()}><Upload size={15}/>{text('打开','Open')}</button><button data-testid="load-starter" disabled={loading} onClick={()=>void loadStarter()}>{text(loading?'载入中…':'载入基础脸模',loading?'Loading…':'Starter face')}</button><button data-testid="load-hairless-example" title={text('载入“无发·对称双脸片”；当前修改会另存，整步可撤销。','Load the symmetric two-face-piece example; preserve unsaved work. Undoable.')} disabled={loading} onClick={()=>void importExample()}>{text('载入示例','Example')}</button><button onClick={save}><Download size={15}/>{text('保存 JSON','Save JSON')}</button><button data-testid="ai-editing-console" title={text('结构化编辑接口','Structured editing interface')} onClick={()=>{if(!apiDialog.current?.open)apiDialog.current?.show();void runApi('inspect');}}><Code2 size={16}/>{text('AI 编辑','AI editing')}</button><button data-testid="language-toggle" onClick={()=>setLanguage(zh?'en':'zh')}>{zh?'English':'中文'}</button>
  </div><input ref={file} type="file" hidden accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;const request=++openRequest.current,before=useEditor.getState().project;try{const p=parseLandmarks(await f.text());if(request!==openRequest.current)return;if(useEditor.getState().project!==before){s.notify(text('载入期间工程已变更，请重新打开文件。','The project changed during import. Please open the file again.'));return;}setMode('drawing');s.load(p);s.endEdit();useDrawing.getState().set({room:true,tool:'select',selection:{ids:[]},layerId:null});}catch(error){s.notify((error as Error).message);}}}/></header>
  <nav className="contour-modebar" aria-label={text('工作模式','Workspace mode')}><div className="mode-tabs"><button data-testid="drawing-mode" aria-pressed={mode==='drawing'} onClick={()=>setMode('drawing')}>{text('绘制模式','Drawing')}</button><button data-testid="recording-mode" aria-pressed={mode==='recording'} onClick={()=>setMode('recording')}>{text('录制模式','Recording')}</button></div><span>{mode==='drawing'?text('钢笔 · 图层 · 独立画稿库 · 源线条编辑','Pen · Layers · Independent artwork library · Source geometry'):text('Angle X / Y · Bézier Warp · 关键形 · 源线条锁定','Angle X / Y · Bézier Warp · Keyforms · Source locked')}</span><button data-testid="view-aids-toggle" aria-pressed={viewPanel} onClick={()=>{setViewPanel(!viewPanel);if(!viewPanel)applyWorkspaceView([{op:'setGuideOptions',rulers:true}]);}}>{text('参考 / 辅助线','Reference / Guides')}</button><button data-testid="ai-guides-toggle" aria-pressed={aiGuides} onClick={()=>setAIGuides(!aiGuides)}>{text('AI 辅助视图','AI visual guides')}</button></nav>
  {mode==='drawing'?<DrawingRoom aiGuides={aiGuides}/>:<RecordingWorkspace aiGuides={aiGuides}/>}
  {viewPanel&&<WorkspaceViewPanel close={()=>setViewPanel(false)}/>}
  {s.message&&<div className="contour-toast" role="status">{s.message}</div>}
  <dialog role="dialog" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();apiDialog.current?.close();}}} ref={apiDialog} className="contour-api-dialog" aria-label={text('AI 结构化编辑','AI structured editing')}><h2>{text('结构化矢量编辑','Structured vector editing')}</h2><p>{text('window.contourAI 提供可检查的源 ID、坐标、事务化命令与预演。源稿与录制写入共享编辑器校验、模式限制和撤销；view 仅修改临时视图，不进入源稿撤销。不会访问外部服务或上传画稿。像素图自动匹配尚未实现。','window.contourAI exposes inspectable source IDs, coordinates, atomic commands and dry runs. Source and rig writes share validation, mode restrictions and undo. View commands change transient aids outside source history. No external requests or artwork uploads. Automatic raster matching is not implemented.')}</p><textarea aria-label="AI command JSON" value={apiInput} onChange={e=>setApiInput(e.target.value)} spellCheck={false}/><footer><button onClick={()=>void runApi('inspect')}>{text('检查源稿','Inspect source')}</button><button data-testid="ai-export-source" onClick={()=>void runApi('exportSource')}>{text('导出源稿 JSON','Export source JSON')}</button><button onClick={()=>void runApi('dryRun')}>{text('预演命令','Dry run')}</button><button onClick={()=>void runApi('execute')}>{text('执行','Apply')}</button><button onClick={()=>apiDialog.current?.close()}>{text('关闭','Close')}</button></footer><p className="contour-api-help">{text('支持 commands 源稿批次，或 inspect / preview / artwork / inspectArtworks / inspectRecording / recording / previewRecording / inspectView / view / snapView 请求。录制写入须在录制模式。','Use source command batches or inspect / preview / artwork / inspectArtworks / inspectRecording / recording / previewRecording / inspectView / view / snapView requests. Rig writes require Recording mode.')}</p>{apiPreview&&<img className="contour-api-preview" alt={text('矢量预览','Vector preview')} src={'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(apiPreview)}/>}<pre data-testid="ai-api-result">{apiResult}</pre></dialog>
 </div>;
}
