import type {LandmarkProject} from '../domain/landmarks/model';
import {applySnapshotCommand,allSnapshotIds,SnapshotCommandError,snapshotCommandNames,type SnapshotCommand,type SnapshotCreation} from '../domain/recordingSnapshot/commands';
import {parseRecordingSnapshots} from '../domain/recordingSnapshot/persistence';
import {ensureRecordingSnapshots} from '../domain/recordingSnapshot/migration';
import {evaluateRecordingSnapshot as evaluateWorkspace,resolveSnapshot,type SnapshotEvaluationOptions} from '../domain/recordingSnapshot/evaluation';
import {emptyRecordingSnapshotWorkspace,type RecordingSnapshotWorkspace,type RecordingSnapshot,type Angle} from '../domain/recordingSnapshot/model';
import {recordingPoseTrackIndex} from '../domain/recordingSnapshot/tracks';
import {sameAngle} from '../domain/vectorRecording/interpolation';

export {snapshotCommandNames};
export type {SnapshotCommand};
export interface SnapshotBatch {recordingId?:string;commands:SnapshotCommand[];expectedRevision?:string;dryRun?:boolean}
export interface SnapshotQuery {recordingId?:string;snapshotId?:string;layerIds?:string[];nameIncludes?:string;includeKeyValues?:boolean;expectedRevision?:string}
export class SnapshotApiError extends Error {constructor(readonly code:string,message:string,readonly commandIndex?:number){super(message);}}
const fail=(code:string,message:string):never=>{throw new SnapshotApiError(code,message);};
const object=(v:unknown,allowed:readonly string[]):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))return fail('INVALID_REQUEST','Expected a JSON object.');const o=v as Record<string,unknown>,extra=Object.keys(o).filter(k=>!allowed.includes(k));if(extra.length)fail('INVALID_REQUEST',`Unknown fields: ${extra.join(', ')}`);return o;};
const id=(v:unknown):string=>typeof v==='string'&&!!v&&v.length<=16384?v:fail('INVALID_REQUEST','Expected an ID.');
const bool=(v:unknown):boolean=>typeof v==='boolean'?v:fail('INVALID_REQUEST','Expected a boolean.');
const list=(v:unknown):string[]=>{if(!Array.isArray(v)||v.length>16384)fail('INVALID_REQUEST','Expected an ID array.');return (v as unknown[]).map(id);};

const pairBasisMutationOps=new Set<SnapshotCommand['op']>(['pasteLayers','cloneLayers','moveLayers','removeLayers','reorderLayers','setLayerPlacement','setShapeElementPlacement','transformShapeElements','moveShapeNode','moveShapeHandle','createWarp','createChild','wrapParent','rebindLayers','setWarp','deleteWarp','editWarpNodes','setVisibility','setLayerOrder','changeInterval','setIntervalEnd','setIntervalEnabled','updateSnapshot','saveSelected','discardSelected']);
/** Interior control commands validate their complete response candidate before
 * committing it. Only genuine endpoint edits need a second basis graph check. */
function mutatesPairBasis(workspace:RecordingSnapshotWorkspace,recordingId:string,op:SnapshotCommand['op']):boolean {
 if(!pairBasisMutationOps.has(op))return false;
 const recording=workspace.recordings.find(recording=>recording.id===recordingId),pair=recording?.endpointPair;if(recording?.mode!=='endpoint-pair'||!pair)return false;
 return [pair.startSnapshotId,pair.endSnapshotId].some(id=>{const snapshot=workspace.snapshots.find(snapshot=>snapshot.id===id);return !!snapshot&&sameAngle(snapshot.angle,recording.angle);});
}
function checkPairBasis(workspace:RecordingSnapshotWorkspace,recordingId:string,commandIndex?:number):void {const recording=workspace.recordings.find(recording=>recording.id===recordingId);if(recording?.mode!=='endpoint-pair')return;try{evaluateWorkspace(workspace,recordingId,{angle:recording.angle,useDraft:true,diagnostics:'preview'});}catch(error){throw new SnapshotApiError('ENDPOINT_BASIS_INCOMPATIBLE',(error as Error).message,commandIndex);}}

/** One pure, detached plan shared by the native UI and the JSON editing facade.
 * A failed command or graph check never writes any project/source/history state. */
export function prepareSnapshotBatch(project:LandmarkProject,raw:unknown){
 const request=object(raw,['recordingId','commands','expectedRevision','dryRun']);if(request.expectedRevision!==undefined)id(request.expectedRevision);if(request.dryRun!==undefined)bool(request.dryRun);if(!Array.isArray(request.commands)||request.commands.length>1000)fail('INVALID_REQUEST','commands must contain at most 1000 items.');
 const before=project.recordingSnapshots??emptyRecordingSnapshotWorkspace(),draft=parseRecordingSnapshots(ensureRecordingSnapshots(project).recordingSnapshots),priorActive=draft.activeRecordingId;let explicitSelection=false;const pairBasisChecks=new Map<string,number>();
 if(request.recordingId!==undefined){const target=id(request.recordingId);if(!draft.recordings.some(r=>r.id===target))fail('NOT_FOUND','Recording does not exist.');draft.activeRecordingId=target;}
 const placementChecks=new Map<string,{snapshotId:string;angle:Angle;distances:Map<string,number>;commandIndex:number}>();
 const linkDistances=(evaluation:ReturnType<typeof resolveSnapshot>)=>new Map((evaluation.drawing.endpointLinks??[]).map(link=>{const a=evaluation.drawing.curves.find(c=>c.id===link.a.curveId),b=evaluation.drawing.curves.find(c=>c.id===link.b.curveId),p=a&&evaluation.drawing.nodes.find(n=>n.id===a.nodes[link.a.end])?.position,q=b&&evaluation.drawing.nodes.find(n=>n.id===b.nodes[link.b.end])?.position;return [link.id,p&&q?Math.hypot(p[0]-q[0],p[1]-q[1]):Infinity] as const;}));
 const refs=new Map<string,string>(),created:Array<SnapshotCreation&{commandIndex:number}>=[],removedIds:string[]=[],idMaps:Array<{commandIndex:number;idMap:Record<string,string>}>=[];
 const canonical=(value:string)=>allSnapshotIds(draft).includes(value);
 const dereference=(value:unknown,key=''):unknown=>{if(typeof value==='string'&&/Id$|Ids$/.test(key)&&value.startsWith('$')){if(canonical(value))return value;return refs.get(value.slice(1))??fail('UNKNOWN_REFERENCE',`Unknown batch reference ${value}.`);}if(Array.isArray(value))return value.map(v=>dereference(v,key));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,dereference(v,k)]));return value;};
 for(const [index,command] of (request.commands as unknown[]).entries())try{
  const resolved=dereference(command),op=(resolved as SnapshotCommand).op;if(draft.activeRecordingId&&mutatesPairBasis(draft,draft.activeRecordingId,op))pairBasisChecks.set(draft.activeRecordingId,index);if(op==='setLayerPlacement'){const current=draft.recordings.find(r=>r.id===draft.activeRecordingId),sid=current?.activeSnapshotId;if(current&&sid){const key=JSON.stringify([sid,current.angle]);if(!placementChecks.has(key))placementChecks.set(key,{snapshotId:sid,angle:structuredClone(current.angle),distances:linkDistances(resolveSnapshot(draft,sid,{angle:current.angle,diagnostics:'preview'})),commandIndex:index});}}const effects=applySnapshotCommand(draft,resolved);if(['createRecording','createEndpointPairRecording','selectRecording','deleteRecording'].includes(op))explicitSelection=true;
  for(const item of effects.created){if(item.ref!==undefined){if(!/^[A-Za-z][A-Za-z0-9_-]{0,79}$/.test(item.ref))fail('INVALID_REQUEST','Invalid batch ref.');if(refs.has(item.ref))fail('DUPLICATE_REFERENCE','Batch refs must be unique.');if(canonical(`$${item.ref}`))fail('REFERENCE_COLLISION','Batch ref collides with a canonical ID.');refs.set(item.ref,item.id);}created.push({...item,commandIndex:index});}removedIds.push(...effects.removedIds);if(effects.idMap)idMaps.push({commandIndex:index,idMap:effects.idMap});
 }catch(error){const e=error as Error;throw new SnapshotApiError(e instanceof SnapshotApiError||e instanceof SnapshotCommandError?e.code:'CONSTRAINT_VIOLATION',e.message,index);}
 const recordingId=draft.activeRecordingId,recording=draft.recordings.find(r=>r.id===recordingId),snapshotId=recording?.activeSnapshotId;if(request.recordingId!==undefined&&!explicitSelection)draft.activeRecordingId=priorActive;
 for(const check of placementChecks.values()){if(!draft.snapshots.some(s=>s.id===check.snapshotId))continue;const result=resolveSnapshot(draft,check.snapshotId,{angle:check.angle,diagnostics:'preview'}),distances=linkDistances(result);for(const link of result.drawing.endpointLinks??[]){if((check.distances.get(link.id)??Infinity)>1e-8||(distances.get(link.id)??0)<=1e-8)continue;const owners=[link.a,link.b].map(end=>result.drawing.layers.find(layer=>layer.items.includes(end.curveId)));if(owners[0]?.id===owners[1]?.id)continue;throw new SnapshotApiError('LINKED_LAYER_PLACEMENT',`Placement separates linked layers ${owners.map(layer=>layer?.name??'missing layer').join(' and ')}. Include both linked layers in the same placement transform.`,check.commandIndex);}}
 for(const [id,index] of pairBasisChecks)checkPairBasis(draft,id,index);
 let recordingSnapshots;try{recordingSnapshots=parseRecordingSnapshots(draft);const needsResolution=(request.commands as SnapshotCommand[]).some(c=>['pasteLayers','moveLayers','cloneLayers','createSnapshot','createEndpointPairRecording','removeLayers','rebindLayers','setWarp','deleteWarp'].includes(c.op));if(needsResolution&&snapshotId&&!recording?.legacy)resolveSnapshot(draft,snapshotId,{useDraft:true,angle:recording?.angle,diagnostics:'preview'});}catch(error){throw new SnapshotApiError('CONSTRAINT_VIOLATION',(error as Error).message,(request.commands as unknown[]).length? (request.commands as unknown[]).length-1:undefined);}
 return {before,recordingSnapshots,recordingId,snapshotId,angle:recording?.angle,changed:JSON.stringify(before)!==JSON.stringify(recordingSnapshots),dryRun:request.dryRun===true,created,removedIds:[...new Set(removedIds)],idMaps};
}

export interface SnapshotPreviewRequest {recordingId?:string;commands:readonly SnapshotCommand[]}
const localPreviewOps=new Set<SnapshotCommand['op']>(['setAngle','selectSnapshot','setLayerPlacement','setShapeElementPlacement','moveShapeNode','moveShapeHandle','transformShapeElements','editWarpNodes','setVisibility','setLayerOrder','changeInterval','setIntervalEnd','setIntervalEnabled','discardSelected','setTolerance','setInterpolationWeight','resetInterpolationWeight','correctShapeNode','correctShapeHandle','setControlResponse','resetControlResponse','updateEndpointCorrection','discardEndpointCorrection']);
const interpolationSourceCache=new WeakMap<RecordingSnapshotWorkspace,Map<string,ReturnType<typeof resolveSnapshot>['source']>>();
/** Trusted native UI preview. Canonical geometry, saved keys, source snapshots
 * and archive remain immutable shared inputs. External JSON requests always use
 * prepareSnapshotBatch, including external dry runs. Structural UI commands
 * take that same fully validated path rather than widening this fast boundary. */
export function prepareSnapshotPreview(project:LandmarkProject,request:SnapshotPreviewRequest):SnapshotBatchPlan {
 const q=object(request,['recordingId','commands']);if(!Array.isArray(q.commands)||q.commands.length>1000)fail('INVALID_REQUEST','commands must contain at most 1000 items.');
 if(request.commands.some(command=>!localPreviewOps.has(command.op)))return prepareSnapshotBatch(project,{...request,dryRun:true});
 const before=ensureRecordingSnapshots(project).recordingSnapshots,recordingId=request.recordingId===undefined?before.activeRecordingId:id(request.recordingId),original=before.recordings.find(r=>r.id===recordingId)??fail('NO_RECORDING','Create or select a Recording first.'),changesTracks=request.commands.some(command=>!['setAngle','selectSnapshot','setTolerance','setInterpolationWeight','resetInterpolationWeight'].includes(command.op));
 const changesWeights=request.commands.some(command=>command.op==='setInterpolationWeight'||command.op==='resetInterpolationWeight');
 const recording={...original,...(original.endpointPair?{endpointPair:structuredClone(original.endpointPair)}:{}),tracks:changesTracks?[...original.tracks]:original.tracks,...(changesWeights&&original.interpolationWeights?{interpolationWeights:[...original.interpolationWeights]}:{})};
 const draft:RecordingSnapshotWorkspace={...before,recordings:before.recordings.map(r=>r===original?recording:r),snapshots:before.snapshots,activeRecordingId:recording.id},written=new Map<string,RecordingSnapshot>();
 const snapshotForWrite=(snapshotId:string)=>{const known=written.get(snapshotId);if(known)return known;const index=draft.snapshots.findIndex(s=>s.id===snapshotId),source=draft.snapshots[index];if(!source)fail('NOT_FOUND','Snapshot does not exist.');const copy={...source,deformation:{...source.deformation,relationPositions:{...source.deformation.relationPositions}}};if(draft.snapshots===before.snapshots)draft.snapshots=[...before.snapshots];draft.snapshots[index]=copy;written.set(snapshotId,copy);return copy;};
 const writableTracks=new Set<string>();const trackForWrite=(trackId:string)=>{const index=recording.tracks.findIndex(t=>t.id===trackId),track=recording.tracks[index];if(!track)fail('NOT_FOUND','Track does not exist.');if(writableTracks.has(trackId)||!original.tracks.includes(track))return track;const copy={...track};recording.tracks[index]=copy;writableTracks.add(trackId);return copy;};
 const sourceForInterpolationWeight=(snapshotId:string)=>{let cache=interpolationSourceCache.get(before);if(!cache){cache=new Map();interpolationSourceCache.set(before,cache);}let source=cache.get(snapshotId);if(!source){source=resolveSnapshot(before,snapshotId,{useDraft:false,diagnostics:'preview'}).source;cache.set(snapshotId,source);}return source;};
 const created:Array<SnapshotCreation&{commandIndex:number}>=[],removedIds:string[]=[],checks=new Map<string,{snapshotId:string;angle:Angle;distances:Map<string,number>;commandIndex:number}>();
 let pairBasisIndex=-1;
 const distances=(evaluation:ReturnType<typeof resolveSnapshot>)=>new Map((evaluation.drawing.endpointLinks??[]).map(link=>{const a=evaluation.drawing.curves.find(c=>c.id===link.a.curveId),b=evaluation.drawing.curves.find(c=>c.id===link.b.curveId),p=a&&evaluation.drawing.nodes.find(n=>n.id===a.nodes[link.a.end])?.position,q=b&&evaluation.drawing.nodes.find(n=>n.id===b.nodes[link.b.end])?.position;return [link.id,p&&q?Math.hypot(p[0]-q[0],p[1]-q[1]):Infinity] as const;}));
 for(const [index,command] of request.commands.entries())try{
  if(mutatesPairBasis(draft,recording.id,command.op))pairBasisIndex=index;
  if(command.op==='setLayerPlacement'&&recording.activeSnapshotId){const key=JSON.stringify([recording.activeSnapshotId,recording.angle]);if(!checks.has(key))checks.set(key,{snapshotId:recording.activeSnapshotId,angle:{...recording.angle},distances:distances(resolveSnapshot(draft,recording.activeSnapshotId,{angle:recording.angle,diagnostics:'preview'})),commandIndex:index});}
  const effects=applySnapshotCommand(draft,command,{snapshotForWrite,trackForWrite,sourceForInterpolationWeight});created.push(...effects.created.map(item=>({...item,commandIndex:index})));removedIds.push(...effects.removedIds);
 }catch(error){const e=error as Error;throw new SnapshotApiError(e instanceof SnapshotApiError||e instanceof SnapshotCommandError?e.code:'CONSTRAINT_VIOLATION',e.message,index);}
 for(const check of checks.values()){const evaluation=resolveSnapshot(draft,check.snapshotId,{angle:check.angle,diagnostics:'preview'}),after=distances(evaluation);for(const link of evaluation.drawing.endpointLinks??[]){if((check.distances.get(link.id)??Infinity)>1e-8||(after.get(link.id)??0)<=1e-8)continue;const owners=[link.a,link.b].map(end=>evaluation.drawing.layers.find(layer=>layer.items.includes(end.curveId)));if(owners[0]?.id===owners[1]?.id)continue;throw new SnapshotApiError('LINKED_LAYER_PLACEMENT',`Placement separates linked layers ${owners.map(layer=>layer?.name??'missing layer').join(' and ')}. Include both linked layers in the same placement transform.`,check.commandIndex);}}
 if(pairBasisIndex>=0)checkPairBasis(draft,recording.id,pairBasisIndex);
 if(request.recordingId!==undefined)draft.activeRecordingId=before.activeRecordingId;
 if(recording.tracks.length===original.tracks.length&&recording.tracks.every((track,index)=>track===original.tracks[index]))recording.tracks=original.tracks;
 const changed=written.size>0||JSON.stringify(recording.endpointPair)!==JSON.stringify(original.endpointPair)||changesWeights&&JSON.stringify(recording.interpolationWeights)!==JSON.stringify(original.interpolationWeights)||recording.angle.x!==original.angle.x||recording.angle.y!==original.angle.y||recording.activeSnapshotId!==original.activeSnapshotId||recording.tolerance!==original.tolerance||recording.tracks.length!==original.tracks.length||recording.tracks.some((track,index)=>track.draft!==original.tracks[index]?.draft&&JSON.stringify(track.draft)!==JSON.stringify(original.tracks[index]?.draft));
 return {before,recordingSnapshots:changed?draft:before,recordingId:recording.id,snapshotId:recording.activeSnapshotId,angle:recording.angle,changed,dryRun:true,created,removedIds:[...new Set(removedIds)],idMaps:[]};
}

export function snapshotOverview(project:LandmarkProject,raw:unknown={}){
 const q=object(raw,['recordingId','snapshotId','layerIds','nameIncludes','includeKeyValues','expectedRevision']);if(q.includeKeyValues!==undefined)bool(q.includeKeyValues);if(q.nameIncludes!==undefined&&typeof q.nameIncludes!=='string')fail('INVALID_REQUEST','nameIncludes must be text.');if(q.expectedRevision!==undefined)id(q.expectedRevision);
 const workspace=ensureRecordingSnapshots(project).recordingSnapshots,recordingId=q.recordingId===undefined?workspace.activeRecordingId:id(q.recordingId),recording=workspace.recordings.find(r=>r.id===recordingId);if(q.recordingId!==undefined&&!recording)fail('NOT_FOUND','Recording does not exist.');
 const recordings=workspace.recordings.map(r=>({id:r.id,name:r.name,mode:r.mode??'tracks',endpointPair:r.endpointPair,angle:r.angle,snapshotIds:r.snapshotIds,activeSnapshotId:r.activeSnapshotId,snapshotCount:r.snapshotIds.length,trackCount:r.tracks.length,interpolationWeightCount:r.interpolationWeights?.length??0,authoredKeyCount:r.tracks.reduce((n,t)=>n+t.keys.length,0),readOnly:!!r.legacy}));
 const availableSnapshots=workspace.snapshots.map(s=>({id:s.id,name:s.name,kind:s.kind,angle:s.angle,layers:s.layers,authoredKeyCount:s.authored.length,...(s.source?{artworkId:s.source.artworkId}:{})}));
 if(!recording)return {exists:false,recordings,availableSnapshots,sourceReadOnly:true};
 const snapshotId=q.snapshotId===undefined?undefined:id(q.snapshotId);if(snapshotId&&!recording.snapshotIds.includes(snapshotId))fail('NOT_FOUND','Snapshot does not belong to this Recording.');
 const evaluation=recording.snapshotIds.length?evaluateWorkspace(workspace,recording.id,{snapshotId,diagnostics:'preview'}):undefined,selected=evaluation&&workspace.snapshots.find(s=>s.id===evaluation.snapshotId),layerIds=q.layerIds===undefined?undefined:list(q.layerIds),matches=(name:string)=>q.nameIncludes===undefined||name.toLocaleLowerCase().includes(String(q.nameIncludes).toLocaleLowerCase());
 const tracks=recording.tracks.map(t=>q.includeKeyValues?t:{...t,keys:t.keys.map(k=>({id:k.id,name:k.name,angle:k.angle})),...(t.draft?{draft:{angle:t.draft.angle}}:{})});
 return structuredClone({exists:true,recordingId:recording.id,snapshotId:selected?.id,name:recording.name,mode:recording.mode??'tracks',endpointPair:recording.endpointPair,angle:recording.angle,recordings,availableSnapshots,snapshots:recording.snapshotIds.map(sid=>workspace.snapshots.find(s=>s.id===sid)!).map(s=>({id:s.id,name:s.name,kind:s.kind,angle:s.angle,layerCount:s.layers.length,authored:s.authored})),layers:(selected?.layers??[]).filter(l=>(!layerIds||layerIds.includes(l.id))&&matches(l.name)).map(l=>({...l,currentPlacement:evaluation?.placements[l.id],currentShape:evaluation?.state.layers[l.id]?.shape??{nodes:{},handles:{}},members:evaluation?.drawing.layers.find(x=>x.id===l.id)?.items??[],authoredKeyCount:recording.tracks.filter(t=>t.targetId===l.id).reduce((n,t)=>n+t.keys.length,0)})),warps:evaluation?.state.warps??[],bindings:evaluation?.state.bindings??[],interpolationWeights:recording.interpolationWeights??[],tracks,trackIndex:recordingPoseTrackIndex(recording,workspace),diagnostics:evaluation?.diagnostics??[],readOnly:!!recording.legacy,legacyReason:recording.legacy?.reason,hasDraft:!!recording.endpointPair?.draft||recording.tracks.some(t=>!!t.draft),tolerancePixels:(recording.tolerance??1/250)*250,sourceReadOnly:true});
}

export function evaluateRecordingSnapshot(project:LandmarkProject,request:Pick<SnapshotEvaluationOptions,'angle'|'useDraft'|'snapshotId'|'stopAtWarpId'|'omitPlacements'>&{recordingId?:string}={}){
 const q=object(request,['recordingId','snapshotId','angle','useDraft','stopAtWarpId','omitPlacements']);if(q.useDraft!==undefined)bool(q.useDraft);if(q.omitPlacements!==undefined)bool(q.omitPlacements);
 const workspace=ensureRecordingSnapshots(project).recordingSnapshots,recordingId=q.recordingId===undefined?workspace.activeRecordingId:id(q.recordingId),recording=workspace.recordings.find(r=>r.id===recordingId)??fail('NO_RECORDING','Create or select a Recording first.');
 if(q.angle!==undefined){const angle=object(q.angle,['x','y']);if(![angle.x,angle.y].every(n=>typeof n==='number'&&Number.isFinite(n)&&n>=-90&&n<=90))fail('INVALID_REQUEST','Angle must be finite in −90…90.');}
 if(q.snapshotId!==undefined&&!recording.snapshotIds.includes(id(q.snapshotId)))fail('NOT_FOUND','Snapshot does not belong to this Recording.');if(q.stopAtWarpId!==undefined)id(q.stopAtWarpId);
 const useDraft=q.useDraft===undefined?q.angle===undefined:bool(q.useDraft),result=evaluateWorkspace(workspace,recording.id,{...request,useDraft,diagnostics:'full'}),drafts=recording.tracks.filter(t=>t.draft);if(q.stopAtWarpId!==undefined&&!result.state.warps.some(w=>w.id===q.stopAtWarpId))fail('NOT_FOUND','Local preview Warp does not exist.');
 return {...result,recordingId:recording.id,usedDraft:useDraft&&(drafts.some(t=>sameAngle(t.draft!.angle,result.angle))||!!recording.endpointPair?.draft&&sameAngle(recording.endpointPair.draft.angle,recording.angle)),hasUnappliedDraft:drafts.some(t=>!useDraft||!sameAngle(t.draft!.angle,result.angle))||!!recording.endpointPair?.draft&&(!useDraft||!sameAngle(recording.endpointPair.draft.angle,recording.angle))};
}
export type SnapshotBatchPlan=ReturnType<typeof prepareSnapshotBatch>;
