import {propagateAutomaticSnapshotLayers} from '../domain/recordingSnapshot/automaticSnapshotEdits';
import type {LandmarkProject} from '../domain/landmarks/model';
import {applySnapshotCommand,allSnapshotIds,SnapshotCommandError,snapshotCommandNames as allSnapshotCommandNames,type SnapshotCommand,type SnapshotCreation} from '../domain/recordingSnapshot/commands';
import {parseRecordingSnapshots} from '../domain/recordingSnapshot/persistence';
import {ensureRecordingSnapshots} from '../domain/recordingSnapshot/migration';
import {evaluateRecordingSnapshot as evaluateWorkspace,resolveSnapshot,retainSnapshotSavedEvaluationIdentity,type SnapshotEvaluationOptions} from '../domain/recordingSnapshot/evaluation';
import {emptyRecordingSnapshotWorkspace,type RecordingSnapshotWorkspace,type RecordingSnapshot,type Angle} from '../domain/recordingSnapshot/model';
import {recordingPoseTrackIndex} from '../domain/recordingSnapshot/tracks';
import {recordingRetirementStatus,assertRecordingProjectActive,RECORDING_RETIRED_MESSAGE} from '../domain/recordingSnapshot/retirement';

const retiredCreationOps=new Set<SnapshotCommand['op']>(['createRecording','createEndpointPairRecording','createTriangulatedRecordingCopy']);
export const snapshotCommandNames=allSnapshotCommandNames.filter(op=>!retiredCreationOps.has(op));
export const recordingRetiredReason=RECORDING_RETIRED_MESSAGE;
export type {SnapshotCommand};
export interface SnapshotBatch {recordingId?:string;commands:SnapshotCommand[];expectedRevision?:string;dryRun?:boolean}
export interface SnapshotQuery {recordingId?:string;snapshotId?:string;layerIds?:string[];nameIncludes?:string;includeKeyValues?:boolean;expectedRevision?:string}
export class SnapshotApiError extends Error {constructor(readonly code:string,message:string,readonly commandIndex?:number){super(message);}}
const fail=(code:string,message:string):never=>{throw new SnapshotApiError(code,message);};
const object=(v:unknown,allowed:readonly string[]):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))return fail('INVALID_REQUEST','Expected a JSON object.');const o=v as Record<string,unknown>,extra=Object.keys(o).filter(k=>!allowed.includes(k));if(extra.length)fail('INVALID_REQUEST',`Unknown fields: ${extra.join(', ')}`);return o;};
const id=(v:unknown):string=>typeof v==='string'&&!!v&&v.length<=16384?v:fail('INVALID_REQUEST','Expected an ID.');
const bool=(v:unknown):boolean=>typeof v==='boolean'?v:fail('INVALID_REQUEST','Expected a boolean.');
const list=(v:unknown):string[]=>{if(!Array.isArray(v)||v.length>16384)fail('INVALID_REQUEST','Expected an ID array.');return (v as unknown[]).map(id);};
function assertProjectRecordingActive(project:LandmarkProject):void {try{assertRecordingProjectActive(project);}catch{fail('LEGACY_RECORDING_RETIRED',recordingRetiredReason);}}

/** One pure, detached plan shared by the native UI and the JSON editing facade.
 * A failed command or graph check never writes any project/source/history state. */
export function prepareSnapshotBatch(project:LandmarkProject,raw:unknown){
 const request=object(raw,['recordingId','commands','expectedRevision','dryRun']);if(request.expectedRevision!==undefined)id(request.expectedRevision);if(request.dryRun!==undefined)bool(request.dryRun);if(!Array.isArray(request.commands)||request.commands.length>1000)fail('INVALID_REQUEST','commands must contain at most 1000 items.');
 assertProjectRecordingActive(project);
 const before=project.recordingSnapshots??emptyRecordingSnapshotWorkspace(),draft=parseRecordingSnapshots(ensureRecordingSnapshots(project).recordingSnapshots),priorActive=draft.activeRecordingId;let explicitSelection=false;
 if(request.recordingId!==undefined){const target=id(request.recordingId);if(!draft.recordings.some(r=>r.id===target))fail('NOT_FOUND','Recording does not exist.');draft.activeRecordingId=target;}
 const placementOnly=(request.commands as SnapshotCommand[]).length>0&&(request.commands as SnapshotCommand[]).every(command=>command?.op==='setLayerPlacement');
 let placementEvaluation:ReturnType<typeof resolveSnapshot>|undefined;
 const placementChecks=new Map<string,{snapshotId:string;angle:Angle;distances:Map<string,number>;commandIndex:number}>();
 const linkDistances=(evaluation:ReturnType<typeof resolveSnapshot>)=>new Map((evaluation.drawing.endpointLinks??[]).map(link=>{const a=evaluation.drawing.curves.find(c=>c.id===link.a.curveId),b=evaluation.drawing.curves.find(c=>c.id===link.b.curveId),p=a&&evaluation.drawing.nodes.find(n=>n.id===a.nodes[link.a.end])?.position,q=b&&evaluation.drawing.nodes.find(n=>n.id===b.nodes[link.b.end])?.position;return [link.id,p&&q?Math.hypot(p[0]-q[0],p[1]-q[1]):Infinity] as const;}));
 const refs=new Map<string,string>(),created:Array<SnapshotCreation&{commandIndex:number}>=[],removedIds:string[]=[],idMaps:Array<{commandIndex:number;idMap:Record<string,string>}>=[],diagnostics:Array<{code:string;message:string}>=[];
 const canonical=(value:string)=>allSnapshotIds(draft).includes(value);
 const dereference=(value:unknown,key=''):unknown=>{if(typeof value==='string'&&/Id$|Ids$/.test(key)&&value.startsWith('$')){if(canonical(value))return value;return refs.get(value.slice(1))??fail('UNKNOWN_REFERENCE',`Unknown batch reference ${value}.`);}if(Array.isArray(value))return value.map(v=>dereference(v,key));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,dereference(v,k)]));return value;};
 for(const [index,command] of (request.commands as unknown[]).entries())try{
  const op=(command as SnapshotCommand)?.op;if(retiredCreationOps.has(op))fail('LEGACY_RECORDING_RETIRED',`${op} is retired. Use createTriangulatedRecording for a new Recording. ${recordingRetiredReason}`);const resolved=dereference(command);if(op==='setLayerPlacement'){const current=draft.recordings.find(r=>r.id===draft.activeRecordingId),sid=current?.activeSnapshotId;if(current&&sid){const key=JSON.stringify([sid,current.angle]);if(!placementChecks.has(key)){const evaluation=current.mode==='triangulated'?evaluateWorkspace(draft,current.id,{angle:current.angle,diagnostics:'preview'}):resolveSnapshot(draft,sid,{angle:current.angle,diagnostics:'preview'});if(placementOnly)placementEvaluation=evaluation;placementChecks.set(key,{snapshotId:sid,angle:structuredClone(current.angle),distances:linkDistances(evaluation),commandIndex:index});}}}const effects=applySnapshotCommand(draft,resolved,placementEvaluation?{layerPlacementDrawing:placementEvaluation.drawing}:undefined);if(['createTriangulatedRecording','selectRecording','deleteRecording'].includes(op))explicitSelection=true;
  for(const item of effects.created){if(item.ref!==undefined){if(!/^[A-Za-z][A-Za-z0-9_-]{0,79}$/.test(item.ref))fail('INVALID_REQUEST','Invalid batch ref.');if(refs.has(item.ref))fail('DUPLICATE_REFERENCE','Batch refs must be unique.');if(canonical(`$${item.ref}`))fail('REFERENCE_COLLISION','Batch ref collides with a canonical ID.');refs.set(item.ref,item.id);}created.push({...item,commandIndex:index});}removedIds.push(...effects.removedIds);diagnostics.push(...effects.diagnostics??[]);if(effects.idMap)idMaps.push({commandIndex:index,idMap:effects.idMap});
 }catch(error){const e=error as Error;throw new SnapshotApiError(e instanceof SnapshotApiError||e instanceof SnapshotCommandError?e.code:'CONSTRAINT_VIOLATION',e.message,index);}
 const inherited=propagateAutomaticSnapshotLayers(before,draft);draft.snapshots=inherited.workspace.snapshots;diagnostics.push(...inherited.diagnostics);
 const recordingId=draft.activeRecordingId,recording=draft.recordings.find(r=>r.id===recordingId),snapshotId=recording?.activeSnapshotId;if(request.recordingId!==undefined&&!explicitSelection)draft.activeRecordingId=priorActive;
 for(const check of placementChecks.values()){if(!draft.snapshots.some(s=>s.id===check.snapshotId))continue;const owner=draft.recordings.find(recording=>recording.snapshotIds.includes(check.snapshotId)),result=owner?.mode==='triangulated'?evaluateWorkspace(draft,owner.id,{angle:check.angle,diagnostics:'preview'}):resolveSnapshot(draft,check.snapshotId,{angle:check.angle,diagnostics:'preview'}),distances=linkDistances(result);for(const link of result.drawing.endpointLinks??[]){if((check.distances.get(link.id)??Infinity)>1e-8||(distances.get(link.id)??0)<=1e-8)continue;const owners=[link.a,link.b].map(end=>result.drawing.layers.find(layer=>layer.items.includes(end.curveId)));if(owners[0]?.id===owners[1]?.id)continue;throw new SnapshotApiError('LINKED_LAYER_PLACEMENT',`Placement separates linked layers ${owners.map(layer=>layer?.name??'missing layer').join(' and ')}. Include both linked layers in the same placement transform.`,check.commandIndex);}}
 let recordingSnapshots;try{recordingSnapshots=parseRecordingSnapshots(draft);const needsResolution=(request.commands as SnapshotCommand[]).some(c=>['pasteLayers','moveLayers','cloneLayers','createSnapshot','createEndpointPairRecording','createTriangulatedRecordingCopy','removeLayers','rebindLayers','setWarp','deleteWarp'].includes(c.op));if(needsResolution&&snapshotId&&!recording?.legacy)recording?.mode==='triangulated'?evaluateWorkspace(draft,recording.id,{useDraft:true,angle:recording.angle,diagnostics:'preview'}):resolveSnapshot(draft,snapshotId,{useDraft:true,angle:recording?.angle,diagnostics:'preview'});}catch(error){throw new SnapshotApiError('CONSTRAINT_VIOLATION',(error as Error).message,(request.commands as unknown[]).length? (request.commands as unknown[]).length-1:undefined);}
 return {before,recordingSnapshots,recordingId,snapshotId,angle:recording?.angle,changed:JSON.stringify(before)!==JSON.stringify(recordingSnapshots),dryRun:request.dryRun===true,created,removedIds:[...new Set(removedIds)],idMaps,diagnostics};
}

export interface SnapshotPreviewRequest {recordingId?:string;commands:readonly SnapshotCommand[]}
const localPreviewOps=new Set<SnapshotCommand['op']>(['setAngle','selectSnapshot','setLayerPlacement','setShapeElementPlacement','moveShapeNode','moveShapeHandle','transformShapeElements','editWarpNodes','setVisibility','setLayerOrder','changeInterval','setIntervalEnd','setIntervalEnabled','discardSelected','setTolerance','correctShapeNode','correctShapeHandle','setControlResponse','resetControlResponse','updateEndpointCorrection','discardEndpointCorrection']);
/** Trusted native UI preview. Canonical geometry, saved keys, source snapshots
 * and archive remain immutable shared inputs. External JSON requests always use
 * prepareSnapshotBatch, including external dry runs. Structural UI commands
 * take that same fully validated path rather than widening this fast boundary. */
export function prepareSnapshotPreview(project:LandmarkProject,request:SnapshotPreviewRequest):SnapshotBatchPlan {
 const q=object(request,['recordingId','commands']);if(!Array.isArray(q.commands)||q.commands.length>1000)fail('INVALID_REQUEST','commands must contain at most 1000 items.');
 assertProjectRecordingActive(project);
 if(request.commands.some(command=>!localPreviewOps.has(command.op)))return prepareSnapshotBatch(project,{...request,dryRun:true});
 const before=ensureRecordingSnapshots(project).recordingSnapshots,recordingId=request.recordingId===undefined?before.activeRecordingId:id(request.recordingId),original=before.recordings.find(r=>r.id===recordingId)??fail('NO_RECORDING','Create or select a Recording first.'),changesTracks=request.commands.some(command=>!['setAngle','selectSnapshot','setTolerance'].includes(command.op));
 const placementOnly=request.commands.length>0&&request.commands.every(command=>command.op==='setLayerPlacement');
 const recording={...original,...(original.endpointPair?{endpointPair:structuredClone(original.endpointPair)}:{}),tracks:changesTracks&&!(placementOnly&&original.mode==='triangulated')?[...original.tracks]:original.tracks};
 const draft:RecordingSnapshotWorkspace={...before,recordings:before.recordings.map(r=>r===original?recording:r),snapshots:before.snapshots,activeRecordingId:recording.id},written=new Map<string,RecordingSnapshot>();
 const snapshotForWrite=(snapshotId:string)=>{const known=written.get(snapshotId);if(known)return known;const index=draft.snapshots.findIndex(s=>s.id===snapshotId),source=draft.snapshots[index];if(!source)fail('NOT_FOUND','Snapshot does not exist.');const copy={...source,deformation:{...source.deformation,relationPositions:{...source.deformation.relationPositions}}};if(placementOnly)retainSnapshotSavedEvaluationIdentity(copy,source);if(draft.snapshots===before.snapshots)draft.snapshots=[...before.snapshots];draft.snapshots[index]=copy;written.set(snapshotId,copy);return copy;};
 const writableTracks=new Set<string>();const trackForWrite=(trackId:string)=>{const index=recording.tracks.findIndex(t=>t.id===trackId),track=recording.tracks[index];if(!track)fail('NOT_FOUND','Track does not exist.');if(writableTracks.has(trackId)||!original.tracks.includes(track))return track;const copy={...track};recording.tracks[index]=copy;writableTracks.add(trackId);return copy;};
 const created:Array<SnapshotCreation&{commandIndex:number}>=[],removedIds:string[]=[],checks=new Map<string,{snapshotId:string;angle:Angle;distances:Map<string,number>;commandIndex:number}>();
 const distances=(evaluation:ReturnType<typeof resolveSnapshot>)=>new Map((evaluation.drawing.endpointLinks??[]).map(link=>{const a=evaluation.drawing.curves.find(c=>c.id===link.a.curveId),b=evaluation.drawing.curves.find(c=>c.id===link.b.curveId),p=a&&evaluation.drawing.nodes.find(n=>n.id===a.nodes[link.a.end])?.position,q=b&&evaluation.drawing.nodes.find(n=>n.id===b.nodes[link.b.end])?.position;return [link.id,p&&q?Math.hypot(p[0]-q[0],p[1]-q[1]):Infinity] as const;}));
 // Layer placement changes neither membership nor locks. Resolve its immutable
 // input once, then evaluate only the complete copied snapshot. Evaluating
 // between writes would cache a partially edited pose under that same identity.
 let placementEvaluation:ReturnType<typeof resolveSnapshot>|undefined;
 for(const [index,command] of request.commands.entries())try{
  if(command.op==='setLayerPlacement'&&recording.activeSnapshotId){const key=JSON.stringify([recording.activeSnapshotId,recording.angle]);if(!checks.has(key)){const evaluation=recording.mode==='triangulated'?evaluateWorkspace(draft,recording.id,{angle:recording.angle,diagnostics:'preview',immutableInputs:placementOnly}):resolveSnapshot(draft,recording.activeSnapshotId,{angle:recording.angle,diagnostics:'preview',immutableInputs:placementOnly});if(placementOnly)placementEvaluation=evaluation;checks.set(key,{snapshotId:recording.activeSnapshotId,angle:{...recording.angle},distances:distances(evaluation),commandIndex:index});}}
  const effects=applySnapshotCommand(draft,command,{snapshotForWrite,trackForWrite,immutableInputs:placementOnly||request.commands.length===1,...(placementEvaluation?{layerPlacementDrawing:placementEvaluation.drawing}:{})});created.push(...effects.created.map(item=>({...item,commandIndex:index})));removedIds.push(...effects.removedIds);
 }catch(error){const e=error as Error;throw new SnapshotApiError(e instanceof SnapshotApiError||e instanceof SnapshotCommandError?e.code:'CONSTRAINT_VIOLATION',e.message,index);}
 for(const check of checks.values()){const evaluation=recording.mode==='triangulated'?evaluateWorkspace(draft,recording.id,{angle:check.angle,diagnostics:'preview',immutableInputs:placementOnly}):resolveSnapshot(draft,check.snapshotId,{angle:check.angle,diagnostics:'preview',immutableInputs:placementOnly}),after=distances(evaluation);for(const link of evaluation.drawing.endpointLinks??[]){if((check.distances.get(link.id)??Infinity)>1e-8||(after.get(link.id)??0)<=1e-8)continue;const owners=[link.a,link.b].map(end=>evaluation.drawing.layers.find(layer=>layer.items.includes(end.curveId)));if(owners[0]?.id===owners[1]?.id)continue;throw new SnapshotApiError('LINKED_LAYER_PLACEMENT',`Placement separates linked layers ${owners.map(layer=>layer?.name??'missing layer').join(' and ')}. Include both linked layers in the same placement transform.`,check.commandIndex);}}
 if(request.recordingId!==undefined)draft.activeRecordingId=before.activeRecordingId;
 if(recording.tracks.length===original.tracks.length&&recording.tracks.every((track,index)=>track===original.tracks[index]))recording.tracks=original.tracks;
 const changed=written.size>0||recording.angleGraph!==original.angleGraph||JSON.stringify(recording.endpointPair)!==JSON.stringify(original.endpointPair)||recording.angle.x!==original.angle.x||recording.angle.y!==original.angle.y||recording.activeSnapshotId!==original.activeSnapshotId||recording.tolerance!==original.tolerance||recording.tracks.length!==original.tracks.length||recording.tracks.some((track,index)=>track.draft!==original.tracks[index]?.draft&&JSON.stringify(track.draft)!==JSON.stringify(original.tracks[index]?.draft));
 return {before,recordingSnapshots:changed?draft:before,recordingId:recording.id,snapshotId:recording.activeSnapshotId,angle:recording.angle,changed,dryRun:true,created,removedIds:[...new Set(removedIds)],idMaps:[],diagnostics:[]};
}

export function snapshotOverview(project:LandmarkProject,raw:unknown={}){
 const q=object(raw,['recordingId','snapshotId','layerIds','nameIncludes','includeKeyValues','expectedRevision']);if(q.includeKeyValues!==undefined)bool(q.includeKeyValues);if(q.nameIncludes!==undefined&&typeof q.nameIncludes!=='string')fail('INVALID_REQUEST','nameIncludes must be text.');if(q.expectedRevision!==undefined)id(q.expectedRevision);
 const retirement=recordingRetirementStatus(project),workspace=retirement?(project.recordingSnapshots??emptyRecordingSnapshotWorkspace()):ensureRecordingSnapshots(project).recordingSnapshots,recordingId=q.recordingId===undefined?workspace.activeRecordingId:id(q.recordingId),recording=workspace.recordings.find(r=>r.id===recordingId);if(q.recordingId!==undefined&&!recording)fail('NOT_FOUND','Recording does not exist.');
 const recordings=workspace.recordings.map(r=>({id:r.id,name:r.name,mode:r.mode??'tracks',endpointPair:r.endpointPair,angleGraph:r.angleGraph,angle:r.angle,snapshotIds:r.snapshotIds,activeSnapshotId:r.activeSnapshotId,snapshotCount:r.snapshotIds.length,trackCount:r.tracks.length,authoredKeyCount:r.tracks.reduce((n,t)=>n+t.keys.length,0),readOnly:!!retirement,retired:r.mode!=='triangulated'||!!r.legacy}));
 const boundAngle=(snapshot:RecordingSnapshot,owner=workspace.recordings.find(recording=>recording.snapshotIds.includes(snapshot.id)))=>owner?.mode==='triangulated'?owner.angleGraph?.mesh.vertices.find(vertex=>vertex.snapshotId===snapshot.id)?.angle??snapshot.angle:snapshot.angle;
 const availableSnapshots=workspace.snapshots.map(s=>({id:s.id,name:s.name,kind:s.kind,angle:boundAngle(s),layers:s.layers,authoredKeyCount:s.authored.length,...(s.source?{artworkId:s.source.artworkId}:{})}));
 if(!recording)return structuredClone({exists:!!retirement,recordings,availableSnapshots,sourceReadOnly:true,readOnly:!!retirement,retired:!!retirement,retiredReason:retirement?recordingRetiredReason:undefined,retirement});
 const snapshotId=q.snapshotId===undefined?undefined:id(q.snapshotId);if(snapshotId&&!recording.snapshotIds.includes(snapshotId))fail('NOT_FOUND','Snapshot does not belong to this Recording.');
 const evaluation=!retirement&&recording.snapshotIds.length?evaluateWorkspace(workspace,recording.id,{snapshotId,diagnostics:'preview'}):undefined,selected=evaluation&&workspace.snapshots.find(s=>s.id===evaluation.snapshotId),layerIds=q.layerIds===undefined?undefined:list(q.layerIds),matches=(name:string)=>q.nameIncludes===undefined||name.toLocaleLowerCase().includes(String(q.nameIncludes).toLocaleLowerCase());
 const tracks=recording.tracks.map(t=>q.includeKeyValues?t:{...t,keys:t.keys.map(k=>({id:k.id,name:k.name,angle:k.angle})),...(t.draft?{draft:{angle:t.draft.angle}}:{})});
 return structuredClone({exists:true,recordingId:recording.id,snapshotId:selected?.id??(retirement?snapshotId??recording.activeSnapshotId:undefined),name:recording.name,mode:recording.mode??'tracks',endpointPair:recording.endpointPair,angleGraph:recording.angleGraph,angleSurface:evaluation?.angleSurface?{role:evaluation.angleSurface.role,coordinateSpace:evaluation.angleSurface.coordinateSpace,simplex:evaluation.angleSurface.simplex,basisSnapshotIds:evaluation.angleSurface.bases.map(base=>base.snapshotId),outsideCurves:evaluation.angleSurface.outsideCurves.map(({cubic,...curve})=>curve)}:undefined,angle:recording.angle,recordings,availableSnapshots,snapshots:recording.snapshotIds.map(sid=>workspace.snapshots.find(s=>s.id===sid)).filter((s):s is RecordingSnapshot=>!!s).map(s=>({id:s.id,name:s.name,kind:s.kind,angle:boundAngle(s,recording),layerCount:s.layers.length,authored:s.authored})),layers:(selected?.layers??[]).filter(l=>(!layerIds||layerIds.includes(l.id))&&matches(l.name)).map(l=>({...l,currentPlacement:evaluation?.placements[l.id],currentShape:evaluation?.state.layers[l.id]?.shape??{nodes:{},handles:{}},members:evaluation?.drawing.layers.find(x=>x.id===l.id)?.items??[],authoredKeyCount:recording.tracks.filter(t=>t.targetId===l.id).reduce((n,t)=>n+t.keys.length,0)})),warps:evaluation?.state.warps??[],bindings:evaluation?.state.bindings??[],tracks,trackIndex:retirement?undefined:recordingPoseTrackIndex(recording,workspace),diagnostics:evaluation?.diagnostics??[],readOnly:!!retirement,retired:!!retirement,retiredReason:retirement?recordingRetiredReason:undefined,retirement,legacyReason:recording.legacy?.reason,hasDraft:!!recording.endpointPair?.draft||recording.angleGraph?.correctionFrames?.some(frame=>frame.status==='draft')||recording.snapshotIds.some(id=>workspace.snapshots.find(snapshot=>snapshot.id===id)?.draft)||recording.mode!=='triangulated'&&recording.tracks.some(t=>!!t.draft),tolerancePixels:(recording.tolerance??1/250)*250,sourceReadOnly:true});
}

export function evaluateRecordingSnapshot(project:LandmarkProject,request:Pick<SnapshotEvaluationOptions,'angle'|'useDraft'|'snapshotId'|'stopAtWarpId'|'omitPlacements'>&{recordingId?:string}={}){
 const q=object(request,['recordingId','snapshotId','angle','useDraft','stopAtWarpId','omitPlacements']);if(q.useDraft!==undefined)bool(q.useDraft);if(q.omitPlacements!==undefined)bool(q.omitPlacements);
 assertProjectRecordingActive(project);
 const workspace=ensureRecordingSnapshots(project).recordingSnapshots,recordingId=q.recordingId===undefined?workspace.activeRecordingId:id(q.recordingId),recording=workspace.recordings.find(r=>r.id===recordingId)??fail('NO_RECORDING','Create or select a Recording first.');
 if(q.angle!==undefined){const angle=object(q.angle,['x','y']);if(![angle.x,angle.y].every(n=>typeof n==='number'&&Number.isFinite(n)&&n>=-90&&n<=90))fail('INVALID_REQUEST','Angle must be finite in −90…90.');}
 if(q.snapshotId!==undefined&&!recording.snapshotIds.includes(id(q.snapshotId)))fail('NOT_FOUND','Snapshot does not belong to this Recording.');if(q.stopAtWarpId!==undefined)id(q.stopAtWarpId);
 const useDraft=q.useDraft===undefined?q.angle===undefined:bool(q.useDraft),result=evaluateWorkspace(workspace,recording.id,{...request,useDraft,diagnostics:'full'});if(q.stopAtWarpId!==undefined&&!result.state.warps.some(w=>w.id===q.stopAtWarpId))fail('NOT_FOUND','Local preview Warp does not exist.');
 const surfaceDraft=recording.angleGraph?.correctionFrames?.some(frame=>frame.status==='draft'),usedBasisIds=new Set([...(result.angleSurface?.bases.map(base=>base.snapshotId)??[]),...(result.angleSurface?.outsideCurves.flatMap(curve=>curve.snapshotIds)??[])]),localDraft=recording.mode==='triangulated'&&recording.angleGraph?.mesh.vertices.some(vertex=>usedBasisIds.has(vertex.snapshotId)&&vertex.angle.x===recording.angle.x&&vertex.angle.y===recording.angle.y&&workspace.snapshots.find(snapshot=>snapshot.id===vertex.snapshotId)?.draft);
 return {...result,recordingId:recording.id,usedDraft:useDraft&&!!(surfaceDraft||localDraft),hasUnappliedDraft:!!surfaceDraft&&!useDraft||recording.snapshotIds.some(id=>{const snapshot=workspace.snapshots.find(snapshot=>snapshot.id===id),vertex=recording.angleGraph?.mesh.vertices.find(vertex=>vertex.snapshotId===id);return !!snapshot?.draft&&(!useDraft||!vertex||!usedBasisIds.has(id)||vertex.angle.x!==recording.angle.x||vertex.angle.y!==recording.angle.y);})};

}
export type SnapshotBatchPlan=ReturnType<typeof prepareSnapshotBatch>;
