import SceneRecordingWorkspace from './SceneRecordingWorkspace';
import {emptyRecordingScenes} from '../../domain/recordingScene/model';
import {migrateLegacyRecordingScenes} from '../../domain/recordingScene/migration';
import {getWorkspaceView} from '../../app/workspaceView';
import {snapWorkspacePoint} from '../../app/workspaceViewSnap';
import ArtworkReference from '../workspaceView/ArtworkReference';
import ViewGuidesOverlay from '../workspaceView/ViewGuidesOverlay';
import {displayRouteDiagnostics} from '../../domain/drawing/displayRouteInk';
import IntervalPoseControls from './IntervalPoseControls';
import AIGuideOverlay from '../drawing/AIGuideOverlay';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useEditor} from '../../app/store';
import {useWorkspaceMode} from '../../app/workspaceMode';
import {emptyDrawing,layerFor,type Point2} from '../../domain/drawing/model';
import {type WarpGrid,moveWarpNode} from '../../domain/vectorWarp/model';
import {deformDrawing} from '../../domain/vectorWarp/evaluation';
import {changedIntervalTracks,acceptArtworkSource,drawingSignature,addDeformer,applyVisibility,currentPose,deformerChain,discardDraft,drawingBounds,emptyVectorRecording,emptyPose,ensureArtworkRig,evaluatePose,removeDeformer,replaceRig,saveKeyform,setDeformerParent,setRigAngle,sourceArtworkId,type ArtworkRig,type VectorPose,type VectorRecording} from '../../domain/vectorRecording/model';
import {sameAngle} from '../../domain/vectorRecording/interpolation';
import PaintScene from '../drawing/PaintScene';
import {curvePath} from '../drawing/geometry';
import {useDrawing} from '../drawing/session';
import {useLanguage} from '../i18n';
import './vectorRecording.css';
const EMPTY=emptyDrawing(),noop=()=>{};
type Drag={kind:'nodes'|'handle'|'box'|'pan';start:Point2;client:Point2;pose:VectorPose;indices:number[];handle?:'handleU'|'handleV';index?:number;pan?:Point2};
export default function RecordingWorkspace({aiGuides=false}:{aiGuides?:boolean}={}){
 const project=useEditor(s=>s.project);
 useEffect(()=>{const editor=useEditor.getState();if(!editor.project.recordingScenes)editor.setRecordingScenes(migrateLegacyRecordingScenes(editor.project).recordingScenes??emptyRecordingScenes());},[project.recordingScenes]);
 if(project.recordingScenes)return <SceneRecordingWorkspace aiGuides={aiGuides}/>;
 // Existing direct callers can render the legacy state while the store seeds
 // its compatibility scene; all persisted new scenes use the scene workspace.
 if(project.vectorRecording?.rigs.length)return <LegacyRecordingWorkspace aiGuides={aiGuides}/>;
 return <div className="vector-loading" role="status">准备录制场景…</div>;
}
function LegacyRecordingWorkspace({aiGuides=false}:{aiGuides?:boolean}={}){
 const zh=useLanguage(s=>s.language)==='zh',txt=(cn:string,en:string)=>zh?cn:en;
 const project=useEditor(s=>s.project),drawing=project.drawing??EMPTY,artworkId=sourceArtworkId(project.drawingSnapshots?.activeId);
 const recording=project.vectorRecording??emptyVectorRecording(),rig=recording.rigs.find(r=>r.artworkId===artworkId);
 const stale=!!rig&&rig.sourceSignature!==drawingSignature(drawing),[recovering,setRecovering]=useState(false);
 useEffect(()=>{if(!rig){const s=useEditor.getState();s.setVectorRecording(ensureArtworkRig(s.project.vectorRecording??emptyVectorRecording(),artworkId,drawing));}},[rig,artworkId]);
 useEffect(()=>{if(!stale)return;let live=true;setRecovering(true);void useEditor.getState().recoverVectorRecordingSource().catch(()=>false).finally(()=>{if(live)setRecovering(false);});return()=>{live=false;};},[rig,drawing,stale]);
 if(!rig)return <div className="vector-loading" role="status">{txt('准备矢量录制…','Preparing vector recording…')}</div>;
 if(stale&&recovering)return <div className="vector-loading" role="status">{txt('正在同步绘制源稿，保留现有 Warp 与关键形…','Synchronizing Drawing source; keeping existing Warps and keyforms…')}</div>;
 if(stale)return <section className="vr-source-review" role="alert"><h2>{txt('源画稿需要兼容性检查','Source artwork needs a compatibility check')}</h2>{changedIntervalTracks(rig,drawing).size>0&&<p className="vr-error">{txt('贯通改变显隐路径，相关区间角度键需重新录制。接受后会清除这些区间的角度覆盖与启用键；其它关键形保留。','Through routing changed interval semantics. Accepting resets affected interval appearance and enable keys for re-authoring; unrelated keyforms remain.')}</p>}<p>{txt('同拓扑几何修改会自动同步。此稿的结构或显示路径已改变，部分区间材料无法精确迁移，或旧版本没有足够源稿记录来确认兼容性。原有 Warp 和角度关键形仍在；已删除图层的挂接会清理，新图层需要重新挂接。显示路径坐标系改变的区间覆盖会回到新的源区间，避免把旧百分比误套到新路径；接受后请复查各角度的拟合与显隐。','Same-topology geometry edits sync automatically. This source has structural/display-path changes, some interval material cannot be transferred exactly, or its older version lacks enough source evidence to verify compatibility. Existing Warps and keyforms are still retained. Deleted-layer bindings are removed; new layers must be bound. Interval overrides whose display coordinate frame changed return to the new source ranges rather than reusing old percentages. Review fit and visibility after accepting.')}</p><button data-testid="vr-accept-source" onClick={()=>useEditor.getState().commitVectorRecording(replaceRig(recording,acceptArtworkSource(rig,drawing)))}>{txt('使用更新后的源画稿，保留关键形','Use updated source; keep keyforms')}</button><button onClick={()=>useWorkspaceMode.getState().setMode('drawing')}>{txt('返回绘制模式检查','Return to Drawing')}</button></section>;
 return <RigEditor key={rig.id} {...{recording,rig,drawing,zh,txt,aiGuides}} artworkName={project.drawingSnapshots?.items.find(a=>a.id===artworkId)?.name??txt('当前画稿','Current artwork')}/>;
}
function RigEditor({recording,rig,drawing,zh,txt,artworkName,aiGuides}:{aiGuides:boolean;recording:VectorRecording;rig:ArtworkRig;drawing:typeof EMPTY;zh:boolean;txt:(cn:string,en:string)=>string;artworkName:string}){
 const showFills=useDrawing(s=>s.showFills);
 const [deformerId,setDeformerId]=useState(rig.deformers[0]?.id??''),[layerIds,setLayerIds]=useState<string[]>([]),[selection,setSelection]=useState<number[]>([]),[selectionMode,setSelectionMode]=useState<'node'|'row'|'column'>('node');
 const [parameterTick,setParameterTick]=useState(0),[parametersMoving,setParametersMoving]=useState(false),[localEdit,setLocalEdit]=useState(true),[showGrid,setShowGrid]=useState(true),[showHandles,setShowHandles]=useState(false),[rows,setRows]=useState(3),[columns,setColumns]=useState(3),[size,setSize]=useState({width:800,height:650}),[pan,setPan]=useState<Point2>([0,0]),[zoom,setZoom]=useState(1),[preview,setPreview]=useState<VectorPose|null>(null),[box,setBox]=useState<{a:Point2;b:Point2}|null>(null),[error,setError]=useState(''),[guideSnap,setGuideSnap]=useState<{point:Point2;kind:string}|null>(null);
 const host=useRef<HTMLDivElement>(null),svg=useRef<SVGSVGElement>(null),drag=useRef<Drag|null>(null),space=useRef(false),previewRef=useRef<VectorPose|null>(null),nudge=useRef<VectorPose|null>(null),nudgeKeys=useRef(new Set<string>());
 const storedPose=useMemo(()=>currentPose(rig,drawing),[rig,drawing]),pose=preview??storedPose,deformer=rig.deformers.find(d=>d.id===deformerId),grid=deformer&&(pose.grids[deformer.id]??deformer.grid);
 useEffect(()=>{if(!rig.deformers.some(d=>d.id===deformerId)){setDeformerId(rig.deformers[0]?.id??'');setSelection([]);}},[rig.deformers,deformerId]);
 useEffect(()=>{const h=host.current;if(!h)return;const observer=new ResizeObserver(entries=>{const r=entries[0].contentRect;setSize({width:r.width,height:r.height});});observer.observe(h);return()=>observer.disconnect();},[]);
 const bounds=useMemo(()=>drawingBounds(drawing),[drawing]),center:Point2=[(bounds.min[0]+bounds.max[0])/2,(bounds.min[1]+bounds.max[1])/2],baseUnit=Math.min((size.width-100)/(bounds.max[0]-bounds.min[0]),(size.height-100)/(bounds.max[1]-bounds.min[1])),unit=Math.max(1,baseUnit)*zoom;
 const screen=(p:Point2):Point2=>[size.width/2+(p[0]-center[0])*unit+pan[0],size.height/2-(p[1]-center[1])*unit+pan[1]],world=(p:Point2):Point2=>[(p[0]-size.width/2-pan[0])/unit+center[0],-(p[1]-size.height/2-pan[1])/unit+center[1]];
 const at=(e:{clientX:number;clientY:number}):Point2=>{const r=svg.current!.getBoundingClientRect();return [e.clientX-r.left,e.clientY-r.top];};
 const childLocal=!!deformer?.parentId&&localEdit,canManipulate=!deformer?.parentId||localEdit;
 const evaluated=useMemo(()=>{let source=applyVisibility(drawing,pose);const included=new Set(drawing.layers.filter(layer=>{let id=rig.bindings[layer.id];while(id){if(id===deformerId)return true;id=rig.deformers.find(d=>d.id===id)?.parentId??'';}return false;}).flatMap(layer=>layer.items));
  if(childLocal)source={...source,curves:source.curves.map(c=>({...c,visible:c.visible&&included.has(c.id)})),fills:source.fills.map(f=>({...f,visible:f.visible&&included.has(f.id)})),offsets:source.offsets.map(o=>({...o,visible:o.visible&&included.has(o.id)}))};
  return deformDrawing(source,(curveId:string)=>childLocal&&!included.has(curveId)?[]:deformerChain(rig,layerFor(drawing,curveId)?.id??'',pose,childLocal?deformerId:undefined),{tolerance:recording.tolerance,diagnostics:preview||parametersMoving?'preview':'full'});
 },[drawing,pose,rig,recording.tolerance,childLocal,deformerId,!!preview,parametersMoving]);
 const routeDiagnostics=useMemo(()=>displayRouteDiagnostics(evaluated.drawing),[evaluated.drawing]);
 const activeKey=rig.keys.find(k=>sameAngle(k.angle,rig.angle));
 function commit(next:ArtworkRig){useEditor.getState().commitVectorRecording(replaceRig(recording,next));setError('');}
 function safe(action:()=>void){try{action();}catch(e){setError((e as Error).message);}}
 function setPose(next:VectorPose){commit({...rig,draft:next});}
 function changeAngle(axis:'x'|'y',value:number){safe(()=>{const next=setRigAngle(rig,{...rig.angle,[axis]:value});setParameterTick(n=>n+1);setParametersMoving(true);useEditor.getState().setVectorRecording(replaceRig(recording,next));});}
 function chooseAngle(x:number,y:number){safe(()=>{const next=setRigAngle(rig,{x,y});setParameterTick(n=>n+1);setParametersMoving(true);useEditor.getState().setVectorRecording(replaceRig(recording,next));});}
 useEffect(()=>{const timer=setTimeout(()=>setParametersMoving(false),140);return()=>clearTimeout(timer);},[parameterTick,rig.angle.x,rig.angle.y]);
 function withGrid(next:WarpGrid,base=storedPose):VectorPose{return {...base,grids:{...base.grids,[deformerId]:next}};}
 function begin(e:React.PointerEvent,index:number,handle?:'handleU'|'handleV'){
  if(!grid||!canManipulate||e.button!==0)return;e.stopPropagation();e.preventDefault();svg.current!.focus({preventScroll:true});svg.current!.setPointerCapture(e.pointerId);
  let indices=[index];if(!handle&&selectionMode==='row'){const row=Math.floor(index/(grid.columns+1));indices=grid.nodes.map((_,i)=>i).filter(i=>Math.floor(i/(grid.columns+1))===row);}else if(!handle&&selectionMode==='column'){const column=index%(grid.columns+1);indices=grid.nodes.map((_,i)=>i).filter(i=>i%(grid.columns+1)===column);}
  if(e.shiftKey)indices=[...new Set([...selection,...indices])];else if(!handle&&selection.includes(index)&&selectionMode==='node')indices=selection;
  setSelection(indices);drag.current={kind:handle?'handle':'nodes',start:world(at(e)),client:at(e),pose:storedPose,indices,handle,index};
 }
 function move(e:React.PointerEvent){const d=drag.current;if(!d)return;const p=at(e);if(d.kind==='pan'){setPan([d.pan![0]+p[0]-d.client[0],d.pan![1]+p[1]-d.client[1]]);return;}if(d.kind==='box'){setBox({a:d.client,b:p});return;}if(!deformer)return;
  const base=d.pose.grids[deformerId]??deformer.grid,q=world(p);let delta:Point2=[q[0]-d.start[0],q[1]-d.start[1]];const anchor=d.index===undefined?null:d.kind==='handle'?base.nodes[d.index][d.handle!]:base.nodes[d.index].position,hit=anchor&&!e.altKey?snapWorkspacePoint(evaluated.drawing,useEditor.getState().project.drawingSnapshots,getWorkspaceView(),[anchor[0]+delta[0],anchor[1]+delta[1]],1/unit):null;if(hit&&anchor)delta=[hit.point[0]-anchor[0],hit.point[1]-anchor[1]];setGuideSnap(hit);let next=base;
  if(d.kind==='handle'){next={...base,nodes:base.nodes.map((n,i)=>i===d.index?{...n,[d.handle!]:[n[d.handle!][0]+delta[0],n[d.handle!][1]+delta[1]]}:n)};}
  else for(const i of d.indices)next=moveWarpNode(next,i,[base.nodes[i].position[0]+delta[0],base.nodes[i].position[1]+delta[1]]);
  previewRef.current=withGrid(next,d.pose);setPreview(previewRef.current);
 }
 function finish(e:React.PointerEvent){const d=drag.current;if(!d)return;drag.current=null;setGuideSnap(null);if(svg.current?.hasPointerCapture(e.pointerId))svg.current.releasePointerCapture(e.pointerId);
  if(d.kind==='box'&&box&&grid){const min=[Math.min(box.a[0],box.b[0]),Math.min(box.a[1],box.b[1])],max=[Math.max(box.a[0],box.b[0]),Math.max(box.a[1],box.b[1])];const ids=grid.nodes.map((n,i)=>({i,p:screen(n.position)})).filter(({p})=>p[0]>=min[0]&&p[0]<=max[0]&&p[1]>=min[1]&&p[1]<=max[1]).map(x=>x.i);setSelection(e.shiftKey?[...new Set([...selection,...ids])]:ids);}
  if(previewRef.current)setPose(previewRef.current);previewRef.current=null;setPreview(null);setBox(null);
 }
 function cancel(){drag.current=null;setGuideSnap(null);nudge.current=null;nudgeKeys.current.clear();previewRef.current=null;setPreview(null);setBox(null);}
 useEffect(()=>{const cancelGesture=()=>cancel();window.addEventListener('contour:cancel-recording-gesture',cancelGesture);window.addEventListener('blur',cancelGesture);return()=>{window.removeEventListener('contour:cancel-recording-gesture',cancelGesture);window.removeEventListener('blur',cancelGesture);};},[]);
 useEffect(()=>{cancel();},[rig,deformerId]);
 useEffect(()=>{function key(e:KeyboardEvent){const target=e.target as HTMLElement;if(target.closest('input,select,textarea,dialog,[role=dialog],[contenteditable]'))return;
  if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z')cancel();
  if(e.code==='Space'){e.preventDefault();space.current=true;}if(e.key==='Escape'){e.preventDefault();cancel();}
  if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'&&grid){e.preventDefault();setSelection(grid.nodes.map((_,i)=>i));}
  if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&grid&&canManipulate&&selection.length&&!drag.current){e.preventDefault();nudgeKeys.current.add(e.key);const base=nudge.current??storedPose,baseGrid=base.grids[deformerId]??grid,step=(e.shiftKey?10:1)/unit,delta:Point2=[e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0,e.key==='ArrowDown'?-step:e.key==='ArrowUp'?step:0];let next=baseGrid;for(const i of selection)next=moveWarpNode(next,i,[baseGrid.nodes[i].position[0]+delta[0],baseGrid.nodes[i].position[1]+delta[1]]);nudge.current=withGrid(next,base);setPreview(nudge.current);}}
  function up(e:KeyboardEvent){if(e.code==='Space')space.current=false;if(nudgeKeys.current.delete(e.key)&&!nudgeKeys.current.size&&nudge.current){const pose=nudge.current;nudge.current=null;setPreview(null);setPose(pose);}}window.addEventListener('keydown',key);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('keyup',up);};
 },[grid,selection,storedPose,rig,recording,unit,canManipulate]);
 function toDrawing(ids:string[]=[]){cancel();useDrawing.getState().set({room:true,tool:'direct',selection:{ids}});useWorkspaceMode.getState().setMode('drawing');}
 function toggleLayer(id:string,checked:boolean){setLayerIds(checked?[...new Set([...layerIds,id])]:layerIds.filter(x=>x!==id));}
 function layerVisibility(id:string){const layer=drawing.layers.find(l=>l.id===id)!;return layer.items.some(id=>pose.visibility[id]??[...drawing.curves,...drawing.fills,...drawing.offsets].find(o=>o.id===id)?.visible);}
 function visibility(id:string){const layer=drawing.layers.find(l=>l.id===id)!,value=!layerVisibility(id);setPose({...storedPose,visibility:{...storedPose.visibility,...Object.fromEntries(layer.items.map(id=>[id,value]))}});}
 return <main className="vector-recording" data-testid="vector-recording">
  <aside className="vr-sidebar vr-left">
   <section className="vr-section"><h2>{txt('画稿 / ARTWORK','ARTWORK')}</h2><strong>{artworkName}</strong><p>{txt('源线条只在绘制模式修改；每份画稿拥有独立的角度关键形。','Source geometry is editable only in Drawing. Each artwork owns an independent rig.')}</p><button onClick={()=>toDrawing()}>{txt('打开画稿库 / 编辑源稿','Artwork library / Edit source')}</button></section>
   <section className="vr-section vr-deformers"><h2>{txt('变形器 / DEFORMERS','DEFORMERS')}<span>{rig.deformers.length}</span></h2>
    {rig.deformers.length===0&&<p>{txt('选择下方图层，创建第一个 Warp。角度本身不会自动生成侧脸。','Select layers below and create a Warp. Angles do not generate a side view automatically.')}</p>}
    <div className="vr-tree">{rig.deformers.map(d=>{let depth=0,p=d.parentId;while(p&&depth<10){depth++;p=rig.deformers.find(x=>x.id===p)?.parentId;}return <button key={d.id} className={d.id===deformerId?'selected':''} style={{paddingLeft:10+depth*14}} onClick={()=>{cancel();setDeformerId(d.id);setSelection([]);}} data-testid="vr-deformer">◇ {d.name}<small>{Object.values(rig.bindings).filter(id=>id===d.id).length}</small></button>;})}</div>
    <div className="vr-grid-count"><label>{txt('行','Rows')}<input aria-label="Warp rows" type="number" min="1" max="8" value={rows} onChange={e=>setRows(Math.max(1,Math.min(8,Number(e.target.value)||1)))}/></label><label>{txt('列','Columns')}<input aria-label="Warp columns" type="number" min="1" max="8" value={columns} onChange={e=>setColumns(Math.max(1,Math.min(8,Number(e.target.value)||1)))}/></label></div>
    <button className="vr-primary" data-testid="vr-add-warp" onClick={()=>safe(()=>{const next=addDeformer(rig,drawing,layerIds,undefined,rows,columns);commit(next);setDeformerId(next.deformers.at(-1)!.id);setSelection([]);})}>{txt('＋ 创建 Warp 变形器','＋ Create Warp deformer')}</button>
    {deformer&&<><label className="vr-field">{txt('名称','Name')}<input aria-label="Deformer name" value={deformer.name} onChange={e=>{const name=e.target.value;if(name.trim())commit({...rig,deformers:rig.deformers.map(d=>d.id===deformerId?{...d,name}:d)});}}/></label><label className="vr-field">{txt('父变形器','Parent')}<select aria-label="Parent deformer" value={deformer.parentId??''} onChange={e=>safe(()=>commit(setDeformerParent(rig,deformer.id,e.target.value||undefined)))}><option value="">{txt('根层级','Root')}</option>{rig.deformers.filter(d=>d.id!==deformer.id).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button onClick={()=>safe(()=>{const next=addDeformer(rig,drawing,layerIds,deformer.id,rows,columns);commit(next);setDeformerId(next.deformers.at(-1)!.id);setSelection([]);})}>{txt('＋ 创建子 Warp','＋ Add child Warp')}</button><button className="vr-muted-button" onClick={()=>{commit(removeDeformer(rig,deformer.id));setSelection([]);}}>{txt('移除变形器（可撤销）','Remove deformer (undoable)')}</button></>}
   </section>
   <section className="vr-section vr-layers"><h2>{txt('图层 / LAYERS','LAYERS')}<button onClick={()=>setLayerIds(layerIds.length===drawing.layers.length?[]:drawing.layers.map(l=>l.id))}>{txt('全选','All')}</button></h2>
    {deformer&&<div className="vr-bind-actions"><button disabled={!layerIds.length} data-testid="vr-bind-layers" onClick={()=>commit({...rig,bindings:{...rig.bindings,...Object.fromEntries(layerIds.map(id=>[id,deformer.id]))}})}>{txt('挂接所选图层','Bind selected')}</button><button disabled={!layerIds.length} onClick={()=>commit({...rig,bindings:Object.fromEntries(Object.entries(rig.bindings).filter(([id])=>!layerIds.includes(id)))})}>{txt('解除','Unbind')}</button></div>}
    {drawing.layers.map(l=><div key={l.id} className={`vr-layer ${layerIds.includes(l.id)?'selected':''}`}><input type="checkbox" aria-label={`${txt('选择图层','Select layer')} ${l.name}`} checked={layerIds.includes(l.id)} onChange={e=>toggleLayer(l.id,e.target.checked)}/><button title={txt('此角度显隐（不改变源稿）','Visibility at this angle (source unchanged)')} aria-label={`${txt('显隐','Visibility')} ${l.name}`} onClick={()=>visibility(l.id)}>{layerVisibility(l.id)?'◉':'○'}</button><span title={l.name}>{l.name}<small>{rig.deformers.find(d=>d.id===rig.bindings[l.id])?.name??txt('未挂接','Unbound')}</small></span></div>)}
   </section>
  </aside>
  <section className="vr-center">
   <header className="vr-canvas-toolbar">{deformer?.parentId&&<button data-testid="vr-local-edit" aria-pressed={localEdit} onClick={()=>{cancel();setLocalEdit(!localEdit);}}>{localEdit?txt('局部编辑 · 切换全局预览','Local edit · Global preview'):txt('全局预览 · 返回局部编辑','Global preview · Local edit')}</button>}<div className="vr-segmented">{(['node','row','column'] as const).map(mode=><button key={mode} aria-pressed={selectionMode===mode} onClick={()=>setSelectionMode(mode)}>{mode==='node'?txt('节点','Nodes'):mode==='row'?txt('整行','Row'):txt('整列','Column')}</button>)}</div><button disabled={!grid} onClick={()=>grid&&setSelection(grid.nodes.map((_,i)=>i))}>{txt('全选网格','All nodes')}</button><button aria-pressed={showGrid} onClick={()=>setShowGrid(!showGrid)}>{txt('网格','Grid')}</button><button data-testid="vr-show-fills" aria-pressed={showFills} title={txt('仅切换填充显示，不修改源稿、姿态或导出','View only; source, poses and exports stay unchanged')} onClick={()=>useDrawing.getState().set({showFills:!showFills})}>{txt('填充','Fills')}</button><button aria-pressed={showHandles} onClick={()=>setShowHandles(!showHandles)}>{txt('Bézier 柄','Bézier handles')}</button><span>{selection.length} {txt('节点','nodes')}</span><button onClick={()=>{setZoom(1);setPan([0,0]);}}>{txt('适应','Fit')}</button></header>
   <div ref={host} className="vr-canvas-host"><svg ref={svg} width={size.width} height={size.height} data-testid="vr-canvas" aria-label={txt('矢量 Warp 画布','Vector Warp canvas')} tabIndex={0} onPointerMove={move} onPointerUp={finish} onPointerCancel={cancel} onLostPointerCapture={()=>{if(drag.current)cancel();}} onPointerDown={e=>{if(e.button!==0&&e.button!==1)return;svg.current!.focus();e.preventDefault();svg.current!.setPointerCapture(e.pointerId);const p=at(e);if(space.current||e.button===1)drag.current={kind:'pan',start:world(p),client:p,pose:storedPose,indices:[],pan};else{drag.current={kind:'box',start:world(p),client:p,pose:storedPose,indices:[]};setBox({a:p,b:p});}}} onWheel={e=>{const factor=Math.exp(-e.deltaY*.001),z=Math.max(.15,Math.min(6,zoom*factor));setZoom(z);}}>
    <rect width="100%" height="100%" fill="#f6f7f5"/>
    <ArtworkReference screen={screen} unit={unit}/>
    <g pointerEvents="none"><PaintScene d={evaluated.drawing} screen={screen} unit={unit} pixelsPerUnit={unit} preview showFills={showFills} referenceMoving={false} tool="select" curveDown={noop} paintDown={noop} arcDown={noop}/></g>
    <g pointerEvents="none">{evaluated.diagnostics.filter(d=>d.warning).map(d=><path key={d.sourceCurveId} data-testid="vr-fit-warning" data-source-id={d.sourceCurveId} d={curvePath(d.cubic,screen)} fill="none" stroke="#db3948" strokeWidth="2.5"/>)}</g>
    {showGrid&&grid&&canManipulate&&<g className="vr-grid" data-testid="vr-grid">
     {Array.from({length:grid.rows+1},(_,row)=>{const points=Array.from({length:grid.columns+1},(_,col)=>grid.nodes[row*(grid.columns+1)+col]);let d='';points.forEach((n,i)=>{const p=screen(n.position);if(!i)d=`M ${p}`;else{const before=points[i-1],a=screen(before.handleU),b=screen([2*n.position[0]-n.handleU[0],2*n.position[1]-n.handleU[1]]);d+=` C ${a} ${b} ${p}`;}});return <path key={`r${row}`} d={d}/>;})}
     {Array.from({length:grid.columns+1},(_,col)=>{const points=Array.from({length:grid.rows+1},(_,row)=>grid.nodes[row*(grid.columns+1)+col]);let d='';points.forEach((n,i)=>{const p=screen(n.position);if(!i)d=`M ${p}`;else{const before=points[i-1],a=screen(before.handleV),b=screen([2*n.position[0]-n.handleV[0],2*n.position[1]-n.handleV[1]]);d+=` C ${a} ${b} ${p}`;}});return <path key={`c${col}`} d={d}/>;})}
     {grid.nodes.map((n,i)=>{const p=screen(n.position),selected=selection.includes(i);return <g key={i}>{showHandles&&selected&&(['handleU','handleV'] as const).map(h=>{const a=screen(n[h]);return <g key={h}><line x1={p[0]} y1={p[1]} x2={a[0]} y2={a[1]}/><circle className="vr-handle" data-testid="vr-handle" data-node={i} data-handle={h} cx={a[0]} cy={a[1]} r="4" onPointerDown={e=>begin(e,i,h)}/></g>})}<circle data-testid="vr-node" data-index={i} data-selected={selected} className={selected?'selected':''} cx={p[0]} cy={p[1]} r={selected?5:4} onPointerDown={e=>begin(e,i)}/></g>;})}
    </g>}
    {aiGuides&&<><AIGuideOverlay d={evaluated.drawing} curveIds={[...evaluated.warningCurveIds,...drawing.curves.filter(c=>layerIds.includes(layerFor(drawing,c.id)?.id??'')).map(c=>c.id)]} screen={screen} unit={unit} width={size.width} height={size.height}/>{evaluated.diagnostics.filter(d=>d.warning).slice(0,32).map(d=>{const p=screen(d.peakExpected);return <g key={d.sourceCurveId} pointerEvents="none" data-testid="ai-fit-location"><circle cx={p[0]} cy={p[1]} r="8" fill="none" stroke="#d12948"/><text x={p[0]+10} y={p[1]-9} fontSize="10" fill="#ab1634" paintOrder="stroke" stroke="white" strokeWidth="3">{d.sourceCurveId?.slice(0,8)} · {(d.maxError*250).toFixed(2)}px</text></g>;})}</>}
    {box&&<rect x={Math.min(box.a[0],box.b[0])} y={Math.min(box.a[1],box.b[1])} width={Math.abs(box.a[0]-box.b[0])} height={Math.abs(box.a[1]-box.b[1])} fill="#31a1e021" stroke="#338bc4" strokeDasharray="4 2" pointerEvents="none"/>}
   {guideSnap&&<g pointerEvents="none" data-testid="vr-guide-snap"><circle cx={screen(guideSnap.point)[0]} cy={screen(guideSnap.point)[1]} r={8} fill="none" stroke="#148b96" strokeWidth={2}/><text x={screen(guideSnap.point)[0]+12} y={screen(guideSnap.point)[1]-10} fill="#148b96" fontSize={12}>{txt('辅助线吸附','Guide snap')}</text></g>}<ViewGuidesOverlay screen={screen} unit={unit} width={size.width} height={size.height}/></svg><div className="vr-canvas-badge">{artworkName}{childLocal?txt(' · 子 Warp 局部坐标（父变形暂不显示）',' · Child Warp local space (ancestors excluded)'):''} · X {rig.angle.x}° / Y {rig.angle.y}°</div>{!rig.deformers.length&&<div className="vr-canvas-guide">{txt('先选择图层，再创建 Warp 网格','Select layers, then create a Warp grid')}</div>}</div>
   <footer className="vr-status"><span>{txt('源画稿锁定','Source locked')} · {drawing.curves.length} {txt('源段','source segments')}</span><span>{txt('Shift 多选 · 框选 · 空格平移 · 滚轮缩放 · Esc 取消拖动','Shift multi-select · Marquee · Space pan · Wheel zoom · Esc cancel drag')}</span><span>{Math.round(zoom*100)}%</span></footer>
  </section>
  <aside className="vr-sidebar vr-right">
   <section className="vr-section"><h2>{txt('参数 / PARAMETERS','PARAMETERS')}</h2><p>{txt('前半球范围 ±90°；每个关键形由你塑形。','Front hemisphere ±90°. Sculpt each keyform yourself.')}</p>
    <p>{txt('正面 X=0；+X 向画面右转，−X 向画面左转。+Y 仰头，−Y 低头。','Front X=0; +X turns toward screen right, −X toward screen left. +Y looks up, −Y looks down.')}</p>
    {(['x','y'] as const).map(axis=><div className="vr-parameter" key={axis}><label>Angle {axis.toUpperCase()}<input aria-label={`Angle ${axis.toUpperCase()}`} type="number" min="-90" max="90" step="1" disabled={!!rig.draft} value={rig.angle[axis]} onChange={e=>changeAngle(axis,Number(e.target.value))}/><span>°</span></label><input type="range" aria-label={`Angle ${axis.toUpperCase()} slider`} min="-90" max="90" step="1" disabled={!!rig.draft} value={rig.angle[axis]} onChange={e=>changeAngle(axis,Number(e.target.value))}/><div className="vr-ticks"><span>−90</span><button disabled={!!rig.draft} onClick={()=>changeAngle(axis,0)}>0</button><span>90</span></div></div>)}
    <div className="vr-parameter-map" data-testid="vr-parameter-map" onClick={e=>{if(rig.draft)return;const r=e.currentTarget.getBoundingClientRect();chooseAngle(Math.round((e.clientX-r.left)/r.width*180-90),Math.round(90-(e.clientY-r.top)/r.height*180));}}><span className="vr-axis-x"/><span className="vr-axis-y"/>{rig.keys.map(k=><button key={k.id} aria-label={k.name} title={`${k.name} X${k.angle.x} Y${k.angle.y}`} className="vr-map-key" style={{left:`${(k.angle.x+90)/180*100}%`,top:`${(90-k.angle.y)/180*100}%`}} onClick={e=>{e.stopPropagation();chooseAngle(k.angle.x,k.angle.y);}}/>)}<i style={{left:`${(rig.angle.x+90)/180*100}%`,top:`${(90-rig.angle.y)/180*100}%`}}/></div>
   </section>
   <section className="vr-section"><h2>{txt('关键形 / KEYFORMS','KEYFORMS')}</h2><div className={`vr-save-state ${rig.draft?'dirty':''}`} data-testid="vr-pose-status">{rig.draft?txt('● 姿态草稿 · 未写入关键形','● Draft pose · not saved to a keyform'):activeKey?txt('◆ 已保存关键形','◆ Saved keyform'):txt('◇ 插值预览 · 尚无关键形','◇ Interpolated preview · no keyform')}</div><button data-testid="vr-save-key" className="vr-primary" onClick={()=>commit(saveKeyform(rig,undefined,drawing))}>{activeKey?txt('更新当前关键形','Update keyform'):txt('＋ 创建此角度关键形','＋ Create keyform here')}</button>{rig.draft&&<button data-testid="vr-discard-draft" onClick={()=>commit(discardDraft(rig))}>{txt('放弃姿态草稿','Discard pose draft')}</button>}<p>{txt('草稿自动保存在工程中。先更新或放弃，再切换参数；画稿与关键形分别保存。','Drafts autosave with the project. Save or discard before changing parameters. Artwork and keyforms are separate.')}</p>{activeKey&&!rig.draft&&<><label className="vr-field">{txt('关键形名称','Keyform name')}<input key={activeKey.id+activeKey.name} aria-label="Keyform name" defaultValue={activeKey.name} onBlur={e=>{const name=e.target.value.trim();if(name&&name!==activeKey.name)commit({...rig,keys:rig.keys.map(k=>k.id===activeKey.id?{...k,name}:k)});}}/></label><button disabled={(activeKey.angle.x===0&&[-90,0,90].includes(activeKey.angle.y))||(activeKey.angle.y===0&&[-90,0,90].includes(activeKey.angle.x))} onClick={()=>commit({...rig,keys:rig.keys.filter(k=>k.id!==activeKey.id)})}>{txt('删除此中间关键形','Delete intermediate keyform')}</button></>}<button disabled={!rig.deformers.length} onClick={()=>setPose({...storedPose,grids:Object.fromEntries(rig.deformers.map(d=>[d.id,d.grid]))})}>{txt('只重置此角度网格（草稿）','Reset only this angle’s grids (draft)')}</button><div className="vr-key-list">{rig.keys.map(k=><button key={k.id} disabled={!!rig.draft} aria-pressed={activeKey?.id===k.id} onClick={()=>chooseAngle(k.angle.x,k.angle.y)}><span>◆ {k.name}</span><small>{k.angle.x} / {k.angle.y}</small></button>)}</div></section>
   <IntervalPoseControls drawing={drawing} pose={storedPose} layerIds={layerIds} onChange={setPose}/>
   <section className="vr-section"><h2>{txt('拟合检查 / FIT','CUBIC FIT')}</h2><label className="vr-field">{txt('误差阈值 / px','Tolerance / px')}<input aria-label="Fit tolerance pixels" type="number" min=".1" max="20" step=".1" value={Number((recording.tolerance*250).toFixed(2))} onChange={e=>{const value=Number(e.target.value);if(Number.isFinite(value)&&value>=.1&&value<=20)useEditor.getState().commitVectorRecording({...recording,tolerance:value/250});}}/></label><p>{txt('每个源段始终只输出一条 Bézier。红色超差段需回绘制模式分段；不会偷偷加点。','Exactly one output Bézier per source segment. Split red over-tolerance segments in Drawing; topology is never silently changed.')}</p>{evaluated.diagnostics.some(d=>d.endpointConflict)&&<p className="vr-error" data-testid="vr-endpoint-conflict-guidance">{txt('联动端点仍保持重合，但不同变形域请求的位置冲突。请对齐网格控制或使用共同父变形器；给源线分段不能解决此约束冲突。','Linked endpoints remain coincident, but their deformation fields request different positions. Align the controls or use a shared parent deformer; source subdivision cannot resolve this constraint conflict.')}</p>}{!!evaluated.intervalTransportErrors.length&&<p className="vr-error">{evaluated.intervalTransportErrors.length} {txt('个显示区间无法可靠传递；请检查折叠或退化段。','intervals could not be transported reliably; inspect folds or degenerate segments.')}</p>}{routeDiagnostics.map((message,i)=><p key={'route:'+i} className="vr-error" data-testid="vr-route-diagnostic">{message}</p>)}{evaluated.diagnosticStage==='preview'&&<p>{txt('拖动中的快速误差预览；松开后进行完整采样检查。','Fast error preview while dragging; full sampled checks after release.')}</p>}<strong className={evaluated.warningCurveIds.length?'vr-error':''}>{evaluated.diagnostics.filter(d=>d.exceedsTolerance).length} {txt('段超差','over tolerance')} · {evaluated.diagnostics.filter(d=>d.endpointConflict).length} {txt('端点冲突','endpoint conflicts')} · max {(evaluated.maxError*250).toFixed(2)} px</strong>{evaluated.warningCurveIds.length>0&&<button onClick={()=>toDrawing(evaluated.warningCurveIds)}>{txt('回绘制模式检查红色段','Inspect flagged sources in Drawing')}</button>}</section>
   {error&&<div className="vr-error" role="alert">{error}</div>}
  </aside>
 </main>;
}
