import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {useEditor} from '../../app/store';
import {useWorkspaceMode} from '../../app/workspaceMode';
import {recordingSceneSources} from '../../app/recordingSceneSources';
import {prepareSceneBatch} from '../../app/recordingSceneApi';
import {evaluateScene} from '../../domain/recordingScene/evaluation';
import {evaluateDepthTrack,evaluateIntervalTrack,evaluatePlacementTrack,composePlacementSimilarity,applyScenePlacementMatrix,tryInverseScenePlacement,scenePlacementScales,setScenePlacementAxisScale} from '../../domain/recordingScene/tracks';
import {identityScenePlacement,layerTrackIds,sceneLayerKey,type ScenePlacementValue,type RecordingScene,type SceneLayerRef,type WarpGrid} from '../../domain/recordingScene/model';
import type {SceneCommand} from '../../domain/recordingScene/commands';
import {sameAngle,type Angle} from '../../domain/vectorRecording/interpolation';
import {drawingSignature} from '../../domain/vectorRecording/model';
import {planArtworkLayerImport} from '../../domain/drawing/importArtworkLayers';
import {inkTaperDistance,type DrawingDocument} from '../../domain/drawing/model';
import {selectedLayers,type DrawingSelection} from '../drawing/session';
import {selectListRows} from '../drawing/listSelection';
import {selectionBounds} from '../drawing/geometry';
import {useLanguage} from '../i18n';
import SceneWarpCanvas,{type RecordingCurveEdit} from './SceneWarpCanvas';
import SceneLayerPanel from './SceneLayerPanel';
import SceneAnglePad from './SceneAnglePad';
import SceneOnionSkin,{SceneOnionControls,useSceneOnionFrames,DEFAULT_SCENE_ONION_SETTINGS} from './SceneOnionSkin';
import {useRecordingReference} from './RecordingReferenceControls';
import WorkspaceViewPanel from '../workspaceView/WorkspaceViewPanel';
import {useFloatingPanel} from '../shared/useFloatingPanel';
import {sceneSelectionPayload} from './sceneSelection';
import {sceneLayerWarpSelection,sceneWarpAction,pruneRemovedSceneInstanceSelection,type SceneWarpAction} from './sceneWarpSelection';
import './vectorRecording.css';

type Text=(cn:string,en:string)=>string;
/** Legacy object-key positions remain usable until first explicit view action. */
export function sceneViewEntries(scene:RecordingScene){
 const explicit=scene.viewpoints??[],all=[...scene.warps,...scene.visibilityTracks,...scene.intervalTracks,...(scene.depthTracks??[]),...(scene.placementTracks??[]),...(scene.shapeTracks??[])];
 const result=explicit.map(v=>({...v,stored:true}));
 if(scene.viewpoints===undefined)for(const t of all)for(const k of t.keys)if(!result.some(v=>sameAngle(v.angle,k.angle)))result.push({id:`existing:${k.angle.x}:${k.angle.y}`,name:`X ${k.angle.x}° / Y ${k.angle.y}°`,angle:k.angle,stored:false});
 return result.sort((a,b)=>a.angle.y-b.angle.y||a.angle.x-b.angle.x);
}
export default function SceneRecordingWorkspace({aiGuides=false}:{aiGuides?:boolean}={}){
 const project=useEditor(s=>s.project),zh=useLanguage(s=>s.language)==='zh',txt:Text=(cn,en)=>zh?cn:en;
 const recording=project.recordingScenes!,scene=recording.scenes.find(s=>s.id===recording.activeSceneId)??recording.scenes[0];
 const [name,setName]=useState(''),[error,setError]=useState('');
 const create=()=>{try{const p=prepareSceneBatch(useEditor.getState().project,{commands:[{op:'createScene',name:name.trim()||txt('录制场景','Recording scene')}]});useEditor.getState().commitRecordingScenes(p.recordingScenes);}catch(e){setError((e as Error).message);}};
 if(!scene)return <section className="vr-source-review"><h2>{txt('新建录制场景','New recording scene')}</h2><p>{txt('先建立0°或90°视角，再从右侧加载画稿并调整图层。','Establish a viewpoint, then load artwork and edit its layers on the right.')}</p><input aria-label="New scene name" value={name} onChange={e=>setName(e.target.value)}/><button data-testid="scene-create" onClick={create}>{txt('创建场景','Create scene')}</button>{error&&<p role="alert">{error}</p>}</section>;
 return <SceneEditor key={scene.id} scene={scene} {...{zh,txt,aiGuides}}/>;
}
function SceneEditor({scene,zh,txt,aiGuides}:{scene:RecordingScene;zh:boolean;txt:Text;aiGuides:boolean}){
 const project=useEditor(s=>s.project),recording=project.recordingScenes!,sources=useMemo(()=>recordingSceneSources(project),[project.drawing,project.drawingSnapshots,project.drawingWorkingCopies]);
 const resolve=useCallback((id:string)=>Object.hasOwn(sources,id)?sources[id]:undefined,[sources]);
 const [selection,setSelection]=useState<DrawingSelection>({ids:[]}),[layerRefs,setLayerRefs]=useState<SceneLayerRef[]>([]),[warpIds,setWarpIds]=useState<string[]>(scene.warps[0]?[scene.warps[0].id]:[]),[activeWarpId,setActiveWarpId]=useState(scene.warps[0]?.id??''),[previewGrid,setPreviewGrid]=useState<WarpGrid|null>(null),[localEdit,setLocalEdit]=useState(true),[rows,setRows]=useState(3),[columns,setColumns]=useState(3),[error,setError]=useState(''),[assetId,setAssetId]=useState(project.drawingSnapshots?.items[0]?.id??(project.drawing?'$working':'')),[assetLayers,setAssetLayers]=useState<string[]>([]),[viewName,setViewName]=useState(''),[newSceneName,setNewSceneName]=useState('');
 const [gridRevealKey,setGridRevealKey]=useState(0);
 const [previewShapeScene,setPreviewShapeScene]=useState<RecordingScene|null>(null);
 const [previewPlacementValue,setPreviewPlacementValue]=useState<ScenePlacementValue|null>(null);
 const [instanceIds,setInstanceIds]=useState<string[]>([]),[previewPlacement,setPreviewPlacement]=useState<ScenePlacementValue|null>(null),[activeFrameId,setActiveFrameId]=useState('');
 const instanceAnchor=useRef<string|null>(null);
 const [onion,setOnion]=useState(DEFAULT_SCENE_ONION_SETTINGS),[referenceOpen,setReferenceOpen]=useState(false);
 const referenceButton=useRef<HTMLButtonElement>(null);
 const floatingReference=useFloatingPanel({open:referenceOpen,storageKey:'contour-reference-panel-position-v1'});
 const closeReference=()=>{setReferenceOpen(false);referenceButton.current?.focus({preventScroll:true});};
 const reference=useRecordingReference(`${project.meta.createdAt}/${scene.id}`,project.drawing?.reference);
 useEffect(()=>{if(reference.moving)setReferenceOpen(false);},[reference.moving]);
 const warp=scene.warps.find(w=>w.id===activeWarpId),asset=resolve(assetId),views=sceneViewEntries(scene),currentView=views.find(v=>sameAngle(v.angle,scene.angle));
 const allTracks=[...scene.warps,...scene.visibilityTracks,...scene.intervalTracks,...(scene.depthTracks??[]),...(scene.placementTracks??[]),...(scene.shapeTracks??[])],currentDrafts=allTracks.filter(t=>t.draft&&sameAngle(t.draft.angle,scene.angle)),otherDrafts=allTracks.filter(t=>t.draft&&!sameAngle(t.draft.angle,scene.angle));
 useEffect(()=>{setAssetLayers(asset?.layers.map(l=>l.id)??[]);},[assetId]);
 useEffect(()=>{setPreviewGrid(null);setPreviewPlacement(null);setPreviewPlacementValue(null);setPreviewShapeScene(null);setInstanceIds(ids=>ids.filter(id=>scene.instances.some(i=>i.id===id)));if(activeWarpId&&!scene.warps.some(w=>w.id===activeWarpId))setActiveWarpId('');setWarpIds(ids=>ids.filter(id=>scene.warps.some(w=>w.id===id)));setLayerRefs(refs=>refs.filter(ref=>scene.instances.some(i=>i.id===ref.instanceId)));},[scene]);
 const run=useCallback((commands:SceneCommand[],history=true)=>{try{const prepared=prepareSceneBatch(useEditor.getState().project,{sceneId:scene.id,commands});if(prepared.changed){const s=useEditor.getState();history?s.commitRecordingScenes(prepared.recordingScenes):s.setRecordingScenes(prepared.recordingScenes);}setError('');return prepared;}catch(e){setError((e as Error).message);return undefined;}},[scene.id]);
 const edit=(commands:SceneCommand[])=>{if(!currentView){setError(txt('请先为当前角度建立视角。','Establish this viewpoint before editing.'));return;}return run(commands);};
 const materializeViews=():SceneCommand[]=>scene.viewpoints===undefined?views.map((v,i)=>({op:'createViewpoint',name:v.name,angle:v.angle,ref:`existing-view-${i}`})):[];
 function addView(){const commands=materializeViews();commands.push({op:'createViewpoint',name:viewName.trim()||`X ${scene.angle.x}° / Y ${scene.angle.y}°`,angle:scene.angle});if(run(commands))setViewName('');}
 function updateView(){if(!currentView)return;const commands=materializeViews(),viewpointId=currentView.stored?currentView.id:`$existing-view-${views.indexOf(currentView)}`;commands.push({op:'updateViewpoint',viewpointId});run(commands);}
 const previewScene=useMemo(()=>{
  if(previewShapeScene)return previewShapeScene;
  let next=previewGrid&&warp?{...scene,warps:scene.warps.map(w=>w.id===warp.id?{...w,draft:{angle:scene.angle,value:previewGrid}}:w)}:scene;
  if(previewPlacement&&instanceIds.length){const tracks=[...(scene.placementTracks??[])];for(const id of instanceIds){const at=tracks.findIndex(t=>t.instanceId===id),track=at>=0?tracks[at]:undefined,value=composePlacementSimilarity(track?evaluatePlacementTrack(track,scene.angle):identityScenePlacement(),previewPlacement),updated={...(track??{id:`preview:${id}`,instanceId:id,keys:[]}),draft:{angle:scene.angle,value}};if(at>=0)tracks[at]=updated;else tracks.push(updated);}next={...next,placementTracks:tracks};}
  if(previewPlacementValue&&instanceIds.length===1){const instanceId=instanceIds[0],tracks=[...(next.placementTracks??[])],at=tracks.findIndex(t=>t.instanceId===instanceId),track=at>=0?tracks[at]:undefined,updated={...(track??{id:`preview:${instanceId}`,instanceId,keys:[]}),draft:{angle:scene.angle,value:previewPlacementValue}};if(at>=0)tracks[at]=updated;else tracks.push(updated);next={...next,placementTracks:tracks};}
  return next;
 },[scene,previewGrid,warp,previewPlacement,previewPlacementValue,instanceIds,previewShapeScene]);
 const evaluated=useMemo(()=>evaluateScene(previewScene,resolve,{useDraft:true,diagnostics:previewGrid||previewPlacement||previewPlacementValue||previewShapeScene?'preview':'full',...(warp?.parentId&&localEdit?{stopAtWarpId:warp.id}:{})}),[previewScene,resolve,warp?.id,warp?.parentId,localEdit,!!previewGrid,!!previewPlacement,!!previewPlacementValue,!!previewShapeScene]);
 const onionResult=useSceneOnionFrames(scene,resolve,onion,warp?.parentId&&localEdit?warp.id:undefined);
 const globalEvaluated=useMemo(()=>warp?.parentId&&localEdit?evaluateScene(previewScene,resolve,{useDraft:true,diagnostics:'preview'}):evaluated,[previewScene,resolve,evaluated,warp?.parentId,localEdit]);
 const onPreview=useCallback((g:WarpGrid|null)=>setPreviewGrid(g),[]);
 const onWarpSelection=useCallback(()=>{if(!activeWarpId)return;setInstanceIds([]);setWarpIds([activeWarpId]);setLayerRefs([]);setSelection({ids:[]});},[activeWarpId]);
 const onCommit=useCallback((g:WarpGrid)=>{if(!activeWarpId||!currentView)return;run([{op:'editWarpNodes',warpId:activeWarpId,moveHandles:false,edits:g.nodes.map((n,index)=>({index,...n}))}]);},[activeWarpId,!!currentView,run]);
 const gridEditable=!reference.moving&&!!currentView&&!!warp&&(!warp.parentId||localEdit)&&(!warp.draft||sameAngle(warp.draft.angle,scene.angle));
 function choose(next:DrawingSelection){setInstanceIds([]);setPreviewPlacement(null);setPreviewPlacementValue(null);setPreviewShapeScene(null);setSelection(next);const ids=new Set(selectedLayers(next)),refs=globalEvaluated.layers.filter(l=>ids.has(l.compiledLayerId)).map(({instanceId,sourceLayerId})=>({instanceId,sourceLayerId}));if(!refs.length&&next.ids.length){setWarpIds([]);setLayerRefs([]);setActiveWarpId('');setGridRevealKey(k=>k+1);}else{const chosen=sceneLayerWarpSelection(scene,refs,activeWarpId);if(refs.length)setActiveFrameId(refs.at(-1)!.instanceId);setWarpIds(chosen.warpIds);setLayerRefs(chosen.layerRefs);setActiveWarpId(chosen.activeWarpId);if(refs.length&&chosen.activeWarpId)setGridRevealKey(k=>k+1);}setPreviewGrid(null);}
 function selectWarp(id:string,multiple=false){reference.setMoving(false);setPreviewShapeScene(null);setInstanceIds([]);setPreviewPlacement(null);setPreviewPlacementValue(null);setPreviewGrid(null);setActiveWarpId(id);setGridRevealKey(k=>k+1);setWarpIds(ids=>!id?[]:multiple?(ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]):[id]);if(!multiple){setLayerRefs([]);setSelection({ids:[]});}}
 function removeInstance(instanceId:string){
  window.dispatchEvent(new Event('contour:cancel-recording-gesture'));setPreviewShapeScene(null);
  const result=run([{op:'removeInstance',instanceId}]);if(!result?.changed)return;
  setPreviewGrid(null);setPreviewPlacement(null);setPreviewPlacementValue(null);setInstanceIds(ids=>ids.filter(id=>id!==instanceId));setSelection(previous=>pruneRemovedSceneInstanceSelection(previous,instanceId));setLayerRefs(previous=>previous.filter(ref=>ref.instanceId!==instanceId));
 }
 function selectInstance(id:string,mod:{shift:boolean;toggle:boolean}){
  window.dispatchEvent(new Event('contour:cancel-recording-gesture'));setPreviewShapeScene(null);reference.setMoving(false);
  const result=selectListRows(scene.instances.map(i=>({key:i.id,ids:[i.id],kind:'layer' as const})),instanceAnchor.current,id,instanceIds,mod);instanceAnchor.current=result.anchor;
  const ids=result.ids,selectedLayers=globalEvaluated.layers.filter(l=>l.included&&ids.includes(l.instanceId)),layerIds=selectedLayers.map(l=>l.compiledLayerId),items=globalEvaluated.drawing.layers.filter(l=>layerIds.includes(l.id)).flatMap(l=>l.items),curves=new Set(globalEvaluated.drawing.curves.map(c=>c.id));
  setInstanceIds(ids);setGridRevealKey(k=>k+1);setActiveFrameId(id);setLayerRefs(selectedLayers.map(({instanceId,sourceLayerId})=>({instanceId,sourceLayerId})));setWarpIds([]);setActiveWarpId('');setPreviewGrid(null);setPreviewPlacement(null);setPreviewPlacementValue(null);setSelection({ids:items.filter(id=>curves.has(id)),paintIds:items.filter(id=>!curves.has(id)),layers:layerIds,layer:layerIds.length===1?layerIds[0]:undefined});
 }
 const onPlacementPreview=useCallback((delta:ScenePlacementValue|null)=>setPreviewPlacement(delta),[]);
 const onPlacementCommit=useCallback((delta:ScenePlacementValue)=>{if(!currentView||!instanceIds.length)return;const commands:SceneCommand[]=instanceIds.map(instanceId=>{const track=scene.placementTracks?.find(t=>t.instanceId===instanceId);return{op:'setInstancePlacement',instanceId,value:composePlacementSimilarity(track?evaluatePlacementTrack(track,scene.angle):identityScenePlacement(),delta)};});run(commands);setPreviewPlacement(null);setPreviewPlacementValue(null);},[scene,instanceIds,!!currentView,run]);
 const onPlacementValuePreview=useCallback((value:ScenePlacementValue|null)=>setPreviewPlacementValue(value),[]);
 const onPlacementValueCommit=useCallback((value:ScenePlacementValue)=>{if(!currentView||instanceIds.length!==1)return;run([{op:'setInstancePlacement',instanceId:instanceIds[0],value}]);setPreviewPlacementValue(null);},[instanceIds,!!currentView,run]);
 const shapeCommand=useCallback((change:RecordingCurveEdit):SceneCommand=>{
  const compiled=change.kind==='node'?change.nodeId:change.curveId,p=globalEvaluated.provenance[compiled];if(!p)throw Error(txt('所选曲线已不在当前实例中。','The selected curve is no longer in this instance.'));
  const placement=globalEvaluated.placements[p.instanceId]??identityScenePlacement(),inverse=tryInverseScenePlacement(placement);if(!inverse)throw Error(txt('快照宽或高为 0，请先用 V 边柄或宽高数值拉开，再编辑曲线。','This snapshot has zero width or height. Expand it with V edge handles or scale values before editing curves.'));const position=applyScenePlacementMatrix(inverse,change.position);
  return change.kind==='node'?{op:'moveShapeNode',instanceId:p.instanceId,nodeId:p.sourceId,position}:{op:'moveShapeHandle',instanceId:p.instanceId,curveId:p.sourceId,end:change.end,position};
 },[globalEvaluated,txt]);
 const onShapePreview=useCallback((change:RecordingCurveEdit|null)=>{if(!change){setPreviewShapeScene(null);return;}if(!currentView)return;try{const prepared=prepareSceneBatch(useEditor.getState().project,{sceneId:scene.id,commands:[shapeCommand(change)],dryRun:true});setPreviewShapeScene(prepared.recordingScenes.scenes.find(s=>s.id===scene.id)??null);setError('');}catch(e){setError((e as Error).message);}},[scene.id,!!currentView,shapeCommand]);
 const onShapeCommit=useCallback((change:RecordingCurveEdit)=>{if(!currentView)return;try{run([shapeCommand(change)]);}catch(e){setError((e as Error).message);}setPreviewShapeScene(null);},[!!currentView,shapeCommand,run]);
 useEffect(()=>{setPreviewShapeScene(null);window.dispatchEvent(new Event('contour:cancel-recording-gesture'));},[sources]);
 function createdWarp(commands:SceneCommand[]){if(!currentView)return;const materialized=materializeViews(),result=run([...materialized,...(materialized.length?[{op:'setAngle' as const,angle:scene.angle}]:[]),...commands]);if(!result)return;const added=result.recordingScenes.scenes.find(s=>s.id===scene.id)?.warps.find(w=>!scene.warps.some(old=>old.id===w.id));if(added)selectWarp(added.id);}
 function affects(warpId:string,leafId:string){let id:string|undefined=leafId;const seen=new Set<string>();while(id&&!seen.has(id)){if(id===warpId)return true;seen.add(id);id=scene.warps.find(w=>w.id===id)?.parentId;}return false;}
 function sourceName(id:string){return project.drawingSnapshots?.items.find(a=>a.id===id)?.name??(id==='$working'?txt('未保存画稿','Unsaved artwork'):id);}
 const sourceDependencies=useMemo(()=>{if(!asset||!assetLayers.length)return;try{return planArtworkLayerImport(asset,assetLayers);}catch{return undefined;}},[asset,assetLayers]);
 const guideLabels=useMemo(()=>Object.fromEntries(Object.entries(evaluated.provenance).map(([id,p])=>[id,`${scene.instances.find(i=>i.id===p.instanceId)?.name.slice(0,14)??'实例'} · ${p.sourceId.slice(0,8)}`])),[evaluated.provenance,scene.instances]);
 const guideCurveIds=[...new Set([...evaluated.warningCurveIds,...selection.ids,...evaluated.source.layers.filter(l=>scene.bindings.some(b=>evaluated.layerMap[sceneLayerKey(b)]===l.id&&warpIds.some(id=>affects(id,b.warpId)))).flatMap(l=>l.items).filter(id=>evaluated.source.curves.some(c=>c.id===id))])];
 const shapeSelectionIds=!warp&&!instanceIds.length&&!layerRefs.length?[...new Set(selection.ids.map(id=>globalEvaluated.provenance[id]?.instanceId).filter(Boolean))]:[];
 const objectInstanceIds=instanceIds.length?instanceIds:shapeSelectionIds;
 const selected=objectInstanceIds.length?{instanceIds:objectInstanceIds}:sceneSelectionPayload(warpIds,layerRefs),canSave=!!currentView&&(!!objectInstanceIds.length||!!warpIds.length||!!layerRefs.length),selectedObjects=[...scene.instances.filter(i=>objectInstanceIds.includes(i.id)).map(i=>({id:i.id,name:i.name+' · '+txt('实例姿态','Instance pose'),tracks:[...(scene.placementTracks??[]),...(scene.shapeTracks??[])].filter(t=>t.instanceId===i.id) as KeyedTrack[]})),...scene.warps.filter(w=>warpIds.includes(w.id)).map(w=>({id:w.id,name:w.name,tracks:[w] as KeyedTrack[]})),...(instanceIds.length?[]:layerRefs).map(ref=>{const ids=new Set(layerTrackIds(scene,ref,resolve)),instance=scene.instances.find(i=>i.id===ref.instanceId),layer=instance&&resolve(instance.artworkId)?.layers.find(l=>l.id===ref.sourceLayerId);return{id:sceneLayerKey(ref),name:`${instance?.name} / ${layer?.name}`,tracks:allTracks.filter(t=>ids.has(t.id)) as KeyedTrack[]};})];
 const trackName=(id:string)=>scene.warps.find(w=>w.id===id)?.name??(scene.shapeTracks?.some(t=>t.id===id)?txt('曲线形变','Curve shape'):scene.placementTracks?.some(t=>t.id===id)?txt('快照变换','Placement'):scene.intervalTracks.some(t=>t.id===id)?txt('显示区间','Display interval'):scene.depthTracks?.some(t=>t.id===id)?txt('层序','Layer order'):txt('显隐','Visibility'));
 const localDiagnostics=evaluated.diagnostics.filter(d=>d.code==='LOCAL_SPACE'),otherDiagnostics=evaluated.diagnostics.filter(d=>d.code!=='LOCAL_SPACE');
 const curveEditActive=!warp&&!instanceIds.length&&!layerRefs.length&&selection.ids.length>0;
 const shapeInstances=[...new Set(selection.ids.map(id=>globalEvaluated.provenance[id]?.instanceId).filter(Boolean))];
 const shapeSingular=shapeInstances.some(id=>!tryInverseScenePlacement(globalEvaluated.placements[id]??identityScenePlacement()));
 const curveEditable=!shapeSingular&&!reference.moving&&!!currentView&&shapeInstances.every(id=>{const track=scene.shapeTracks?.find(t=>t.instanceId===id);return !track?.draft||sameAngle(track.draft.angle,scene.angle);});
 const placementIds=globalEvaluated.drawing.curves.filter(c=>instanceIds.includes(globalEvaluated.provenance[c.id]?.instanceId)&&c.visible).map(c=>c.id),placementBounds=selectionBounds(globalEvaluated.drawing,placementIds);
 const placementMaterialBounds=instanceIds.length===1?selectionBounds(globalEvaluated.prePlacementDrawing,placementIds):null;
 const placementValue=instanceIds.length===1?globalEvaluated.placements[instanceIds[0]]??identityScenePlacement():undefined;
 const placementEditable=!reference.moving&&!!currentView&&instanceIds.every(id=>{const t=scene.placementTracks?.find(t=>t.instanceId===id);return !t?.draft||sameAngle(t.draft.angle,scene.angle);});
 const frameInstances=warp?scene.instances.filter(i=>scene.bindings.some(b=>b.instanceId===i.id&&affects(warp.id,b.warpId))):[],frameInstance=frameInstances.find(i=>i.id===activeFrameId)??frameInstances[0];
 const gridPlacement=frameInstance?evaluated.placements[frameInstance.id]:undefined,ghostGridPlacements=frameInstances.filter(i=>i!==frameInstance).map(i=>({instanceId:i.id,name:i.name,value:evaluated.placements[i.id]??identityScenePlacement()}));
 const warpAction=sceneWarpAction(scene,layerRefs);
 const selectedPlacementFrames=new Set(layerRefs.map(ref=>JSON.stringify(globalEvaluated.placements[ref.instanceId]??identityScenePlacement())));
 const warpControls=<>{selectedPlacementFrames.size>1&&<small data-testid="scene-placement-warp-note">{txt('所选快照放置不同：共享 Warp 在原域编辑，各快照显示各自投影框。','Different snapshot placements: the shared Warp edits its original domain, with a projected cage per snapshot.')}</small>}<div className="vr-grid-count"><label>{txt('行','Rows')}<input aria-label="Warp rows" type="number" min="1" max="16" value={rows} onChange={e=>setRows(Math.max(1,Math.min(16,Number(e.target.value)||1)))}/></label><label>{txt('列','Columns')}<input aria-label="Warp columns" type="number" min="1" max="16" value={columns} onChange={e=>setColumns(Math.max(1,Math.min(16,Number(e.target.value)||1)))}/></label></div><SceneWarpSelectionControl action={warpAction} currentView={!!currentView} txt={txt} onCreate={()=>createdWarp([{op:'createWarp',layerRefs,rows,columns}])} onShow={id=>{reference.setMoving(false);setPreviewGrid(null);setActiveWarpId(id);setGridRevealKey(k=>k+1);setError('');}}/>{!!warpIds.length&&<button data-testid="scene-wrap-parent" disabled={!currentView} onClick={()=>createdWarp([{op:'wrapParent',warpIds,rows,columns}])}>{txt('包为父 Warp','Wrap in parent Warp')}</button>}{warp&&warpAction.kind==='show'&&warpAction.warpId===warp.id&&<button data-testid="scene-create-child" disabled={!currentView} onClick={()=>createdWarp([{op:'createChild',parentWarpId:warp.id,layerRefs,rows,columns}])}>{txt('加入子 Warp','Create child Warp')}</button>}</>;
 return <main className="vector-recording vr-view-workflow" data-testid="recording-scene">
  <aside className="vr-sidebar vr-left" data-testid="scene-viewpoint-panel">
   <section className="vr-section"><h2>{txt('录制 · 视角','RECORDING · VIEWPOINTS')}</h2><select aria-label="Recording scene" value={scene.id} onChange={e=>run([{op:'selectScene',sceneId:e.target.value}])}>{recording.scenes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><details><summary>{txt('新建场景','New scene')}</summary><input aria-label="New scene name" value={newSceneName} onChange={e=>setNewSceneName(e.target.value)}/><button data-testid="scene-create" onClick={()=>run([{op:'createScene',name:newSceneName.trim()||txt('录制场景','Recording scene')}])}>{txt('新建空场景','New empty scene')}</button></details></section>
   <section className="vr-section vr-angle-section"><h2>{txt('视角坐标','VIEWPOINT COORDINATES')}<span>{currentView?txt('已建立','Established'):txt('预览位置','Preview only')}</span></h2>
    <SceneAnglePad angle={scene.angle} views={views} onChange={angle=>run([{op:'setAngle',angle}],false)} zh={zh}/>
    <div className="vr-angle-values">{(['x','y'] as const).map(axis=><label key={axis}>{axis==='x'?txt('左右 X','Yaw X'):txt('上下 Y','Pitch Y')}<SceneAngleInput axis={axis} value={scene.angle[axis]} commit={value=>run([{op:'setAngle',angle:{...scene.angle,[axis]:value}}],false)}/><span>°</span></label>)}</div>
    <small>{txt('+X 向画面右转 · +Y 仰头 · 拖动只预览','+X turns screen right · +Y looks up · Drag to preview')}</small>
   <h2 className="vr-current-view-title">{currentView?currentView.name:txt('建立这个视角','ESTABLISH VIEWPOINT')}</h2>{currentView?<><p className={'vr-save-state'+(currentDrafts.length?' dirty':'')} data-testid="viewpoint-draft-summary">{currentDrafts.length?txt(`此角度有 ${currentDrafts.length} 个通道待更新`,`${currentDrafts.length} changed channels at this angle`):txt('此角度已保存，可调整曲线、快照、图层或 Warp','Saved. Edit curves, snapshots, layers or a Warp at this angle.')}</p><button className="vr-primary" data-testid="scene-update-viewpoint" onClick={updateView}>{txt('更新此视角','Update this viewpoint')}</button>{currentDrafts.length>0&&<small className="vr-onion-save-hint">{txt('先更新视角，再用洋葱皮检查连续形变。','Update this viewpoint before checking interpolation with onion skin.')}</small>}</>:<><p>{txt('此处可预览插值。先建立视角，再修改曲线、快照、显隐或网格。','Preview interpolation here. Establish a viewpoint before editing curves, snapshots, visibility or grids.')}</p><input aria-label="Viewpoint name" placeholder={txt('视角名称（可留空）','Viewpoint name (optional)')} value={viewName} onChange={e=>setViewName(e.target.value)}/><button className="vr-primary" data-testid="scene-create-viewpoint" onClick={addView}>{txt('＋ 建立视角','＋ Establish viewpoint')}</button></>}
    <div className="vr-view-list">{views.map(v=><button key={v.id} aria-pressed={sameAngle(v.angle,scene.angle)} onClick={()=>run([{op:'setAngle',angle:v.angle}],false)}><span>◆ {v.name}</span><small>X {v.angle.x} / Y {v.angle.y}</small></button>)}</div>
    {otherDrafts.length>0&&<details><summary>{txt(`其他角度还有 ${otherDrafts.length} 个草稿`,`${otherDrafts.length} drafts at other angles`)}</summary>{otherDrafts.map(t=><button key={t.id} onClick={()=>run([{op:'setAngle',angle:t.draft!.angle}],false)}>{trackName(t.id)} · X{t.draft!.angle.x} / Y{t.draft!.angle.y}</button>)}</details>}
   </section>
   <div className="vr-inspection-controls"><SceneOnionControls settings={onion} onChange={setOnion} zh={zh} preparing={onionResult.preparing} error={onionResult.error} frameCount={onionResult.frames.filter(f=>!sameAngle(f.angle,scene.angle)).length}/></div>
   <section className="vr-section vr-reference-entry"><button ref={referenceButton} data-testid="scene-reference-toggle" aria-expanded={referenceOpen} aria-controls="recording-reference-panel" onClick={()=>{reference.setMoving(false);setReferenceOpen(open=>!open);}}>{txt('参考 / 辅助线','Reference / guides')}{reference.reference?' · '+reference.reference.name:''}</button><small>{txt('背景照片 · 快照参考 · 辅助线','Background image · artwork reference · guides')}</small></section>
   <details className="vr-section"><summary>{txt('所选对象 · 独立关键形','Selected objects · independent keys')}</summary><button data-testid="scene-save-selected" disabled={!canSave} onClick={()=>edit([{op:'saveSelected',...selected}])}>{objectInstanceIds.length?txt('保存所选实例姿态','Save selected instance poses'):warpIds.length===1&&!layerRefs.length?txt('保存此 Warp 关键形','Save this Warp key'):txt('保存所选对象关键形','Save selected object keys')}</button><button disabled={!canSave} onClick={()=>edit([{op:'discardSelected',...selected}])}>{txt('放弃所选对象草稿','Discard selected drafts')}</button>{selectedObjects.map(object=><ObjectKeys key={object.id} object={object} angle={scene.angle} {...{run,txt,trackName}}/>)}</details>
   <details className="vr-section"><summary>{txt('检查','Diagnostics')} · {evaluated.warningCurveIds.length+otherDiagnostics.length}</summary>{evaluated.fitDiagnostics.some(d=>'placementErrorBound' in d&&d.placementErrorBound)&&<p>{txt('非等比放置后的拟合误差显示保守上界；红线仍保留供检查。','Fit errors after nonuniform placement are conservative bounds; red curves remain visible for inspection.')}</p>}{localDiagnostics.length>0&&<p>{txt('局部编辑暂不显示父变形；外部联动只在全局预览生效。','Local editing excludes parent deformation; external links apply in global preview.')}</p>}{otherDiagnostics.map((d,i)=><p className="vr-error" key={i}>{d.message}</p>)}{!!evaluated.intervalTransportErrors.length&&<p className="vr-error">{evaluated.intervalTransportErrors.length} {txt('区间材料问题','interval material issues')}</p>}<label className="vr-field">{txt('拟合阈值 px','Fit tolerance px')}<input aria-label="Fit tolerance pixels" type="number" min=".1" max="20" step=".1" value={(scene.tolerance??1/250)*250} onChange={e=>run([{op:'setTolerance',pixels:Number(e.target.value)}])}/></label></details>
   {error&&<div className="vr-error" role="alert">{error}</div>}
  </aside>
  <aside ref={floatingReference.panelRef} style={floatingReference.style} className="vr-reference-popover vr-section" id="recording-reference-panel" role="dialog" aria-label={txt('工作区参考 / 辅助线','Workspace reference / guides')} hidden={!referenceOpen} data-testid="scene-reference-popover" data-ui-keyboard onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();closeReference();}}}>
   <header {...floatingReference.headerProps} data-testid="workspace-reference-drag-handle" className="reference-panel-drag-handle" title={txt('拖动标题栏移动面板','Drag the title bar to move this panel')}><strong>{txt('工作区参考 / 辅助线','Workspace reference / guides')}</strong><button aria-label={txt('关闭参考面板','Close reference panel')} onClick={closeReference}>×</button></header>
   <section className="vr-reference-controls" data-testid="scene-reference-controls">{reference.controls}</section>
   <details className="vr-view-aids-controls"><summary>{txt('快照参考 / 辅助线','Artwork reference / guides')}</summary><WorkspaceViewPanel embedded/></details>
  </aside>
  <SceneWarpCanvas curveEdit={curveEditActive?{editable:curveEditable,onPreview:onShapePreview,onCommit:onShapeCommit}:undefined} curveEditDisabledReason={shapeSingular?txt('宽或高为 0：请先点快照标题，用 V 边柄或宽高数值拉开，再编辑端点、柄。','Zero width or height: select the snapshot title and expand it with V edge handles or scale values before editing endpoints or handles.'):undefined} instanceTransform={instanceIds.length&&placementBounds?{ids:instanceIds,bounds:placementBounds,...(placementValue&&placementMaterialBounds?{basePlacement:placementValue,materialBounds:placementMaterialBounds,onValuePreview:onPlacementValuePreview,onValueCommit:onPlacementValueCommit}:{}),onPreview:onPlacementPreview,onCommit:onPlacementCommit,editable:placementEditable,label:scene.instances.filter(i=>instanceIds.includes(i.id)).map(i=>i.name).join(" + ")}:undefined} gridPlacement={gridPlacement} ghostGridPlacements={ghostGridPlacements} reference={reference} underlay={(screen,unit)=><SceneOnionSkin frames={onionResult.frames} angle={scene.angle} opacity={onion.opacity} screen={screen} unit={unit}/>} warpPicker={{value:activeWarpId,items:scene.warps.map(w=>({id:w.id,name:w.name})),onChange:id=>selectWarp(id)}} revealGridKey={gridRevealKey} source={evaluated.source} drawing={evaluated.drawing} grid={warp?evaluated.warpGrids[warp.id]:undefined} editEnabled={gridEditable&&!!tryInverseScenePlacement(gridPlacement??identityScenePlacement())} selection={selection} onSelection={choose} targetKey={`${scene.id}/${warp?.id??''}/${scene.angle.x}/${scene.angle.y}/${localEdit}/${instanceIds.join(',')}/${frameInstance?.id??''}/${curveEditActive?selection.ids.join(','):''}`} label={`${currentView?'':'预览 · '}${scene.name} · X ${scene.angle.x}° / Y ${scene.angle.y}°${instanceIds.length?' · '+txt('V 快照变换 · 边柄宽高 / 角点等比','V snapshot transform · axis edges / proportional corners'):frameInstance?' · '+frameInstance.name:''}${warp?.parentId&&localEdit?' · '+txt('子域局部 · 父变形暂不显示','Child local · parent excluded'):''}`} paintBatches={evaluated.paintBatches} warnings={evaluated.fitDiagnostics} onWarpSelection={onWarpSelection} aiGuide={aiGuides?{curveIds:guideCurveIds,labels:guideLabels}:undefined} {...{onPreview,onCommit,zh}} localToggle={warp?.parentId?{local:localEdit,change:()=>setLocalEdit(v=>!v)}:undefined}/>
  <aside className="vr-sidebar vr-right" data-testid="scene-source-layer-panel">
   <details className="vr-section vr-load-parts"><summary>{txt('＋ 加载画稿','＋ Load artwork')}</summary><select aria-label="Source artwork" value={assetId} onChange={e=>setAssetId(e.target.value)}>{!project.drawingSnapshots?.activeId&&project.drawing&&<option value="$working">{txt('当前未保存画稿','Current unsaved artwork')}</option>}{project.drawingSnapshots?.items.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><details className="vr-source-layer-picker"><summary>{txt('选择图层','Choose layers')} · {assetLayers.length}</summary>{asset?.layers.map(l=><label className="vr-checkbox" key={l.id}><input type="checkbox" checked={assetLayers.includes(l.id)} onChange={e=>setAssetLayers(ids=>e.target.checked?[...ids,l.id]:ids.filter(id=>id!==l.id))}/>{l.name}</label>)}</details>{sourceDependencies?.additionalLayerIds.length?<div className="vr-import-dependencies"><p>{txt('还需要关联图层：','Related layers required: ')}{sourceDependencies.additionalLayerIds.map(id=>asset?.layers.find(l=>l.id===id)?.name).join('、')}</p><button onClick={()=>setAssetLayers(sourceDependencies.layerIds)}>{txt('一并包含','Include dependencies')}</button></div>:null}<button data-testid="scene-add-instance" disabled={!asset||!assetLayers.length} onClick={()=>run([{op:'addInstance',artworkId:assetId,name:sourceName(assetId),...(assetLayers.length===asset!.layers.length?{}:{sourceLayerIds:assetLayers})}])}>{txt('加载到场景','Load into scene')}</button></details>
   {placementValue&&<section className="vr-section vr-placement-scale" data-testid="scene-placement-scale"><h2>{txt('快照宽高','Snapshot scale')}</h2><div className="vr-interval-numbers">{(['x','y'] as const).map((axis,index)=><label key={axis}>{axis==='x'?txt('宽度 %','Width %'):txt('高度 %','Height %')}<ScenePlacementScaleInput axis={axis} value={scenePlacementScales(placementValue)[index]*100} disabled={!placementEditable} commit={percent=>onPlacementValueCommit(setScenePlacementAxisScale(placementValue,axis,percent/100,placementMaterialBounds?.center))}/></label>)}</div><small>{txt('边柄分别调整宽高，可设为 0；角点等比缩放。0 宽/高可从这里恢复。','Edges resize each axis, including 0; corners scale proportionally. Restore collapsed axes here.')}</small></section>}
   <SceneLayerPanel scene={scene} evaluated={globalEvaluated} selection={selection} onSelection={choose} run={edit} editEnabled={!!currentView} headerActions={warpControls} onRemoveInstance={removeInstance} onSelectInstance={selectInstance} selectedInstanceIds={instanceIds}/>
   <section className="vr-section vr-warp-tree"><h2>Warp</h2>{warp&&frameInstances.length>0&&<label className="vr-field">{txt('网格显示于','Cage projection')}<select aria-label="Warp cage instance" value={frameInstance?.id??''} onChange={e=>{window.dispatchEvent(new Event('contour:cancel-recording-gesture'));setActiveFrameId(e.target.value);}}>{frameInstances.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select>{frameInstances.length>1&&<small>{txt('同一原域 Warp，按各快照放置显示；淡框不可拖动。','One shared Warp in its original domain; each snapshot projects it. Faint cages are read-only.')}</small>}</label>}<div className="vr-tree">{scene.warps.map(w=>{let depth=0,p=w.parentId;const seen=new Set<string>();while(p&&!seen.has(p)){seen.add(p);depth++;p=scene.warps.find(x=>x.id===p)?.parentId;}return <button data-testid="scene-warp" key={w.id} className={warpIds.includes(w.id)?'selected':''} style={{paddingLeft:10+depth*14}} onClick={e=>selectWarp(w.id,e.ctrlKey||e.metaKey||e.shiftKey)}>◇ {w.name}<small>{w.keys.length} {txt('键','keys')} · {txt('直挂','direct')} {scene.bindings.filter(b=>b.warpId===w.id).length} / {txt('影响','affected')} {scene.bindings.filter(b=>affects(w.id,b.warpId)).length}</small></button>;})}</div>{warp&&<details><summary>{txt('所选 Warp 设置','Selected Warp settings')}</summary><label className="vr-field">{txt('名称','Name')}<input aria-label="Warp name" key={warp.id} defaultValue={warp.name} onBlur={e=>{const name=e.target.value.trim();if(name&&name!==warp.name)run([{op:'setWarp',warpId:warp.id,name}]);}}/></label><label className="vr-field">{txt('父级','Parent')}<select aria-label="Parent Warp" value={warp.parentId??''} onChange={e=>edit([{op:'setWarp',warpId:warp.id,parentId:e.target.value||null}])}><option value="">{txt('根','Root')}</option>{scene.warps.filter(w=>w.id!==warp.id).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><button disabled={!currentView||!layerRefs.length} onClick={()=>edit([{op:'rebindLayers',layerRefs,warpId:warp.id}])}>{txt('挂接所选图层','Rebind selected layers')}</button><button disabled={!currentView} onClick={()=>edit([{op:'deleteWarp',warpId:warp.id}])}>{txt('移除 Warp','Remove Warp')}</button></details>}</section>
   {layerRefs.map(ref=>{const instance=scene.instances.find(i=>i.id===ref.instanceId),source=instance&&resolve(instance.artworkId),layer=source?.layers.find(l=>l.id===ref.sourceLayerId);if(!source||!layer)return null;const depth=scene.depthTracks?.find(t=>sceneLayerKey(t.target)===sceneLayerKey(ref));return <details className="vr-section" key={sceneLayerKey(ref)}><summary>{layer.name} · {txt('区间 / 层序','Intervals / order')}</summary><fieldset disabled={!currentView} style={{border:0,padding:0}}><label className="vr-field">{txt('场景层序','Scene order')}<input aria-label={`Scene layer offset ${layer.id}`} type="number" step="1" value={depth?evaluateDepthTrack(depth,scene.angle):0} onChange={e=>edit([{op:'setLayerOrder',target:ref,value:Number(e.target.value)}])}/></label>{(source.displayIntervals??[]).filter(t=>layer.items.includes(t.anchor.id)).map(base=><SceneIntervalControl key={base.id} {...{scene,source,ref,base,txt}} run={edit}/>)}</fieldset></details>;})}
  </aside>
 </main>;
}
function SceneIntervalControl({scene,source,ref,base,run,txt}:{scene:RecordingScene;source:DrawingDocument;ref:SceneLayerRef;base:NonNullable<DrawingDocument['displayIntervals']>[number];run:(commands:SceneCommand[],history?:boolean)=>unknown;txt:(cn:string,en:string)=>string}){
 const track=scene.intervalTracks.find(t=>t.instanceId===ref.instanceId&&t.sourceTrackId===base.id);let appearance=base,enabled:Record<string,boolean>={};try{if(track){const value=evaluateIntervalTrack(track,source,scene.angle);appearance=value.appearance??base;enabled=value.enabled;}}catch{/* The evaluator shows the local material issue; keep source controls inspectable. */}
 const suspended=!!track?.materialIssue&&track.materialIssue.sourceSignature!==drawingSignature(source);if(suspended){appearance=base;enabled={};}
 const owner={instanceId:ref.instanceId,sourceTrackId:base.id},curve=source.curves.find(c=>c.id===base.anchor.id);
 return <details className="vr-interval-track"><summary>{txt('显示区间','Display interval')} · {curve?.name??base.id}</summary><p>{txt('贯通路径由此来源层唯一持有；不会复制到其它参与层。','This source layer owns the route channel once; other participating layers do not duplicate it.')}</p>{suspended&&<p className="vr-error">{txt('此通道材料关系已失效，当前使用源稿范围；旧关键形仍保留。撤销相关源改变或恢复原关系后可接回。','This channel’s material mapping is suspended; current source ranges are shown and old keys are retained. Undo or restore the source relationship to reconnect it.')}</p>}<fieldset disabled={suspended} style={{border:0,padding:0,margin:0}}>{appearance.ranges.map((range,i)=><div className="vr-interval-range" key={range.id}><label className="vr-checkbox"><input type="checkbox" aria-label={`Interval ${range.id} enabled`} checked={enabled[range.id]??range.enabled!==false} onChange={e=>run([{op:'setIntervalEnabled',...owner,rangeId:range.id,enabled:e.target.checked}])}/>{txt('区间','Range')} {i+1}<select value={range.mode??'SHOW'} onChange={e=>run([{op:'changeInterval',...owner,rangeId:range.id,mode:e.target.value as 'SHOW'|'HIDE'}])}><option value="SHOW">{txt('显示','Show')}</option><option value="HIDE">{txt('隐藏','Hide')}</option></select></label><div className="vr-interval-numbers">{(['start','end'] as const).map(bound=><label key={bound}>{bound==='start'?txt('起界 %','Start %'):txt('终界 %','End %')}<input type="number" min="0" max="100" step=".1" value={+(range[bound]*100).toFixed(4)} onChange={e=>run([{op:'changeInterval',...owner,rangeId:range.id,[bound]:Number(e.target.value)/100}])}/></label>)}</div><div className="vr-interval-numbers">{([0,1] as const).map(end=><label key={end}>{end?txt('末端收尖 px','End taper px'):txt('起端收尖 px','Start taper px')}<input type="number" min="0" max="500" step=".1" value={+(inkTaperDistance(range.inkEnds?.[end]??{},curve?.width??.01,0)*250).toFixed(3)} onChange={e=>{const style={...range.inkEnds?.[end],taper:Number(e.target.value)/250};delete style.taperWidthScale;run([{op:'setIntervalEnd',...owner,rangeId:range.id,end,style}]);}}/></label>)}</div></div>)}</fieldset></details>;
}

function SceneAngleInput({axis,value,commit}:{axis:'x'|'y';value:number;commit:(value:number)=>void}){
 const [text,setText]=useState(String(value));
 useEffect(()=>setText(String(value)),[value]);
 const finish=(raw:string)=>{const number=raw.trim()?Number(raw):NaN;if(Number.isFinite(number)&&number>=-90&&number<=90)commit(number);else setText(String(value));};
 return <input aria-label={`Angle ${axis.toUpperCase()}`} inputMode="decimal" type="text" value={text} onChange={e=>setText(e.target.value)} onBlur={e=>finish(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){e.currentTarget.value=String(value);setText(String(value));e.currentTarget.blur();}}}/>;
}

type KeyedTrack={id:string;keys:{id:string;name?:string;angle:{x:number;y:number}}[];draft?:{angle:{x:number;y:number}}};
function ObjectKeys({object,angle,run,txt,trackName}:{object:{id:string;name:string;tracks:KeyedTrack[]};angle:{x:number;y:number};run:(commands:SceneCommand[],history?:boolean)=>unknown;txt:(a:string,b:string)=>string;trackName:(id:string)=>string}){
 const angles:{angle:{x:number;y:number};entries:{trackId:string;key:KeyedTrack['keys'][number]}[]}[]=[];
 for(const track of object.tracks)for(const key of track.keys){let entry=angles.find(e=>sameAngle(e.angle,key.angle));if(!entry){entry={angle:key.angle,entries:[]};angles.push(entry);}entry.entries.push({trackId:track.id,key});}
 angles.sort((a,b)=>a.angle.y-b.angle.y||a.angle.x-b.angle.x);
 const draftAngles:{x:number;y:number}[]=[];for(const track of object.tracks)if(track.draft&&!draftAngles.some(a=>sameAngle(a,track.draft!.angle)))draftAngles.push(track.draft.angle);
 return <details className="vr-object-track" open><summary>{object.name} · {angles.length} {txt('角度键','angle keys')}</summary>{draftAngles.map(a=><p className="vr-save-state dirty" key={`${a.x},${a.y}`}>{txt('草稿角度','Draft angle')} X{a.x} / Y{a.y}<button onClick={()=>run([{op:'setAngle',angle:a}],false)}>{txt('返回草稿','Go to draft')}</button></p>)}<div className="vr-key-list">{angles.map(entry=><div className="vr-key-row" key={`${entry.angle.x},${entry.angle.y}`}><button aria-pressed={sameAngle(entry.angle,angle)} onClick={()=>run([{op:'setAngle',angle:entry.angle}],false)}>◆ X{entry.angle.x} / Y{entry.angle.y}</button><button aria-label={`Delete object key ${object.id} ${entry.angle.x} ${entry.angle.y}`} onClick={()=>run(entry.entries.map(({trackId,key})=>({op:'deleteKey',trackId,keyId:key.id})))}>×</button></div>)}</div>{object.tracks.length>1&&<details><summary>{txt('内部通道','Internal channels')} · {object.tracks.length}</summary>{object.tracks.map(track=><p key={track.id}>{trackName(track.id)} · {track.keys.length} {txt('键','keys')}</p>)}</details>}</details>;
}

/** Displaying an existing grid is safe in preview and never issues a scene command. */
export function SceneWarpSelectionControl({action,currentView,onCreate,onShow,txt}:{action:SceneWarpAction;currentView:boolean;onCreate:()=>void;onShow:(id:string)=>void;txt:Text}){
 return <><button data-testid="scene-create-warp" disabled={action.kind==='none'||action.kind==='blocked'||action.kind==='create'&&!currentView} onClick={()=>{if(action.kind==='show')onShow(action.warpId);else if(action.kind==='create'&&currentView)onCreate();}}>{action.kind==='show'?txt('显示已有 Warp','Show existing Warp'):txt('＋ 所选图层建立 Warp','＋ Warp for selected layers')}</button>{action.kind==='blocked'&&<p className="vr-error" role="status" data-testid="scene-warp-binding-message">{txt('所选图层包含不同 Warp 或部分未绑定，不能重复建立。请在 Warp 列表中多选已有 Warp 后包为父 Warp，或按住 Ctrl / ⌘ 选择目标 Warp，再明确挂接所选图层。','These layers use different Warps or include unbound layers. Select existing Warps to wrap in a parent, or Ctrl / Cmd-select a target Warp and explicitly rebind the selected layers.')}</p>}{action.kind==='show'&&<small data-testid="scene-warp-binding-message">{txt('可继续编辑网格，通过左侧“更新此视角”保存；图层选择不会额外选中 Warp。','Continue editing the grid and save with Update this viewpoint on the left. Selecting layers does not additionally select their Warp.')}</small>}</>;
}

function ScenePlacementScaleInput({axis,value,disabled,commit}:{axis:'x'|'y';value:number;disabled:boolean;commit:(value:number)=>void}){
 const [text,setText]=useState(String(+value.toFixed(6)));
 useEffect(()=>setText(String(+value.toFixed(6))),[value]);
 const finish=()=>{const next=text.trim()?Number(text):NaN;if(Number.isFinite(next)&&next>=0&&next<=1e8){if(next!==value)commit(next);}else setText(String(+value.toFixed(6)));};
 return <input data-testid={`scene-placement-scale-${axis}`} aria-label={`Snapshot scale ${axis.toUpperCase()} percent`} disabled={disabled} inputMode="decimal" value={text} onChange={e=>setText(e.target.value)} onBlur={finish} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){setText(String(+value.toFixed(6)));e.preventDefault();}}}/>;
}
