import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {useEditor} from '../../app/store';
import {prepareSnapshotBatch,prepareSnapshotPreview} from '../../app/recordingSnapshotApi';
import {evaluateRecordingSnapshot,resolveSnapshot} from '../../domain/recordingSnapshot/evaluation';
import {snapshotMigrationId} from '../../domain/recordingSnapshot/migration';
import type {RecordingSnapshotWorkspace} from '../../domain/recordingSnapshot/model';
import type {SnapshotCommand} from '../../domain/recordingSnapshot/commands';
import {identityScenePlacement,type ScenePlacementValue,type WarpGrid} from '../../domain/recordingScene/model';
import {applyScenePlacementMatrix,tryInverseScenePlacement,composePlacementSimilarity,scenePlacementScales,setScenePlacementAxisScale} from '../../domain/recordingScene/tracks';
import {sameAngle} from '../../domain/vectorRecording/interpolation';
import {layerFor} from '../../domain/drawing/model';
import {selectionBounds} from '../drawing/geometry';
import {selectedLayers,type DrawingSelection} from '../drawing/session';
import {useLanguage} from '../i18n';
import SceneWarpCanvas,{type RecordingCurveEdit} from './SceneWarpCanvas';
import SnapshotLayerPanel,{type SnapshotLayerSelection,type SnapshotLayerClipboardSource} from './SnapshotLayerPanel';
import SceneAnglePad from './SceneAnglePad';
import SceneOnionSkin,{SceneOnionControls,DEFAULT_SCENE_ONION_SETTINGS,type SceneOnionSettings} from './SceneOnionSkin';
import {useSnapshotOnionFrames} from './useSnapshotOnionFrames';
import {useRecordingReference} from './RecordingReferenceControls';
import WorkspaceViewPanel from '../workspaceView/WorkspaceViewPanel';
import {useFloatingPanel} from '../shared/useFloatingPanel';
import './vectorRecording.css';

type Text=(cn:string,en:string)=>string;
export default function SnapshotRecordingWorkspace(){
 const project=useEditor(s=>s.project),workspace=project.recordingSnapshots!,zh=useLanguage(s=>s.language)==='zh',txt:Text=(a,b)=>zh?a:b;
 const recording=workspace.recordings.find(r=>r.id===workspace.activeRecordingId)??workspace.recordings[0];
 const [name,setName]=useState(''),[error,setError]=useState('');
 const create=()=>{try{const result=prepareSnapshotBatch(useEditor.getState().project,{commands:[{op:'createRecording',name:name.trim()||txt('录制','Recording')}]});useEditor.getState().commitRecordingSnapshots(result.recordingSnapshots);}catch(e){setError((e as Error).message);}};
 if(!recording)return <section className="vr-source-review"><h2>{txt('建立录制','Create recording')}</h2><p>{txt('先建立一个空视角快照，再从来源快照剪切图层并粘贴进来。','Start with an empty view snapshot, then cut layers from source snapshots and paste them here.')}</p><input aria-label="New recording name" value={name} onChange={e=>setName(e.target.value)}/><button data-testid="snapshot-create-recording" onClick={create}>{txt('建立空快照 · 0°','Create empty snapshot · 0°')}</button>{error&&<p role="alert">{error}</p>}</section>;
 if(!recording.snapshotIds.length)return <section className="vr-source-review"><h2>{txt('当前录制没有视角快照','No view snapshots')}</h2><button data-testid="snapshot-create-first-view" onClick={()=>{try{const result=prepareSnapshotBatch(useEditor.getState().project,{recordingId:recording.id,commands:[{op:'createSnapshot',name:txt('视角 0','View 0'),angle:{x:0,y:0}}]});useEditor.getState().commitRecordingSnapshots(result.recordingSnapshots);}catch(e){setError((e as Error).message);}}}>{txt('建立空视角快照 · 0°','Create empty view snapshot · 0°')}</button>{error&&<p role="alert">{error}</p>}</section>;
 return <SnapshotEditor key={recording.id} recordingId={recording.id} {...{zh,txt}}/>;
}
function SnapshotEditor({recordingId,zh,txt}:{recordingId:string;zh:boolean;txt:Text}){
 const project=useEditor(s=>s.project),workspace=project.recordingSnapshots!,recording=workspace.recordings.find(r=>r.id===recordingId)!;
 const [preview,setPreview]=useState<RecordingSnapshotWorkspace|null>(null),[error,setError]=useState(''),[selection,setSelection]=useState<DrawingSelection>({ids:[]}),[layerSelections,setLayerSelections]=useState<SnapshotLayerSelection[]>([]),[warpId,setWarpId]=useState(''),[localEdit,setLocalEdit]=useState(true),[gridRevealKey,setGridRevealKey]=useState(0),[viewName,setViewName]=useState(''),[recordingName,setRecordingName]=useState(''),[sourceIds,setSourceIds]=useState<string[]>([]),[sourceToAdd,setSourceToAdd]=useState(''),[clipboard,setClipboard]=useState<{kind:'cut'|'copy';sources:SnapshotLayerClipboardSource[]}|null>(null),[selectedSnapshotIds,setSelectedSnapshotIds]=useState<string[]>([]),[curveTool,setCurveTool]=useState<'select'|'direct'>('direct'),[onionEndpoints,setOnionEndpoints]=useState(()=>defaultOnionEndpoints(workspace,recordingId)),[onion,setOnion]=useState<SceneOnionSettings>({...DEFAULT_SCENE_ONION_SETTINGS,min:-90,max:0,axis:'x' as const}),[referenceOpen,setReferenceOpen]=useState(false);
 const referenceSceneId=project.recordingScenes?.scenes.find(scene=>snapshotMigrationId('recording',scene.id)===recordingId)?.id??recordingId;
 const referenceButton=useRef<HTMLButtonElement>(null),reference=useRecordingReference(`${project.meta.createdAt}/${recordingId}`,project.drawing?.reference,referenceSceneId!==recordingId?`${project.meta.createdAt}/${referenceSceneId}`:undefined),floating=useFloatingPanel({open:referenceOpen,storageKey:'contour-reference-panel-position-v1'});
 const views=recording.snapshotIds.flatMap(id=>{const s=workspace.snapshots.find(s=>s.id===id);return s?[s]:[];}),currentView=views.find(v=>sameAngle(v.angle,recording.angle));
 const run=useCallback((commands:SnapshotCommand[],history=true)=>{try{const result=(history?prepareSnapshotBatch:prepareSnapshotPreview)(useEditor.getState().project,{recordingId,commands});if(result.changed){const store=useEditor.getState();history?store.commitRecordingSnapshots(result.recordingSnapshots):store.setRecordingSnapshots(result.recordingSnapshots);}setError('');return result;}catch(e){setError((e as Error).message);return undefined;}},[recordingId]);
 const previewCommands=useCallback((commands:SnapshotCommand[]|null)=>{if(!commands){setPreview(null);return;}if(!currentView)return;try{const result=prepareSnapshotPreview(useEditor.getState().project,{recordingId,commands});setPreview(result.recordingSnapshots);setError('');}catch(e){setError((e as Error).message);}},[recordingId,!!currentView]);
 const evaluated=useMemo(()=>evaluateRecordingSnapshot(preview??workspace,recordingId,{angle:recording.angle,useDraft:true,immutableInputs:true,diagnostics:preview?'preview':'full',...(warpId&&localEdit?{stopAtWarpId:warpId}:{})}),[workspace,preview,recordingId,recording.angle,warpId,localEdit]);
 const baseline=useMemo(()=>evaluateRecordingSnapshot(workspace,recordingId,{angle:recording.angle,useDraft:true,immutableInputs:true,diagnostics:'preview'}),[workspace,recordingId,recording.angle]);
 const snapshot=workspace.snapshots.find(s=>s.id===evaluated.snapshotId),drawing=evaluated.drawing,state=evaluated.state;
 const warp=state.warps.find(w=>w.id===warpId),selectedLayerIds=selectedLayers(selection).filter(id=>drawing.layers.some(l=>l.id===id));
 const sourceOptions=workspace.snapshots.filter(s=>s.kind==='drawing'||s.kind==='sculpt');
 const sourcePanels=useMemo(()=>workspace.snapshots.filter(s=>sourceIds.includes(s.id)).map(snapshot=>({snapshotId:snapshot.id,name:snapshot.name,drawing:resolveSnapshot(workspace,snapshot.id,{useDraft:false,immutableInputs:true}).drawing})),[workspace.library,workspace.snapshots,sourceIds]);
 const currentPanel=snapshot?{snapshotId:snapshot.id,name:`${txt('当前视角快照','Current view snapshot')} · ${snapshot.name} · X ${recording.angle.x}° / Y ${recording.angle.y}°`,drawing}:undefined;
 const onChoose=(next:DrawingSelection,layers:SnapshotLayerSelection[]=[],tool:'select'|'direct'='direct')=>{setCurveTool(tool);setSelection(next);setLayerSelections(layers);setSelectedSnapshotIds([]);setPreview(null);const currentLayers=layers.filter(l=>l.snapshotId===snapshot?.id).map(l=>l.layerId),bindings=state.bindings.filter(b=>currentLayers.includes(b.layerId)),ids=[...new Set(bindings.map(b=>b.warpId))];void ids;setWarpId('');setGridRevealKey(k=>k+1);};
 const selectSnapshot=(id:string)=>{if(id!==snapshot?.id){setSelectedSnapshotIds([]);return;}const layerIds=drawing.layers.map(l=>l.id);setSelection({layers:layerIds,layer:layerIds.length===1?layerIds[0]:undefined,ids:drawing.curves.map(c=>c.id),paintIds:[...drawing.fills,...drawing.offsets].map(x=>x.id)});setLayerSelections(layerIds.map(layerId=>({snapshotId:id,layerId})));setSelectedSnapshotIds([id]);setWarpId('');setGridRevealKey(k=>k+1);};
 const editable=!!currentView&&!reference.moving,hasLayerSelection=selectedLayerIds.length>0&&layerSelections.every(ref=>ref.snapshotId===snapshot?.id),placementIds=drawing.curves.filter(c=>selectedLayerIds.includes(layerFor(drawing,c.id)?.id??'')).map(c=>c.id),bounds=selectionBounds(drawing,placementIds),materialBounds=selectedLayerIds.length===1?selectionBounds(evaluated.prePlacementDrawing,placementIds):null;
 const layerPlacement=(id:string)=>evaluated.placements[id]??identityScenePlacement(),singlePlacement=selectedLayerIds.length===1?layerPlacement(selectedLayerIds[0]):undefined;
 const placementCommands=(delta:ScenePlacementValue):SnapshotCommand[]=>selectedLayerIds.map(layerId=>({op:'setLayerPlacement',layerId,value:composePlacementSimilarity(baseline.placements[layerId]??identityScenePlacement(),delta)}));
 const valueCommands=(value:ScenePlacementValue):SnapshotCommand[]=>selectedLayerIds.length===1?[{op:'setLayerPlacement',layerId:selectedLayerIds[0],value}]:[];
 const shapeLayerIds=[...new Set(selection.ids.map(id=>layerFor(drawing,id)?.id).filter((id):id is string=>!!id))],shapeSingular=shapeLayerIds.some(id=>!tryInverseScenePlacement(layerPlacement(id)));
 const shapeCommand=(change:RecordingCurveEdit):SnapshotCommand=>{const curve=change.kind==='handle'?drawing.curves.find(c=>c.id===change.curveId):drawing.curves.find(c=>c.nodes.includes(change.nodeId)),layerId=curve&&layerFor(drawing,curve.id)?.id;if(!layerId)throw Error('The selected source is no longer in this snapshot.');const inverse=tryInverseScenePlacement(layerPlacement(layerId));if(!inverse)throw Error('Restore width or height before editing curves.');const position=applyScenePlacementMatrix(inverse,change.position);return change.kind==='node'?{op:'moveShapeNode',layerId,nodeId:change.nodeId,position}:{op:'moveShapeHandle',layerId,curveId:change.curveId,end:change.end,position};};
 const elementTransformIds=selection.ids.filter(id=>drawing.curves.some(c=>c.id===id)),elementTransformBounds=!hasLayerSelection&&!warp?selectionBounds(drawing,elementTransformIds):null;
 const elementCommands=(value:ScenePlacementValue):SnapshotCommand[]=>[{op:'transformShapeElements',curveIds:elementTransformIds,value}];
 const onCurvePreview=(change:RecordingCurveEdit|null)=>{try{previewCommands(change?[shapeCommand(change)]:null);}catch(e){setError((e as Error).message);}};
 const onCurveCommit=(change:RecordingCurveEdit)=>{try{run([shapeCommand(change)]);}catch(e){setError((e as Error).message);}setPreview(null);};
 const warpCommands=(grid:WarpGrid):SnapshotCommand[]=>[{op:'editWarpNodes',warpId,edits:grid.nodes.map((n,index)=>({index,...n})),moveHandles:false}];
 const affects=(leaf:string)=>{let id:string|undefined=leaf;const seen=new Set<string>();while(id&&!seen.has(id)){if(id===warpId)return true;seen.add(id);id=state.warps.find(w=>w.id===id)?.parentId;}return false;};
 const frameLayers=drawing.layers.filter(l=>state.bindings.some(b=>b.layerId===l.id&&affects(b.warpId))),frameLayer=frameLayers[0],gridPlacement=frameLayer?layerPlacement(frameLayer.id):undefined,ghostGridPlacements=frameLayers.filter(l=>l!==frameLayer).map(l=>({instanceId:l.id,name:l.name,value:layerPlacement(l.id)}));
 const currentDrafts=recording.tracks.filter(t=>t.draft&&sameAngle(t.draft.angle,recording.angle)),otherDrafts=recording.tracks.filter(t=>t.draft&&!sameAngle(t.draft.angle,recording.angle));
 const onionResult=useSnapshotOnionFrames(preview??workspace,recordingId,recording.angle,onion,warpId&&localEdit?warpId:undefined,onionEndpoints,evaluated);
 useEffect(()=>{setOnionEndpoints(old=>{const validStart=recording.snapshotIds.includes(old.startSnapshotId),validEnd=recording.snapshotIds.includes(old.endSnapshotId);return validStart&&validEnd&&(old.startSnapshotId!==old.endSnapshotId||recording.snapshotIds.length<2)?old:defaultOnionEndpoints(workspace,recordingId);});},[recording.snapshotIds.join('|')]);

 useEffect(()=>{setPreview(null);setSelection({ids:[]});setLayerSelections([]);setSelectedSnapshotIds([]);},[recording.activeSnapshotId]);
 useEffect(()=>{setPreview(null);},[workspace]);
 useEffect(()=>{window.dispatchEvent(new Event('contour:cancel-recording-gesture'));},[workspace.library]);
 const paste=()=>{if(!editable||!clipboard)return;const commands:SnapshotCommand[]=clipboard.sources.map(source=>({op:clipboard.kind==='copy'?'cloneLayers':'moveLayers',sourceSnapshotId:source.snapshotId,layerIds:source.layerIds}));const result=run(commands);if(result){setClipboard(null);setSelection({ids:[]});setLayerSelections([]);}};
 return <main className="vector-recording vr-view-workflow" data-testid="recording-snapshot-v2"><aside className="vr-sidebar vr-left" data-testid="snapshot-view-panel">
  <section className="vr-section"><select aria-label="Recording" value={recordingId} onChange={e=>run([{op:'selectRecording',recordingId:e.target.value}])}>{workspace.recordings.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><details><summary>{txt('新建录制','New recording')}</summary><input aria-label="New recording name" value={recordingName} onChange={e=>setRecordingName(e.target.value)}/><button onClick={()=>run([{op:'createRecording',name:recordingName.trim()||txt('录制','Recording')}])}>＋</button></details></section>
  <section className="vr-section"><h2>{txt('视角快照','View snapshots')}</h2><SceneAnglePad angle={recording.angle} views={views} onChange={angle=>run([{op:'setAngle',angle}],false)} zh={zh}/><div className="vr-interval-numbers">{(['x','y'] as const).map(axis=><label key={axis}>{axis.toUpperCase()}<Numeric value={recording.angle[axis]} label={`Angle ${axis.toUpperCase()}`} commit={value=>run([{op:'setAngle',angle:{...recording.angle,[axis]:Math.max(-90,Math.min(90,value))}}],false)}/></label>)}</div>
   {currentView?<><button className="vr-primary" data-testid="snapshot-update-view" onClick={()=>run([{op:'updateSnapshot',snapshotId:currentView.id}])}>{txt('更新此视角','Update this viewpoint')} · {currentDrafts.length}</button>{currentDrafts.length>0&&<small>{txt('所选端点的未保存改动实时参与两端插值；更新视角后正式保存。','Unsaved edits at a selected endpoint update endpoint interpolation live. Update this viewpoint to save them.')}</small>}</>:<><p>{txt('预览：先建立视角快照才能编辑。','Preview: create a view snapshot to edit.')}</p><input aria-label="View snapshot name" value={viewName} onChange={e=>setViewName(e.target.value)}/><button data-testid="snapshot-create-view" onClick={()=>run([{op:'createSnapshot',name:viewName.trim()||undefined,angle:recording.angle}])}>{txt('建立视角快照','Create view snapshot')}</button></>}
   <div className="vr-view-list">{views.map(v=><div className="vr-key-row" key={v.id}><button aria-pressed={sameAngle(v.angle,recording.angle)} onClick={()=>run([{op:'selectSnapshot',snapshotId:v.id}])}>{v.name}<small>X {v.angle.x} / Y {v.angle.y}</small></button><button data-testid="snapshot-delete-view" aria-label={`${txt('删除视角快照','Delete view snapshot')} ${v.name}`} title={txt('只移除此视角及其独占关键状态；源稿保留，可撤销','Remove this view and its exclusive authored keys. Keep sources; Undo is available.')} onClick={()=>run([{op:'deleteSnapshot',snapshotId:v.id}])}>×</button></div>)}</div>{otherDrafts.map(t=><button key={t.id} onClick={()=>run([{op:'setAngle',angle:t.draft!.angle}],false)}>{txt('返回草稿','Return to draft')} · {t.channel} {t.draft!.angle.x}/{t.draft!.angle.y}</button>)}</section>
  <SceneOnionControls endpointViews={views} endpoints={onionEndpoints} onEndpointsChange={setOnionEndpoints} settings={onion} onChange={setOnion} zh={zh} preparing={onionResult.preparing} error={onionResult.error} diagnostics={onionResult.diagnostics} frameCount={onionResult.frames.filter(f=>!sameAngle(f.angle,recording.angle)).length}/>
  <section className="vr-section"><button ref={referenceButton} onClick={()=>{reference.setMoving(false);setReferenceOpen(v=>!v);}}>{txt('参考 / 辅助线','Reference / guides')}</button></section>
  <details className="vr-section"><summary>{txt('检查','Diagnostics')} · {evaluated.diagnostics.length+evaluated.warningCurveIds.length}</summary>{evaluated.diagnostics.map((d,i)=><p key={i} className="vr-error">{d.message}</p>)}</details>{error&&<p className="vr-error" role="alert">{error}</p>}
 </aside>
 <aside ref={floating.panelRef} style={floating.style} className="vr-reference-popover vr-section" hidden={!referenceOpen} role="dialog" aria-label={txt('工作区参考 / 辅助线','Workspace reference / guides')} data-ui-keyboard><header {...floating.headerProps} className="reference-panel-drag-handle"><strong>{txt('参考 / 辅助线','Reference / guides')}</strong><button onClick={()=>setReferenceOpen(false)}>×</button></header>{reference.controls}<details><summary>{txt('快照参考 / 辅助线','Artwork reference / guides')}</summary><WorkspaceViewPanel embedded/></details></aside>
 <SceneWarpCanvas showWarpTools={false} inspectionHideFills={onion.enabled} source={evaluated.source} drawing={drawing} paintBatches={evaluated.paintBatches} warnings={evaluated.fitDiagnostics} targetKey={`${recordingId}/${snapshot?.id}/${recording.angle.x}/${recording.angle.y}/${warpId}/${selectedLayerIds.join(',')}`} label={`${recording.name} · X ${recording.angle.x}° / Y ${recording.angle.y}°`} zh={zh} selection={selection} onSelectionTool={(next,tool)=>onChoose(next,selectedLayers(next).map(layerId=>({snapshotId:snapshot?.id??'',layerId})),tool)} grid={warp?evaluated.warpGrids[warp.id]:undefined} gridPlacement={gridPlacement} ghostGridPlacements={ghostGridPlacements} editEnabled={editable&&(!warp?.parentId||localEdit)&&!!tryInverseScenePlacement(gridPlacement??identityScenePlacement())} onPreview={grid=>previewCommands(grid?warpCommands(grid):null)} onCommit={grid=>{run(warpCommands(grid));setPreview(null);}} revealGridKey={gridRevealKey} onWarpSelection={()=>{setSelection({ids:[]});setLayerSelections([]);setSelectedSnapshotIds([]);}} reference={reference} localToggle={warp?.parentId?{local:localEdit,change:()=>setLocalEdit(v=>!v)}:undefined} warpPicker={{value:warpId,items:state.warps.map(w=>({id:w.id,name:w.name})),onChange:id=>{setWarpId(id);setSelectedSnapshotIds([]);setGridRevealKey(k=>k+1);}}}
  instanceTransform={!warp&&hasLayerSelection&&bounds?{ids:selectedLayerIds,bounds,editable,label:txt('所选图层变换','Selected layer transform'),onPreview:delta=>previewCommands(delta?placementCommands(delta):null),onCommit:delta=>{run(placementCommands(delta));setPreview(null);},...(singlePlacement&&materialBounds?{basePlacement:singlePlacement,materialBounds,onValuePreview:value=>previewCommands(value?valueCommands(value):null),onValueCommit:value=>{run(valueCommands(value));setPreview(null);}}:{})}:elementTransformBounds?{ids:elementTransformIds,bounds:elementTransformBounds,editable:editable&&!shapeSingular,allowCurveSelection:true,label:txt('整笔变换','Stroke transform'),onPreview:value=>previewCommands(value?elementCommands(value):null),onCommit:value=>{run(elementCommands(value));setPreview(null);}}:undefined}
  curveEdit={!warp&&!hasLayerSelection&&selection.ids.length?{revealTool:curveTool,editable:editable&&!shapeSingular,onPreview:onCurvePreview,onCommit:onCurveCommit}:undefined} curveEditDisabledReason={shapeSingular?txt('宽或高为 0，请先恢复后再编辑节点。','Restore zero width or height before editing nodes.'):undefined}
  underlay={(screen,unit)=><SceneOnionSkin frames={onionResult.frames} angle={recording.angle} opacity={onion.opacity} screen={screen} unit={unit}/>}/>
 <aside className="vr-sidebar vr-right">{singlePlacement&&hasLayerSelection&&<section className="vr-section"><div className="vr-interval-numbers">{(['x','y'] as const).map((axis,index)=><label key={axis}>{axis==='x'?txt('宽度 %','Width %'):txt('高度 %','Height %')}<Numeric disabled={!editable} value={scenePlacementScales(singlePlacement)[index]*100} label={`Layer scale ${axis.toUpperCase()} percent`} commit={n=>{if(n>=0&&n<=1e8)run(valueCommands(setScenePlacementAxisScale(singlePlacement,axis,n/100,materialBounds?.center)));}}/></label>)}</div></section>}
 <section className="vr-section snapshot-source-picker"><details><summary>{txt('＋ 添加来源','＋ Add source')}</summary><select aria-label="Add source snapshot" value={sourceToAdd||sourceOptions[0]?.id||''} onChange={e=>setSourceToAdd(e.target.value)}>{sourceOptions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button data-testid="snapshot-show-source" disabled={!sourceOptions.length} onClick={()=>{const id=sourceToAdd||sourceOptions[0]?.id;if(id)setSourceIds(ids=>ids.includes(id)?ids:[...ids,id]);}}>{txt('列出此来源的图层','Show this source’s layers')}</button></details></section>
 <SnapshotLayerPanel collapseSourcesByDefault={false} current={currentPanel} sources={sourcePanels} selection={selection} layerSelections={layerSelections} onSelection={onChoose} editEnabled={editable} canPaste={!!clipboard} onCut={sources=>setClipboard({kind:'cut',sources})} onCopy={sources=>setClipboard({kind:'copy',sources})} onPaste={paste} onSelectSnapshot={selectSnapshot} selectedSnapshotIds={selectedSnapshotIds} headerActions={undefined} onVisibilityChange={(ids,visible)=>{if(editable)run(ids.flatMap(id=>{const layerId=layerFor(drawing,id)?.id;return layerId?[{op:'setVisibility' as const,layerId,objectId:id,visible}]:[];}));}} onLayerReorder={(id,target,after)=>{const ids=drawing.layers.map(l=>l.id).filter(x=>x!==id),index=ids.indexOf(target);if(index>=0){ids.splice(index+(after?1:0),0,id);run([{op:'reorderLayers',layerIds:ids}]);}}}/>
 {selectedLayerIds.map(layerId=><details className="vr-section" key={layerId}><summary>{drawing.layers.find(l=>l.id===layerId)?.name} · {txt('区间 / 层序','Intervals / order')}</summary><fieldset disabled={!editable} style={{border:0,padding:0}}><label>{txt('角度层序偏移','Pose order offset')}<Numeric label={`Layer order ${layerId}`} value={state.layers[layerId]?.depth??0} commit={value=>run([{op:'setLayerOrder',layerId,value}])}/></label>{(evaluated.source.displayIntervals??[]).filter(t=>evaluated.source.layers.find(l=>l.id===layerId)?.items.includes(t.anchor.id)).map(base=>{const value=state.layers[layerId]?.intervals?.[base.id],appearance=value?.appearance??base;return <details key={base.id}><summary>{txt('显隐区间','Visibility interval')}</summary>{appearance.ranges.map(range=><div key={range.id}><label><input type="checkbox" checked={value?.enabled[range.id]??range.enabled!==false} onChange={e=>run([{op:'setIntervalEnabled',layerId,sourceTrackId:base.id,rangeId:range.id,enabled:e.target.checked}])}/>{txt('启用','Enabled')}<select value={range.mode??'SHOW'} onChange={e=>run([{op:'changeInterval',layerId,sourceTrackId:base.id,rangeId:range.id,mode:e.target.value as 'SHOW'|'HIDE'}])}><option value="SHOW">SHOW</option><option value="HIDE">HIDE</option></select></label><div className="vr-interval-numbers">{(['start','end'] as const).map(bound=><label key={bound}>{bound}<Numeric label={`${base.id} ${range.id} ${bound}`} value={range[bound]*100} commit={number=>run([{op:'changeInterval',layerId,sourceTrackId:base.id,rangeId:range.id,[bound]:Math.max(0,Math.min(1,number/100))}])}/></label>)}</div></div>)}</details>;})}<button onClick={()=>{run([{op:'removeLayers',layerIds:[layerId]}]);setSelection({ids:[]});setLayerSelections([]);}}>{txt('从此视角移除图层','Remove layer from this view')}</button></fieldset></details>)}
 </aside></main>;
}
function Numeric({value,label,disabled=false,commit}:{value:number;label:string;disabled?:boolean;commit:(n:number)=>void}){const [text,setText]=useState(String(+value.toFixed(6)));useEffect(()=>setText(String(+value.toFixed(6))),[value]);return <input aria-label={label} disabled={disabled} inputMode="decimal" value={text} onChange={e=>setText(e.target.value)} onBlur={()=>{const n=text.trim()?Number(text):NaN;if(Number.isFinite(n)){if(n!==value)commit(n);}else setText(String(+value.toFixed(6)));}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();else if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();e.stopPropagation();const base=text.trim()&&Number.isFinite(Number(text))?Number(text):value,step=e.altKey?.1:e.shiftKey?10:1,next=Math.round((base+(e.key==='ArrowUp'?step:-step))*1e6)/1e6;setText(String(next));commit(next);}}}/>;}

function defaultOnionEndpoints(workspace:RecordingSnapshotWorkspace,recordingId:string){const recording=workspace.recordings.find(r=>r.id===recordingId),views=recording?.snapshotIds.flatMap(id=>{const s=workspace.snapshots.find(v=>v.id===id);return s?[s]:[];})??[];const start=views.find(v=>v.angle.x===0&&v.angle.y===0)??views[0],end=views.find(v=>v.angle.x===-90&&v.angle.y===0)??views.find(v=>v.id!==start?.id)??start;return {startSnapshotId:start?.id??'',endSnapshotId:end?.id??''};}
