import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {prepareSnapshotEdit,snapshotEditContext} from '../../app/snapshotEditTransaction';
import {createCurveSplitIntent} from '../../domain/drawing/layerEditIntent';
import {useEditor} from '../../app/store';
import {prepareSnapshotBatch,prepareSnapshotPreview} from '../../app/recordingSnapshotApi';
import {evaluateRecordingSnapshot,resolveSnapshot,type SnapshotEvaluation} from '../../domain/recordingSnapshot/evaluation';
import {snapshotMigrationId} from '../../domain/recordingSnapshot/migration';
import type {RecordingSnapshotWorkspace} from '../../domain/recordingSnapshot/model';
import type {SnapshotCommand} from '../../domain/recordingSnapshot/commands';
import {identityScenePlacement,type ScenePlacementValue,type WarpGrid} from '../../domain/recordingScene/model';
import {applyScenePlacementMatrix,tryInverseScenePlacement,composePlacementSimilarity,scenePlacementScales,setScenePlacementAxisScale} from '../../domain/recordingScene/tracks';
import {sameAngle} from '../../domain/vectorRecording/interpolation';
import {layerFor,type DrawingDocument} from '../../domain/drawing/model';
import {selectionBounds,curvePath} from '../drawing/geometry';
import {useLayerReferenceClipboard} from '../drawing/layerReferenceClipboard';
import {captureSnapshotLayerClipboard} from '../../domain/recordingSnapshot/referenceClipboard';
import {selectedLayers,type DrawingSelection,type DrawingTool} from '../drawing/session';
import {useLanguage} from '../i18n';
import {chooseDrawingSelection,selectDrawingTool} from '../drawing/interactionController';
import {createDrawingLayer,duplicateDrawingLayers,deleteDrawingSelection,type DrawingStructuralResult} from '../drawing/layerStructuralCommands';
import SceneWarpCanvas,{type RecordingCurveEdit,type RecordingCanvasTool} from './SceneWarpCanvas';
import type {RecordingInstanceTransform} from './SceneInstanceTransformBox';
import SnapshotLayerPanel,{type SnapshotLayerSelection,type SnapshotLayerClipboardSource} from './SnapshotLayerPanel';
import SceneAnglePad from './SceneAnglePad';
import SceneOnionSkin,{SceneOnionControls,DEFAULT_SCENE_ONION_SETTINGS,type SceneOnionSettings} from './SceneOnionSkin';
import {useSnapshotOnionFrames} from './useSnapshotOnionFrames';
import {onionPreferenceKey,snapshotOnionPreferences} from './onionPreferences';
import {useRecordingReference} from './RecordingReferenceControls';
import WorkspaceViewPanel from '../workspaceView/WorkspaceViewPanel';
import {useFloatingPanel} from '../shared/useFloatingPanel';
import EndpointCorrectionEditor from './EndpointCorrectionEditor';
import EndpointRelationControls from '../drawing/EndpointRelationControls';
import {snapshotStrokeTransformFrame,snapshotStrokeValueCommands,snapshotStrokeDeltaCommands} from './snapshotStrokeTransform';
import './vectorRecording.css';

type Text=(cn:string,en:string)=>string;
export default function SnapshotRecordingWorkspace(){
 const project=useEditor(s=>s.project),workspace=project.recordingSnapshots!,zh=useLanguage(s=>s.language)==='zh',txt:Text=(a,b)=>zh?a:b;
 const recording=workspace.recordings.find(r=>r.id===workspace.activeRecordingId)??workspace.recordings[0];
 const [name,setName]=useState(''),[error,setError]=useState('');
 const create=()=>{try{const result=prepareSnapshotBatch(useEditor.getState().project,{commands:[{op:'createTriangulatedRecording',name:name.trim()||txt('录制','Recording')}]});useEditor.getState().commitRecordingSnapshots(result.recordingSnapshots);}catch(e){setError((e as Error).message);}};
 if(!recording)return <section className="vr-source-review"><h2>{txt('建立录制','Create recording')}</h2><p>{txt('先建立一个空视角快照，再从来源快照剪切图层并粘贴进来。','Start with an empty view snapshot, then cut layers from source snapshots and paste them here.')}</p><input aria-label="New recording name" value={name} onChange={e=>setName(e.target.value)}/><button data-testid="snapshot-create-recording" onClick={create}>{txt('建立空快照 · 0°','Create empty snapshot · 0°')}</button>{error&&<p role="alert">{error}</p>}</section>;
 if(!recording.snapshotIds.length)return <section className="vr-source-review"><h2>{txt('当前录制没有视角快照','No view snapshots')}</h2><button data-testid="snapshot-create-first-view" onClick={()=>{try{const result=prepareSnapshotBatch(useEditor.getState().project,{recordingId:recording.id,commands:[{op:'createSnapshot',name:txt('视角 0','View 0'),angle:{x:0,y:0}}]});useEditor.getState().commitRecordingSnapshots(result.recordingSnapshots);}catch(e){setError((e as Error).message);}}}>{txt('建立空视角快照 · 0°','Create empty view snapshot · 0°')}</button>{error&&<p role="alert">{error}</p>}</section>;
 return <SnapshotEditor key={`${project.meta.createdAt}/${recording.id}`} recordingId={recording.id} {...{zh,txt}}/>;
}
function SnapshotEditor({recordingId,zh,txt}:{recordingId:string;zh:boolean;txt:Text}){
 const project=useEditor(s=>s.project),workspace=project.recordingSnapshots!,recording=workspace.recordings.find(r=>r.id===recordingId)!;
 const pair=recording.mode==='endpoint-pair'?recording.endpointPair:undefined,surface=recording.mode==='triangulated'?recording.angleGraph:undefined;
 const clipboard=useLayerReferenceClipboard(s=>s.clipboard),clipboardSession=useLayerReferenceClipboard();
 const pairStart=workspace.snapshots.find(s=>s.id===pair?.startSnapshotId),pairEnd=workspace.snapshots.find(s=>s.id===pair?.endSnapshotId);
 const pairBasis=!!pair&&!![pairStart,pairEnd].find(s=>s&&sameAngle(s.angle,recording.angle)),pairCorrection=!!pair&&!pairBasis;
 const [correctionControl,setCorrectionControl]=useState<RecordingCurveEdit|null>(null);
 const preferenceKey=onionPreferenceKey(project.meta.createdAt,recordingId),[initialOnion]=useState(()=>snapshotOnionPreferences.read(preferenceKey,{settings:{...DEFAULT_SCENE_ONION_SETTINGS,min:-90,max:0,axis:'x'},endpoints:defaultOnionEndpoints(workspace,recordingId)}));
 const [preview,setPreview]=useState<RecordingSnapshotWorkspace|null>(null),[error,setError]=useState(''),[selection,setSelection]=useState<DrawingSelection>({ids:[]}),[layerSelections,setLayerSelections]=useState<SnapshotLayerSelection[]>([]),[warpId,setWarpId]=useState(''),[localEdit,setLocalEdit]=useState(true),[gridRevealKey,setGridRevealKey]=useState(0),[viewName,setViewName]=useState(''),[recordingName,setRecordingName]=useState(''),[sourceIds,setSourceIds]=useState<string[]>([]),[sourceToAdd,setSourceToAdd]=useState(''),[selectedSnapshotIds,setSelectedSnapshotIds]=useState<string[]>([]),[canvasTool,setCanvasTool]=useState<RecordingCanvasTool>('select'),[activeDrawingLayer,setActiveDrawingLayer]=useState<string|null>(null),[onionEndpoints,setOnionEndpoints]=useState(initialOnion.endpoints),[onion,setOnion]=useState<SceneOnionSettings>(initialOnion.settings),[referenceOpen,setReferenceOpen]=useState(false);
 const referenceSceneId=project.recordingScenes?.scenes.find(scene=>snapshotMigrationId('recording',scene.id)===recordingId)?.id??recordingId;
 const referenceButton=useRef<HTMLButtonElement>(null),reference=useRecordingReference(`${project.meta.createdAt}/${recordingId}`,project.drawing?.reference,referenceSceneId!==recordingId?`${project.meta.createdAt}/${referenceSceneId}`:undefined),floating=useFloatingPanel({open:referenceOpen,storageKey:'contour-reference-panel-position-v1'});
 const views=recording.snapshotIds.flatMap(id=>{const s=workspace.snapshots.find(s=>s.id===id),binding=surface?.mesh.vertices.find(v=>v.snapshotId===id);return s?[binding?{...s,angle:binding.angle}:s]:[];}),currentView=views.find(v=>surface?v.angle.x===recording.angle.x&&v.angle.y===recording.angle.y:sameAngle(v.angle,recording.angle));
 const run=useCallback((commands:SnapshotCommand[],history=true)=>{try{const result=(history?prepareSnapshotBatch:prepareSnapshotPreview)(useEditor.getState().project,{recordingId,commands});if(result.changed){const store=useEditor.getState();history?store.commitRecordingSnapshots(result.recordingSnapshots):store.setRecordingSnapshots(result.recordingSnapshots);}setError(result.diagnostics?.map(d=>d.message).join(' ')??'');return result;}catch(e){setError((e as Error).message);return undefined;}},[recordingId]);
 const previewCommands=useCallback((commands:SnapshotCommand[]|null)=>{if(!commands){setPreview(null);return;}if(!currentView&&!pair&&!surface)return;try{const result=prepareSnapshotPreview(useEditor.getState().project,{recordingId,commands});setPreview(result.recordingSnapshots);setError('');}catch(e){setError((e as Error).message);}},[recordingId,!!currentView,!!pair,!!surface]);
 const evaluated=useMemo(()=>evaluateRecordingSnapshot(preview??workspace,recordingId,{angle:recording.angle,useDraft:true,immutableInputs:true,diagnostics:preview?'preview':'full',...(warpId&&localEdit?{stopAtWarpId:warpId}:{})}),[workspace,preview,recordingId,recording.angle,warpId,localEdit]);
 const baseline=useMemo(()=>evaluateRecordingSnapshot(workspace,recordingId,{angle:recording.angle,useDraft:true,immutableInputs:true,diagnostics:'preview'}),[workspace,recordingId,recording.angle]);
 const snapshot=workspace.snapshots.find(s=>s.id===evaluated.snapshotId),drawing=evaluated.drawing,state=evaluated.state,correction=pairCorrection||evaluated.angleSurface?.role==='correction',surfaceOutside=evaluated.angleSurface?.role==='outside';
 const correctionDraft=surface?.correctionFrames?.find(frame=>frame.status==='draft')??pair?.draft;
 const warp=state.warps.find(w=>w.id===warpId),selectedLayerIds=selectedLayers(selection).filter(id=>drawing.layers.some(l=>l.id===id));
 const sourceOptions=workspace.snapshots.filter(s=>s.kind==='drawing'||s.kind==='sculpt');
 const sourcePanels=useMemo(()=>workspace.snapshots.filter(s=>sourceIds.includes(s.id)).map(snapshot=>({snapshotId:snapshot.id,name:snapshot.name,drawing:resolveSnapshot(workspace,snapshot.id,{useDraft:false,immutableInputs:true}).drawing})),[workspace.library,workspace.snapshots,sourceIds]);
 const currentPanel=snapshot&&!surfaceOutside?{snapshotId:snapshot.id,name:`${correction?txt('反推修正预览','Inverse-correction preview'):txt('当前视角快照','Current view snapshot')} · ${snapshot.name} · X ${recording.angle.x}° / Y ${recording.angle.y}°`,drawing}:undefined;
 const onChoose=(next:DrawingSelection,layers:SnapshotLayerSelection[]=[],mode?:DrawingTool,reveal=true)=>{const localLayer=layers.find(ref=>ref.snapshotId===snapshot?.id)?.layerId??(!layers.length?next.layer??(next.ids[0]?layerFor(drawing,next.ids[0])?.id:undefined):undefined);if(localLayer)setActiveDrawingLayer(localLayer);const transition=chooseDrawingSelection(canvasTool,next,mode);setCanvasTool(transition.tool as typeof canvasTool);setSelection(transition.selection);setLayerSelections(layers);setSelectedSnapshotIds([]);setCorrectionControl(null);setPreview(null);setWarpId('');if(reveal)setGridRevealKey(k=>k+1);};
 const onCanvasTool=(tool:typeof canvasTool)=>{const transition=selectDrawingTool(tool,selection);setCanvasTool(tool);setSelection(transition.selection);if(transition.clearActiveControl)setCorrectionControl(null);};
 const selectSnapshot=(id:string)=>{if(id!==snapshot?.id){setSelectedSnapshotIds([]);return;}const layerIds=drawing.layers.map(l=>l.id);onChoose({layers:layerIds,layer:layerIds.length===1?layerIds[0]:undefined,ids:drawing.curves.map(c=>c.id),paintIds:[...drawing.fills,...drawing.offsets].map(x=>x.id)},layerIds.map(layerId=>({snapshotId:id,layerId})),'select');setSelectedSnapshotIds([id]);};
 const editable=!!currentView&&!reference.moving,curveEditable=(!!currentView||!!pair||!!surface&&!surfaceOutside)&&!reference.moving,hasLayerSelection=selectedLayerIds.length>0&&layerSelections.every(ref=>ref.snapshotId===snapshot?.id),placementIds=drawing.curves.filter(c=>selectedLayerIds.includes(layerFor(drawing,c.id)?.id??'')).map(c=>c.id),bounds=selectionBounds(drawing,placementIds),materialBounds=selectedLayerIds.length===1?selectionBounds(evaluated.prePlacementDrawing,placementIds):null;
 const layerPlacement=(id:string)=>evaluated.placements[id]??identityScenePlacement(),singlePlacement=selectedLayerIds.length===1?layerPlacement(selectedLayerIds[0]):undefined;
 const placementCommands=(delta:ScenePlacementValue):SnapshotCommand[]=>selectedLayerIds.map(layerId=>({op:'setLayerPlacement',layerId,value:composePlacementSimilarity(baseline.placements[layerId]??identityScenePlacement(),delta)}));
 const valueCommands=(value:ScenePlacementValue):SnapshotCommand[]=>selectedLayerIds.length===1?[{op:'setLayerPlacement',layerId:selectedLayerIds[0],value}]:[];
 const shapeLayerIds=[...new Set(selection.ids.map(id=>layerFor(drawing,id)?.id).filter((id):id is string=>!!id))],shapeSingular=!correction&&(shapeLayerIds.some(id=>!tryInverseScenePlacement(layerPlacement(id)))||selection.ids.some(id=>!tryInverseScenePlacement(evaluated.elementPlacements[id]??identityScenePlacement())));
 const shapeCommand=(change:RecordingCurveEdit):SnapshotCommand=>{const curve=change.kind==='handle'?drawing.curves.find(c=>c.id===change.curveId):drawing.curves.find(c=>c.nodes.includes(change.nodeId)),layerId=curve&&layerFor(drawing,curve.id)?.id;if(!layerId)throw Error('The selected source is no longer in this snapshot.');if(pair||surface&&correction)return change.kind==='node'?{op:'moveShapeNode',layerId,nodeId:change.nodeId,position:change.position}:{op:'moveShapeHandle',layerId,curveId:change.curveId,end:change.end,position:change.position};const inverse=tryInverseScenePlacement(layerPlacement(layerId));if(!inverse)throw Error('Restore width or height before editing curves.');const elementInverse=tryInverseScenePlacement(evaluated.elementPlacements[curve!.id]??identityScenePlacement());if(!elementInverse)throw Error('Restore the stroke width or height before editing curves.');const position=applyScenePlacementMatrix(elementInverse,applyScenePlacementMatrix(inverse,change.position));return change.kind==='node'?{op:'moveShapeNode',layerId,nodeId:change.nodeId,position}:{op:'moveShapeHandle',layerId,curveId:change.curveId,end:change.end,position};};
 const elementTransformIds=selection.ids.filter(id=>drawing.curves.some(c=>c.id===id)),elementFrame=!hasLayerSelection&&!warp?snapshotStrokeTransformFrame(evaluated,elementTransformIds):null,elementTransformBounds=elementFrame?.bounds;
 const transformsForSelection=(ids:string[])=>!warp?snapshotStrokeSelectionTransform(evaluated,baseline,ids,curveEditable,previewCommands,commands=>{run(commands);setPreview(null);},txt('整笔变换','Stroke transform')):undefined;
 const correctionLayerTransform=correction&&hasLayerSelection?transformsForSelection(placementIds):undefined;
 const elementValueCommands=(value:ScenePlacementValue):SnapshotCommand[]=>snapshotStrokeValueCommands(elementTransformIds,value);
 const onCurvePreview=(change:RecordingCurveEdit|null)=>{try{previewCommands(change?[shapeCommand(change)]:null);}catch(e){setError((e as Error).message);}};
 const onCurveCommit=(change:RecordingCurveEdit)=>{try{run([shapeCommand(change)]);}catch(e){setError((e as Error).message);}setPreview(null);};
 const topologyEditable=editable&&!correction&&!surfaceOutside&&!pair,topologyHint=pair?txt('先建立三角插值录制副本，再创建或删除图层与曲线。','Create a triangulated Recording copy before adding or deleting layers and curves.'):txt('先在当前角度建立真实快照，再修改拓扑。','Create a real snapshot at this angle before changing topology.');
 const penLayerId=drawing.layers.find(layer=>layer.id===activeDrawingLayer)?.id??drawing.layers[0]?.id??null;
 const commitTopology=(beforeDrawing:DrawingDocument,next:DrawingDocument):RecordingSnapshotWorkspace|undefined=>{if(!topologyEditable||!snapshot){setError(topologyHint);return;}try{const store=useEditor.getState(),plan=prepareSnapshotEdit(snapshotEditContext(store.project,false),{kind:'local-drawing-topology',recordingId,snapshotId:snapshot.id,angle:recording.angle,beforeDrawing,drawing:next});store.commitPreparedSnapshotEdit(plan);setPreview(null);setError(plan.diagnostics?.map(value=>value.message).join(' ')??'');return useEditor.getState().project.recordingSnapshots;}catch(error){setError((error as Error).message);return;}};
 const applyStructural=(operation:()=>DrawingStructuralResult)=>{if(!topologyEditable){setError(topologyHint);return;}try{const result=operation();if(!commitTopology(drawing,result.document))return;if(result.activeLayerId)setActiveDrawingLayer(result.activeLayerId);onChoose(result.selection,selectedLayers(result.selection).map(layerId=>({snapshotId:snapshot!.id,layerId})),'select');}catch(error){setError((error as Error).message);}};
 const deleteSelection=()=>{if(layerSelections.some(ref=>ref.snapshotId!==snapshot?.id))return;applyStructural(()=>deleteDrawingSelection(drawing,selection));};
 const structuralCommands={editable:topologyEditable,disabledReason:topologyEditable?undefined:topologyHint,addLayer:()=>applyStructural(()=>createDrawingLayer(drawing,txt('图层','Layer')+(drawing.layers.length+1),penLayerId)),duplicateLayers:(ids:string[])=>applyStructural(()=>duplicateDrawingLayers(drawing,ids)),deleteLayers:(ids:string[])=>applyStructural(()=>deleteDrawingSelection(drawing,{ids:[],layers:ids})),deleteSelection};
 const onSplit=(curveId:string,t:number)=>{if(!currentView||!snapshot||correction||surfaceOutside){setError(txt('先在当前角度建立真实快照，再修改拓扑。','Create a real snapshot at this angle before changing topology.'));return;}try{const store=useEditor.getState(),intent=createCurveSplitIntent(drawing,curveId,t),plan=prepareSnapshotEdit(snapshotEditContext(store.project,false),{kind:'local-curve-split',snapshotId:snapshot.id,intent});store.commitPreparedSnapshotEdit(plan);onChoose({ids:[...intent.childCurveIds]},[],'direct');setError(plan.diagnostics?.map(value=>value.message).join(' ')??'');}catch(e){setError((e as Error).message);}};
 const warpCommands=(grid:WarpGrid):SnapshotCommand[]=>[{op:'editWarpNodes',warpId,edits:grid.nodes.map((n,index)=>({index,...n})),moveHandles:false}];
 const affects=(leaf:string)=>{let id:string|undefined=leaf;const seen=new Set<string>();while(id&&!seen.has(id)){if(id===warpId)return true;seen.add(id);id=state.warps.find(w=>w.id===id)?.parentId;}return false;};
 const frameLayers=drawing.layers.filter(l=>state.bindings.some(b=>b.layerId===l.id&&affects(b.warpId))),frameLayer=frameLayers[0],gridPlacement=frameLayer?layerPlacement(frameLayer.id):undefined,ghostGridPlacements=frameLayers.filter(l=>l!==frameLayer).map(l=>({instanceId:l.id,name:l.name,value:layerPlacement(l.id)}));
 const currentDrafts=recording.tracks.filter(t=>t.draft&&sameAngle(t.draft.angle,recording.angle)),otherDrafts=recording.tracks.filter(t=>t.draft&&!sameAngle(t.draft.angle,recording.angle));
 useEffect(()=>snapshotOnionPreferences.save(preferenceKey,{settings:onion,endpoints:onionEndpoints}),[preferenceKey,onion,onionEndpoints]);
 const effectiveOnionEndpoints=pair?{startSnapshotId:pair.startSnapshotId,endSnapshotId:pair.endSnapshotId}:onionEndpoints;
 const onionResult=useSnapshotOnionFrames(preview??workspace,recordingId,recording.angle,onion,warpId&&localEdit?warpId:undefined,effectiveOnionEndpoints,evaluated);
 useEffect(()=>{setOnionEndpoints(old=>{const validStart=recording.snapshotIds.includes(old.startSnapshotId),validEnd=recording.snapshotIds.includes(old.endSnapshotId);return validStart&&validEnd&&(old.startSnapshotId!==old.endSnapshotId||recording.snapshotIds.length<2)?old:defaultOnionEndpoints(workspace,recordingId);});},[recording.snapshotIds.join('|')]);

 useEffect(()=>{setPreview(null);setSelection(previous=>retainSnapshotDrawingSelection(previous,drawing));setLayerSelections(previous=>previous.filter(ref=>drawing.layers.some(layer=>layer.id===ref.layerId)).map(ref=>({...ref,snapshotId:recording.activeSnapshotId??ref.snapshotId})));setSelectedSnapshotIds([]);},[recording.activeSnapshotId]);
 useEffect(()=>{setPreview(null);},[workspace]);
 useEffect(()=>{window.dispatchEvent(new Event('contour:cancel-recording-gesture'));},[workspace.library]);
 const changeAngle=(angle:{x:number;y:number})=>run([{op:'setAngle',angle:pair&&pairStart&&pairEnd?{x:Math.max(Math.min(pairStart.angle.x,pairEnd.angle.x),Math.min(Math.max(pairStart.angle.x,pairEnd.angle.x),angle.x)),y:pairStart.angle.y}:angle}],false);
 const capture=(intent:'reference'|'duplicate',sources:SnapshotLayerClipboardSource[])=>{try{clipboardSession.capture(captureSnapshotLayerClipboard(clipboardSession.projectId,intent,sources));setError('');}catch(e){setError((e as Error).message);}};
 const paste=()=>{if(!editable||!clipboard)return;const commands:SnapshotCommand[]=clipboard.sources.map(source=>({op:clipboard.intent==='duplicate'?'cloneLayers':'pasteLayers',sourceSnapshotId:source.snapshotId,layerIds:[...source.layerIds]}));const result=run(commands);if(result){setSelection({ids:[]});setLayerSelections([]);}};
 return <main className="vector-recording vr-view-workflow" data-testid="recording-snapshot-v2"><aside className="vr-sidebar vr-left" data-testid="snapshot-view-panel">
  <section className="vr-section"><select aria-label="Recording" value={recordingId} onChange={e=>run([{op:'selectRecording',recordingId:e.target.value}])}>{workspace.recordings.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><details><summary>{txt('新建录制','New recording')}</summary><input aria-label="New recording name" value={recordingName} onChange={e=>setRecordingName(e.target.value)}/><button onClick={()=>run([{op:'createTriangulatedRecording',name:recordingName.trim()||txt('录制','Recording')}])}>＋</button></details></section>
  <section className="vr-section"><h2>{pair?txt('两端基础形状','Two basis shapes'):txt('视角快照','View snapshots')}</h2>{pair&&<button data-testid="snapshot-create-triangulated-copy" onClick={()=>run([{op:'createTriangulatedRecordingCopy',name:`${recording.name} · ${txt('二维工作副本','2D working copy')}`}])}>{txt('建立二维录制工作副本','Create 2D recording copy')}</button>}{pair&&<small>{txt('只有两端是形状关键帧；中间角为反推修正位置。','Only the two endpoints are shape keys. Angles between them are correction positions.')}</small>}<SceneAnglePad angle={recording.angle} views={views} onChange={changeAngle} zh={zh} exactBindings={!!surface} connections={surface?.mesh.edges.map(edge=>({id:edge.id,from:surface.mesh.vertices.find(v=>v.id===edge.vertexIds[0])!.angle,to:surface.mesh.vertices.find(v=>v.id===edge.vertexIds[1])!.angle}))}/><div className="vr-interval-numbers">{(['x','y'] as const).map(axis=><label key={axis}>{axis.toUpperCase()}<Numeric disabled={!!pair&&axis==='y'} value={recording.angle[axis]} label={`Angle ${axis.toUpperCase()}`} commit={value=>changeAngle({...recording.angle,[axis]:Math.max(-90,Math.min(90,value))})}/></label>)}</div>
   {correction?<><p data-testid="endpoint-correction-position">{txt('反推修正位置：A 拖端点／柄；V 变换所选线或图层，只保存响应。','Correction position: A edits controls; V transforms selected strokes or layers. Only responses are saved.')}</p><button className="vr-primary" data-testid="snapshot-save-correction" disabled={!correctionDraft||!sameAngle(correctionDraft.angle,recording.angle)} onClick={()=>run([{op:'updateEndpointCorrection'}])}>{txt('保存反推修正','Save inverse correction')}</button>{correctionDraft&&<button onClick={()=>run([{op:'discardEndpointCorrection'}])}>{txt('放弃未保存修正','Discard correction draft')}</button>}<small>{txt('整组变换逐点反推；不可解的坐标会拒绝本次操作。区间两端可独立反推；显示开关和层序在真实快照编辑。','Group transforms inverse-solve their controls; unavailable coordinates reject the whole edit. Interval endpoints have independent responses; edit display switches and order in real snapshots.')}</small>{surface&&<button data-testid="snapshot-create-real-view" onClick={()=>run([{op:'createSnapshot',name:viewName.trim()||undefined,angle:recording.angle}])}>{txt('在此建立真实快照','Create a real snapshot here')}</button>}</>:currentView?<><button className="vr-primary" data-testid="snapshot-update-view" onClick={()=>run([{op:'updateSnapshot',snapshotId:currentView.id}])}>{pair?txt('更新基础端点','Update basis endpoint'):txt('更新此视角','Update this viewpoint')} · {surface?(snapshot?.draft?1:0):currentDrafts.length}</button>{surface&&<details><summary>{txt('修改此快照的角度绑定','Rebind this snapshot angle')}</summary><div className="vr-interval-numbers">{(['x','y'] as const).map(axis=><label key={axis}>{axis.toUpperCase()}<Numeric label={`Snapshot binding ${axis.toUpperCase()}`} value={currentView.angle[axis]} commit={value=>run([{op:'rebindSnapshotAngle',snapshotId:currentView.id,angle:{...currentView.angle,[axis]:Math.max(-90,Math.min(90,value))}}])}/></label>)}</div></details>}{(surface?!!snapshot?.draft:currentDrafts.length>0)&&<small>{txt('所选端点的未保存改动实时参与两端插值；更新视角后正式保存。','Unsaved edits at a selected endpoint update endpoint interpolation live. Update this viewpoint to save them.')}</small>}</>:<><p>{txt('预览：先建立视角快照才能编辑。','Preview: create a view snapshot to edit.')}</p><input aria-label="View snapshot name" value={viewName} onChange={e=>setViewName(e.target.value)}/><button data-testid="snapshot-create-view" onClick={()=>run([{op:'createSnapshot',name:viewName.trim()||undefined,angle:recording.angle}])}>{txt('建立视角快照','Create view snapshot')}</button></>}
   <div className="vr-view-list">{views.map(v=><div className="vr-key-row" key={v.id}><button aria-pressed={sameAngle(v.angle,recording.angle)} onClick={()=>run([{op:'selectSnapshot',snapshotId:v.id}])}>{v.name}<small>X {v.angle.x} / Y {v.angle.y}</small></button><button data-testid="snapshot-delete-view" disabled={!!pair} aria-label={`${txt('删除视角快照','Delete view snapshot')} ${v.name}`} title={txt('只移除此视角及其独占关键状态；源稿保留，可撤销','Remove this view and its exclusive authored keys. Keep sources; Undo is available.')} onClick={()=>run([{op:'deleteSnapshot',snapshotId:v.id}])}>×</button></div>)}</div>{pair?.draft&&!sameAngle(pair.draft.angle,recording.angle)&&<button data-testid="return-correction-draft" onClick={()=>changeAngle(pair.draft!.angle)}>{txt('返回未保存修正','Return to correction draft')} · X {pair.draft.angle.x}°</button>}{otherDrafts.map(t=><button key={t.id} onClick={()=>run([{op:'setAngle',angle:t.draft!.angle}],false)}>{txt('返回草稿','Return to draft')} · {t.channel} {t.draft!.angle.x}/{t.draft!.angle.y}</button>)}</section>
  {error&&<p className="vr-error" role="alert" style={{overflowWrap:"anywhere"}}>{error}</p>}
  {surface&&evaluated.angleSurface?.outsideCurves.length? <p className="vr-error" data-testid="surface-coverage-status">{txt(`${evaluated.angleSurface.outsideCurves.length} 条红线超出各自录制范围，只读参考。`,`${evaluated.angleSurface.outsideCurves.length} red curves are read-only outside their recorded coverage.`)}</p>:null}
  <SceneOnionControls surfaceDriven={!!surface} pairDriven={!!pair} endpointViews={views} endpoints={effectiveOnionEndpoints} onEndpointsChange={pair?()=>{}:setOnionEndpoints} settings={onion} onChange={setOnion} zh={zh} preparing={onionResult.preparing} error={onionResult.error} frameCount={onionResult.frames.filter(f=>!sameAngle(f.angle,recording.angle)).length}/>
  {surface?<section className="vr-section" data-testid="surface-correction-summary"><strong>{txt('录制器 · 三角插值','Recorder · triangular interpolation')}</strong><p>{txt('真实快照定义覆盖。A / V 在中间位置反推响应；红色曲线是范围外的只读参考，不会加入当前快照。','Real snapshots define coverage. A / V inverse-edit responses between them. Red curves are out-of-coverage references and are not current snapshot members.')}</p>{surface.correctionFrames?.filter(frame=>frame.status==='saved').map(frame=><button key={frame.id} onClick={()=>changeAngle(frame.angle)}>{txt('修正帧','Correction')} · {frame.angle.x} / {frame.angle.y}</button>)}</section>:pair?<EndpointCorrectionEditor recording={recording} views={views} drawing={drawing} curveIds={selection.ids.filter(id=>drawing.curves.some(curve=>curve.id===id))} selected={correctionControl} nodeAuthorities={evaluated.endpointPair?.nodeAuthorities} basisStart={evaluated.endpointPair?.start.drawing} basisEnd={evaluated.endpointPair?.end.drawing} zh={zh} preview={previewCommands} commit={commands=>run(commands)}/>:<><section className="vr-section"><strong>{txt('旧关键帧录制','Legacy keyed recording')}</strong><p>{txt('以洋葱皮所选两端创建反推录制副本。原记录和中间键完整保留；副本仅以两端重新生成，不声称匹配原中间形状。','Create an inverse-response copy from the two selected onion endpoints. The original and middle keys remain intact; the copy regenerates from its endpoints and may differ in between.')}</p><button data-testid="snapshot-create-endpoint-pair" disabled={!onionEndpoints.startSnapshotId||!onionEndpoints.endSnapshotId||onionEndpoints.startSnapshotId===onionEndpoints.endSnapshotId} onClick={()=>run([{op:'createEndpointPairRecording',...onionEndpoints,name:`${recording.name} · ${txt('两端反推','Endpoint corrections')}`}])}>{txt('建立两端反推副本','Create endpoint-correction copy')}</button></section></>}
  {onion.enabled&&onionResult.diagnostics.length>0&&<details className="vr-section vr-onion-diagnostics" data-testid="snapshot-onion-diagnostics"><summary>{txt(`${onionResult.diagnostics.length} 条插值提示`,`${onionResult.diagnostics.length} interpolation notes`)}</summary>{onionResult.diagnostics.map((message,index)=><p key={index}>{message}</p>)}</details>}
  <section className="vr-section"><button ref={referenceButton} onClick={()=>{reference.setMoving(false);setReferenceOpen(v=>!v);}}>{txt('参考 / 辅助线','Reference / guides')}</button></section>
  <details className="vr-section"><summary>{txt('检查','Diagnostics')} · {evaluated.diagnostics.length+evaluated.warningCurveIds.length}</summary>{evaluated.diagnostics.map((d,i)=><p key={i} className="vr-error">{d.message}</p>)}</details>
 </aside>
 <aside ref={floating.panelRef} style={floating.style} className="vr-reference-popover vr-section" hidden={!referenceOpen} role="dialog" aria-label={txt('工作区参考 / 辅助线','Workspace reference / guides')} data-ui-keyboard><header {...floating.headerProps} className="reference-panel-drag-handle"><strong>{txt('参考 / 辅助线','Reference / guides')}</strong><button onClick={()=>setReferenceOpen(false)}>×</button></header>{reference.controls}<details><summary>{txt('快照参考 / 辅助线','Artwork reference / guides')}</summary><WorkspaceViewPanel embedded/></details></aside>
 <SceneWarpCanvas topology={{editable:editable&&!correction&&!surfaceOutside,onSplit,relations:{editable:topologyEditable,disabledReason:topologyHint,targetKey:`${recordingId}/${snapshot?.id}/${recording.angle.x}/${recording.angle.y}`,historyKey:workspace,layerId:penLayerId,onCommit:commitTopology,onSelection:next=>onChoose(next,[],'link',false),onError:setError},onDelete:topologyEditable?deleteSelection:undefined,pen:{editable:topologyEditable,disabledReason:topologyHint,targetKey:`${recordingId}/${snapshot?.id}/${recording.angle.x}/${recording.angle.y}/${penLayerId}`,historyKey:workspace,layerId:penLayerId,onCommit:commitTopology,onSelection:ids=>{setSelection({ids});setLayerSelections([]);setSelectedSnapshotIds([]);},onError:setError}}} interaction={{tool:canvasTool,onToolChange:onCanvasTool}} showWarpTools={false} inspectionHideFills={onion.enabled} source={evaluated.source} drawing={drawing} paintBatches={evaluated.paintBatches} warnings={evaluated.fitDiagnostics} targetKey={`${recordingId}/${snapshot?.id}/${recording.angle.x}/${recording.angle.y}/${warpId}/${selectedLayerIds.join(',')}`} label={`${recording.name} · X ${recording.angle.x}° / Y ${recording.angle.y}°`} zh={zh} selection={selection} onSelectionTool={(next,tool)=>onChoose(next,selectedLayers(next).map(layerId=>({snapshotId:snapshot?.id??'',layerId})),tool,false)} transformsForSelection={transformsForSelection} grid={warp?evaluated.warpGrids[warp.id]:undefined} gridPlacement={gridPlacement} ghostGridPlacements={ghostGridPlacements} editEnabled={editable&&(!warp?.parentId||localEdit)&&!!tryInverseScenePlacement(gridPlacement??identityScenePlacement())} onPreview={grid=>previewCommands(grid?warpCommands(grid):null)} onCommit={grid=>{run(warpCommands(grid));setPreview(null);}} revealGridKey={gridRevealKey} onWarpSelection={()=>{setSelection({ids:[]});setLayerSelections([]);setSelectedSnapshotIds([]);}} reference={reference} localToggle={warp?.parentId?{local:localEdit,change:()=>setLocalEdit(v=>!v)}:undefined} warpPicker={{value:warpId,items:state.warps.map(w=>({id:w.id,name:w.name})),onChange:id=>{setWarpId(id);setSelectedSnapshotIds([]);setGridRevealKey(k=>k+1);}}}
  instanceTransform={correctionLayerTransform?{...correctionLayerTransform,ids:selectedLayerIds,allowCurveSelection:false,label:txt('所选图层反推变换','Selected layer inverse transform')}:!warp&&hasLayerSelection&&bounds?{ids:selectedLayerIds,bounds,editable,label:txt('所选图层变换','Selected layer transform'),onPreview:delta=>previewCommands(delta?placementCommands(delta):null),onCommit:delta=>{run(placementCommands(delta));setPreview(null);},...(singlePlacement&&materialBounds?{basePlacement:singlePlacement,materialBounds,onValuePreview:value=>previewCommands(value?valueCommands(value):null),onValueCommit:value=>{run(valueCommands(value));setPreview(null);}}:{})}:elementTransformBounds?transformsForSelection(elementTransformIds):undefined}
  curveEdit={!warp&&selection.ids.length?{editable:curveEditable&&!shapeSingular,onPreview:onCurvePreview,onCommit:onCurveCommit,onSelect:setCorrectionControl}:undefined} curveEditDisabledReason={shapeSingular?txt('宽或高为 0，请先恢复后再编辑节点。','Restore zero width or height before editing nodes.'):undefined}
  overlay={screen=>evaluated.angleSurface?.outsideCurves.length?<g data-testid="snapshot-outside-coverage" pointerEvents="none" aria-hidden="true">{evaluated.angleSurface.outsideCurves.map(curve=><path key={curve.curveId} data-preview-curve-id={curve.curveId} data-evaluated-x={curve.evaluatedAngle.x} data-evaluated-y={curve.evaluatedAngle.y} d={curvePath(curve.cubic,screen)} fill="none" stroke="#e24755" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/>)}</g>:null}
  underlay={(screen,unit)=><SceneOnionSkin frames={onionResult.frames} angle={recording.angle} opacity={onion.opacity} screen={screen} unit={unit}/>}/>
 <aside className="vr-sidebar vr-right">{!correction&&singlePlacement&&hasLayerSelection&&<section className="vr-section"><div className="vr-interval-numbers">{(['x','y'] as const).map((axis,index)=><label key={axis}>{axis==='x'?txt('宽度 %','Width %'):txt('高度 %','Height %')}<Numeric disabled={!editable} value={scenePlacementScales(singlePlacement)[index]*100} label={`Layer scale ${axis.toUpperCase()} percent`} commit={n=>{if(n>=0&&n<=1e8)run(valueCommands(setScenePlacementAxisScale(singlePlacement,axis,n/100,materialBounds?.center)));}}/></label>)}</div></section>}
 {!correction&&elementFrame?.placement&&<section className="vr-section" data-testid="snapshot-stroke-axis-controls"><div className="vr-interval-numbers">{(['x','y'] as const).map((axis,index)=><label key={axis}>{axis==='x'?txt('笔画宽度 %','Stroke width %'):txt('笔画高度 %','Stroke height %')}<Numeric disabled={!editable} value={scenePlacementScales(elementFrame.placement!)[index]*100} label={`Stroke scale ${axis.toUpperCase()} percent`} commit={n=>{if(n>=0&&n<=1e8)run(elementValueCommands(setScenePlacementAxisScale(elementFrame.placement!,axis,n/100,elementFrame.materialBounds.center)));}}/></label>)}</div></section>}
 {(drawing.endpointLinks??[]).filter(link=>[link.a,link.b].some(endpoint=>selection.ids.includes(endpoint.curveId))).map(link=><EndpointRelationControls key={link.id} drawing={drawing} link={link} editable={topologyEditable} run={operation=>{try{commitTopology(drawing,operation());}catch(error){setError((error as Error).message);}}}/>)}
 <section className="vr-section snapshot-source-picker"><details><summary>{txt('＋ 添加来源','＋ Add source')}</summary><select aria-label="Add source snapshot" value={sourceToAdd||sourceOptions[0]?.id||''} onChange={e=>setSourceToAdd(e.target.value)}>{sourceOptions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button data-testid="snapshot-show-source" disabled={!sourceOptions.length} onClick={()=>{const id=sourceToAdd||sourceOptions[0]?.id;if(id)setSourceIds(ids=>ids.includes(id)?ids:[...ids,id]);}}>{txt('列出此来源的图层','Show this source’s layers')}</button></details></section>
 <SnapshotLayerPanel structuralCommands={structuralCommands} collapseSourcesByDefault={false} current={currentPanel} sources={sourcePanels} selection={selection} layerSelections={layerSelections} onSelection={onChoose} editEnabled={editable} canPaste={!!clipboard} onCut={sources=>capture('reference',sources)} onCopy={sources=>capture('duplicate',sources)} onPaste={paste} onSelectSnapshot={selectSnapshot} selectedSnapshotIds={selectedSnapshotIds} headerActions={undefined} onVisibilityChange={(ids,visible)=>{if(editable)run(ids.flatMap(id=>{const layerId=layerFor(drawing,id)?.id;return layerId?[{op:'setVisibility' as const,layerId,objectId:id,visible}]:[];}));}} onLayerReorder={(id,target,after)=>{const ids=drawing.layers.map(l=>l.id).filter(x=>x!==id),index=ids.indexOf(target);if(index>=0){ids.splice(index+(after?1:0),0,id);run([{op:'reorderLayers',layerIds:ids}]);}}}/>
 {selectedLayerIds.map(layerId=><details className="vr-section" key={layerId}><summary>{drawing.layers.find(l=>l.id===layerId)?.name} · {txt('区间 / 层序','Intervals / order')}</summary><fieldset disabled={!editable&&!(surface&&correction&&!reference.moving)} style={{border:0,padding:0}}><label>{txt('角度层序偏移','Pose order offset')}<Numeric disabled={!editable} label={`Layer order ${layerId}`} value={state.layers[layerId]?.depth??0} commit={value=>run([{op:'setLayerOrder',layerId,value}])}/></label>{((surface&&correction?drawing:evaluated.source).displayIntervals??[]).filter(t=>(surface&&correction?drawing:evaluated.source).layers.find(l=>l.id===layerId)?.items.includes(t.anchor.id)).map(base=>{const value=state.layers[layerId]?.intervals?.[base.id],appearance=surface&&correction?base:value?.appearance??base;return <details key={base.id}><summary>{txt('显隐区间','Visibility interval')}</summary>{appearance.ranges.map(range=><div key={range.id}><label>{!surface&&<><input type="checkbox" checked={value?.enabled[range.id]??range.enabled!==false} onChange={e=>run([{op:'setIntervalEnabled',layerId,sourceTrackId:base.id,rangeId:range.id,enabled:e.target.checked}])}/>{txt('启用','Enabled')}</>}<select disabled={!editable} value={range.mode??'SHOW'} onChange={e=>run([{op:'changeInterval',layerId,sourceTrackId:base.id,rangeId:range.id,mode:e.target.value as 'SHOW'|'HIDE'}])}><option value="SHOW">SHOW</option><option value="HIDE">HIDE</option></select></label><div className="vr-interval-numbers">{(['start','end'] as const).map(bound=><label key={bound}>{bound}<Numeric label={`${base.id} ${range.id} ${bound}`} value={range[bound]*100} commit={number=>run([{op:'changeInterval',layerId,sourceTrackId:base.id,rangeId:range.id,[bound]:Math.max(0,Math.min(1,number/100))}])}/></label>)}</div>{surface&&<small>{txt('两端重合为零长度；中间角只记录区间响应，不建立新快照。','Coincident endpoints have zero length. Intermediate edits record only interval responses, without creating a snapshot.')}</small>}</div>)}</details>;})}<button disabled={!editable} onClick={()=>{run([{op:'removeLayers',layerIds:[layerId]}]);setSelection({ids:[]});setLayerSelections([]);}}>{txt('从此视角移除图层','Remove layer from this view')}</button></fieldset></details>)}
 </aside></main>;
}
function Numeric({value,label,disabled=false,commit}:{value:number;label:string;disabled?:boolean;commit:(n:number)=>void}){const [text,setText]=useState(String(+value.toFixed(6)));useEffect(()=>setText(String(+value.toFixed(6))),[value]);return <input aria-label={label} disabled={disabled} inputMode="decimal" value={text} onChange={e=>setText(e.target.value)} onBlur={()=>{const n=text.trim()?Number(text):NaN;if(Number.isFinite(n)){if(n!==value)commit(n);}else setText(String(+value.toFixed(6)));}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();else if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();e.stopPropagation();const base=text.trim()&&Number.isFinite(Number(text))?Number(text):value,step=e.altKey?.1:e.shiftKey?10:1,next=Math.round((base+(e.key==='ArrowUp'?step:-step))*1e6)/1e6;setText(String(next));commit(next);}}}/>;}

function defaultOnionEndpoints(workspace:RecordingSnapshotWorkspace,recordingId:string){const recording=workspace.recordings.find(r=>r.id===recordingId),views=recording?.snapshotIds.flatMap(id=>{const s=workspace.snapshots.find(v=>v.id===id),binding=recording?.angleGraph?.mesh.vertices.find(v=>v.snapshotId===id);return s?[binding?{...s,angle:binding.angle}:s]:[];})??[];const start=views.find(v=>v.angle.x===0&&v.angle.y===0)??views[0],end=views.find(v=>v.angle.x===-90&&v.angle.y===0)??views.find(v=>v.angle.x===90&&v.angle.y===0)??(recording?.mode==='triangulated'?start:views.find(v=>v.id!==start?.id))??start;return {startSnapshotId:start?.id??'',endSnapshotId:end?.id??''};}

/** Canonical selection follows the same referenced elements across views. A
 * genuinely missing member is dropped instead of targeting another object. */
export function retainSnapshotDrawingSelection(selection:DrawingSelection,drawing:DrawingDocument):DrawingSelection {
 const ids=new Set(drawing.curves.map(curve=>curve.id)),layers=selectedLayers(selection).filter(id=>drawing.layers.some(layer=>layer.id===id)),paint=new Set([...drawing.fills,...drawing.offsets].map(item=>item.id));
 return {...selection,ids:selection.ids.filter(id=>ids.has(id)),layers,layer:layers.length===1?layers[0]:undefined,paint:selection.paint&&paint.has(selection.paint)?selection.paint:undefined,paintIds:selection.paintIds?.filter(id=>paint.has(id)),node:selection.node&&drawing.nodes.some(node=>node.id===selection.node)?selection.node:undefined,handle:selection.handle&&ids.has(selection.handle.curveId)?selection.handle:undefined,group:selection.group&&drawing.groups?.some(group=>group.id===selection.group)?selection.group:undefined,displayInterval:selection.displayInterval&&drawing.displayIntervals?.some(track=>track.id===selection.displayInterval!.track&&track.ranges.some(range=>range.id===selection.displayInterval!.range))?selection.displayInterval:undefined};
}

/** Freeze the selected stroke IDs and baseline for one pose-only transaction. */
export function snapshotStrokeSelectionTransform(evaluation:SnapshotEvaluation,baseline:SnapshotEvaluation,selectedIds:string[],editable:boolean,preview:(commands:SnapshotCommand[]|null)=>void,commit:(commands:SnapshotCommand[])=>void,label='Stroke transform'):RecordingInstanceTransform|undefined{
 const ids=[...selectedIds];
 if(evaluation.endpointPair?.role==='correction'||evaluation.angleSurface?.role==='correction'){
  // Correction controls already live in final viewport coordinates. Never apply
  // the nearer basis placement again to this frame or its pointer targets.
  const bounds=selectionBounds(evaluation.drawing,ids);if(!bounds)return undefined;
  const commands=(value:ScenePlacementValue):SnapshotCommand[]=>[{op:'transformShapeElements',curveIds:ids,value}];
  return {ids,bounds,materialBounds:bounds,basePlacement:identityScenePlacement(),editable,allowCurveSelection:true,label,
   onPreview:value=>preview(value?commands(value):null),onCommit:value=>commit(commands(value)),
   onValuePreview:value=>preview(value?commands(value):null),onValueCommit:value=>commit(commands(value))};
 }
 const frame=snapshotStrokeTransformFrame(evaluation,ids);if(!frame)return undefined;
 const singular=ids.some(id=>{const layerId=layerFor(evaluation.drawing,id)?.id;return !tryInverseScenePlacement(evaluation.placements[layerId??'']??identityScenePlacement())||!tryInverseScenePlacement(evaluation.elementPlacements[id]??identityScenePlacement());});
 const deltaCommands=(value:ScenePlacementValue)=>snapshotStrokeDeltaCommands(baseline,ids,value),valueCommands=(value:ScenePlacementValue)=>snapshotStrokeValueCommands(ids,value);
 return {ids,bounds:frame.bounds,editable:editable&&(frame.placement?frame.parentInvertible:!singular),allowCurveSelection:true,label,onPreview:value=>preview(value?deltaCommands(value):null),onCommit:value=>commit(deltaCommands(value)),...(frame.placement?{basePlacement:frame.placement,displayPlacement:frame.displayPlacement,materialBounds:frame.materialBounds,onValuePreview:(value:ScenePlacementValue|null)=>preview(value?valueCommands(value):null),onValueCommit:(value:ScenePlacementValue)=>commit(valueCommands(value))}:{})};
}
