import {useEffect,useRef} from 'react';
import {applyWorkspaceView,getWorkspaceView,replaceWorkspaceView,useWorkspaceView,type WorkspaceView,type ViewGuide} from '../../app/workspaceView';
import {uid,type Point2} from '../../domain/drawing/model';
const RULER=19;
/** View gestures never enter the source editor transaction or history. */
export default function ViewGuidesOverlay({screen,unit,width,height,view:provided}:{screen:(p:Point2)=>Point2;unit:number;width:number;height:number;view?:WorkspaceView}){
 const stored=useWorkspaceView(),view=provided??stored,gesture=useRef<{before:WorkspaceView;last:WorkspaceView;id:string;axis:'x'|'y';svg:SVGSVGElement;pointerId:number}|null>(null),latest=useRef({screen,unit});latest.current={screen,unit};
 function value(e:{clientX:number;clientY:number},svg:SVGSVGElement,axis:'x'|'y'){const rect=svg.getBoundingClientRect(),o=latest.current.screen([0,0]);return axis==='x'?(e.clientX-rect.left-o[0])/latest.current.unit:-(e.clientY-rect.top-o[1])/latest.current.unit;}
 function begin(e:React.PointerEvent<SVGElement>,axis:'x'|'y',guide?:ViewGuide){if(e.button!==0||gesture.current)return;e.preventDefault();e.stopPropagation();const svg=e.currentTarget.ownerSVGElement!;const before=structuredClone(getWorkspaceView()),id=guide?.id??uid();if(!guide)applyWorkspaceView([{op:'addGuide',id,axis,value:value(e,svg,axis)}]);gesture.current={before,last:getWorkspaceView(),id,axis,svg,pointerId:e.pointerId};svg.setPointerCapture(e.pointerId);}
 useEffect(()=>{function move(e:PointerEvent){const g=gesture.current;if(!g||e.pointerId!==g.pointerId)return;if(getWorkspaceView()!==g.last){finish();return;}e.preventDefault();g.last=applyWorkspaceView([{op:'changeGuide',id:g.id,value:value(e,g.svg,g.axis)}]);}function finish(e?:PointerEvent,rollback=false){const g=gesture.current;if(!g||e&&e.pointerId!==g.pointerId)return;gesture.current=null;if(rollback&&getWorkspaceView()===g.last)replaceWorkspaceView(g.before);if(g.svg.hasPointerCapture(g.pointerId))g.svg.releasePointerCapture(g.pointerId);}const up=(e:PointerEvent)=>finish(e),cancel=(e:PointerEvent)=>finish(e,true),key=(e:KeyboardEvent)=>{if(!gesture.current)return;e.preventDefault();e.stopImmediatePropagation();if(e.key==='Escape')finish(undefined,true);},blur=()=>finish(undefined,true);window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);window.addEventListener('pointercancel',cancel);window.addEventListener('keydown',key,true);window.addEventListener('blur',blur);return()=>{finish(undefined,true);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',cancel);window.removeEventListener('keydown',key,true);window.removeEventListener('blur',blur);};},[]);
 const origin=screen([0,0]),step=Math.pow(10,Math.floor(Math.log10(70/Math.max(unit,1e-6)))),ticks=(axis:'x'|'y')=>{const o=axis==='x'?origin[0]:origin[1],extent=axis==='x'?width:height,start=Math.floor((axis==='x'?-o:o-extent)/unit/step)-1,end=Math.ceil((axis==='x'?extent-o:o)/unit/step)+1;return Array.from({length:Math.min(300,Math.max(0,end-start+1))},(_,i)=>(start+i)*step);};
 return <g data-testid="workspace-view-guides">
 {view.guidesVisible&&view.guides.map(g=>{const p=screen(g.axis==='x'?[g.value,0]:[0,g.value]);return <line key={g.id} data-guide-id={g.id} x1={g.axis==='x'?p[0]:0} x2={g.axis==='x'?p[0]:width} y1={g.axis==='y'?p[1]:0} y2={g.axis==='y'?p[1]:height} stroke="#41a8c5" strokeWidth="1" strokeDasharray="5 4" opacity=".7" pointerEvents="none"/>;})}
 {view.rulersVisible&&<><rect x={0} y={0} width={width} height={RULER} fill="#e7eef1" stroke="#bacbd3" onPointerDown={e=>begin(e,'y')} style={{cursor:'ns-resize'}}><title>拖出水平辅助线</title></rect><rect x={0} y={0} width={RULER} height={height} fill="#e7eef1" stroke="#bacbd3" onPointerDown={e=>begin(e,'x')} style={{cursor:'ew-resize'}}><title>拖出垂直辅助线</title></rect>
 {ticks('x').map(n=>{const x=screen([n,0])[0];return <g key={'x'+n} pointerEvents="none"><line x1={x} x2={x} y1={13} y2={19} stroke="#839ca8"/><text x={x+2} y={11} fontSize="9" fill="#627984">{+n.toFixed(5)}</text></g>;})}{ticks('y').map(n=>{const y=screen([0,n])[1];return <g key={'y'+n} pointerEvents="none"><line x1={13} x2={19} y1={y} y2={y} stroke="#839ca8"/><text x={2} y={y-3} fontSize="9" fill="#627984">{+n.toFixed(5)}</text></g>;})}
 {view.guidesVisible&&view.guides.map(g=>{const p=screen(g.axis==='x'?[g.value,0]:[0,g.value]),points=g.axis==='x'?`${p[0]-5},2 ${p[0]+5},2 ${p[0]},13`:`2,${p[1]-5} 2,${p[1]+5} 13,${p[1]}`;return <polygon key={g.id} data-testid="view-guide-grip" points={points} fill="#177e9b" stroke="white" style={{cursor:g.axis==='x'?'ew-resize':'ns-resize'}} onPointerDown={e=>begin(e,g.axis,g)}><title>{g.axis.toUpperCase()}={g.value}</title></polygon>;})}</>}
 </g>;
}
