import {modulePickable} from './moduleAccess';
import {uiText} from "../i18n";
import {useWindows} from '../windows/state';
import {useEditor} from '../../app/store';
import {isSection} from '../../domain/curves/model';
import {regionCandidates} from '../../domain/head/regions';

export default function CreationShelf(){
 const s=useEditor(),t=s.tool,curve=s.selection?.kind==='curve'?s.project.curves.find(c=>c.id===s.selection!.id):undefined;
 const run=(f:()=>void)=>{s.cancelTool();f();};
 const surfacePoint=()=>{s.setTool({kind:'surfacePoint',centerline:false});};
 const item=(name:string,action:()=>void,reason?:string)=><li><button disabled={!!reason} onClick={e=>{action();if(useEditor.getState().tool.kind!=='select'&&!useWindows.getState().visible.viewport)useWindows.getState().toggle('viewport');e.currentTarget.closest('details')?.removeAttribute('open');}}>{uiText(name)}</button>{uiText(reason&&<small>{uiText(reason)}</small>)}</li>;
 const preview=()=>{try{if(t.kind!=='region')return;const candidates=regionCandidates(s.project,t.ids);if(!candidates.length)throw Error('没有合法区域');if(candidates.length===1){const c=candidates[0],id=crypto.randomUUID();s.addLoomisRegion({id,name:'Loomis Region',cuts:c.cuts,seed:c.seed});s.cancelTool();s.selectObject({kind:'surface',source:'REGION',id});}else{s.setTool({...t,preview:true});}}catch(e){s.notify((e as Error).message);}};
 const patch=t.kind==='patch'?t.pending:null;
 return <div className="creation-shelf" data-testid="creation-shelf" data-ui-keyboard><nav aria-label={uiText("Geometry Tools")}>
 <details><summary>{uiText("＋ Point ▾")}</summary><ul>{item('Regular Point · 中线',()=>run(()=>s.addDefaultPoint(true)))}{item('Regular Point · 对称',()=>run(()=>s.addDefaultPoint(false)))}{item('On Curve Point',()=>run(()=>s.addOnCurvePoint(curve!.id)),curve?undefined:'Select a Curve first')}{item('Construction Surface Point',surfacePoint,s.project.headFrame?undefined:'Requires HeadFrame')}{item('合并曲线定位点',()=>s.startPointMerge())}</ul></details>
 <details><summary>{uiText("Curve ▾")}</summary><ul>{item('Free Curve',()=>s.startCurve())}{item('Loomis Section',()=>run(()=>s.createLoomisSection()))}{item('中线 Section',()=>run(()=>s.createLoomisSection(true)))}{item('On Surface Curve',()=>s.setTool({kind:'onPatch',...(s.selection?.kind==='surface'&&s.selection.source==='PATCH'?{hostId:s.selection.id}:{})}))}</ul></details>
 <details><summary>{uiText("Surface ▾")}</summary><ul>{item('Boundary Surface',()=>s.startPatch())}{item('Loop Surface',()=>{s.startPatch();s.setPatchMode('loop');})}{item('Section Cap',()=>run(()=>s.closeSection(curve!.id)),curve&&isSection(curve)?undefined:'Select a Section first')}{item('Loomis Region',()=>s.setTool({kind:'region',ids:[],preview:false}),s.project.headFrame?undefined:'Requires HeadFrame')}</ul></details>
 </nav>{t.kind!=='select'&&<div className="active-tool-bar" data-testid="active-tool-bar"><strong>{uiText(t.kind==='mergePoint'?'合并曲线定位点':t.kind==='onPatch'?'On Surface Curve':t.kind==='curve'?'Free Curve':t.kind==='patch'?(patch?.mode==='loop'?'Loop Surface':'Boundary Surface'):t.kind==='region'?'Loomis Region':'Construction Surface Point')}</strong>
 <span>{uiText(t.kind==='mergePoint'?(t.keepId?'选择要并入的点 · 同一宿主、零 Offset':'选择保留位置的点 · 再点击要并入的点'):t.kind==='onPatch'?(t.previewId?'Step: Preview → 确认创建':!t.hostId?'Step: Select Host Patch':!t.startId?'Step: 2D 点击面上或边界端点 A':'Step: 2D 点击面上或边界端点 B'):t.kind==='curve'?(t.pending.startId?'Step: 选择终点 B':'Step: 选择起点 A'):t.kind==='patch'?(patch?.host?`Host: ${s.project.curves.find(c=>c.id===patch.host)?.name} · ${patch.start?'选择第二个定位点':'选择第一个定位点'}`:'Step: 选择边界曲线'):t.kind==='region'?(t.preview?'Step: 2D 点击候选区域':'Step: 勾选参与区域的 Sections'):s.activeModule==='EYES'?'Step: 2D 点击眼柱曲面 → 预览 → 确认':'Step: 2D 点击球面 / Cap → 预览 → 确认')}</span>
 {t.kind==='mergePoint'&&t.keepId&&<small>{uiText('保留点：')}{s.project.landmarks.find(l=>l.id===t.keepId)?.name}</small>}
 {uiText(t.kind==='curve'&&t.pending.startId&&<small>{uiText("Start:")}{s.project.landmarks.find(l=>l.id===t.pending.startId)?.name}</small>)}
 {patch&&<><div>{(['whole','span','loop'] as const).map(m=><button key={m} aria-pressed={patch.mode===m} onClick={()=>s.setPatchMode(m)}>{uiText(m==='whole'?'整线':m==='span'?'区间':'环形')}</button>)}</div><div>{patch.uses.map((b,i)=><button key={i} onClick={()=>s.removePatchBoundary(i)}>{s.project.curves.find(c=>c.id===b.curveId)?.name} ×</button>)}</div>{patch.mode!=='loop'&&patch.uses.length===2&&<button onClick={s.completeLensPatch}>{uiText("生成两边面")}</button>}{patch.mode==='loop'&&patch.uses.length===2&&<><button onClick={s.flipLoopTraversal}>{uiText("翻转第二环方向")}</button><button onClick={s.createLoopPatch}>{uiText("创建环形面")}</button></>}</>}
 {uiText(t.kind==='onPatch'&&t.previewId&&<button onClick={()=>{const id=t.previewId!;s.commitToolDraft();if(useEditor.getState().tool.kind==='select')s.selectObject({kind:'curve',id});}}>{uiText("确认创建 On Surface Curve")}</button>)}
 {t.kind==='surfacePoint'&&<div><button aria-pressed={!t.centerline} onClick={()=>s.setTool({...t,centerline:false,draft:undefined})}>{uiText("对称点")}</button><button disabled={s.activeModule==='EYES'} aria-pressed={t.centerline} onClick={()=>s.setTool({...t,centerline:true,draft:undefined})}>{uiText("中线点")}</button><span>{uiText("Side:")}{uiText(t.branch==='back'?'Back':'Front')}</span><button disabled={s.activeModule==='EYES'} onClick={()=>s.setTool({...t,branch:t.branch==='back'?'front':'back',draft:undefined})}>{uiText("Switch Front / Back")}</button>{t.draft&&<button onClick={()=>{const id=t.draft!.points[0]?.id;s.commitToolDraft();if(id)s.selectObject({kind:'point',id});}}>{uiText("确认创建")}</button>}</div>}
 {t.kind==='region'&&!t.preview&&<div>{s.project.curves.filter(c=>isSection(c)&&modulePickable(c.id)).map(c=><label key={c.id}><input type="checkbox" checked={t.ids.includes(c.id)} onChange={()=>s.setTool({...t,ids:t.ids.includes(c.id)?t.ids.filter(id=>id!==c.id):[...t.ids,c.id]})}/>{c.name}</label>)}<button disabled={!t.ids.length} onClick={preview}>{uiText("预览区域")}</button></div>}
 <div><button disabled={t.kind==='mergePoint'&&!t.keepId||t.kind==='surfacePoint'||t.kind==='curve'&&!t.pending.startId||!!patch&&!patch.host&&!patch.uses.length||t.kind==='region'&&!t.preview&&!t.ids.length} onClick={s.undoToolStep}>{uiText("Undo Step")}</button><button onClick={s.cancelTool}>{uiText("Cancel Esc")}</button></div>
 </div>}</div>;
}
